### ISSUE TITLE
Overwriting Service Options 

### ISSUE THREAD

**Issue by brainoverflow98** [aspnet/Docs#10015]
```

services.AddIdentity<ApplicationUser, IdentityRole>()
        .AddEntityFrameworkStores<ApplicationDbContext>()
        .AddDefaultTokenProviders();

services.AddAuthentication().AddFacebook(facebookOptions =>
{
    facebookOptions.AppId = Configuration["Authentication:Facebook:AppId"];
    facebookOptions.AppSecret = Configuration["Authentication:Facebook:AppSecret"];
});
```
Like in given code above, AddAuthentication was added in AddIdentity internally, what's the expected behavior of a service added for the second time ? Does that overwrite every configured option in the second call or that only overwrites the ones that already exists in first one ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2c6faa2-8c65-073b-4988-672c1aa9690c
* Version Independent ID: d22d616f-907e-ae62-1f43-88ad176a87d4
* Content: [Facebook external login setup in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/facebook-logins?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/authentication/social/facebook-logins.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/social/facebook-logins.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
These need to be updated for the Identity changes that were introduced in 2.1
@01binary any chance you could update these?

**Comment by 01binary** [comment]
I should have time this weekend

**Comment by 01binary** [comment]
I spent a couple of hours looking at this, but all relevant methods are undocumented (that is, there are docs that describe parameters but nothing about what the methods actually do).

@brainoverflow98 is saying that calling `.AddAuthentication()` after `.AddDefaultIdentity()` may erase the following defaults configured by `AddDefaultIdentity`:

```
services.AddAuthentication(o =>
            {
                o.DefaultScheme = IdentityConstants.ApplicationScheme;
                o.DefaultSignInScheme = IdentityConstants.ExternalScheme;
            })
            .AddIdentityCookies(o => { });
```

I confirmed that nothing is actually broken (i.e. just following instructions will produce a working app) so it's likely that either those settings are not overridden, or they are overridden with the same defaults. Further, I don't see a way to add social authentication without calling `AddAuthentication` first because `AddFacebook` and other social methods are extensions on `AuthenticationBuilder`:

https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.authenticationbuilder?view=aspnetcore-2.1

I don't see a way to get this authentication builder without having to call `AddAuthentication`. I think this means that even if calling `AddAuthentication` does reset auth config, you are forced to do that in order to use social logins.

Can whoever wrote AddAuthentication chime in on this? Otherwise I propose to just update the sample code in the articles to match what's currently being generated from a web app template with individual user account auth, since I know the instructions result in a functioning app.

**Comment by Rick-Anderson** [comment]
@HaoK 	please respond.

**Comment by 01binary** [comment]
Where is the repository that's actually published to https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/facebook-logins?view=aspnetcore-2.2?

I checked out master on https://github.com/aspnet/Docs and the content is totally different. Do I work with another branch or repo?

**Comment by 01binary** [comment]
Compare the text of:
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/facebook-logins (appears to be newer)
and...
https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/social/facebook-logins.md (appears to be older)

Ctrl+F for "The call to AddIdentity configures the default scheme settings."

I am observing that the master branch on aspnetcore docs appears to be behind what's published on docs.microsoft.com because it doesn't have that paragraph. I must have missed some notice about the repo move. If I have to make any updates to sample code used in social logins articles I definitely need to make sure I make it in the right place :)

**Comment by Rick-Anderson** [comment]
It's always been master. I looked at the build of master and it appears to be identical to the build of live. Maybe the include file is throwing you off. The only way they can be out of sink is if someone does a PR against live and we miss that and merge the PR. Here is the image of the master build:

![image](https://user-images.githubusercontent.com/3605364/50115383-46e70b80-01eb-11e9-89d0-29ed3627b7b2.png)

**Comment by Rick-Anderson** [comment]
@01binary 	I checked out live in one folder and master in another and diffed them - they're identical.

**Comment by 01binary** [comment]
Ah, it's the include! Sorry I wasn't familiar with markdown includes. I did see it but I thought it included sample code (not used to seeing includes pull in actual content).
