### ISSUE TITLE
Assess/enhance tooling instructions for publish in host+deploy topics

### ISSUE THREAD

**Issue by pholly** [aspnet/Docs#10045]
Visual Studio 2017 15.9.4 
Asp.net Core 2.2
The example on this page for framework-dependent deployment contains `dotnet` processPath. When I publish from Visual Studio with framework-dependent Deployment Mode the generated web.config contains a `.exe` in the processPath. My target framework is `netcoreapp2.2`. and target runtime is `win-x64`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe69b3a9-896f-e189-0c2c-f87ff735df9c
* Version Independent ID: 97c8549b-66ad-0a23-1971-784fb923042a
* Content: [ASP.NET Core Module configuration reference](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-2.2)
* Content Source: [aspnetcore/host-and-deploy/aspnet-core-module.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/aspnet-core-module.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Drop the target runtime (RID) and try again

**Comment by pholly** [comment]
Ahh when I change it to `portable` the processPath is now `dotnet`. Thanks.

**Comment by guardrex** [comment]
Yes, thanks for mentioning this. I've felt it best for tooling and configuration to stabilize well before broaching the subject of how we describe configuration using the tooling. We have tabs for the docs, where we can put VS on a tab, VSC on a tab, CLI on a tab, etc. Going into Q1-2019, I think we're at a good spot to run thru the setup and config content and include instructions based on the tooling in use. Let's use this issue to track the work, and I hope to dig into this in Q1.

**Comment by Julian89757** [comment]
.netcore 2.2 aspnetcore module come up with  in-process host model,  
 Is there an official preference between in-process and out-process host model?
What are the advantages  between with the 2 host model?

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by guardrex** [comment]
@Rick-Anderson Our topics for host and deploy config are almost completely project-file based. As you know, many devs rely heavily on configuration property pages/panels in VS. Given the churn, I think that we made the right move in not putting a lot of effort in on this issue.

VS screens, property displays, etc. seem to have stabilized quite a bit. I left this issue open to track the work on updating our host and deploy tooling instructions with tabs to explain how to make these settings in IDEs generally, and VS specifically.

**Comment by guardrex** [comment]
@Rick-Anderson @scottaddie @tdykstra Let's confer on how/if we're going to proceed:

* CLI ... no probs, since ur editing the project file.
* VSC ... no probs, since ur editing the project file.
* VS and VS4Mac ... **_PROBS!_** ... Devs look for IDE property pages to set project characteristics that we're calling out in these topics, and the IDE takes care of changes to the project file.

My plan is to go thru our *Host and deploy* topic set and ...

* Where we say/show 'edit the project file', see if there are equivalent approaches for VS and VS4Mac in property pages. Drop in a tab control and explain the VS and VS4Mac property page approaches (**_no screenshots_**, of course). I'll combine tabs for the manual approach, which usually covers CLI and VSC.
* If there isn't an IDE property page approach, it's probably still wise to go with a tab control because VS and VS4Mac use their 'Edit the project file' scenario to even get the project file open in order to manually edit it.

The alternative is to *do nothing* and let the dev figure it out on their own. If we go that way, we can close this as a `wontfix`.

**Versioning Concern**

*Versioning* ... 🙈. Since the IDEs change so much, we might *do nothing*.

Even if we work this issue, let's wait until post VS2019 RTM so that we're doing this work for the most recent version. It's 💸 **_too costly_** 💸 to engage this now and then re-engage it within a few months ...

![thecollectorsm](https://user-images.githubusercontent.com/1622880/53699420-a2b63f00-3dad-11e9-81ba-4acfca93886b.jpg)

### *An unprofitable operation, Hade.*
&ndash; The Collector ([Henry Woolf](https://www.imdb.com/name/nm0941146/))
[Doctor Who](https://www.bbc.co.uk/programmes/b006q2x0): [The Sun Makers](https://www.bbc.co.uk/programmes/p00q05st), ©1977 [BBC](https://www.bbc.com/)

**Comment by Rick-Anderson** [comment]
This is an advanced topic. Dev's that don't know how to edit the project file can google that. Feel free to put instructions at the top of this issue and retitle the issue.
