### ISSUE TITLE
Is there an equivalent article to use user secrets in console/unit test projects? 

### ISSUE THREAD

**Issue by samsmithnz** [aspnet/Docs#10053]
There seems to be a lot of content for using secrets in ASP.NET Core. This is great. https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-2.2&tabs=windows

However, this content does not exist for other types of applications. This is a problem.

For example, what happens when you need to use a secret in a console or unit (technically integration) test project? Typically you'd want to keep your secrets out of the source code for these types of projects and connect to external resources using Azure Key Vault, but this guidance does not exist. It seems that to achieve this today, work arounds and hacks are needed. 

Examples:
- https://medium.com/@granthair5/how-to-add-and-use-user-secrets-to-a-net-core-console-app-a0f169a8713f
- https://patrickhuber.github.io/2017/07/26/avoid-secrets-in-dot-net-core-tests.html

Given that security is so important, and Microsoft is pushing tools like credscan to remove secrets from code, I think this documentation would be helpful for developers.

Edit:
Or perhaps the recommendation is that these types of applications use environment variables?

**Comment by gsuttie** [comment]
I was just trying this very thing out in a sample app, not sure how to share code and make it runnable for end users - what are people doing? - looking forward to aswers

**Comment by guardrex** [comment]
Hello @samsmithnz ... There's nothing stopping secrets from working in tests as long as the SUT is tested in the Development environment. It should ✨ *Just Work*:tm: ✨. However, I haven't personally tried it, so I can't say from first-hand experience.

WRT console apps ... I don't see any reason why that scenario wouldn't just work as well. Keep in mind that this doc set isn't really about console apps ... we're all *web bits* here ... so that explains perhaps why we're a bit light on 'how to do this in a console app' coverage. You should be able to call `AddUserSecrets` on a config builder in a console app and get it working. https://docs.microsoft.com/aspnet/core/security/app-secrets#access-a-secret

> share code and make it runnable for end users

@gsuttie It's for development only. Secrets aren't meant to be used in a Production environment.

In general, *Yes* on env vars and Azure Key Vault. Those are common scenarios.

**Comment by guardrex** [comment]
I'm going to close as answered, but we can re-open to discuss further if you like. The main thing is just that the docs here on the aspnet/Docs repo are the *web docs*, focused on web workload scenarios.

WRT integration testing, User Secrets should work fine (in the Development environment). If anyone finds out otherwise, please open an issue on the [aspnet/AspNetCore issues](https://github.com/aspnet/AspNetCore/issues) for engineering to take a look.

**Comment by samsmithnz** [comment]
Thanks Guardrex. Appreciate the direction to use environment variables - makes sense given the increased usage of containers. I think the docs could benefit from even a short article on "What about if you aren't developing a web app" options type of doc, to direct people in this direction. I know you are always looking for ways to improve the docs. 

As a fairly experienced developer, in general, I found the Azure Key Vault documentation difficult to follow. It gets deep very very quickly. I think some of it could be split into multiple documents and more tutorials and quick starts could be useful. Perhaps if you sat behind someone who had never used Key Vault and watched how they used the documentation you would see what I mean.

**Comment by guardrex** [comment]
> Azure Key Vault documentation

The vast majority of it isn't owned by this team. We just have the following ...

* [Configure ASP.NET Core Data Protection: ProtectKeysWithAzureKeyVault](https://docs.microsoft.com/aspnet/core/security/data-protection/configuration/overview#protectkeyswithazurekeyvault)
* [Azure Key Vault configuration provider](https://docs.microsoft.com/aspnet/core/security/key-vault-configuration)

I have a couple of issues to work for the bits we have: https://github.com/aspnet/Docs/issues/6821 and https://github.com/aspnet/Docs/issues/7932.

Outside of that for other AKV topics in other repos, opening an issue using a **Content feedback** button (if one is present at the bottom of a topic) will allow you to provide feedback. There's also the `Is this page helpful? Yes No` box, but it only allows limited feedback.
