### ISSUE TITLE
Protecting Keys

### ISSUE THREAD

**Issue by hoksource** [aspnet/Docs#10087]
1. I stored the key to azure blob storage. The key is used for protecting cookies for authentication right? Then I also need to protect the key?

2. How do I use the ProtectKeysWithDpapiNG? I really have no idea what this documentation does https://docs.microsoft.com/en-us/windows/desktop/SecCNG/protection-descriptors
also what are those values WEBCREDENTIALS, SID, CERTIFICATE and so on and where do I get or create them?

3. If I didn't protect the keys at rest, what are my risks?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c24ccb9-b297-f942-ebf1-c994d672f183
* Version Independent ID: 5d6eb72e-b1b5-1507-6162-16a9a4a01aa0
* Content: [Key encryption At rest in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/key-encryption-at-rest?view=aspnetcore-2.2#certificate-based-encryption-with-windows-dpapi-ng)
* Content Source: [aspnetcore/security/data-protection/implementation/key-encryption-at-rest.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/data-protection/implementation/key-encryption-at-rest.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by manigandham** [comment]
The Data Protection system provides a simple API to encrypt and decrypt data using a key. Ths risk is that anyone who has access to this key can also encrypt and decrypt that data so keeping it safe is critical for security.

Normally the DP-API will automatically create keys (which are XML files with certificates and metadata inside) and save them locally, while also encrypting the contents by using other APIs from the operating system. If you change the settings to store the keys somewhere else, then the normal key encryption is also turned off so you'll need to configure that separately if you want it. The easiest option is using Azure Key Vault (since you're already storing the keys in Azure Blob Storage).

DPAPI and DPAPI-NG (a newer version) only work on Windows. The first only works on a single machine so it's not a good option. The second requires an ActiveDirectory domain so it's only useful for enterprise Windows deployments. Again, if you don't have experience with this, I highly recommend using the Azure Key Vault option as it just takes a few clicks to create it in the portal.

If the Azure Blob Container you're using is very locked down and only being used to store these keys, then that might be good enough for simpler apps since nothing else can access that storage account to get the keys in the first place.

**Comment by Rick-Anderson** [comment]
@blowdart 	should I add this info to the article?

**Comment by hoksource** [comment]
Thank you very much for the prompt response. That clarifies that encrypting the keys at rest is optional with key vault assuming no one can else can access the blob container. but scaling the app later you might need to do it also.

**Comment by blowdart** [comment]
@Rick-Anderson it's in there already; https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-2.2
