### ISSUE TITLE
Why we must set the `UseAppHost` in netcoreapp2.1?

### ISSUE THREAD

**Issue by baruchiro** [aspnet/Docs#10114]
If I remove him in netcoreapp2.1, I can execute my app in both Windows and Linux, and also register my app as Windows Service.
But if I set `UseAppHost` to `true`, I can't set the `RuntimeIdentifiers` to bot `win-x64` and `linux-x64`.

So I think we need more explanation about this tag.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0bd8cb8-7e28-8c4d-a550-3aea8f3ab4dd
* Version Independent ID: 4b60d24e-ef05-15e5-10b4-483094081bf3
* Content: [Host ASP.NET Core in a Windows Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.1#manage-the-service)
* Content Source: [aspnetcore/host-and-deploy/windows-service.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/windows-service.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
Hello @baruchiro ...

Possibly so, but I'm unclear on your scenario: Can you describe in more detail what type of deployment model (FDE or SCD) you're trying to adopt and how you're trying to run the app (as an app or as a service) for each platform (Windows and Linux)?

I'm wondering why you don't use the SCD approach for all of your deployments. It sounds like you're trying to run as an **_app_** on local Windows and Linux and also register as a **_Windows Service_** for a Windows machine somewhere else. If so, I wonder why not just go for SCD.

IIRC, the `UseAppHost` property was required in 2.1 to make sure that the service would get an activation path (an EXE) in the FDD scenario ... thus producing a working FDE. For 2.2, that's no longer needed ... they made updates to make the SDK *smarter* :smile:. I think (*wildly guess*) that if you ran into trouble removing `UseAppHost` with multiple RIDs that you hit an unsupported scenario for the 2.1 SDK ... it might have been something that they just didn't set up the SDK to support.

btw--- You're not using 2.2 ... just wondering why? There were updates (improvements) to the SDK between 2.1 and 2.2 that changed the need to set `UseAppHost`.

We can ping the engineers for input, but we need to wait until next week to do that. Everyone is out for the ❄️holidays ⛄️ right now.

**Comment by baruchiro** [comment]
OK. My situation is porting a WindowsService API app to .NET Core.
The app should be FDD, and compiled with .NET Core 2.1. This is my company requirements.

So, first I think that is unclear what is our options in netcoreapp2.1 FDD, but maybe because today we have netcoreapp2.2 it is not very important anymore.

You say in netcoreapp2.1 we use `UseAppHost` to get `exe` (to run as win service).
This is very confusing me.

- Why we need `exe`? We can create win service with `binpath="dotnet myservice.dll"`
- Why we want `exe`? With FDD we always getting one dll to executing cross platformly by `dotnet` command.

The big question is **what happened if I will create an FDD service without `UseAppHost` compiled as netcoreapp2.1?**

From our entire conversation it is clear that information is missing.

**Comment by guardrex** [comment]
> unclear what is our options in netcoreapp2.1 FDD

> Why we need exe? We can create win service with binpath="dotnet myservice.dll"

Yes ... what the topic covers was **_by-design_**. We may expand the coverage tho.

Just a bit of history first: The original Windows Service hosting model wasn't FDD at all prior to 2.1. It was SCD-only before that. Even for 2.1, the approach we pushed in the topic remained SCD-only (probably just because we were super-busy 🏃😅 and didn't update it). It was updated to include an FDD approach for 2.2 on https://github.com/aspnet/Docs/pull/9667, and the approach for both 2.1 FDD and 2.2 FDD is specifically for FDE (Framework-Dependent **Executable**). FDE (with the EXE) **_IS_** FDD ... but ... BUT ... it's based on using an EXE to get the service activated over using the `dotnet` command as you correctly point out. By the time we arrived at putting FDD into the topic, 2.2 was here :tada:. At 2.2, FDD is covered (as FDE actually) without having to call `UseAppHost` due to engineering updates for 2.2.

Anyway, the reason a 2.1 (or 2.2 for that matter) **_PURE FDD_** approach isn't covered in the topic is that covering activation with the `dotnet` command would have added another service deployment model to the topic. It's simpler for most use cases ... developing on Windows and running as a service on Windows ... to cover:

  * FDE (FDD with the EXE)
  * SCD

... because either way (FDE/FDD or SCD) the service registration involves activating the app the same way ... **_via an EXE_**. It just makes the service registration explanation simpler to not describe a true pure FDD approach and the (slightly) different set up to use the `dotnet` command.

However, it remains an open question: If you found out that multiple RIDs (specifically, including Linux to dev/test on Linux prior to deployment to Windows) work better when the service is set up as a true pure FDD, then we need to re-assess the coverage. That's a nice option for mixed platform cases if the FDE approach as-described fails for some reason. I'm a bit surprised it failed ... but kind'a not surprised at the same time. We're dealing with project file properties, :sparkles: *SDK magic* :sparkles:, and multiple platforms ... sometimes it can be a bit tricky to get some scenarios to work cleanly ... especially going back to earlier versions when there was engineering churn. *There was some significant engineering churn in SDK publishing bits back in the the 2.1 era.*

> The big question is what happened if I will create an FDD service without UseAppHost compiled as netcoreapp2.1?

Sure ... You can do that if you find it works best for your scenario.

* Only have `<SelfContained>false</SelfContained>`.
* Have multiple RIDs allow you to publish for each platform.
* Use a service registration with the `dotnet` command when you intend to publish for Windows as a Windows Service.

That sounds good. We don't cover it ... but that sounds good if it works well.

I think I've seen a couple of blogs on the pure FDD approach out around the Net; however, those blogs I think were Windows all the way: Run locally with Windows, and run on a Windows Server as a Windows Service. They probably had a single RID. I don't recall any of them talking about a cross-platform publishing (as a console app) of a Windows Service app.

You're raising some good issues. Engineering :cat2: :cat2: :cat2: are mostly out this week for the holiday. I'll ping them for help next week.

**Comment by guardrex** [comment]
@Tratcher @shirhatti @natemcmaster TL;DR ... When we did the last update to the WS topic, we went with the common denominator of SCD and FDE for the deployment. It was a easier to explain service registration with an EXE in-hand using those two deployment types. Do we need to expand coverage to include a pure FDD approach (registering the service to run with `dotnet` command)? I'm a little concerned about wrecking the topic (not opinionated enough and thus offering a confusing number of choices); but if you think we need pure FDD, then I don't see that we have any choice here.

**Comment by Tratcher** [comment]
I can see wanting to keep it simple. Maybe add a separate section at the end that covers the differences for pure FDD?

**Comment by guardrex** [comment]
> separate section at the end 

If we did that, then we should consider just breaking the topic into **_three independent approaches_** (i.e., sections) (in the following order; generally from most-to-least favored):

* FDE
* SCD
* FDD

... with an introduction that states the pros-and-cons of each approach. There would be a bit of content duplication, especially in the service registration commands across FDE and SCD; however, it would be dead simple to adopt any of the three approaches without confusing readers and without having readers read through content that doesn't apply to their chosen approach. Our ability to maintain the topic would also be enhanced going forward, too.

My recommendation is either to:

* Do nothing if FDD shouldn't generally be used and FDE is always preferred.
* Split into three independent sections if FDD useful setup/approach.

**Comment by Tratcher** [comment]
I'll defer to @shirhatti on the desirability of FDD, and to you on layout.

**Comment by natemcmaster** [comment]
I don't have a preference whether we show FDD or FDE. The only reason I opened https://github.com/aspnet/Docs/issues/9214 is that I wanted customers to be aware that they could do Windows Services without doing self-contained. If FDE is still too confusing, I'm okay if we just change the docs to show users how to run "dotnet MyApp.dll" instead.

FWIW, thought. In .NET Core 3.0, the FDE should be generated by default. Not special RID or UseAppHost project properties required.

**Comment by guardrex** [comment]
> If FDE is still too confusing, I'm okay if we just change the docs to show users how to run "dotnet MyApp.dll" instead.

It was the other way around. Because FDE produces an EXE and SCD produces an EXE, it made the service registrations easier to explain. All of the commands are using the same thing ... an EXE.

If the topic introduces FDD, then there will be two sets of commands ... EXE and `dotnet` flavors. That's after splitting the earlier content between FDE, SCD, and FDD ... in other words ... a BIG mess of a topic unless completely independent sections are created for these approaches.

> the FDE should be generated by default.

That lends to the **_do nothing_** notion and to just leave the topic as-is.

To justify the addition of an FDD section and have a big shakeup on the current organization, I think it comes down to how useful FDD is relative to FDE ...

#### Is there anything that FDD can do (makes easier, improves, makes possible) over FDE?

If the answer is generally 'no,' then I think the best course here is to **_do nothing_**.

**Comment by natemcmaster** [comment]
I'm okay with "do nothing". 

I'm also okay with adding a couple of clarifying comments to the doc
```xml
  <!-- These properties instruct the SDK generate an .exe file for Windows. -->
  <RuntimeIdentifier>win7-x64</RuntimeIdentifier>
  <SelfContained>false</SelfContained>
  <!-- This property disables web.config generation because that file is unnecessary for Windows Services. -->
  <IsTransformWebConfigDisabled>true</IsTransformWebConfigDisabled>
```
