### ISSUE TITLE
Rethink Fundamentals and Other topics nodes of ToC

### ISSUE THREAD

**Issue by tdykstra** [aspnet/Docs#10210]
The treejack study revealed a lot of confusion surrounding the **Fundamentals** and **Other** topics nodes of the ToC.  

* **Fundamentals** refers to tasks that apply to all app types. Are there other task-based groupings that this block of articles could be divided up into?
* If we do keep an umbrella node for tasks not specific to an app type, can we come up with a better name?
* Eliminate **Other topics** node and incorporate its content into **Fundamentals** or whatever replaces it. 
* Can some articles now under **Fundamentals** be moved to specific subject areas, like **Hosting**, **Security**, **Testing**, etc.?
* Wrong place for this article and other articles in the tree view of Microsoft Docs #10431

**Comment by guardrex** [comment]
Here's a few i-dears ...

* *URL rewriting* is based on the URL Rewriting Middleware ... that one could go in the *Fundamentals* > *Middleware* node. **_However,_** I'm about to push back **HARD** on this idea in a sec&dagger;.

* The *Request Features* topic content could (with some trimming) become a section of the *Servers* topic. Let me know if you'd like me to do that.

* *Access HttpContext* could be a triple entry: One appearance in each of the following nodes: *Web apps*, *Web APIs*, and *Real-time apps*. Alternatively, the sections of the *Access HttpContext* topic could be broken out and placed into relevant *Overview* topics in the TOC (the *from custom components* section of the topic is probably hard to place tho).

* You moved the *Hosting startup* topic [against the wishes of engineering](https://github.com/aspnet/Docs/issues/6896#issuecomment-395069532) 😨, but you couldn't have known about that convo 😅. David wanted it under *Host*. My concern now about this is that ... *hold on* ... *hold a sec* ... this ties into my earlier remark on the *URL rewriting* topic. Will circle back to this in a sec. I actually *don't* think that this should go *back* into the *Host* node&dagger;.

* The `All` package topic could be deleted and redirected to wherever `App` ends up with a note about it going away. All of the `App` content could be placed into the *Fundamentals* > *Overview* (perhaps with some trimming).

#### &dagger;*Fundamentals reading experience*

We hashed this out in the *Servers* node issue/PR discussion, and I think we all agree that a newbie coming in here is better off starting with a basic set of general scenario topics, our *fundamentals topic set*. That prior *Servers* node had become crazy busy with configuration details not germane to getting one's head wrapped around the basic concepts and server options for hosting ASP.NET Core apps. I'm super-:grinning: that we did that!

Just like *Servers*, *Host* could become a single *Fundamentals* node topic that only describes the Generic Host after the Web Host goes bye-bye :wave: at 3.0. Placing the *Hosting startup* topic back there breaks the opportunity to have a clean set of basic topics under the *Fundamentals* node. *Hosting startup* should go elsewhere.

Continuing that point, I feel the same way about the *Fundamentals* > *Middleware* node: I'd like to see that become **_one Middleware topic_** and have those subtopics go elsewhere.

*But where is elsewhere?*

There are "fundamentals" and "advanced scenarios," so that's one option to consider ... *Advanced scenarios* rather than *Other topics*. I think 🤔 that node would be better directly under the *Fundamentals* node in the TOC and not way down at the bottom where *Other topics* lives today.

**Comment by tdykstra** [comment]
Resolved by creating issues for various plans made -- #10458 #10459 #10460 #10456 #10454 #10452
