### ISSUE TITLE
Release the updates only when VS is updated with the SDK

### ISSUE THREAD

**Issue by gbjbaanb** [aspnet/Docs#10355]
I do this every time - asp.net updates, so i update and then... "The current .NET SDK does not support targeting .NET Core 2.2"

I don't want to update the SDK separately, been there and been burned in the past, so I'd love for you to make these releases only when the Visual Studio update containing the required SDK is also released.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46a10a5c-bacc-1bcf-a7ae-499715e1bfdd
* Version Independent ID: 1585163b-b1d7-eeb8-ebc6-adfc2730f393
* Content: [Migrate from ASP.NET Core 2.1 to 2.2](https://docs.microsoft.com/en-us/aspnet/core/migration/21-to-22?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/migration/21-to-22.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/migration/21-to-22.md)
* Product: **aspnet-core**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
Hello @gbjbaanb ... We don't handle product feedback here on the documentation repo ... just docs issues. You can leave feedback for the engineers and management on the aspnet/AspNetCore repo issues:

https://github.com/aspnet/AspNetCore/issues

**Comment by guardrex** [comment]
@malachib When an issue is closed, please open a new issue using the **Content feedback** button from the bottom of any topic.

WRT to your ask:

You're correct. We don't report that information in this doc set, since we're mostly concerned with the ASP.NET Core aspects. Also, the .NET Core docs folks are mostly concerned with the tooling, language, and framework issues, so they probably don't report that information either.

It might be something that the VS folks report with their release notes ...

https://docs.microsoft.com/visualstudio/releasenotes/vs2017-relnotes

... give that a shot and see what they report.

**Comment by malachib** [comment]
@guardrex I will definitely use the Content feedback button, though I'd like to mention I specifically _didn't_ use it because I assumed it was a one-way classic "hidden" feedback.  Didn't realize it (seems to) produce a discussion.  Thank you for pointing it out

Also, I had already looked at the vs2017-relnotes, but as you can see there's only one mention of ASP.NET Core there and it doesn't include a version.  Also - I promise, I am not trying to be a pain - _that_ page doesn't have the nifty comment feature so unlike this one making the suggestion involves initiating a visual studio feature request.  

Heh, I guess with the effort we've both put in I could have done that by now, but that certainly wasn't my first instinct

**Comment by guardrex** [comment]
> it was a one-way classic "hidden" feedback

Ah ... good point. I wonder how many times that happens. I'll open an issue about that at Microsoft Docs. There's an opportunity there to tell readers what that form does.

WRT the issue: I see. This is good feedback, so I recommend:

1. Submit it via the **Report a problem** process built into VS that their release notes could indicate which .NET Core SDK version ships with each release. That process opens an issue for that team, and I guarantee that a *human* will see it :eyes:.

1. For topic coverage, open an issue over on the VS docs at: https://github.com/MicrosoftDocs/visualstudio-docs/issues ... that seems like the best bet. I double-checked the .NET Core docs, and they really don't get into the VS tooling flavors and tooling versions ... just the dotnet CLI ... that's all they really focus on.

**Comment by malachib** [comment]
Thanks for your attention to detail!  Filling out the stuff now...
