### ISSUE TITLE
502.5

### ISSUE THREAD

**Issue by kkilton** [aspnet/Docs#10464]
After installing the Core hosting runtime, you have to IISRESET. I spent hours trying to figure out why I kept getting this error even though dotnet --info was showing that everything was installed correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4f16c68-708b-003e-8c63-1df60c6344d0
* Version Independent ID: 25fa0508-4450-9051-cdd7-0d3260c60b4f
* Content: [Troubleshoot ASP.NET Core on IIS](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/troubleshoot?view=aspnetcore-2.2)
* Content Source: [aspnetcore/host-and-deploy/iis/troubleshoot.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/iis/troubleshoot.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @kkilton ... It's covered in the IIS topic here (Step 2) ...

https://docs.microsoft.com/aspnet/core/host-and-deploy/iis/#install-the-hosting-bundle

It should also be covered as this common error ...

https://docs.microsoft.com/aspnet/core/host-and-deploy/azure-iis-errors-reference#incorrect-processpath-missing-path-variable-hosting-bundle-not-installed-systemiis-not-restarted-vc-redistributable-not-installed-or-dotnetexe-access-violation

... with the entry that applies being ...

> An FDD may have been deployed and .NET Core installed without restarting IIS. Either restart the server or restart IIS by executing net stop was /y followed by net start w3svc from a command prompt.

This error scenario does rise to the level of a *Troubleshoot* topic entry. Obviously, we can't cover them all there ... that's what the *Common errors* topic exists. I'll add a section there.

I'll also confirm the error conditions because it sounds like they didn't match your browser (502.5) or logging.

Thanks for reporting this @kkilton.

**Comment by kkilton** [comment]
Thanks!

**Comment by guardrex** [comment]
Sure thing ... leave this open ... it will auto-close when the PR merges.

**Comment by guardrex** [comment]
@Rick-Anderson I don't think we should go this way after all. I looked things over, and our current approach (beyond the instruction in the IIS topic, which is good imo) is to cover the common errors for IIS in the IIS/Azure Apps common errors topic.

The *Test, debug, and troubleshoot* > *Troubleshoot* topic can, as it does today, pertain to *other* problem scenarios that don't fit neatly elsewhere (e.g., SDK warnings in VS and the code we show to obtain info from an unruly app). We do cross-link the top of *Troubleshoot* topic here to the IIS/Azure troubleshooting topics and common errors. I think we're ok here.

Thanks again tho to @kkilton for reporting. We will keep an eye on things to see if devs hit this more frequently in the future.
