### ISSUE TITLE
License

### ISSUE THREAD

**Issue by shirhatti** [aspnet/Docs#1046]
What license is the published documentation and included sample code published under?

**Comment by danroth27** [comment]
Anything in the repo (sample code, .rst) is under the license specified by the [LICENCE.txt](https://github.com/aspnet/Docs/blob/master/LICENSE.txt), which is an Apache v2 license.

The published content should be under the [CC-BY-NC](http://creativecommons.org/licenses/by-nc/3.0/) license

**Comment by shirhatti** [comment]
I suggest we modify the footer to make the license explicit.
You can assign it to me, it should be a quick fix

**Comment by Thibaut** [comment]
@danroth27 - Hi, any reason why the ASP.NET docs are licensed under CC BY-NC instead of CC BY, like the [.NET Core docs](https://github.com/dotnet/core-docs/blob/master/license.txt)?

The NC clause makes the docs incompatible with open source. I'm looking to add them to [DevDocs](http://devdocs.io) (https://github.com/Thibaut/devdocs), a popular documentation browser.

Thanks
