### ISSUE TITLE
Update API ref docs

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#1047]
Requires docfx to add support for .NET CLI projects. See https://github.com/dotnet/docfx/issues/137

**Comment by svick** [comment]
I think this is pretty critical. When I want to use an API I don't know, I have pretty much two options:

1. rely on documentation
2. rely on IntelliSense

Because of this, I can't do 1. And if I want to use just a text editor (no VS, Code or OmniSharp), which is being promoted as an acceptable way to do things in Core, I can't do 2 either.

**Comment by danroth27** [comment]
@svick Totally agree! We're working on it.
