### ISSUE TITLE
Unable to host multiple asp.net core application on linux server

### ISSUE THREAD

**Issue by saswatsaubhagya** [aspnet/Docs#10536]
Hello there i am new to the asp.net core, But i have experience on asp.net web-form and asp.net mvc. 
Actually before i host my application on windows server IIS. But now i try to host on Linux server (Ubuntu with Apache 2).
I followed all the Linux server deployment documentation and successfully host the application. But the problem is i only able to host a single application on a server. my requirement is to host multiple application under a single ip . 

So please describe  how could i host multiple web application on linux environment.

Thank you.

**Comment by guardrex** [comment]
@shirhatti

**Comment by shirhatti** [comment]
https://github.com/aspnet/Docs/issues/9851#issuecomment-445306174

As a convenience, we've setup a single virtual host that binds to all host names. If you want to host multiple hostnames, setup up different virtual host instead of a wildcard binding

**Comment by guardrex** [comment]
> setup up different virtual host instead of a wildcard binding

... will be covered in many external topics. Closing as answered; but if we receive this question regularly, we may need to expand coverage in the future.

**Comment by guardrex** [comment]
Yes, consult documentation on virtual hosts. For example ...

* http://httpd.apache.org/docs/2.4/vhosts/
* https://geekflare.com/multiple-domains-on-one-server-with-apache-nginx/

If you need additional support, consult devs on a support forum, such as Stack Overflow, or a support chat such as Slack or Gitter. I'm the wrong person to ask about this because my Linux experience is limited to RPi ... and not with Core ... and not using RPi as any kind of server. I'm sure if you Google around and ask on a few forums/chats that you'll get plenty of help.
