### ISSUE TITLE
What's the relationship between the service configuration here and the one inside Startup?

### ISSUE THREAD

**Issue by nicholasyin** [aspnet/Docs#10564]
I am a bit surprised to see that the custom WebApplicationFactory still has the specification of Startup class. I think it's more intuitive to eliminate the use and get ignorant of the real Startup class, as its name TestServer could imply that it already has all the information of running a testing host, without the knowledge of the real Startup class.
Anyway, what's consequences of having 2 different places to configure the IServiceCollection for a test server? By debugging, the configuration in custom WebApplicationFactory runs first, then it's the configuration in Startup's ConfigureService method. So will they work in an overriding style, or only-effective-when-not-configured style?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.1)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by nicholasyin** [comment]
It looks like the use of real Startup class is to configure the test server with the same configuration as the real server. So this part makes sense to me now. But still the last question remains: how do the 2 places of configuration work, when they actually configure the same server feature?

**Comment by guardrex** [comment]
Hello @nicholasyin ... We can't address your engineering question directly here on the docs repo unless Javier would like to comment on that here. We just handle doc issues (*mostly* lol).

> consequences of having 2 different places to configure the IServiceCollection for a test server?

That's a good ask because we *don't say* in the topic. To complicate matters a bit further (and we probably do a better job with it), there's `ConfigureTestServices` for mocking in a test. That section that pertains to mocking and `ConfigureTestServices` is probably ok as it is.

@javiercn What would you like me to add about SUT `Startup` versus the startup provided by `ConfigureWebHost` `IWebHostBuilder`'s `ConfigureServices` ... just say that `ConfigureWebHost` appends/overrides the SUT's services?

**Comment by javiercn** [comment]
> how do the 2 places of configuration work, when they actually configure the same server feature?

If you call ConfigureServices on the custom WAF it will run before startup.ConfigureServices, you can override services this way if your startup class uses the tryaddXXX pattern.

For other cases there's a ConfigureTestServices extension method that you can call and that will run after Startup.ConfigureServices.

ConfigureTestServices requires that the app has a void ConfigureServices(IServiceCollection services) signature.
