### ISSUE TITLE
No Action From 'dnx' With CoreCLR

### ISSUE THREAD

**Issue by vindicatorr** [aspnet/Docs#1057]
Archlinux
```
$ DNX_BRANCH=dev sh dnvmInstall.sh
$ source ~/.dnx/dnvm/dnvm.sh
$ echo "source ~/.dnx/dnvm/dnvm.sh" | tee --append ~/.bashrc
$ dnvm upgrade -runtime coreclr -unstable
$ dnvm install latest -persistent -runtime coreclr -unstable
```
```
$ cd Home/samples/ConsoleApp
$ dnu restore
$ //nothing but prompt after return
```

**Comment by danroth27** [comment]
No support for Archlinux at this time. Adding @halter73 in case he has additional thoughts on this.

**Comment by halter73** [comment]
Arch Linux is my distro of choice. In the early dnx days things actually worked, but as dependencies were added such as libunwind and the like, it was too painful to keep ally the dependency versions in sync and working.

It's probably possible to get working, but I've since started using Ubuntu since that's one of the distros supported by .NET Core. It's not worth my time at the moment to be that far off the happy path.

**Comment by vindicatorr** [comment]
But don't those deps eventually transcend all of the dists? I'd bank on arch being on the fringe for updates and other dists are more conservative in their timing, but eventually they would all get there, right?
Call Arch a preview of what's to come.
