### ISSUE TITLE
Publish to a Windows Virtual Machine on Azure 

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#107]
ASP.NET 5 -> Publishing and Deployment -> Publish to a Windows Virtual Machine on Azure

**Comment by slamidtfyn** [comment]
Hi

If there is any draft versions of this part of the documentation i would like to see this. I have a lot of trouble getting this up and running.

Br
Søren Larsen
slamidtfyn at gmail dot com

**Comment by GuardRex** [comment]
@slamidtfyn I probably can assist you with that but I won't get back to the office for 2 hours. In the meantime, open an issue in Home repo with the details on where you're having an issue. If u don't get help, I'll get back to you by 4pm PST.

**Comment by murilocurti** [comment]
This topic will cover deploying to a Cloud Service too?
This is very important. One case that is priority for us is that Cloud Services is the only way to communicate with a VPN site to site on azure.
If you could share some drafts we can test them.

Thanks!

**Comment by GuardRex** [comment]
@murilocurti .NET 5 is not supported for Cloud Services.

**Comment by murilocurti** [comment]
@GuardRex It will never be? Is there any technical reason for that?

**Comment by GuardRex** [comment]
@murilocurti They haven't ruled it out, but it will not make RTM based on looking at the issues. They also don't have it on the roadmap. They only specifically mention VB, SignalR, and Web Pages after RTM.

Technically, yes, they would prob have some serious work to do to wire things together with the Cloud Services service configuration. My advice ... do what you're trying to do with your VPN setup using an Azure IIS VM.

**Comment by GuardRex** [comment]
... or Azure Web App, which is also supported.

**Comment by murilocurti** [comment]
hmmmm OK I will take this way, but I will continue investigating this scenario.
Thank you @GuardRex

**Comment by hyrmedia** [comment]
Is there *any* documentation currently available out there on publishing ASP.NET web applications to an Azure VM from within Visual Studio 2015?

**Comment by GuardRex** [comment]
https://docs.asp.net/en/latest/publishing/index.html

**Comment by hyrmedia** [comment]
@GuardRex That's the site that pointed me here in the first place.

See: https://docs.asp.net/en/latest/publishing/azure-windows-vm.html

**Comment by GuardRex** [comment]
@hyrmedia I see. I'm sure you're aware that it's not significantly different from publishing to an on-premises VM. Did you want to publish outside of using Web Deploy? I've been using a (crappy; because I wrote it :smile:) [PowerShell script](https://github.com/GuardRex/net5-iis-ps-publish) to publish to some VM's, where I didn't have WebDeploy available. I intend to stick with PS publishing, because I'll be using a number of Nano Servers in the future. I've never been a big fan of XCopy. I've used a network fileshare to Azure VM's, but I'm sure you know what a pain that is to do.

Those are the major options right now ...

1. Copy bits via SMB file share
2. XCopy
3. Web Deploy (either via the VS Publish or with a custom script* that you can trigger from the Publish to filesystem VS Publish)
4. PowerShell homebrew script

*If you want to see an example of such a custom Web Deploy script, let me know, and I'll paste it in here.

**Comment by danroth27** [comment]
We think what we have in the Publishing to IIS article is sufficient.
