### ISSUE TITLE
/fundamentals/routing "Routing"

### ISSUE THREAD

**Issue by ardalis** [aspnet/Docs#1077]
- [ ]  Fix tables so they don't scroll
- [ ] •Most apps shouldn’t need custom routes - That needs to be in intro.
- [ ]  Needs UE review (Create an instance of RouteBuilder, passing a reference to IApplicationBuilder. don't write in english what's in code)
- [ ] Explain snippets
- [ ] Explain when/why you would use routing
- [ ]  Explain the relationship between the routing middleware and MVC template routing.
- [ ] #1625
- [x] more exposition about the technical process of link generation.
- [ ] What parts apply to Razor Pages?
- [ ] Map[Verb] extensions will need their own section.
- [ ] rewrite startup section/code

In RC2 Middleware later in the request pipeline can access route data using extensions methods on `HttpContext`. 
Also this behavior is updated to use an IRouteHandler.
An IRouter instance returns a delegate, or null (indicating the request was not handled).

**Comment by kichalla** [comment]
I am not clear from the above text that if the following scenario is handled, but I will just put it here so that it doesn't get missed, sorry..

- We can now have conventional routing to middleware where you can define route templates with parameters and get a middleware/middleware-pipeline to be executed.

@rynowak

**Comment by Rick-Anderson** [comment]
Moved to #9239
