### ISSUE TITLE
he following tasks did not complete: min:js Bundle & minify

### ISSUE THREAD

**Issue by egbertn** [aspnet/Docs#10835]
[17:28:36] Starting 'min:js'...
[17:28:36] The following tasks did not complete: min:js
[17:28:36] Did you forget to signal async completion?
Process terminated with code 1.

Is the task correctly defined?
gulp.task('min:js',
    () =&gt; merge(getBundles(regex.js).map(bundle =&gt; {
        return gulp.src(bundle.inputFiles, { base: '.' })
            .pipe(concat(bundle.outputFileName))
            .pipe(uglify())
            .pipe(gulp.dest('.'));
    })));

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36f55e9a-cd3f-83a0-f142-969dc10d3ceb
* Version Independent ID: f6845f70-1ac6-2036-f213-a3b665b3d8bf
* Content: [Bundle and minify static assets in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/bundling-and-minification?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/client-side/bundling-and-minification.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/bundling-and-minification.md)
* Product: **aspnet-core**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by buchatsky** [comment]
I simply used 'merge2' instead of 'merge-stream', it does not produce such error.
Using async task functions has one shortcoming: in case of compound task its subtasks are performed asynchronously despite of gulp.series() so when output from the 1-st subtask serves as an input for the 2-nd one it might not be ready yet.
For ex., to have both minified and non-minified bundle versions I used the following bundleconfig.js:

```
[
    {
        "outputFileName": "wwwroot/js/site.bundle.js",
        "inputFiles": [
            "wwwroot/js/**/*.js",
            "!wwwroot/js/*.bundle*.js"
        ],
        "minify": {
            "enabled": false
        }
    },
    {
        "outputFileName": "wwwroot/js/site.bundle.min.js",
        "inputFiles": [
            "wwwroot/js/site.bundle.js"
        ],
        "minify": {
            "enabled": true
        }
    }
]
```
and got the error:
"File not found with singular glob: proj_path/wwwroot/js/site.bundle.js"
