### ISSUE TITLE
Cannot implicitly convert type System.Net.Mail.MailAddress to SendGrid.Helpers.Mail.EmailAddress

### ISSUE THREAD

**Issue by GuitarHero1969** [aspnet/Docs#10902]
[EDIT] I fixed the code block. Stand-by @GuitarHero1969 ... one of the team members will respond shortly.

I'm trying to follow this:
https://docs.microsoft.com/en-us/aspnet/web-forms/overview/security/create-a-secure-aspnet-web-forms-app-with-user-registration-email-confirmation-and-password-reset

but getting the above type cast error for the new MailAddress object:

```csharp
private async Task configSendGridasync(IdentityMessage message)
{
    var myMessage = new SendGridMessage();

    myMessage.AddTo(message.Destination);
    myMessage.From = 
        new System.Net.Mail.MailAddress(
            "Royce@contoso.com", "Royce Sellars (Contoso Admin)");
```

@Rick-Anderson 	edit: 4K PV, 40% CSAT

**Comment by GuitarHero1969** [comment]
What makes me so angry is the wasted time caused by the authors of these articles who are (supposedly) professional MS developers who get paid a lot of money and get to sit there in sunny California.

**Comment by guardrex** [comment]
I just took a peek, and it's not surprising that things have broken in the topic after **_five years_** (it was written in 2014). I was just looking at https://sendgrid.com/docs/for-developers/sending-email/v2-csharp-code-example/, and the 🧀 has moved. This is the first issue I've seen on this topic in the past ~2 years. Just for the moment until the topic is eyeballed by management, I think your best bet is to use the SendGrid docs and examples. I know that's not a satisfying answer, but it's the best approach at the moment until this is looked into by management.

**Comment by GuitarHero1969** [comment]
Ok, thanks I'm not sure I understand why things would break, perhaps I should look at 'Mailkit' instead ?
... and the cheese has moved.  (lol what on earth does that mean ?)

**Comment by guardrex** [comment]
It's just an expression ... "the 🧀 has moved" ... "the code has changed."

SendGrid has made updates, and MS has updated `System.Net.Mail` over the years. If you exactly used the SendGrid version (I guess v1) and used the .NET Framework from the time that the topic was written, which would be approximately .NET Framework 4.5.2, then it might still work ...... *maybe!* It might still work if the :pray: *server gods* :pray: are happy with you (*Dear server gods, please make this work!* lol). It's not surprising that after five years that it would break using late-model SendGrid API (v2) and the latest .NET Framework.

It seems like ALL of the docs would be tracked and updated regularly. The problem is 💰 *cost* 💰. The ASP.NET and ASP.NET Core doc sets are *hugenormous*:tm: (huge and enormous!) ... the doc sets are so large that it's prohibitively expensive to look at all of them constantly. We do need the community's help to let us know when a topic isn't working, so we thank you :+1: for letting us know about this topic. Management will look and see what we need to do here now.

**Comment by Rick-Anderson** [comment]
@guardrex 	is correct, SendGrid has changed their API several times and for security reasons it's not backwards compatible.

Look at https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-2.2&tabs=visual-studio#enable-account-confirmation-and-password-recovery
