### ISSUE TITLE
Upgrading the sample from core 1 to 2.2

### ISSUE THREAD

**Issue by shadinamrouti** [aspnet/Docs#10944]
Can I upgrade the sample? it's an outdated core 1 xproj. 
I will review the document as well for any reference from the code although it's distracting the users by having lots of external links (I won't remove them until we decide about them) :D 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08d2cf2e-55fb-33a4-b1d4-c97b2d531741
* Version Independent ID: f9a790d8-f25b-0e1d-eb63-c8ed3ac518cf
* Content: [Dependency injection into controllers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/dependency-injection?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/controllers/dependency-injection.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/controllers/dependency-injection.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@shadinamrouti 	 that would be great. CC/ @tdykstra 	@scottaddie

**Comment by Rick-Anderson** [comment]
Many/most? of the external links can probably be removed. DI is pretty well document outside MS.

Bonus points if you can add some Razor Pages(RP) samples and update the article to include mentioning RP.

**Comment by Rick-Anderson** [comment]
Article needs a UE scrub. For example, replace
Implementing an interface like this one so that it uses the system clock at runtime is trivial:

With
The following code implements the `IDateTime` interface.

Rather than update the project to 2.2 - start with a new 2.2 project and add the code in the article.

**Comment by shadinamrouti** [comment]
@Rick-Anderson  all is done except a Razor Pages (PR) sample. We may add it in a future pull request or if I was hired by Microsoft :D and adding a PR sample is in my tasks lists :D

**Comment by Rick-Anderson** [comment]
@shadinamrouti 	thanks so much for helping out on this. Take a look at the live version. It's about half as long as the previous version. The original was far to wordy and had bizzare instructions that don't work - for example, run it and you might get this error because I'm giving instructions in the wrong order. No might, guaranteed to fail. Better to put instructions in the correct order.

Take a look at the MD file now or maybe [files changed](https://github.com/aspnet/Docs/pull/11034/files). I removed all the range numbers. Snippets are vastly better. That should give you a head start on your next PR 👍 

Thanks again for all your help and getting this started.

**Comment by shadinamrouti** [comment]
I would like to thank you @Rick-Anderson for the excellent efforts👌 in rewriting it in clear error-free and easy-to-follow steps. I liked the snippet idea for quoting the code easily. Also thanks to @guardrex for the final helpful hints. This great teamwork can do great things in next PR's.
