### ISSUE TITLE
No Authentication?

### ISSUE THREAD

**Issue by gianlazz** [aspnet/Docs#10955]
Does Razor Components projects not support the usual aspnet core individual authentication option like I've come to expect with Razor Pages & MVC? If not that really limits my practical use cases.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8227c67e-83bb-dee3-e31c-73097df59614
* Version Independent ID: e7b564a3-b078-c390-15ba-b5044bd4edec
* Content: [Get started with Razor Components](https://docs.microsoft.com/en-us/aspnet/core/razor-components/get-started?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/razor-components/get-started.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-components/get-started.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @gianlazz ... It's under discussion and deliberation. They'll need to do quite a bit of work on the security side before they can support an official approach on how to handle it. Search the web for blogs and the aspnet/AspNetCore issues on the subject while they work on an official solution. I'm aware that devs are creating 3rd party/unsupported/unofficial approaches at this time. For example, see: https://github.com/aspnet/AspNetCore/issues/5472

**Comment by guardrex** [comment]
... and https://github.com/aspnet/AspNetCore/issues/4048

**Comment by josephayoung** [comment]
While we await official guidance, I wanted to share a decent authentication pattern I've been using:

- In `Startup.cs`, configure authentication using the normal `AuthenticationBuilder` as though you're configuring a normal MVC app, with OpenIdConnect, Cookies, etc. (Here I'm using an Azure AD B2C package, but behind the scenes it's doing all the normal stuff): 

```csharp
public void ConfigureServices(IServiceCollection services)
{
            services.AddRazorComponents<App.Startup>();

            services.AddAuthentication(o => o.DefaultAuthenticateScheme = AzureADB2CDefaults.CookieScheme)
                .AddAzureADB2C(options => Configuration.Bind("AzureAdB2C", options));
}
```

- Configure DI to inject both the `HttpContextAccessor` and the `ClaimsPrincipal` using that accessor (the latter for easier access in the components):

```csharp
    services.AddHttpContextAccessor();
    services.AddScoped<ClaimsPrincipal>(context => context.GetRequiredService<IHttpContextAccessor>()?.HttpContext?.User);
```

- In the server project, add a normal MVC controller that handles all of your sign-in/sign-out/etc. like you normally would, with methods like this:

``` csharp
public IActionResult SignIn([FromRoute] string scheme)
{
            scheme = scheme ?? AzureADB2CDefaults.AuthenticationScheme;
            var redirectUrl = Url.Content("~/");
            return Challenge(
                new AuthenticationProperties { RedirectUri = redirectUrl },
                scheme);
}
```

- In `Startup.Configure()`, make sure you call `UseAuthentication` and `UseMvcWithDefaultRoute` at the minimum:

```csharp
app.UseAuthentication();
app.UseMvcWithDefaultRoute();
```

- And then, anywhere you need the `ClaimsPrincipal`, you can just ask for it with a `@inject ClaimsPrincipal CurrentUser`. Here's an example using it in a nav bar:

```html
@inject ClaimsPrincipal CurrentUser

    <nav class="nav">
        <a href="/" class="logo">
            <img src="/images/logo.png" />
        </a>

        @if (CurrentUser.Identity.IsAuthenticated == false)
        {
            <div class="nav--right">
                <button onclick=@SignIn style="padding-right: 20px;">Log In</button>
                <!--If user is customer-->
                <cart-mini>
            </div>
        }
        else if (CurrentUser.IsInRole("Photographer"))
        {
            <div class="nav--center">
                <a href="/Photographer" class="menu-item">Dashboard</a>
                <a href="/Photographer/Cards" class="menu-item">Cards</a>
            </div>
            <div class="nav--right">
                <a href="/Photographer/SalesHistory"><img src="~/images/icons/alert.png" alt="notifications" /></a>
                <img src="@(CurrentUser.Avatar() ?? "~/images/avatar_512.png")" onclick=@ToggleDropdown class="profileImg" />
            </div>
      }
```

This pattern ended up feeling cleaner to me than the cascading parameter that the Blazor Pizza workshop uses (https://github.com/dotnet-presentations/blazor-workshop/tree/master/src/BlazingPizza.ComponentsLibrary/Authentication), mainly because I don't like the look of using `[CascadingParameter] public User User { get; set; }` everywhere. I'd rather be able to inject the principal (or a derivative of it) where I need it. 

I also didn't like injecting `IHttpContextAccessor` directly like some people have done, because that feels too ASP.NET-y, whereas `ClaimsPrincipal` is available in the client app without having to reference `Microsoft.AspNetCore.Http`.
