### ISSUE TITLE
`dotnet new webapi` template doesn't have individual authentication

### ISSUE THREAD

**Issue by phil-harmoniq** [aspnet/Docs#11002]
The example given shows these commands:

```c#
dotnet new mvc -au Individual
dotnet new webapi -au Individual
dotnet new webapp -au Individual
```

However, checking the command `dotnet new webapi --help` does not list "Individual" as a specification:

```
  -au|--auth                 The type of authentication to use
                                 None             - No authentication
                                 IndividualB2C    - Individual authentication with Azure AD B2C
                                 SingleOrg        - Organizational authentication for a single tenant
                                 Windows          - Windows authentication
                             Default: None
```

and trying to generate the project anyway using the suggested `dotnet new webapi -au Individual` command outputs a project that uses Azure AD B2C

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0676a8c8-8009-8a7e-72ac-7cde0013fb97
* Version Independent ID: e35e8811-07d1-ca9b-d6e7-e28c1d4b1853
* Content: [Articles based on ASP.NET Core projects created with individual user accounts](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/individual?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/authentication/individual.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/individual.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Found an older-ish issue that asks the same thing ...

[No Individual User Accounts auth option in ASP.NET Core Web API template #3772](https://github.com/aspnet/AspNetCore/issues/3772)

... that links off to ...

[Discussion for API authentication and Identity Server #5833](https://github.com/aspnet/AspNetCore/issues/5833)

Not sure if this should be reported to them: The command help (3.0-preview, 2.2 as well?) makes reference to the option in ...

> -uld|--use-local-db
>
> Whether to use LocalDB instead of SQLite. This option only applies if --auth Individual or --auth IndividualB2C is specified.

Whatever the case with that, this issue seems workable given that the topic seems to be 2.0-era (topic date is 11/29/2017).

Cross-ref: [New topic: Web API + authentication and authorization #4556](https://github.com/aspnet/Docs/issues/4556)

**Comment by YSternlicht** [comment]
@Rick-Anderson I do not understand why has this been completed? In Visual Studio (and in the docs) I can not see an option for --auth Individual

**Comment by carlosharry** [comment]
Any updates on this?
