### ISSUE TITLE
Services that use Entity Framework context

### ISSUE THREAD

**Issue by Burnaster** [aspnet/Docs#11037]
In section "Entity Framework contexts" it is written, that " Services that use the database context should also use the scoped lifetime."

Unfortunatly, it is not elaborated why to do so. For me, the statement is very confusing. Why should it not be fine to use a transient service? When using a singelton service, it makes sense to me. As it will hold on to a reference to a DbContext that is being disposed later. But if you have two transient service (of the same type) holding on to the same instance of a DbContext... ...that should be fine. No?

Even more: a controller is transient (by using the default AddMvc or AddControllerAsServices). If you use a DbContext directly in a controller (which you may do) you allready violating the "should" from the above statement. So somewhere you should find information about, either registering your controllers as scoped when using a DbContext directly or it should be warned about doing so.

Either way, i did not find any more information about the above sentence in the documentation or the blogosphere. 

Am i missing something obvious? Or could it make sense to add some more precise wording about the lifetime of DbContext and it's using services?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d78f540-81fd-1ba9-cb90-591e4ec27d9b
* Version Independent ID: 2251f557-dd3a-ec35-2558-6243337db009
* Content: [Dependency injection in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.2#entity-framework-contexts)
* Content Source: [aspnetcore/fundamentals/dependency-injection.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/dependency-injection.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
> the statement is very confusing

Confusing *and* not accurate because it doesn't specify which services should use the scoped context.

Quick note: I recommend not using "transient scoped service" when referring to a service. "Transient" and "scoped" are two different lifetimes.

Unfortunately, the EF Core docs don't maintain more/better information AFAICT: https://docs.microsoft.com/ef/core/miscellaneous/configuring-dbcontext#using-dbcontext-with-dependency-injection

As you say, the general rule of thumb is don't allow a service of a given lifetime to use another service with a shorter lifetime.

You can set the context's (and options) lifetimes with the `AddDbContext` overloads; and *Yes!* you're correct about a transient service using a transient dB context. For example ...

```csharp
services.AddDbContext<AppDbContext>(options =>
    options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")), 
    ServiceLifetime.Transient, ServiceLifetime.Transient);
```

https://docs.microsoft.com/dotnet/api/microsoft.extensions.dependencyinjection.entityframeworkservicecollectionextensions.adddbcontext

WRT controllers, they are scoped to the request, so the default scoped dB context is fine.

I'll take a look at this in a bit and see what we can do here. Thanks for opening this issue.

**Comment by Burnaster** [comment]
Thanks a lot for your quick reply. I edited the issue and replaced/removed the word "scoping" or "scoped" when i meant lifetime, so it makes it clearer. Nonetheless i think you understood the issue. :)
