### ISSUE TITLE
What about an arbitrary web server

### ISSUE THREAD

**Issue by wbhyde** [aspnet/Docs#11044]
Looks like a good description of what to do to statically host under IIS.  I hope that there will be some automation for that eventually.  What about other web servers?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df31b39a-669b-f6a1-4385-04bd39e921f9
* Version Independent ID: 19409cdc-3ec8-cacb-d21f-6dd90e29f291
* Content: [Host and deploy Razor Components](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/razor-components/?view=aspnetcore-3.0#client-side-blazor-standalone-deployment)
* Content Source: [aspnetcore/host-and-deploy/razor-components/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/razor-components/index.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Since Razor Components (and ASP.NET Core hosted Blazor) is based on an ordinary ASP.NET Core app, any CI/CD approach to automation that works with ASP.NET Core should work today.

For the client-side Blazor scenario (unsupported at this time), any automation that can deploy published output to the hosting system should work.

> What about other web servers?

Any supported hosting platform for ASP.NET Core is supported for Razor Components when 3.0 releases. ASP.NET Core-hosted Blazor support will arrive in a later release.

We're currently performing doc updates for Preview 2, and we haven't reached this one yet. I'll take your remarks into account when I get to it.
