### ISSUE TITLE
IStartupFilter support in HostBuilder

### ISSUE THREAD

**Issue by mcblair** [aspnet/Docs#11077]
Does this exist?

Are there plans?

Currently, are there workarounds to validate TOptions as a part of HostBuilder.Build() flow?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5f1eeee-d500-82bf-0d0a-b4e0d5d5c175
* Version Independent ID: 2373a3df-6ea3-50c7-d63d-61c51d572511
* Content: [.NET Generic Host](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/host/generic-host.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/host/generic-host.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @mcblair ... We haven't received guidance from engineering that anything has changed in those regards for 3.0 (nor are there any [3.0 Announcements](https://github.com/aspnet/Announcements/issues?q=is%3Aopen+is%3Aissue+label%3A3.0.0) in those regards), so (thus far anyway) the answers are:

* Yes
* N/A, since it's already there and works the same way AFAIK.
* Use Options validation as you currently do.

Devil's in the details tho, and I might not be aware of changes. When engineering informs us of changes in those areas, if there are any, we'll get them into the doc set. We'll be doing a lot of that type of work when the RC is released. If you hit anything painful while experimenting with 3.0 Preview releases, ask the engineers in the [aspnet/AspNetCore issues](https://github.com/aspnet/AspNetCore/issues) about it.

**Comment by mcblair** [comment]
Thanks. 

Wouldn't the answer to #1 be 'no' if my only opportunity is to continue using Options validation?

I'm guessing `IStartupFilter` doesn't exist for generic hosts - since they don't `UseStartup<T>`?

**Comment by guardrex** [comment]
@mcblair Yes, I looked a little further. (I have *lots of reading* to do on what they did for 3.0.) Looks like they plan to have devs register an `IHostedService` to run early. https://github.com/aspnet/Extensions/issues/1151

WRT Options, the only issue that popped up (on a quick search) is [Options Validation: support eager validation](https://github.com/aspnet/Extensions/issues/459).

Since both `HostBuilder` and Options are in the Extensions repo, ask your questions there: [aspnet/Extensions issues](https://github.com/aspnet/Extensions/issues).

**Comment by mcblair** [comment]
Will do, thanks.
