### ISSUE TITLE
Add information for using separate layouts and areas

### ISSUE THREAD

**Issue by wstaelens** [aspnet/Docs#11110]
when using areas and you want to use different layouts for each area. Add documentation where to put these layouts.
should they be in a Areas/Admin/Views/Shared/_Layout or should it be an _AdminLayout in the ~/Views/Shared/_AdminLayout.cshtml  etc...

This info is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b29734d0-2d2b-3b82-0456-785cc7f361fd
* Version Independent ID: ab07129c-a4dd-44de-45f9-4b49eff0b54c
* Content: [Layout in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/layout?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/mvc/views/layout.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/layout.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
It's currently covered as ...

> When a partial name is provided, the Razor view engine will search for the layout file using its standard discovery process. The folder where the handler method (or controller) exists is searched first, followed by the Shared folder. This discovery process is identical to the one used to discover partial views.

Partial views is linked over to the *entire topic*, but it might be best to link directly to the section that explains it out ...

https://docs.microsoft.com/aspnet/core/mvc/views/partial#partial-view-discovery

... or perhaps mirror that content over here.

**Comment by wstaelens** [comment]
but what is recommended:

` ~/Areas/Admin/Views/Shared/_Layout.cshtml`

or 

`~/Views/Shared/_AdminLayout.cshtml`

it should be documented what is recommended or preferred way when using areas and having specific layouts for an area.

**Comment by guardrex** [comment]
It's up to you ... some devs will want to go one way ... some the other. I kind'a doubt that a single recommendation is going to work for everyone. As long as the search pattern matches your expected behavior and you get the right layout for the right set of pages ... it's all :smile: and 🍭. My concern is more along the lines of devs not seeing the discovery conventions because we don't link it directly in the *Layouts* topic.

**Comment by wstaelens** [comment]
I understand. but in general when you do a "real world application" using areas, the documentation kinda 'stops'. (I was looking if there is a reason why one over the other is preferred. maybe for security, maybe for performance, maybe for inheritance, or whatever I don't know.)
😸

**Comment by guardrex** [comment]
Fortunately, I never had a *very complicated* scenario to address. Let's ask the team because IMO there's no real *right way* that will generally apply to *all scenarios* other than adopting a rational organization of  the files to make maintaining the areas easy ... and that literally goes without saying.

\+ @tdykstra @scottaddie TL;DR I propose to link the *Layouts* topic text where it speaks to layout discovery directly to the section where Partials discovery is covered and not to the entire Partials topic. Do you feel that we should make specific organizational recommendations? ... I don't plan to do that at the moment. I only plan to improve the cross-link. It will link directly to ...

https://docs.microsoft.com/aspnet/core/mvc/views/partial#partial-view-discovery
