### ISSUE TITLE
More details on section "Server exception handling"

### ISSUE THREAD

**Issue by PingPongSet** [aspnet/Docs#11240]
Is it possible to provide more description or example on the content below?
"
Requests that aren't handled by your app are handled by the server. Any exception that occurs is handled by the server's exception handling. Any configured custom error pages or exception handling middleware or filters don't affect this behavior.
"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e03fdf4-b19b-17c3-04f4-336ab6d2ee06
* Version Independent ID: 38515dfb-91a5-b395-db9d-084bbaf095c8
* Content: [Handle errors in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-2.2#startup-exception-handling)
* Content Source: [aspnetcore/fundamentals/error-handling.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/error-handling.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by simeyla** [comment]
Came here to post something almost identical. Especially important since there is a massive green message saying :

"Exception filters are good for trapping exceptions that occur within MVC actions, but they're not as flexible as error handling middleware. Generally prefer the use of middleware, and use filters only where you need to perform error handling differently based on which MVC action is chosen."

But no example on how to create your OWN middleware to do such a thing. While I can find example of such it would be valuable to have a simple example here - with special attention paid to any caveats about where in the middleware pipeline it should be placed.

**Comment by guardrex** [comment]
@simeyla I didn't write that; but when it refers to middleware, it should be referring to he Exception Handling Middleware provided by the framework. We won't have coverage for custom middleware because that's an edge (and advanced) case.

One thing for sure tho ... glad you mentioned this ... "error handling middleware" should be "Exception Handling Middleware."
