### ISSUE TITLE
Does this server work with an AspNetCore app built against .NET Framework?

### ISSUE THREAD

**Issue by madelson** [aspnet/Docs#11276]
I am trying to get the sample working with an ASP.NET Core app that targets .NET Framework. However, the sample code does does not build because it can't find the extension UseHttpSys(). Is this a supported configuration? If so, what package must be added to get HttpSys?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e347c54-6a6a-d685-4af7-39b023bf7f15
* Version Independent ID: 41aa77f5-9466-6580-5ec6-b1bf97bd0f01
* Content: [HTTP.sys web server implementation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/httpsys?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/servers/httpsys.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/servers/httpsys.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
Hello @madelson ... *In theory* (I haven't tried it myself) according to engineering, the answer is *Yes!* From Item 4 under [Configure Windows Server](https://docs.microsoft.com/aspnet/core/fundamentals/servers/httpsys?view=aspnetcore-2.2#configure-windows-server) ...

> If the app is a [framework-dependent deployment](https://docs.microsoft.com/dotnet/core/deploying/#framework-dependent-deployments-fdd), install .NET Core, .NET Framework, or both (if the app is a .NET Core app targeting the .NET Framework).
>
> * .NET Core – ...
> * .NET Framework – If the app requires .NET Framework, see the [.NET Framework installation guide](https://docs.microsoft.com/dotnet/framework/install/). Install the required .NET Framework. The installer for the latest .NET Framework is available from from the [.NET Core Downloads](https://dotnet.microsoft.com/download) page.

Since the `Microsoft.AspNetCore.App` package is for ASP.NET Core only, you must reference individual packages in the project file when targeting the .NET Framework.

We don't provide troubleshooting advice here ... we just work on the docs. We recommend consulting with devs on a support forum, such as Stack Overflow, or a support chat, such as Slack or Gitter. Of course, MS Support will help if you have a support agreement.

Note that for 3.0+, this scenario won't be supported. See: https://github.com/aspnet/Announcements/issues/324
