### ISSUE TITLE
HTTP Error 500.19 - Internal Server Error

### ISSUE THREAD

**Issue by crtjr64** [aspnet/Docs#11408]
When I follow the steps in section Development-side configuration with a local web.config file. Now I got more bugs to chase down because of your apathy. I despise you guys. Bill Gates should never have left us in your incapable hands. You're terrible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 401ad9a0-9e51-80a2-5846-82e9790d7257
* Version Independent ID: fbc36c26-9992-1f4c-66d3-02f898ee7ec4
* Content: [Configure Windows Authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/security/authentication/windowsauth.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/windowsauth.md)
* Product: **aspnet-core**
* GitHub Login: @scottaddie
* Microsoft Alias: **riande**

**Comment by bdlane** [comment]
I get the same issue - adding the `web.config` with the authentication elements causes a configuration error at runtime.

Starting from the 'Web Application' template in the new project dialog in Visual Studio 2019, with Windows Authentication enabled, I can run and debug the project fine.

Then, following the steps outlined in the 'Development side configuration with a local web.confg' section (i.e. adding a `web.config` file with the  `<system.webServer><security><authentication>` tags), running the project returns a HTTP 500.19, with the following config error:

> This configuration section cannot be used at this path. This happens when the section is locked at a parent level. Locking is either by default (overrideModeDefault="Deny"), or set explicitly by a location tag with overrideMode="Deny" or the legacy allowOverride="false".

You can fix the problem by modifying the `applicationHost.config` file in the solution's `.vs` directory to unlock the relevant sections. However,

1. this step isn't described in the docs, and
2. this can't be right, can it? The `applicationHost.config` file is auto-generated (by VS?), so might get overwritten, and will need to be done on every developer's machine.

Is this the expected behaviour?

<details>
<summary><strong>dotnet --info output</strong></summary>

```console
.NET Core SDK (reflecting any global.json):
 Version:   2.2.203
 Commit:    e5bab63eca

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.203\

Host (useful for support):
  Version: 2.2.4
  Commit:  f95848e524

.NET Core SDKs installed:
  2.2.203 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```
</details>

<details>
<summary><strong>About VS info</strong></summary>

```console
Microsoft Visual Studio Community 2019
Version 16.0.1
VisualStudio.16.Release/16.0.1+28803.156
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Community

Application Insights Tools for Visual Studio Package   9.0.20307.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2019   16.0.12311.10635
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.0.12311.10635
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.0.12311.10635
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.0.12311.10635
Azure Functions and Web Jobs Tools

C# Tools   3.0.0-beta4-19170-01+1deafee3682da88bf07d1c18521a99f47446cee8
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 0x10 - v2.9.0.0

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

NuGet Package Manager   5.0.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.61903.25110
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.10306.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.0.0-beta4-19170-01+1deafee3682da88bf07d1c18521a99f47446cee8
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.0.0.0.  Commit Hash: 809f41207b74a1356208f11b8fa3a15233734050.
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers
```
</details>

**Comment by guardrex** [comment]
@bdlane Please open a new issue using the **This Page** feedback button at the bottom of the topic. We can't track on closed issues.

**Comment by ddrochers** [comment]
To add on @bdlane's, I tried both override methods on the location tag with no success. overrideMode="Allow" seems deprecated and  allowOverride="true" doesn't seem to do anything. 

I guess we aren't supposed to modify this but as he mentioned, changing the applicationHost.config file in .vs works for the developer station, while changing IIS's applicationHost.config under %windir%\system32\inetsrv\config works for 
 published environments. 

In our case, we opted not to change default behaviour of the configurations but instead override them inside the applicationHost.config file. The way we do it is we added our <location path="myWebsite"><...></location> tags at the end of the file, before closing the </configuration> tag. So instead of putting the suggested piece of configuration inside a web.config in the solution, we adjusted the IIS server's applicationHost.config file to include this information. This way we need no adjustment on our dev's machine and the default configuration isn't changed.
