### ISSUE TITLE
Putting my code in a Microsoft namespace

### ISSUE THREAD

**Issue by EldieTurner** [aspnet/Docs#11435]
I would like more clarification on why someone would put code they wrote inside a Microsoft.Extensions.DependencyInjection namespace.  If I see an extension method with this namespace I assume it is code that was written by Microsoft.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d78f540-81fd-1ba9-cb90-591e4ec27d9b
* Version Independent ID: 2251f557-dd3a-ec35-2558-6243337db009
* Content: [Dependency injection in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/fundamentals/dependency-injection.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/dependency-injection.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@EldieTurner Hello ... Thanks for commenting. That guidance was provided by an earlier author, and we haven't had management or engineering take issue with it on the reviews of this topic.  That should be fine. The problem is when devs name (and **_publish_**) their NuGet packages **Microsoft.SomethingCool**. Yeah ... *My advice would be to get a good attorney!!* :smile: lol ... It really does mislead people when a published package has that naming.

**Comment by spankr** [comment]
The issue I am dealing with now is that other engineers are taking the line, _"Place extension methods in the Microsoft.Extensions.DependencyInjection namespace to encapsulate groups of service registrations."_ and declaring it "the standard used by the ASP.NET vNext team" (https://github.com/OData/WebApi/issues/576).

I'm with @EldieTurner on assuming everything under Microsoft.* should be Microsoft-written. It should probably be clarified as either officially good or bad before too many teams take this earlier author's guidance as an industry standard.

**Comment by spankr** [comment]
Okay, that OData link is a poor example(my bad). It makes perfect sense for them to use the namespace, as OData is part of Microsoft (TIL).
But I do have non-MS engineers pointing at examples like that (and this doc) and drawing the conclusion that everyone should be using that namespace for their extensions of **IServiceCollection**.

**Comment by guardrex** [comment]
AFAIK, the answer is *Yes!* I was able to trace the remark back to this ...

https://github.com/aspnet/AspNetCore.Docs/pull/2145#issuecomment-260189456

... where Steve says that the Product Unit said to do it.

Engineering has looked this topic over multiple times since then and never said to change it. We'll be reviewing updates again when we get to 3.0 updates. I'll ask explicitly in a few months when I work it.

**Comment by spankr** [comment]
Hah, that is so crazy! My first thought was it was only meant as a note for other Microsoft devs to share a naming convention across the various Microsoft's github projects.

If its something that happens to be open to a community vote as part of the 3.0 update, I'd be interested in voting to change it. In the meantime, I'll share the response with the rest of my team.

Thank you for checking on this for me, @guardrex!
