### ISSUE TITLE
Document limitations of updating the Identity schema when targeting SQLite

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#1210]
https://github.com/aspnet/identity/issues/816

**Comment by isaac2004** [comment]
@danroth27 Do you have a preference where you want this note? Any page that references SQLite (aspnet and aspnetcore) or a particular page in the [Identity](https://docs.microsoft.com/en-us/aspnet/identity/) set?

**Comment by isaac2004** [comment]
@danroth27 comment?

**Comment by danroth27** [comment]
@blowdart Should probably comment on what he wants here as he now owns this area.

**Comment by blowdart** [comment]
I'd put it under Identity, in Migrations I think. And under the identity articles in Secuirity/Authentication in Core, after Enable QR Code generation

Can we have a page in both?

**Comment by isaac2004** [comment]
@blowdart I think we can just put a note wherever you want no?

Something like

If the application uses SQLite as the datastore for identity, some commands are not supported. Due to limatations in the database engine, AlterCommands will throw the exception "System.NotSupportedException: SQLite does not support this migration operation. To workaround this, run code first migrations on the database to change the tables.

Let me know if this works and I will add a note to the docs you mentioned. If you have any others, let me know

**Comment by blowdart** [comment]
Sure that works.

**Comment by isaac2004** [comment]
@blowdart so all identity data related pages in aspnet core? Sound good?

@scottaddie any advice where on pages this note should go?

**Comment by scottaddie** [comment]
@isaac2004 Here's the exact verbiage I recommend for the note:

> Some commands aren't supported if the app uses SQLite as its Identity data store. Due to limitations in the database engine, `Alter` commands throw the following exception: "System.NotSupportedException: SQLite does not support this migration operation." As a work around, run Code First migrations on the database to change the tables.

Since you plan to include this note in multiple docs, please create a new *includes/identity* folder. Within it, create an *alter-command-exception.md* file with the note verbiage. You can use include syntax like the following in the individual docs:

[!INCLUDE[](~/includes/identity/alter-command-exception.md)]

Based on @blowdart's comments above, I recommend the following pages:

- https://docs.microsoft.com/aspnet/identity/overview/migrations/
- https://docs.microsoft.com/aspnet/identity/overview/migrations/migrating-an-existing-website-from-sql-membership-to-aspnet-identity
- https://docs.microsoft.com/aspnet/identity/overview/migrations/migrating-universal-provider-data-for-membership-and-user-profiles-to-aspnet-identity

It's still unclear to me which ASP.NET Core docs should have this note.
