### ISSUE TITLE
Refer to .NET Core tools doc wherever we discuss our tools

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#1276]
We should link to http://dotnet.github.io/docs/core-concepts/core-sdk/cli/overview.html wherever we discuss our .NET Core tools that we ship.

**Comment by GuardRex** [comment]
Passing note as we discuss `publish-iis` tooling on Slack (cc/ @moozzyk): That doc destination still doesn't say anything about the various tools. cc/ @blackdwarf

**Comment by GuardRex** [comment]
The conclusion chatting in Slack that the tools are not CLI, so perhaps that's not the right spot. Since each tool pertains to a specific section of current docs and thus gets buried within a doc, it begs the question if there should be a top-level "Tools" section at docs.asp.net that would have one doc for each of the tools under it?

**Comment by blackdwarf** [comment]
@GuardRex agreed, for the ASP.NET specific tools you restore, they should be documented on docs.asp.net and then link to the core set of OOB tools as @danroth27 mentions above.

**Comment by GuardRex** [comment]
@blackdwarf The reason this came up today on Slack was that @moozzyk pointed out that there were a lot of misunderstandings about what `publish-iis` did. True, I spoke with at least a half-dozen devs who mostly thought that it actually published the app to IIS! ... which makes perfect sense given the name.

I'll open a discussion issue on it for at least getting it into Publishing to IIS, because we have some other things to look at from @moozzyk's post: https://blog.3d-logic.com/2016/06/08/running-asp-net-core-applications-with-iis-and-antares/

**Comment by blackdwarf** [comment]
@GuardRex ok, this makes sense, I was all confused there for a second. :))

**Comment by retk** [comment]
I agree with @GuardRex that there should be a top level documentation section for .netcore/aspnetcore tools, at least the official ones. I'm pretty sure that there will be more and more in the future. A nuget like feed might be useful too to support tools created by the community.

**Comment by guardrex** [comment]
@danroth27 Updating the destination:

https://docs.microsoft.com/dotnet/core/tools

I'll run thru and see if I can knock this one out quickly. 🥊 *Ding! Ding!*
