### ISSUE TITLE
Razor Syntax Reference

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#130]
ASP.NET MVC -> Views -> Razor Syntax Reference

**Comment by robbert229** [comment]
@danroth27 Is it okay if I author this? I did open up a new issue because originally I didn't see this. Just looking for an okay to start.

**Comment by danroth27** [comment]
Sounds great to me!

@NTaylorMullen

**Comment by robbert229** [comment]
As far as content goes I plan to cover

* Code Blocks
* Implicit
* Explicit
* escaping @ as well as razor ignoring emails
* text tag
* Unencoded html
* server sided comments
* control structures
* delegates / lambdas in razor
* tilde in paths
* classes, ids, and attributes in general

Is there something else that should be covered in this article?
@danroth27 @Rick-Anderson

**Comment by Rick-Anderson** [comment]
@NTaylorMullen  @anurse can you take a look at the Razor Syntax Reference outline - it looks good to me.

**Comment by robbert229** [comment]
The title says reference so I am not planning on making it a full tutorial, more of a guide that will show all of the functionalities of razor, as well as some cool tricks. Is this fine, or do you want a tutorial complete with its' own example project? @danroth27

**Comment by danroth27** [comment]
Correct, this is supposed to be a reference topic, not a tutorial. No sample projects needed.

**Comment by NTaylorMullen** [comment]
> Unencoded html
> control structures
> delegates / lambdas in razor
> classes, ids, and attributes in general

Can you explain in more detail on what you want to cover on the above? It'd probably be good to cover the Razor directives (such as `@inherits`) as well.

**Comment by robbert229** [comment]
@NTaylorMullen 

I forgot about about directives and have since added them into what I will be covering. Right now I am reviewing everything and getting ready to make a pull request.

Sorry about the delayed response, a natural disaster, thanksgiving, and finals have put open source on the back burner for a while.

**Comment by robbert229** [comment]
My roughdraft can be found [Here](https://github.com/robbert229/Docs/blob/robbert229-razor/mvc/views/razor.rst).

 If anyone is willing to take a look at it I would be thankful. Also it is the first article I have written so any constructive criticism will be appreciated.

@danroth27 @NTaylorMullen @Rick-Anderson

**Comment by NTaylorMullen** [comment]
@Rick-Anderson I went ahead and built out a ton of content for this. It pretty much just needs to be rst'd and have links filled in.

Also, at the end there's a few pieces I did not cover which will eventually need to be covered.

[RazorReferenceDoc.docx](https://github.com/aspnet/Docs/files/332706/RazorReferenceDoc.docx)

/cc @danroth27

**Comment by Rick-Anderson** [comment]
@NTaylorMullen  perfect, I'll get it converted to rst

**Comment by Bartmax** [comment]
I can thing of a few things missing:

`EditorTemplates`
`DisplayTemplates`
`HtmlHelpers` and why there are 2 syntaxes (taghelpers/htmlhelpers). I think this will be quite confusing for some when they see `@Html.Raw` instead of `<raw>`. Add a bit of history for extra points :smile: 
`PartialViews` (noting the distinction between `_filename.cshtml` and `filename.cshtml`)
`ViewComponent` (aka invoke directive and a link to the `ViewComponent` doc)
`ViewBag`/`ViewData` (aka passing the title from page X to Layout) and brief notion of `TempData`
`ModelState` & `Metadata` (how is consumed in razor pages)
`_ViewStart.cshtml`
`_ViewImports.cshtml`
Special folder `Shared`
`ViewLocator`/`Expanders`
`HtmlString` when `Raw` is mentioned
in comments section, note that `<!-- this will be rendered on source html -->` but `@* this wont *@`

**Comment by Rick-Anderson** [comment]
@Bartmax  this is Razor Syntax

Editor and Display templates will be covered in another doc. Tag Helpers are not a replacement for HTML Helpers, although there is overlap.  see https://docs.asp.net/en/latest/mvc/views/working-with-forms.html - From that doc:

_In many cases, HTML Helpers provide an alternative approach to a specific Tag Helper, but it’s important to recognize that Tag Helpers do not replace HTML Helpers and there is not a Tag Helper for each HTML Helper._ 

https://docs.asp.net/en/latest/mvc/views/partial.html  covers partials

I'll add links to my View Component doc. Ditto for Partial views and viewbag/viewData. *_ViewStart.cshtml* and *_ViewImports.cshtml* are covered in another doc.

I'll add
in comments section, note that `<!-- this will be rendered on source html -->` but `@* this wont *@`

@Bartmax  can you write up 
`HtmlString` when `Raw` is mentioned
and I'll add it to the doc.

**Comment by Bartmax** [comment]
wow you got everything really covered!! Sorry I just wanted to point out the things I look that might be missing. You all are doing an amazing job with the docs! I'm spending quite amount of time reading them just because they are really enjoyable.

About the `HtmlString`, I'm not sure internally how it works but I imagine something along this lines:

To render HTML content without encoding you can utilize the `Html.Raw` method:
```
@Html.Raw("<div>Hello World</div>") => <div>Hello World</div>
```
or using a `HtmlString` `Type` directly:
```
@using Microsoft.AspNetCore.Html;
@{
    HtmlString text = new HtmlString("<h1>&iexcl;Hola mundo!</h1>");
}
<header>@text</header> => <header><h1>&iexcl;Hola mundo!</h1></header>
```

**Comment by NTaylorMullen** [comment]
https://github.com/aspnet/Docs/commit/260f34d05cc9eb3560be1c40a83de57091f13dad
