### ISSUE TITLE
fundamentals/startup "Application Startup"

### ISSUE THREAD

**Issue by ciwchris** [aspnet/Docs#1307]
The "Services Available in Startup" section in the [Application Startup](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/startup#services-available-in-startup) doc lists `IApplicationEnvironment` as an injectable service, ~but the "Runtime Services Changes" section in the [Migrating from ASP.NET 5 RC1 to ASP.NET Core](https://github.com/aspnet/Docs/blob/d02c9614d2a0af4920e225096cfe4c8a2f352b0d/aspnet/migration/rc1-to-rc2.rst#runtime-services-changes) doc says~

> You must modify code in the Startup class that uses IApplicationEnvironment to use IHostingEnvironment~

EDIT: https://docs.microsoft.com/en-us/aspnet/core/migration/http-modules 

`public Startup(IHostingEnvironment env)`

Therefore my understanding is that all references to `IApplicationEnvironment` should be removed.

**Comment by danroth27** [comment]
We need to do a general update on this doc.

**Comment by Tratcher** [comment]
- The descriptions of Startup as the application entry point are outdated. Compare to https://docs.asp.net/en/dev/conceptual-overview/aspnet.html#application-anatomy
- De-emphasize the discovery and Startup[Environment] pattern, Startup is usually specified via `WebHostBuilder.UseStartup<Startup>();`
- `Hosting:Application` is now the `startupAssembly` configuration key or `ASPNETCORE_STARTUPASSEMBLY` environment variable
- Re-order the sections. Services Available in Startup should come right after the description of DI and the class constructor, then ConfigureServices, then Configure.
- ConfigureServices no longer supports parameter injection, only the ctor and Configure. ConfigureServices only accepts IServiceCollection.

**Comment by Tratcher** [comment]
- There is a new IStartup interface. It's use is optional as using it would prohibit DI parameter injection into Configure. https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting.Abstractions/IStartup.cs

**Comment by Tratcher** [comment]
- "like AppSettings in the example above". There are no AppSettings in the sample's ConfigureServices method.

**Comment by Rick-Anderson** [comment]
- [ ] Fix issues above 

- [ ] UE edit

- [ ] add out of date banner

**Comment by kierenj** [comment]
Anything you can do here is massively appreciated.  I'm just trying to create a from-scratch ASP.NET Core / Web API project, doing things as correctly as possible.  Finding out how to correctly initialise things is proving a real challenge.  `IStartup` looks much more grown-up than a magic class with public properties, thank you.

Where's the best place to ask about how to actually do configuration?  The Configuration section of the docs tells us how to build a configuration object, but then assigns it to a magical Configuration property (`Configuration = builder.Build();`).  Something explicit saying how to hook up ASP.NET to a particular configuration would be good (via `builder.UseConfiguration()` I'd guess - but is that really correct?), along with a list of any config settings that are known to be requested of the config (if any)?

**Comment by davidfowl** [comment]
> Something explicit saying how to hook up ASP.NET to a particular configuration would be good (via builder.UseConfiguration() I'd guess - but is that really correct?), along with a list of any config settings that are known to be requested of the config (if any)?

The configuration API is just like any other API you can use in your application. UseConfiguration on the `WebHostBuilder` is about configuring specific ASP.NET options (like the environment, or the urls) from some configuration object that you're providing. It does not hook up your user configuration to anything.

What are you trying to configure?

**Comment by kierenj** [comment]
I'm trying to understand how to configure ASP.NET Core, from first principles.  I didn't know that `UseConfiguration` was for environment or URLs (there's `UseEnvironment` I think?) - so that kind of info is what I'm looking for.

So basically nothing in the docs (that I stumbled across in a few hours so far):

* Tells me what the default configuration sources are (if any)
* Indicates how you associate a `Configuration` with ASP.NET (I can see `UseConfiguration` - but it's not explicitly referred to or used in any examples I can see)
* Indicates exactly what the `Configuration` object passed in is used by ASP.NET for (which keys are expected, etc)

Note, I was primarily looking in the Startup and Configuration sections of the docs, which just seems to me to be the logical place for this info.

Yes, upon reading other parts of the docs, cross-referencing, digging through some examples and source, and the odd GitHub notification and issue, I can work this out, but still not with the level of certainty I'd like, or in the time I'd like.

I understand it's all a work-in-progress, not a complaint - just trying to give my opinion and stress the value that clearly outlining this stuff would have for me - and I would guess, others too.

**Comment by Rick-Anderson** [comment]
@tdykstra  please review

**Comment by isaac2004** [comment]
@Rick-Anderson isn't this doc being replaced with the doc #3809 ?

**Comment by Rick-Anderson** [comment]
dup of #3809
