### ISSUE TITLE
Authorization Filters

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#133]
ASP.NET MVC -> Security -> Authorization Filters

**Comment by uwbadgerdev** [comment]
Any status update on when this will be written?

**Comment by danroth27** [comment]
Not yet - it's still on the backlog.

**Comment by uwbadgerdev** [comment]
Hi Dan. Thanks for the update.

**Comment by neville-lewis** [comment]
I hope this stays:

[ClaimsPrincipalPermission(SecurityAction.Demand, Operation = "OperationA", Resource = "DeletePage")]

or improves.

At the moment I am unable to find anything that parallels it. I have been searching all of 30 minutes though.

**Comment by danroth27** [comment]
@blowdart

**Comment by blowdart** [comment]
Long gone. Use imperative resource based checks. It was never part of asp.bet in the first place, it was code access security based which has been removed.

**Comment by brockallen** [comment]
> I hope this stays:

What @blowdart is referring to is something similar added to ASP.NET 5, but much improved. Check out the updated docs for more info (policy-based and resource-based authrization).

**Comment by blowdart** [comment]
https://docs.asp.net/en/latest/security/authorization/resourcebased.html

**Comment by danroth27** [comment]
Merging with #119

**Comment by rtpHarry** [comment]
This issue is linked to here https://docs.microsoft.com/en-us/aspnet/core/security/authorization/authorization-filters

It seems like it's been closed incorrectly as  #119 does have [a little bit about authorization filters](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters#authorization-filters) but it doesn't cover it properly and the dedicated page has been [left as a stub](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/authorization-filters).

It seems either this issue should be re-opened or the stub should be removed.

**Comment by danroth27** [comment]
@rtpHarry I think we just need to remove the stub. Most of the authorization related content is actually covered under the Authorization section, which is linked to from the Filters doc: https://docs.microsoft.com/en-us/aspnet/core/security/authorization/introduction. 

Are there specific concerns related to authorization filters that you would like to see added to the docs?

**Comment by rtpHarry** [comment]
I don't know about them, I'm just learning. I just wanted to point it out but I don't have a solution :)

**Comment by danroth27** [comment]
@rtpHarry That's cool. Let us know if you have any specific questions!
