### ISSUE TITLE
Anti-Request Forgery

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#134]
ASP.NET MVC -> Security -> Anti-Request Forgery

**Comment by tbgo** [comment]
The link to for more information in the http://docs.asp.net/projects/mvc/en/latest/getting-started/first-mvc-app/controller-methods-views.html tutorial led me here because the "more information" page (http://docs.asp.net/projects/mvc/en/latest/security/anti-request-forgery.html) was being worked on. When do you expect it may be ready for the masses?
And tnx for a nice tut so far!

**Comment by danroth27** [comment]
We plan to have a completed doc set by the summer.

**Comment by danroth27** [comment]
Merging this content into #89 now that we have merged the MVC content into the ASP.NET Core TOC.
