### ISSUE TITLE
Fix the font sizes

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#1341]
The font sizes are too small, which makes the docs hard to read. The fonts for the API docs are even smaller.

**Comment by Rick-Anderson** [comment]
@neusamir Is this something you could do?

**Comment by neusamir** [comment]
Yes, let me take a look

**Comment by neusamir** [comment]
Should we match the azure.com site and use font size 16px?

**Comment by Rick-Anderson** [comment]
> Should we match the azure.com site and use font size 16px?

That seems reasonable to me - @danroth27

**Comment by danroth27** [comment]
Yeah. It looks like that is also the default font size for the Read the Docs theme, so let's just use that.

**Comment by neusamir** [comment]
Ok sounds good. The code font is 75% the body font, so that will bump to 12px. Should we update that to 16px also so it's easier to read?

On Jun 6, 2016, at 1:53 PM, Daniel Roth <notifications@github.com<mailto:notifications@github.com>> wrote:


Yeah. It looks like that is also the default font size for the Read the Docs theme, so let's just use that.

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/aspnet/Docs/issues/1341#issuecomment-224084848>, or mute the thread<https://github.com/notifications/unsubscribe/ARfRG-wqDHeA5eTouJz2LR7jPAQ_Ue3dks5qJIjSgaJpZM4It5-_>.


Confidentiality Notice: This email and any attachments are confidential. If you have received this in error, please let us know by email reply and delete the email and all attachments from your system.

**Comment by danroth27** [comment]
No, let's leave the code font at 75% of the body font.
