### ISSUE TITLE
Logging on Azure and remote debugging on Azure

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#1673]
- [ ] Need guidance on how to do logging to get error messages.
- [ ] How to do Azure Web App Log Streaming  #2146 
- [ ] Instructions on remote debugging

Per fowler _web.config_

```
<system.web>
    <customErrors mode="Off" />
  ...
  </system.web>
```

no longer works. Need guidance on how to do logging to get error messages.

**Comment by Rick-Anderson** [comment]
@davidebbo  do we have any guidance on this? cc @tdykstra

**Comment by danroth27** [comment]
We should add instructions to the Logging article that shows how to setup logging on Azure today. We also plan to do some feature work to make the experience more seamless. There is some good content on enabling logging in Antares here: https://blog.3d-logic.com/2016/06/08/running-asp-net-core-applications-with-iis-and-antares/. We should probably show using a real logging framework instead of stdout logging.

Remote debugging should "just work" with the latest Azure SDK and with the normal steps.

For setting up the developer exception page in ASP.NET Core see https://docs.asp.net/en/latest/fundamentals/error-handling.html. Our templates set it up for you when you are in the Development environment.

**Comment by tdykstra** [comment]
@danroth27 

>We should probably show using a real logging framework instead of stdout logging.

Which one do you recommend we show?

**Comment by danroth27** [comment]
@glennc Do you have any recommendations on how we should document setting up logging on Azure? Serilog? Something else?

**Comment by Rick-Anderson** [comment]
re-ping @glennc Do you have any recommendations on how we should document setting up logging on Azure? Serilog? Something else?

**Comment by danroth27** [comment]
We have a new Azure specific logging provider in 1.1 that folks will be able to use: https://github.com/aspnet/Logging/tree/dev/src/Microsoft.Extensions.Logging.AzureWebAppDiagnostics.

**Comment by tdykstra** [comment]
@danroth27 For now we could show Serilog, and then for 1.1 we could add AzureWebAppDiagnostics, or we could wait for 1.1 to update the logging article.  

The issue was originally written about Azure logging, but there's a need to show how to use a real logging framework regardless of Azure use.  If we add Serilog as an example now, that content will still be useful after 1.1 when we add AzureWebAppDiagnostics (or we could put AzureWebAppDiagnostics in a separate article or tutorial).

In your 7/15 comment you linked to Pawel's blog (which shows stdout logging) and then said we should show a logging framework instead of stdout logging.  Would showing Serilog with a file sink eliminate the need to show stdout logging for Azure?

**Comment by danroth27** [comment]
I'd rather hold off on documenting how to use Serilog because of the maintenance issues. I think we should just wait for 1.1. The feature is available already to try out, so we could even get started on preparing the content in the dev branch.

**Comment by tdykstra** [comment]
@danroth27 Given that the Azure diagnostics provider works now, we could add content for it now with a note about it being a preview release, instead of using dev branch and waiting for 1.1.  We would provide instructions on how to restore packages from the myget feed, then remove that when 1.1 is released.

**Comment by danroth27** [comment]
No, I don't think we should mix preview content with our docs for stable and supported bits. Those need to be kept separate.

**Comment by Rick-Anderson** [comment]
@danroth27  How about we put the Azure section in a .RST file on  Dev, **but** link to it from the logging doc in master?
If we do that, we'll need to run the conversion tool on dev when we migrate. How much content on dev needs to be migrated?

**Comment by danroth27** [comment]
I don't think we have much if anything in the dev branch beyond what is already in master. 

We need to keep our prelease content and our stable content separate so that customers don't get confused. Can we hold off on documenting this new 1.1 until we are on docs.ms.com?

**Comment by tdykstra** [comment]
Closing the issue, as the only thing left from it is streaming, which is covered by #2146
