### ISSUE TITLE
AspNetCoreModule install fails when IIS shared config is enabled

### ISSUE THREAD

**Issue by shirhatti** [aspnet/Docs#1816]
By design, it is recommended not to install IIS Extensions if shared configuration has already been enabled. The recommended way to is to always install the extensions before IIS shared config is enabled.

We need to update ANCM docs to explicitly call out [this](https://github.com/aspnet/IISIntegration/issues/249#issuecomment-242171371) is not a supported scenario.

**Comment by GuardRex** [comment]
Take it into ...
https://docs.asp.net/en/latest/hosting/aspnet-core-module.html 
or
https://docs.asp.net/en/latest/publishing/iis.html
or
both?

**Comment by shirhatti** [comment]
Given that publishing/iis links to hosting/aspnet-core-module doc from the "[Install](https://docs.asp.net/en/latest/publishing/iis.html#install-the-net-core-windows-server-hosting-bundle)" section. I'm believe just having it in just hosting/aspnet-core-module document should suffice.

**Comment by GuardRex** [comment]
:+1: ... I'll have some draft language in a few hours.

**Comment by GuardRex** [comment]
@shirhatti Can we "steal" @jhkimnew (modified) language for something like this ...

### ASP.NET Core Module with IIS Shared Configuration

The ASP.NET Core Module installer, which is included in the .NET Core Windows Server Hosting bundle installer, runs with the privileges of the **SYSTEM** account. Because the local system account does not have modify permission for the share path which is used by the IIS Shared Configuration, the installer will hit an access denied error when attempting to configure the module settings in **applicationhost.config** on the share.

The unsupported workaround is to disable the IIS Shared Configuration, run the installer, export the updated **applicationhost.config** file to the share, and re-enable the IIS Shared Configuration.

**Comment by shirhatti** [comment]
Looks good to me.
@jhkimnew ?

**Comment by shirhatti** [comment]
@GuardRex Will you be opening a PR? :smile:

**Comment by jhkimnew** [comment]
@shirhatti Looks goood to me as well.

**Comment by GuardRex** [comment]
Sure thing ... I'll have it in within a few hours.
