### ISSUE TITLE
Installing on Linux - missing certificate import steps

### ISSUE THREAD

**Issue by juzzbott** [aspnet/Docs#184]
Hi, 

To be able to use the `dnu restore` command, I had to import some SSL certificates for the restore to work, otherwise Mono was throwing exceptions when trying to restore the packages. 

The commands I had to run are:

    sudo certmgr -ssl -m https://go.microsoft.com
    sudo certmgr -ssl -m https://nugetgallery.blob.core.windows.net
    sudo certmgr -ssl -m https://nuget.org
    mozroots --import --sync

It would be good to see these steps in the documentation to ensure it can work after the tutorial.

Cheers, 
Justin

**Comment by davidfowl** [comment]
You shouldn't have to:

http://www.mono-project.com/docs/getting-started/install/linux/#notes

> Mono on Linux before 3.12 by default didn’t trust any SSL certificates so you got errors when accessing HTTPS resources. This is not required anymore as 3.12 and later include a new tool that runs on package installation and syncs Mono’s certificate store with the system certificate store (on older versions you had to import Mozilla’s list of trusted certificates by running mozroots --import --sync). Some systems are configured in a way so that the necessary package isn’t pulled in when Mono is installed, in those cases make sure the ca-certificates-mono package is installed.

**Comment by juzzbott** [comment]
Hmm, then there might be something else going on. 

Output from `mono --version` is: 
     Mono JIT compiler version 4.0.1 (tarball Tue Apr 28 11:47:58 UTC 2015)

I was getting those SSL errors when trying to run `dnu restore`. As soon as ran those commands above, the `dnu restore` operation completed successfully without any further changes required. 

It could just be that I needed to run the `mozroots --import --sync` without importing the certs, but I don't know as I executed all of the above commands.

Also, I didn't install the 'ca-certificates-mono' packaged mentioned on the link provided, so maybe this is what I was missing. Perhaps that should be put on the aspnet5 docs page, as I just followed the instructions on that page?

This was on a clean install of Linux Mint 17.1

**Comment by danroth27** [comment]
@glennc We should see if we can reproduce this issue.

**Comment by devlux** [comment]
> It could just be that I needed to run the mozroots --import --sync without importing the certs, but I don't know as I executed all of the above commands.

That did the trick for me on linux! Thank you for that hint @juzzbott ! :-)

**Comment by halter73** [comment]
I can also reproduce this issue on Mono version 4.0.3 on OS X.

We should update both the Mac and Linux docs to include the `mozroots --import --sync` step.

We should probably also update [the getting started github wiki](https://github.com/aspnet/Home/wiki/Getting-Started-Prerequisites-for-Debian,-Ubuntu-and-derivitives) since we are still linking to it from https://github.com/aspnet/home.

Without this mozroots step, `dnvm upgrade` hangs indefinitely after printing "Determining latest version".

**Comment by glennc** [comment]
The linux instructions have a not telling you that you need to run this if you compile from source, because you do. Otherwise the import is done when you do a package install. So I don't see anything we should change here for the Linux instructions.

@halter73 How did install Mono on OS X?
@halter73 I have thought and talked about adding MONO_THREADS_PER_CPU and @davidfowl strongly disagrees :)

**Comment by danroth27** [comment]
See latest published instructions here: http://docs.asp.net/en/latest/getting-started/installing-on-linux.html
