### ISSUE TITLE
Replace obsolete documentation with "working on this topic" pages

### ISSUE THREAD

**Issue by ncarandini** [aspnet/Docs#1929]
IHMO, it's much better not to have documentation than to have an obsolete one.
As an example, take the [Application Startup](https://docs.asp.net/en/latest/fundamentals/startup.html) page. Yes, there is a note that warns us that the info is still related to RC1, but people will read the page anyway, as I did to learn more about the topic.

In that page, the sentence:

> In ASP.NET Core, the Startup class provides the entry point for an application, and is required
> for all applications.

is no longer true. The entry point is the `program.cs` that contains the Main method, and even if this is definitely not the way to do it, we can write a program.cs like this:
```
using System;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;

namespace ConsoleApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var host = new WebHostBuilder()
                            .UseKestrel()
                            .Configure(app => app.Run(async (context) =>
                            {
                                await context.Response.WriteAsync(
                                    "Hello World. The Time is: " +
                                    DateTime.Now.ToString("hh:mm:ss tt")
                                );
                            }))
                            .Build();
            host.Run();
        }
    }
}
```
that runs perfectly well without using the `Startup` class.

***So what is the benefit of having such important topics documented in a obsolete way?***

Please don't get me wrong, I'm grateful to all the people that is working hard to produce/enrich/maintain the docs, I'm only suggesting to temporarily remove those obsolete docs and bring them back when updated to the current release.

**Comment by GuardRex** [comment]
Partially a dup of https://github.com/aspnet/Docs/issues/1756

**Comment by ncarandini** [comment]
Yes, @GuardRex, but my suggestion is a little bit more radical :-)
The example is just an example, the point here is to **_Replace obsolete documentation with "working on this topic" pages _**

**Comment by ardalis** [comment]
Regarding Startup, this is covered in #1307 which I've just self-assigned and will work on.

Regarding removing Docs instead of marking them as for a previous version, that might light a fire under us to make these updates faster, but I don't think it would be better overall for people looking for information (IMO).

**Comment by ncarandini** [comment]
Steve, is not my intent to stress you or anyone else.
Please consider that you know very well .net core and aspnet core, so you can easily take the good and skip the obsolete info. But a neofite can have more confusing experience reading old thing trying to do the same. I do agree that searching in the net require the same level of discernment, but I'd like to have only up to date info on official Microsoft website. especially when I read "latest" in the docs version.
My two cents :-)

**Comment by GuardRex** [comment]
> But a neofite can have more confusing experience reading old thing trying to do the same.
> IHMO, it's much better not to have documentation than to have an obsolete one.
> when I read "latest" in the docs version

Great points, but it might not be so black-and-white. I've been bopping around since like beta 5 or so and have noticed that it was rare that any particular doc as completely "obsolete." They were usually a mix of spot-on current info and recently-obsoleted info. Often, they were 70-90% good ... so mostly useful  ... but kind'a painful at times. Mad rushes of PR's flowed under times of heavy WIP to get caught up.

It turned out to be a rolling process of updates, so the question became something like, "Is it better not to have documentation on a topic than to have a 70-90% accurate one while the doc is caught up asap?" @ardalis can may say more about the behind-the-scenes talks, but what I can say is that they respect your feedback and all of us who have contributed have been trying to keep the ones we're on as up-to-date as fast as we can.

Great that you raised the issue. :+1: :beer: I agree with you on "is no longer true" re: `WebHostBuilder`, which is why I referenced the other issue, but they shot that one down. :cry:  ... oh, well ... win some, lose some.

**Comment by ncarandini** [comment]
> "Is it better not to have documentation on a topic than to have a 70-90% accurate one while the doc is caught up asap?"

Instead of answering (I've already wrote my opinion and you and Steve made good points against it) lets look at it from another perspective:

From a quantitative point of view, not counting index pages, external pages and API pages, we actually have 158 pages, Of those, 17 are obsolete (RC1 or RC2 versions) and 12 are on "working on" state. IMHO replacing 17 pages with "working on" state pages is a good thing to do.

From a versioning point of view, to me is not clear what is the meaning of the version list:
 - latest
 - 1.0.0
 - dev

So the versioning mechanism could be used to solve this issue, allowing us to opt for "only up to date" docs or the mix of 70%-90% of good vs. obsolete info.

**Comment by ardalis** [comment]
I can certainly see your point, and ultimately I think it's up to @danroth27 what is done. However, I think this is a temporary problem that will disappear once everything is updated to at least 1.0.0. After that, I don't expect any topics to be retired, since we can expect supported customers will be on a variety of shipping versions of the product.

**Comment by ncarandini** [comment]
Sure is a temporary problem, and I've opened this issue to contribute at solving this.
I'm still learning so maybe I can better represent the point of view of a rookie reader.
It's only a suggestion, I'm fine with whatever will be done about it.

**Comment by danroth27** [comment]
We are working on getting all of the remaining stale topics updated to be consistent with the RTM release, so soon this problem will be moot. In the meantime we think there is still value in having the old content available with an appropriate warning.
