### ISSUE TITLE
ASP.NET 5 on Windows Server Nano

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#194]
Tutorials -> ASP.NET 5 on Nano Server

**Comment by jjmartin** [comment]
i'd love any hint on this ASP.net 5 on nano or ASP.net 4.x 

i've got a nano-server running but its not clear to me even if its running IIS - i don't see an option to add a web server...

our current deploy doesn't work even tho its using WinRM - the current script we have does a Get-WmiObject call and that doesn't work (ConDep) so thats out.

**Comment by jchable** [comment]
I'd love to be part of the ASP.NET 5 on Nano Server documentation early drafts review  :) Thanks guys

**Comment by GuardRex** [comment]
I'm working on the instructions now ... I'll have notes for @Rick-Anderson shortly ... later tonight???!!! It's very rough but working thus far. Fingers crossed for a successful outcome! I'll ping back soon.

**Comment by GuardRex** [comment]
It looks like there is a special version of the `HttpPlatformHandler` for IIS 10 that hasn't been released but that is required to run .NET 5 apps on Nano Server. I say so because when I apply the config seen in IIS 8.5 for the module to the `applicationHost.config` file of IIS 10 it crashes the `AppPool` of the default app. I've sent a message to the IIS Team asking them for clarification on this.

**Comment by GuardRex** [comment]
### Progress Report

**GOT IT!** It's running now (thanks to a critical tips from @davidso). I have a solid set of notes/steps. The scenario I went with includes: an Azure Nano Server ARM VM, PowerShell ISE, a tidbit of PSEdit, and a network share using an Azure Files container.

I'll screenshot everything and provide a Word doc. I'll E-mail it to @Rick-Anderson. If you want me to continue thereafter, I'll happily do so; but if the official doc will be handled internally, I'm sure what I send over will be a huge help to you. I should have it done by noon on Thursday.

@jjmartin @jchable If you want a copy of my doc, let me know, and I'll arrange to post it where you cats can download it.

### :sparkles: **Nano Server** :sparkles: ... small in size ... BIG IN HEART! :heart:

**Comment by jchable** [comment]
Congrats and thanks a lot for your good job @GuardRex ! Could you share a copy of it ?

**Comment by GuardRex** [comment]
@jchable Thanks and sure thing. I'll ping you back here with a link to it. I should have it by Thursday on noon PST.

**Comment by benaadams** [comment]
:+1:

**Comment by GuardRex** [comment]
@danroth27 @Rick-Anderson @jchable @jjmartin

### Update

"Fragile" ... that's the word from today's work with Nano. I ran into config issues with the new test VM that I spun up. I did manage to take almost all of the screenshots needed for the doc; but because a fault with HttpPlatformHandler prevented me from confirming steps work, I'll be starting with a fresh VM in the morning.

It looks like there is a problem trying to install the IIS OneCore packages at the same time you're installing the Reverse Forwarders packages. I say that because after getting a 502, I moved a known-good `applicationHost.config` from yesterday's VM, which runs the Default Web Site and a .NET 5 site perfectly well ... moving that config file to today's VM crashes all AppPools. The only changes in that file are those that hook the HttpPlatformHandler. The module is the **same** DLL file and in the same spot. The only delta on these VM's AFAIK is that I installed IIS and ReverseForwarders packages at the same time in the same `unattend.xml` file.

On a side note, @benaadams recommended seeing the Events. I was able to get on this Nano VM's Events via Server Manager on a 2012R2 box. Events only show the module failing to load and the AppPool crashing right after that. I wasn't able to access the Events in Event Viewer on that server. That's probably my fault though ... I forgot at the time to open 135 in the Azure Portal (for the 2012R2 box) along with 135 on the Nano. It's late. I'm tired and the "working with servers enhancement beverages" wore off.

I'll reset tomorrow morning and try again. Nobody said Preview was going to be a walk in the park, right??!! :smile:

**Comment by GuardRex** [comment]
### Update

All good. Package installs on Nano is a fragile situation. IIS OneCore must be installed via `unattend.xml` followed separately by Reverse Forwarders via `DISM` direct commands. A critical restart (or restart of the `w3svc`) is also required for IIS to pickup the schema of the `HttpPlatformHandler`.

I'm still on target for getting the doc out today ... :sunglasses:

**Comment by GuardRex** [comment]
@danroth27 @Rick-Anderson @jchable @jjmartin

### Update

# :tada: Happy New Year! :tada:

I'm getting this online minutes before partying my rear-end off!

The doc has reached 1st draft stage. I'll leave this link up through the weekend: http://rexwestus.blob.core.windows.net/public/ASPNET5-on-Nano-Server.docx

Notes:
1. It is a 1st DRAFT. I wrote it today and only made a one-pass edit on it.
2. The Troubleshooting section that deals with attaching Event Viewer remotely is there (screenshots and all) ... but BROKEN. I'll get some feedback to sort that out later.
3. My philosophy for tutorials includes: (1) be clear, (2) use a lot of pics, (3) show a lot of code samples, (4) provide extra info and notes to help the reader understand what the heck is going on, and (5) provide adequate jumping-off links for more information. Those were the marks I was trying to hit.

Feedback ... comments, criticisms, remarks, death threats! ... all welcome.

**Comment by benaadams** [comment]
@GuardRex that's good and detailed; nice work :+1:

**Comment by GuardRex** [comment]
@benaadams Thanks ... that means a lot to me coming from you. It was fun to work up; and in spite of being a little rough around the edges (1st draft and all), I think it turned out ok.

**Comment by GuardRex** [comment]
**NOTE:** Talking to @benaadams ... have become aware that Azure will reserve some names used in the tutorial. There are a few spots (where Azure account/VM names are used in PASTE commands) that need to be deleted from the doc. Read past those PASTE commands ... I'll update and provide a revision here soon.

**Comment by GuardRex** [comment]
**NOTE:** @benaadams is providing important feedback now. There will be a set of minor (but important) revisions. Will provide updated doc link ... uh ... late New Year's Day ... uh ... yeah ... VERY late New Year's Day! lol :smile:

**Comment by benaadams** [comment]
Works like a treat!

**Comment by GuardRex** [comment]
# Updated

The doc has been updated based on conversation with @benaadams ... thanks again for his help ...

## http://rexwestus.blob.core.windows.net/public/ASPNET5-on-Nano-Server.docx

Updates
  1. Removed PASTE commands that contain Azure-specific naming, as those names cannot be guaranteed available to tutorial followers, e.g., "nanodemo"
  2. Stronger message on setting Azure security group to 'None' on Azure VM config
  3. Added note on requirement for running WinRM service locally if adding the VM's public IP to local Trusted Hosts fails.

**Comment by GuardRex** [comment]
Lot's of love for Nano ... lot's of love! @davidso @benaadams ... Thanks guys!

![capture](https://cloud.githubusercontent.com/assets/1622880/12072349/950222ba-b08f-11e5-8f0c-e2dd4ee06524.PNG)

**Comment by GuardRex** [comment]
@benaadams 

### :tada: Licked IT! :tada:

Updated the section dealing with remotely attaching Event Viewer on a management server (e.g., a 2012/R2 box with a nice GUI) to the Nano Server to see its Event Logs. The `Remote Event Log Management` firewall rules must be enabled on the Nano if you want to go from this ... :frowning: ... to this ... :smile:

The doc has been updated.

**Comment by GuardRex** [comment]
@danroth27 @Rick-Anderson 

This doc only covers insecure PowerShell access to the Nano. The doc should at least include the steps for 5986 secure access ... along the lines of Refaat Issa's http://blogs.technet.com/b/nanoserver/archive/2015/11/19/nano-server-iaas-image-in-the-azure-gallery.aspx

The question is should the secure approach be the only approach here? If so, it will make the troubleshooting section more complicated, too. It might be a little beyond the scope of the purpose of the doc, which is perhaps the least config required for getting things running.

I'll at least workup a section for it.

**Comment by GuardRex** [comment]
@danroth27 @Rick-Anderson @davidso @benaadams @moozzyk @Pinpoint @jchable @jjmartin  TL;DR ... but this is about the security issues surrounding Nano and PS remoting, so I'll take my time with it (@blowdart smiles! :smile:).

### Security Update on PS Remoting Options & Nano Server

#### Option 1: Use an Azure 2012R2 management VM for the demo
As the doc currently goes, interaction with Nano is via insecure PS remoting on 5985. Not good out in the open, but I would think fine if working with it behind a firewall. For example, the doc could instruct to spin up a 2012R2 management VM first, RDC into that, then follow the doc and do everything PS session-related with the Nano from that VM. This would be simple and secure.

I don't think a Nano public IP address hit on 5985 from another machine in Azure gets outside of Azure, even if the management VM and the Nano are in different datacenters. Of course, someone in-the-know should confirm that.

This approach also has a **great benefit**: All of the troubleshooting bits in the doc for using Server Manager and the remote Event Log work well with this approach. Options 2 & 3 are not going to be able to make this claim.

If this approach is adopted, however, it is absolutely required to add a few steps to the deployment to put the Nano on a Network Security Group and lock it down to port 80 for public access (Internet) ... maybe throw in a 443 option in case the reader knows they want to play with TLS, too.

#### Option 2: Use the Azure Portal to create the Nano VM and set it up post-deployment (only using secure methods of access) for 5986 secure PowerShell remoting
I spent a fair amount of time today working up creating a client authentication management cert locally (`New-SelfSignedCertificate`), getting it into `Cert:\LocalMachine\Root` [`$store.Add($mycert)`], exporting it to the share (`Export-PfxCertificate`) to get it accessible to the Nano. On the Nano side, one should be able to run a script with `Set-AzureRmVMCustomScriptExtension` that will grab the cert and get it installed with a `certoc.exe -ImportPFX ...`, then delete it from the share. This never touches the Nano over 5985.

Only prob with all of this ... Nano is very, VERY stripped down. A lot of PS commands aren't available. `winrm` CLI isn't available, so I don't know how to create the 5986 WinRM listener (yet, anyway). You can't do it via Group Policy either AFAIK. It should be possible to do it manually with `New-Item`/`Set-Item` in WinRM config values for `HTTPS` with the cert thumbprint ... but I didn't get that far.

This approach could work out to allow using the Azure Portal to create the Nano with the only modifications to the doc being: (1) Run a handful of extra commands locally to get the cert and get it on the share, and (2) Put a script on the share to take care of the Nano-side and it trigger it with a simple PS command. Again, everything performed without ever using 5985.

However, getting the listener running is still an unknown ... I didn't get that far today. I'd like to hear back from you before I spend more time with this. Note that Option 1 above and Option 3 (Refaat's approach) below are safer, so there might be an instant desire to drop this approach entirely from contention.

#### Option 3: Use the Refaat approach and drop the use of the Azure Portal entirely (with some gotchas to watch out for)
http://blogs.technet.com/b/nanoserver/archive/2015/11/19/nano-server-iaas-image-in-the-azure-gallery.aspx
  1. The script is not digitally signed, so I had to paste it into a new script and save that to run it.
  2. It doesn't lowercase the location automatically. If you accidentally use any uppercase letters, it will create a mismatch between the VM DNS name and the common name of the certificate, so be sure to provide it like this, for example, `-Location 'west us'`.
  3. There is a significant delay near the end of the deployment ... several minutes after you can see the VM is deployed in the Azure Portal, the script looks like it's hung. It's **not** hung. It just takes a long while before it reports back from Azure that the VM has been deployed with deployment details.
  4. Nit: If you don't supply a `-VMSize`, it defaults to `Standard_A2` ... **hey!** ... that's cool ... if your getting **free Azure because you work for Microsoft!** :smile: ... it should probably default to Standard_A0.
  5. Downsides: You lose setting up the Nano in the Azure Portal. I kind'a liked that bit. It's great that you can script/template your way to ARM Nano VM's ... I'm sure we'll all be doing that plenty, but it's also cool that you can login, do a little point-and-click in the UI, and you're deployment is on the way. No fuss, no mess! A Network Security Group should be added. You don't get Server Manager and Event Viewer fun bits this way.

#### Option 4: Hybrid of Options 1 & 3
Use the Refaat approach to create the Nano but add a Network Security Group to lock down the public side (80+443+5986 only). Also, the doc could have the reader deploy a 2012R2 VM. They can sort of choose on the PS remoting for how to hit the Nano, but the management VM would allow for the Server Manager and Event Log demo pieces of the doc.

### Preliminary Conclusion
My very preliminary gut feeling ... Option 1 ... I like it for three reasons ...
  1. Option 1 involves the Azure Portal for the Nano setup, where I frequently enjoy working.
  2. Security should be covered and no security best practices (that I've heard of anyway) would be violated with Option 1. Of Options 1-3, actually, I think Option 1 is the safest (but I want to hear from security gurus!). I like Refaat's approach, too; but as it stands, it doesn't add a Network Security Group. Even if it did, you'd have to open 5986 publicly.
  3. Option 1 allows for a great demo of remote monitoring with Server Manager and getting a nice GUI Event Viewer safely hooked up to your Nano.

**Comment by GuardRex** [comment]
@moozzyk Asks about the "containers" version or content. I like the idea, too, and I was going to suggest a section could be added to this one or a new doc for it. https://github.com/aspnet/Hosting/issues/539#issuecomment-168789381

**Comment by Rick-Anderson** [comment]
I'm working with the Nano folks to get this working on a local Hyper-V host. That would eliminate all the remoting concerns.

**Comment by Rick-Anderson** [comment]
There is a video on Channel 9 that shows how to do this end-to-end. https://channel9.msdn.com/Series/Nano-Server-Team/Demo-Building-a-Nano-Server-VHDX-for-a-Hyper-V-VM
I have that working and will explore that approach.

**Comment by GuardRex** [comment]
A few things jump to mind ...
  1. The lowest barrier to entry is probably the Azure image MS provides (for a tutorial I mean) ... not even a VHD image spun up in Azure. There's significantly more that has to be explained and that can go wrong with a generated VHD. It also takes lot longer to do: The Nano Server bits are in a folder with the full ISO, so it can take forever for that multi-gigabyte monster to download over a slow connection.
  2. A Hypervisor-based approach might be better as an add-on section, since the thrust seems to be AFAIK to get .NET 5 on Nano ... it would take (potentially) a lot more explaining ... and again, more can go wrong ... and probably will. :smile:
  3. Using an Azure 2012R2 VM for management (prob on the same subnet, prob with the Nano using an NSG) will be required anyway, even if a 100% Hypervisor approach is taken [but I'm not familiar (yet) with PS remoting through the Hypervisor itself (if I have that straight from Snover's comments), and I do like that idea and am looking forward to trying it out]. PS remoting over a locked-down subnet should be plenty secure and in-line with best practices. PS remoting has a lower barrier to entry.

I got pretty far with Hypervisor last night. I'm sitting down now to push ahead with it. What I'm doing is connecting an Azure 2012R2 with an installed Hypervisor (not via Roles & Features ... by PS command) to talk to an Azure Nano. I have the Hypervisor talking to the Nano ... I don't have the Nano playing nicely with it yet ... maybe I still need to open a few more ports. If they tell you all of the ports that need to be open on the Nano (and a full list of the required services would be nice, too), please ping me back.

**Comment by Rick-Anderson** [comment]
I'm working with the Nano team. Looks like they have already added a cert (or will add one soon).  I agree, we'll stick with the Azure image route for now.

**Comment by GuardRex** [comment]
Cool.

In the vid, Refaat is not using any kind of special Hypervisor-based remoting. I thought that's what Snover was talking about in some vids ... that there is a Hypervisor-based PS remoting that didn't run through the PowerShell CLI or ISE but through the Hypervisor itself.

Anyway ... whatever the case with that ... I'm going to see if I can get this Nano to play nicely with my Hypervisor. I guess they didn't give you a port (and services) list. No worries ... I just need my :hammer: and :wrench: to get it working!

**Comment by shirhatti** [comment]
*"I'm going to see if I can get this Nano to play nicely with my Hypervisor"*. 
@GuardRex Could you elaborate on how you are blocked?

**Comment by Rick-Anderson** [comment]
I was blocked too. Follow the 3 minute video https://channel9.msdn.com/Series/Nano-Server-Team/Demo-Building-a-Nano-Server-VHDX-for-a-Hyper-V-VM to get it working. The nano team claims the instructions at https://technet.microsoft.com/en-us/library/mt126167.aspx also work.

**Comment by GuardRex** [comment]
@shirhatti @Rick-Anderson Apparently, the Guest Drivers package doesn't open all of the ports if DISM is used on a running Azure Nano. I had to manually open ...
```
Virtual Machine Monitoring (RPC)
Virtual Machine Monitoring (NB-Session-In)
Virtual Machine Monitoring (Echo Request - ICMPv6-In)
Virtual Machine Monitoring (Echo Request - ICMPv4-In)
Virtual Machine Monitoring (DCOM-In)
```
@Rick-Anderson The VHD(X) built image(s) seem to get the right ports open by default. The Azure image-generated Nano seems not to have them open. I even tried adding the SCVMM package to see if that had a good effect, but it didn't.

... and the exception Hypervisor is giving me is ...

> Hyper-V encountered an error trying to access an object on computer 'NANODEMO' because the object was not found. The object might have been deleted, or you might not have permission to perform the task. Verify that the Virtual Machine Management service on the computer is running. If the service is running, try to perform the task again by using Run as Administrator.

That's as far as I got last night, and I just sat down to pick up from there, so I haven't done any additional troubleshooting yet on that one ... but at least the Hypervisor sees and is trying talk to the Nano now.

**Comment by GuardRex** [comment]
@shirhatti I guess I should also note that I'm not doing this an officially "MS supported" way, thus what I'm doing now can't go into the doc. Azure VM's don't support Hypervisor. You can't use Roles & Features to install the tools. You have to manually do it in PS. That's why this is more a "for Luke's fun and use" than a "very helpful for the doc" kind of thing.

**Comment by GuardRex** [comment]
@shirhatti I found the complete list of ports for Server Manager AFAIK ...

* Remote Service Management (NP-In)
* Remote Service Management (RPC)
* Remote Service Management (RPC-EPMAP)
* Remote Event Log Management (NP-In) 
* Remote Event Log Management (RPC)
* Remote Event Log Management (RPC-EPMAP)
* Windows Firewall Remote Management (RPC)
* Windows Firewall Remote Management (RPC-EPMAP)

... still getting ...

> Error nanodemo : BPA result refresh failed with the following error: The system cannot find the file specified. 	1/6/2016 1:47:15 AM
> Error nanodemo : Performance counter refresh failed with the following error: Class not registered 	1/6/2016 1:47:15 AM

I guess those are totally expected right now ... biz practices analyzer and perf counters ... under development I guess.

I'm switching over to look at the Hypervisor bits now (got slowed down by some company ops stuff this afternoon). Thus far, I see some Events that look related to this Hyper-V problem:

  1. The VM and host networking components failed to negotiate protocol version '6.0'
  2. The VM and host networking components failed to negotiate protocol version '6.1'

**Comment by GuardRex** [comment]
@Rick-Anderson @shirhatti I'll pick back up with my unsupported-by-MS :smile: Hypervisor scenario later. Bigger :fish: to fry now ...

Big doc update tomorrow. I'll ping here and by E-mail when the updated doc is ready sometime Wednesday afternoon.

**Comment by GuardRex** [comment]
@Rick-Anderson @shirhatti The doc has been (mostly) updated with a major emphasis on security. Instead of having folks go direct to the Nano Server via 5985/5986 over the open Internet :skull:, the doc has been revised for the following ...
  * Added sections and notes dealing with security issues with links to starting points for learning more.
  * Create a 2012R2 Management VM (so there are a pair of VM's now).
  * Have the management VM and Nano on a VNET.
  * Create Network Security Groups for the VM's.
    - 2012R2: Opens only RDP (3389).
    - Nano: Opens only HTTP (80) & HTTPS (443) to the Internet. Opens 5985 on the VNET.
  * Eliminated the PSEdit example, as 2012R2 comes out-of-the-box with PS 3.
  * Utilized a set of prelim steps in Azure to establish the Resource Group, Storage Account (and File Share container), the Virtual Network, and the Network Security Groups for use later in the tutorial when deploying the Azure VM's.
  * Have the folks also create and use static IP addresses and set a DNS address label on the Nano for easy reference.

This 2nd draft is **almost** done. I still need to carry the DNS address label down through the Troubleshooting section (Server Manager and remote Event Log). I should have that done by Friday noon. You can probably look at this now ... you'll just see IP addresses in the Troubleshooting section that will become "nanodemo1234" by Friday.

As I was making these changes today, it didn't escape my attention that this does make the tutorial substantially heavier. However, may I remind you of the ... let's call it ... The @blowdart Gambit! That's a sacrifice of time and energy initially for a great advantage in security later. I prefer this approach and cross-introduction to a few good security concepts while demonstrating the **amazing** Nano Server. "Small in size. Big in :heart:!" However, your call, of course.

#### http://rexpublic.blob.core.windows.net/public/ASPNET5-on-Nano-Server.zip

**Comment by blowdart** [comment]
Wait, are you calling me heavy?

More seriously I'm pretty sure everyone knows I would like everything secure by default, even if it brings more work. Otherwise folks will take the easy route, if you present it to them, regardless of security implications/

**Comment by GuardRex** [comment]
@blowdart :+1: ... and the easy route would be to make the tutorial simple and fast but almost encourage folks to leave 5986 open publicly (and other ports for Server Manager and remote Event Viewer ... Event Viewer being virtually required for .NET work), when that's vastly less secure and a violation of best management practices.

There's no easy way around it. If we want management points locked down, then we have to take the time in the tutorial to show it. If they go off-road and set the Nano up for direct access, or even worse use it publicly over 5985, that's on them. I even wanted to use a non-standard port for RDP, except that NSG doesn't do NAT, and we don't want them changing the port in the registry ... had to draw the line somewhere. The tutorial obviously can't be a book.

I'm looking forward to feedback. I'll get rid of the Nano IP address in Troubleshooting (in favor of the Nano's DNS address label) within 48 hours and ping back when that's done.

**Comment by blowdart** [comment]
I appreciate the work going into this.

Honestly.

**Comment by benaadams** [comment]
@GuardRex shouldn't
```
New-NetFirewallRule -Name "DCOM-In_135" -DisplayName "DCOM Service Control Manager (DCOM-In)" -Protocol tcp -LocalPort 135 -Action Allow -Enabled True
```
As its an existing rule, be something more like
```
Set-NetFirewallRule -DisplayName "Windows Remote Management (HTTP-In)" -Enabled True
```
Not sure what the right rules are but you can get them with
```
> Get-NetFirewallRule
```

**Comment by GuardRex** [comment]
@benaadams In the latest draft, I only have `Net-NewFilewallRule` for opening port 8000. There is a handy one for the existing rules ...
```
Enable-NetFirewallRule -DisplayName "<DISPLAY_NAME>"
```
... which I found works better than using the `-Name` property on that command (for whatever reason).

If you haven't seen the latest draft, I'm still working on grammar and phrasing, but you can get it at http://rexpublic.blob.core.windows.net/public/ASPNET5-on-Nano-Server.zip

**Comment by benaadams** [comment]
Also you can use the PS command
```
> Restart-Computer
```
rather than doing it in the portal

**Comment by GuardRex** [comment]
@benaadams thx ... change made.

@Rick-Anderson @danroth27 

2nd Draft Final is done (when you open, confirm by looking at the title, which states "2nd Draft Final"). I'm going to run through it all again start-to-finish from scratch on Saturday morning. I'll ping here if anything goes sideways.

#### http://rexpublic.blob.core.windows.net/public/ASPNET5-on-Nano-Server.zip

Let me know as soon as you can if you want to take this approach or go back to the low-security-one-VM-5986-direct (with new Nano cert) version. I'd like to start refactoring into RST asap, but I'll wait until you make a final call on the approach before I do the deed. :wrench:

**Comment by GuardRex** [comment]
1/8 10:13pm PST ... Minor update regarding use of `cmdkey` to persist the credentials for the network file share across reboots.

**Comment by GuardRex** [comment]
1/9 11:06am PST ... Minor update: Removed static public IP address assignment step for the Nano as unnecessary. Added a note as to why the management VM is getting a static public IP address [it's merely a convenience for using Remote Desktop Connection (RDP) across deallocating/re-allocating the management VM].

**Comment by GuardRex** [comment]
For the 3rd draft, I want to change the name of the storage account to "storage1234," because I think naming the storage (currently "nanodemo1234") the same as the Nano ("nanodemo1234") but also using that storage for the management VM ("vmmdemo1234") is a bit confusing. I also think that using the word "nano" in the shared services isn't good.

How about a scheme like this:

Resource | Name
------------ | -------------
Nano Server VM | nano1234
Management Server VM | vmm1234
Resource Group | group1234
Storage Account | storage1234
Virtual Network | vnet1234

**Comment by GuardRex** [comment]
@Rick-Anderson I've updated the text and images to conform to the naming in my last comment. It's definitely an improvement.

#### http://rexpublic.blob.core.windows.net/public/ASPNET5-on-Nano-Server.zip

Unless you have any objection, I'm going to move it to RST now.

**Comment by GuardRex** [comment]
@Rick-Anderson It's going well with RST. I'll have it done today. I have one more minor update to apply: For convenience, I used the same username for the management VM as for the Nano. Since the tutorial takes its time on security issues, I want the management VM on username "adminuser" and the Nano on username "nanouser."

Note that I'm pulling the direct link to the Word version out this issue. There have been a number of minor updates going into RST that make the Word version obsolete (especially those horribly long section and sub-section titles that I had).

**Comment by rs38** [comment]
@Rick-Anderson @danroth27 
any chance to update the nano tp5 tutorial to RTM?
are the workarounds still necessary?

**Comment by danroth27** [comment]
@rs38 Yup, we will be doing a general content refresh once we have completed the migration to docfx. It would be great if you could file a new issue specifically for updating the Nano article.
