### ISSUE TITLE
Documentation: Improve discoverability of "htmlAttributes" entry in `ViewDataDictionary`

### ISSUE THREAD

**Issue by Eilon** [aspnet/Docs#2009]
_From @dougbu on October 6, 2014 17:5_

`@Html.Editor()` and `@Html.EditorFor()` special-case an entry named "htmlAttributes" in the `ViewDataDictionary` (optionally augmented using `additionalViewData` parameters) when executing their default templates. MVC 5.2 issue [#2142](https://aspnetwebstack.codeplex.com/workitem/2142) is an indication this feature needs additional documentation. Users will otherwise search for ways to control generated HTML attributes when using these methods.

Couple of details:
- "htmlAttributes" key is case-insensitive
- entry is handled very similarly to the `htmlAttributes` object passed to input helpers such as `@Html.HiddenFor()` and `@Html.TextBox()`

_Copied from original issue: aspnet/Mvc#1233_

**Comment by ardalis** [comment]
Where should this be documented? https://docs.microsoft.com/en-us/aspnet/core/mvc/views/overview seems like the closest place, currently.

**Comment by dougbu** [comment]
@ardalis that page doesn't mention `@Html.Editor(...)` or `@Html.EditorFor(...)` and those are the only methods that support `"htmlAttributes"` keys in the `ViewDataDictionary`. I suggest https://docs.microsoft.com/en-us/aspnet/core/mvc/views/working-with-forms

Side notes (FYI):
- Doesn't really matter what adds the key to `ViewDataDictionary`. It's most commonly done in the `@Html.Editor[For]()` call (using the `additionalViewData` parameter) because it's rare for the same HTML attributes to be correct for multiple calls in a view.
-  `@Html.Display()` and `@Html.DisplayFor()` also support `additionalViewData` parameters but don't check the merged `ViewDataDictionary` for the `"htmlAttributes"` key.

**Comment by Rick-Anderson** [comment]
@ardalis can you do this under PO?
