### ISSUE TITLE
 how to set ENVIRONMENT VARIABLES per IIS AppPool 

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#2030]

**Comment by Rick-Anderson** [comment]
@Tratcher 

In [Working with Multiple Environments](https://docs.asp.net/en/latest/fundamentals/environments.html) customer asks:

>here is no explanation on how to set ENVIRONMENT VARIABLES per IIS AppPool anywhere.  Setting global environment variables per server is not ideal in some cases.

cc @danroth27 @GuardRex @spboyer

**Comment by Rick-Anderson** [comment]
I think his question might be, what if I have several production app pools for different production apps.

**Comment by Tratcher** [comment]
One way to do it is via the aspnetcore section of your web.config. Just keep in mind that you want to add app secrets to this file during/after deployment such that they are not checked into source control.
https://docs.asp.net/en/latest/hosting/aspnet-core-module.html#setting-environment-variables
http://stackoverflow.com/questions/31049152/publish-to-iis-setting-environment-variable/36836533#36836533

Some hosting environments have their own way for you to set env variables. Here's one for Azure App Services: http://stackoverflow.com/a/34622196/2588374

**Comment by GuardRex** [comment]
> I think his question might be, what if I have several production app pools for different production apps.

I thought so, too. I thought he was asking from the standpoint of perhaps deploying apps to staging and production AppPools without wishing to set env vars explicitly for each site in IIS.

I asked him in Disqus if he would elaborate on his setup.

**Comment by GuardRex** [comment]
From Disqus @guardrex ...

> how do you set different pools to have different environment variables?

Good point, and some sys admins will want to distinguish an app's configuration based upon the AppPool. The APP_POOL_ID env var is set by process, so it should return the AppPool of the app. Try some app startup logic that can set the environment for the app based on the name of the AppPool returned ...
```
var appPool = Environment.GetEnvironmentVariable("APP_POOL_ID");

string localEnvironment;

if (appPool == "My_Production_AppPool")
{
    localEnvironment = "Production";
}
else if (appPool == "My_Staging_AppPool")
{
    localEnvironment = "Staging";
}
else
{
    localEnvironment = "Development";
}
...
var host = new WebHostBuilder()
    ...
    .UseEnvironment(localEnvironment)
    ...
```
That's affectionately known (or despised and ridiculed) as the "NutJob Startup Pattern," by your's truly. I use a similar pattern based on well-named VM's, because I hate both env vars and config files all over the place. I like an app that just has to ask one question, "Where am I?" ... then completely configures itself based upon where it finds itself. https://gist.github.com/GuardRex/f40f1b1414e175a6514f

Natan, could you talk a little more about what you're trying to accomplish? I'm sure you're aware that env vars are set in IIS by site, not by AppPool.

You're asking about them in relation to .NET Core, but the only thing that exists in the tooling to help is web.config, where you can set them in the aspNetCore element: https://docs.asp.net/en/latest...

Personally, I've always hated working with them, and I steer clear of config files across hosting environments, too. If your goal was to just have the app configure itself based on which AppPool its running under, then I think what I posted below should work ok and it avoids the pain of dealing with env vars on servers.

**Comment by GuardRex** [comment]
From Disqus @nvivo ...

Sure. I have some apps where we use the same server for different environments. For example: site.com, dev.site.com, test.site.com are all in the same VM. I'd like the environment to be defined for the site instead of the entire server.

Web.config allows me to define environment variables per site, but I need to change that during publish or I need the build system to take care of that.

What would be ideal is to be able to set environment variables per site the same way you can globally per server. With global environment variables, I can have a "production server", and a "testing server", and get the correct environment just by publishing code to that server. But it's currently quite hard to have a "test site" and a "production site" in the same server and get the correct environment just by putting the files into a different folder.

There are ways, it seems possible to add an environment variable for each IIS AppPool user, but that is currently so complicated and requires so many steps I find it easier to change the appsettings.json manually. The tooling for that is terrible at this moment.

I feel this should be a common scenario everywhere, but there is hardly anything written about it. Every doc assumes I'm either using Azure or I have a dedicated machine for each instance of the app, which in many cases isn't true.

A simple way to set environment variables per IIS site is what I'm missing.

**Comment by GuardRex** [comment]
From Disqus @guardrex ...

> it seems possible to add an environment variable for each IIS AppPool user

Yes, that's common, but I agree with you that that's a big 'ole mess.

> What would be ideal is to be able to set environment variables per site

Except for using `web.config`, which sucks because of the problem of needing different `web.config` files, this is an IIS thing. You'd have to open something with the IIS folks about it. The .NET cats probably won't be able to do much in this regard.

> I feel this should be a common scenario everywhere

The most common thing I've seen in my travels is settings configuration files. To me, that can be a bit of a mess, too. Config files lying around all over the place.

I've always felt that env vars are difficult to work with on servers: They're somewhat hidden. You always have to remember to set them up when you spin up a new box. What I do is to well-name my VM's and use that as you see in my "nutjob" pattern for startup. It's rock solid, and I don't have config files or env vars anywhere ... not on servers, not for staging, not on my local machine.

Similarly as I posted below, what you could do is just detect the AppPool directly in the app's startup, then have the app totally configure itself based on the AppPool name (aka "nutjob" pattern). That would solve the whole problem without ever needing or setting an env var.

**Comment by Tratcher** [comment]
@shirhatti This is an IIS feature request.

**Comment by shirhatti** [comment]
The ability to set [environment variables on IIS worker processes](https://www.iis.net/configreference/system.applicationhost/applicationpools/add/environmentvariables) was introduced in IIS 10.

Try this
```
appcmd.exe set config -section:system.applicationHost/applicationPools /+"[name='DefaultAppPool'].environmentVariables.[name='VAR',value='val']" /commit:apphost`
```

**Comment by andrecarlucci** [comment]
@shirhatti Nice, but how to do the same for a specific website instead of the whole apppool? I can do it using the IIS Manager, but I couldn't find a way to do the same with appcmd.exe :(

**Comment by ljani** [comment]
@shirhatti Thanks for the tip, exactly what I was looking for!

In my opinion, app pool environment variables should be mentioned in the IIS section of the docs.

Having environment variables in `web.config` is not a good option, because as said, it requires manual intervention during deployment or checking `web.config` into version control (ie. you end up with another `appsettings.json`). App pool environment variables are perfect for this.
