### ISSUE TITLE
ASP.NET hub page needs link to ASP.NET Core

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#2055]
The [ASP.NET hub ](https://review.docs.microsoft.com/en-us/aspnet/?branch=master) page needs links for:

- [x]   [WebHooks](https://review.docs.microsoft.com/en-us/aspnet/webhooks/)
- [ ]  ASP.NET Core Documentation

This page should be consistent with the [.NET hub page](https://docs.microsoft.com/en-us/dotnet/)
@bradygaster  how can I links from Docs\aspnet to Docs\aspnetcore ? They have different OPS build scripts.

**Comment by Rick-Anderson** [comment]
#2056  is related

**Comment by bradygaster** [comment]
@Rick-Anderson there should be no links to /aspnetcore. the url should be /aspnet/core

**Comment by bradygaster** [comment]
@Rick-Anderson i have created and fixed the index.md file so that it is a properly-rendering hub page. i've also changed the GUID so that it is unique for this asset id and made you the owner in the metadata. I removed all the titles and links and stuff, as the hub page was having a LOT of issues when copied/pasted from the .net core hub page repo. At this point the page is ready for you to add real links and to make it what the team wants. marking this item as closed.
