### ISSUE TITLE
POST Conversion: remove newlines on bullet lists

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#2111]
master issue [704183](https://mseng.visualstudio.com/TechnicalContent/_workItems?id=704183&fullScreen=false&_a=edit)

**Comment by tdykstra** [comment]
@Rick-Anderson Be careful about how this is implemented, as there are many places where extra lines are in lists on purpose.  E.g., 

* Here is item 1

  Here is descriptive text for item 1.

* Here is item 2

  Here is descriptive text for item 2.

Here is what happens when lines are removed.

* Here is item 1
  Here is descriptive text for item 1.
* Here is item 2
  Here is descriptive text for item 2.

In some cases the alternate formatting might be OK. But each instance would have to be verified and fixed if necessary.

**Comment by Rick-Anderson** [comment]
Maybe it's best to do this manually. The extra lines are not too bad. Should I close the help desk request to fix this?

**Comment by tdykstra** [comment]
Manually makes sense to me.
