### ISSUE TITLE
Document whether injected objects should be disposed

### ISSUE THREAD

**Issue by denisz1** [aspnet/Docs#2112]
[The DI document](http://docs.asp.net/en/latest/fundamentals/dependency-injection.html#service-lifetimes-and-registration-options) should make it very clear whether we need to dispose injected objects, or whether we can rely on the built-in IoC container to do that for us.

I've looked into the source code, so I know what is happening behind the scenes, but I cannot rely on that behavior.

Please document this.

**Comment by davidfowl** [comment]
That's  good to document especially since we just made a change to the behavior is 1.1. The DI container will dispose things it creates. If you add an instance to the container then it won't be disposed in 1.1. We currently dispose everything in 1.0.

**Comment by denisz1** [comment]
@davidfowl I don't think I understand the change from 1.0 to 1.1 (please forgive my n00bness)... are you saying in 1.1 the container doesn't dispose my objects, and I should dispose them myself?

**Comment by davidfowl** [comment]
@denisz1 Here's an illustration:

```C#
public interface IFoo
{
}

public class Foo1 : IFoo, IDisposable
{
    public void Dispose() => Console.WriteLine("Disposed Foo1");
}

public class Foo2 : IFoo, IDisposable
{
    public void Dispose() => Console.WriteLine("Disposed Foo2");
}

var services = new ServiceCollection();
services.AddSingleton<Foo1>();
services.AddSingleton<Foo2>(new Foo2());
var sp = services.BuildServiceProvider();
var foo1 = sp.GetService<Foo1>();
var foo2 =sp.GetService<Foo2>();
((IDisposable)sp).Dispose(); // Dispose the container
```

In 1.0.0, the above will print

```
Disposed Foo1
Disposed Foo2
```

In 1.1.0, the above will print

```
Disposed Foo1
```

The important part is this:

```C#
services.AddSingleton<Foo2>(new Foo2());
```

If you add an instance to the container, we no longer call dispose on it. Generally, you dispose things you control the lifetime of. When the user specifies an instance, it might be something they want to explicitly control so we shouldn't be disposing it. It causes more problems when you share an instance between multiple containers, disposing one container would cause it to dispose an active reference in another container. That's why we fixed it.

**Comment by denisz1** [comment]
I understand now, thanks!
That example is great BTW, it should be used in the docs, when this item is documented.

**Comment by ardalis** [comment]
Looking to update this once the doc is updated to 1.1.

**Comment by Rick-Anderson** [comment]
@ardalis  can you give me an ETA on this?

**Comment by ardalis** [comment]
Knocking it out now.
