### ISSUE TITLE
performance/caching/middleware.md "Response caching middleware"

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#2198]
@GuardRex  [meeting notes](https://dl.dropboxusercontent.com/u/18075777/Record_0005.wav)
go at it.

**Comment by GuardRex** [comment]
@JunTaoLuo Just adding myself here so I'll get an E-mail from GH when the outline is ready.

**Comment by tinchou** [comment]
There's a subscribe button you'll find pretty useful :)

**Comment by GuardRex** [comment]
I'm subscribed to this repo's issues, but I don't get E-mail from GH on a specific issue unless I post to it. I just want to make sure I get an E-mail on this one so I can jump right on it when the outline is ready. [The Rex is lick'in his chops to get into this! :smile: ]

**Comment by JunTaoLuo** [comment]
Topics to include:
- Sample
  - Use something similar to the sample in the ResponseCaching repo: https://github.com/aspnet/ResponseCaching/blob/dev/samples/ResponseCachingSample/Startup.cs
  - Note that this sample does not illustrate how to use the `ResponseCachingFeature` to configure `VaryByQueryKeys`
- Extensions needed to use the middleware
  - `AddResponseCaching()`, `UseResponseCaching()`
- Options
  - `UseCaseSensitivePaths`
  - `MaximumBodySize`
- ResponseCachingFeature
  - `VaryByQueryKeys`
- functions as an HTTP cache
  - relevant headers:
  - `Authorization` (we do not cache if it exists)
  - `Cache-Control`
    - `max-age`, `max-stale`, `min-fresh`, `must-revalidate`, `no-cache`, `no-store`, `only-if-cached`, `private`, `public`, `s-maxage`, `proxy-revalidate`
  - `Pragma`
    - `no-cache`
  - `Set-Cookie`
  - `Vary`
  - `Expires`
  - `If-None-Match`
  - `If-Modified-Since`
  - The middleware also sets the following when appropriate:
  - `Date`
  - `Age`
  - `Content-Length`

**Comment by JunTaoLuo** [comment]
@GuardRex Thanks for helping out, let me know if you have any questions.

**Comment by Rick-Anderson** [comment]
@GuardRex  [meeting notes](https://dl.dropboxusercontent.com/u/18075777/Record_0005.wav)

**Comment by GuardRex** [comment]
@JunTaoLuo Thanks John. I'll be wrapping the Pub IIS doc with Tom's feedback by tomorrow afternoon. I want to take a quick look at the use of ["command line" language (Docs/2248)](https://github.com/aspnet/Docs/issues/2248) and get back to to Tom on that Wednesday afternoon, then I'll get right on this.

**Comment by GuardRex** [comment]
@JunTaoLuo Bit of a side-question, but I'm confused on seeing ...
```
context.Response.Headers[HeaderNames.Vary] = new string[] { "Accept-Encoding" };
```
I would have expected to see it in a compression sample, where the Response Compression Middleware changes the encoding but doesn't set the header automatically AFAICT from my testing. 

In a purely caching sample, where there only ever is one encoding (`text/plain` in the sample, for example), do you want that there? ... I mean the Response Caching Middleware never changes the encoding all by itself, does it?

**Comment by JunTaoLuo** [comment]
@GuardRex The `Vary` in the sample was there to illustrate how to vary the cached response by another header. In the example, the `Accept-Encoding` header was used but we could have used any other header. The `Microsoft.Extensions.Caching.Memory` dependency is unnecessary as you have mentioned and seems to be something that was not cleaned up.

**Comment by GuardRex** [comment]
@JunTaoLuo I'm researching whether or not it is relevant to mention disabling IIS output caching in `web.config` for an app that prefers to use the middleware where IIS has been configured at the server level to cache objects.

I ran a test with the `HttpCacheModule` ...
1. a non-ANCM site to confirm IIS output caching was working normally (it worked :+1:)
2. a non-middlware ANCM-Kestrel site serving the same test image with the same `Cache-Control` header

I couldn't get the IIS module to cache the test image from the ANCM-Kestrel site. so it looks like the module isn't effective with reverse-proxy setups. Is that correct? If it should work, I'll go back and check my test setup again.
