### ISSUE TITLE
How to convert document from rst to md format

### ISSUE THREAD

**Issue by kiler398** [aspnet/Docs#2217]
Hi，I have attend a open source project for translate .net core document into chinese (https://github.com/dotnetcore/aspnetcore-doc-cn/).

We have work on the translate rst file,but we find that all the rst file have been change to md.

Is there any tools for microsoft to convert rst to md format? so we can reduce effort on translate work。

**Comment by Rick-Anderson** [comment]
@shirhatti can you share your conversion tool?

**Comment by shirhatti** [comment]
I'd recommending using [`pandoc`](https://pandoc.org/try/) to convert individual files from rst to Markdown.

Unfortunately, I can't share the tool I authored since it is an a dismal state right now. 
I basically implemented a Sphinx builder based off the [HTML builder](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/builders/html.py) as part of Sphinx. If you are interested in replicating it, I can share more details.

**Comment by xbuilder** [comment]
So,There is no solution?

**Comment by Rick-Anderson** [comment]
We don't have one, but you could try using [`pandoc`](https://pandoc.org/try/) to convert individual files from rst to Markdown.

We will be starting localization of our docs early next year.
