### ISSUE TITLE
Guidance on Deployment multi-tire MVC/EF Core 1.0 .net 4.6 starting with local IIS then Azure VM 

### ISSUE THREAD

**Issue by ElvisHalil** [aspnet/Docs#2318]
Hello,

As the title states, I would like some guidance or documentation on how to deploy first locally to IIS (running windows 10) and then to a azure VM.  My assumption is that this will be quite a similar process for the two.  

I'm having a hard time finding proper documentation on this.  

I have a multi-tier solution running successfully in VS locally.  It has a web component with MVC 6 and a few class library projects including one for Entity Framework core 1.0.  It is utilizing full .net 4.6 framework. 

Some help would be much appreciated!

**Comment by GuardRex** [comment]
@ElvisHalil 

For the local IIS case, go by https://docs.microsoft.com/en-us/aspnet/core/publishing/iis
For the Azure case, go by https://docs.microsoft.com/en-us/aspnet/core/tutorials/publish-to-azure-webapp-using-vs

The main docs entry point is https://docs.microsoft.com/en-us/aspnet/core/

**Comment by ElvisHalil** [comment]
Thank you @GuardRex 

I have seen these docs, I will try to follow and see if I can get any success.  

I am not using the ASP.NET Core Web Application (.NET Core) rather I am using 

ASP.NET Core Web Application (.NET Framework)

does this make a big difference regarding deployment?

**Comment by GuardRex** [comment]
There's no difference, because both on IIS and in Azure Apps, Kestrel must use IIS as a reverse-proxy server; so in both cases, IIS will use the ASP.NET Core Module (ANCM) to proxy the requests.

You prob saw the docs for the module. Those are good to look at as well when setting up IIS and the app when hosting .NET Core apps (both Core CLR and .NET Framework).

It comes down to Kestrel ... If your app is on Kestrel and you're trying to run on IIS, then you should use the ANCM. You will install it using the hosting bundle installer locally, and Microsoft has it installed in Azure Apps for apps there to use.

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/aspnet-core-module
https://docs.microsoft.com/en-us/aspnet/core/hosting/aspnet-core-module

**Comment by ElvisHalil** [comment]
When I follow the instructions and try to browse to the site I get a error:

This site can’t be reached

www.tech.com’s server DNS address could not be found.

**Comment by GuardRex** [comment]
Sounds like a DNS resolution issue.

btw--- Given that this is the Docs repo, you probably should close here and open an issue over in the IISIntegration repo: https://github.com/aspnet/IISIntegration/issues

**Comment by ElvisHalil** [comment]
@GuardRex  Thank you sir, will move over there.  

Much appreciate the guidance!
