### ISSUE TITLE
Document how to host ASP.NET Core in a Windows Service

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#2467]
Using https://docs.microsoft.com/en-us/aspnet/core/api/microsoft.aspnetcore.hosting.windowsservices

**Comment by danroth27** [comment]
Note, this currently only works on full .NET.

**Comment by spboyer** [comment]
https://github.com/lankaapura/MusicStoreAsWindowsService

**Comment by danroth27** [comment]
@muratg Who can help out with the outline and technical details for this one?

**Comment by tdykstra** [comment]
@Tratcher Can you help out with the outline and technical details for this one?

**Comment by Tratcher** [comment]
https://github.com/aspnet/Hosting/issues/771#issuecomment-270608527

**Comment by Rick-Anderson** [comment]
@Tratcher  what are the scenarios for running in a windows service? Why would you do that?

**Comment by Tratcher** [comment]
When you want it to always be running. Windows will start it for you on boot, restart it if it crashes, etc..

**Comment by tdykstra** [comment]
Proposed outline for the doc:

* Overview:

  * Article explains how to run in Windows Service.
  * Scenario:
    * You want to run on Windows,
    * You don't want to use IIS,
    * You want automatic restart after reboot or crash

* Prerequisites
  * Runs only on .NET Framework 
    * (.csproj example showing TargetFramework and RuntimeIdentifier) 
    * When creating a project in VS, use the ASP.NET Core Application (.NET Framework) template.
  * Use WebListener rather than Kestrel for edge deployments.  See [When to use Kestrel with a reverse proxy](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel#when-to-use-kestrel-with-a-reverse-proxy)  

* Getting started
  * Install package [Microsoft.AspNetCore.Hosting.WindowsServices](https://www.nuget.org/packages/Microsoft.AspNetCore.Hosting.WindowsServices/).
  * In Program.Main:
    * Use an absolute path to the publish location for UseContentRoot
    * Call host.RunAsService instead of Run
    * (code snippet example)
  * Publish
  * Create the service (`sc create servicename binPath="path to executable"`)
  * Start the service (`sc start servicename` or use Services MMC)
  * Can now browse to same path as when running as console app

* Provide a way to run outside of a service
  * Check command-line args and/or debugger attached and call RunAsService only if running as a service
  * (code snippet example)

* Handle stopping and starting events
  * Create an implementation of WebHostService and IWebHost extension method.
  * In Program.Main change the host.RunAsService command to use new extension method
  * (code snippet example)

* Sample app 
  * Create from MVC web app template, add package and code needed for example snippets.  

@Tratcher please review, plus a question:  can you point me to an example that shows how to get services (e.g., a logger) in a WebHostService derived class?

**Comment by Tratcher** [comment]
Looks good.

As for services, they're on the IWebHost, and your constructor should have access to that.
https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting.WindowsServices/WebHostService.cs#L30-L32

**Comment by tdykstra** [comment]
[Review URL](https://review.docs.microsoft.com/en-us/aspnet/core/hosting/windows-service?branch=td/runinsvc)
