### ISSUE TITLE
Discrepancy in resource based authorization docs

### ISSUE THREAD

**Issue by rtpHarry** [aspnet/Docs#2519]
https://docs.microsoft.com/en-us/aspnet/core/security/authorization/resourcebased

At the top it shows the auth service being injected and saved as `_authorizationService` but the rest of the snippets refer back to it as `authorizationService`.

Should I create a PR for this?

**Comment by GuardRex** [comment]
I'm a community cat, but I can tell you 'yes' on that. For a simple grammatical problem or broken code situation, you can just float the PR directly without an issue. Sometimes they must reject the PR because the update needs more design or should be addressed broadly across docs; but in this case, it really is broken code that just needs a touch-up.
