### ISSUE TITLE
Publishing to IIS doc does not cover how to ACL the directory containing your site

### ISSUE THREAD

**Issue by shirhatti** [aspnet/Docs#2532]
It would be great if https://docs.microsoft.com/en-us/aspnet/core/publishing/iis referenced https://docs.microsoft.com/en-us/aspnet/core/hosting/apppool#securing-resources this somewhere as that information is otherwise difficult to discover.

Linked issue https://github.com/aspnet/Hosting/issues/914

**Comment by GuardRex** [comment]
@shirhatti @tdykstra Do you want me float some language in there for this?

**Comment by tdykstra** [comment]
@GuardRex Yes, that would be great.  How about incorporating the App Pool doc content into publishing/iis and retire the separate app pool doc?

**Comment by GuardRex** [comment]
Sure ... I can handle that.

There's a few things to consider ...
* In the **Add Website** dialog, IIS fills the "Site name" text over to the "Application pool" textbox and creates a new AppPool for each new site created unless you click **Select** to use an existing AppPool. @shirhatti, your opening paragraph might be misinterpreted by a reader that they will need to explicitly setup a new AppPool for each app separately after the site is created (outside of the **Add Website** dialog). If it's ok, I'd like to refactor that language a hair.
* We don't want to make anyone think that merely running a site requires an AppPool identity other than `ApplicationPoolIdentity`. It comes up when the process needs other permissions. I'm concerned about the "To grant the IIS worker process access to your application, you will need to ..." language. The "access" could be misinterpreted as "to even load the site" and the "you will need to" implies that it must be done for every app. If it's ok, I'd like to work on that text just a bit.

... and I'll update the images to WS2016.

Finally, there's that open PR at https://github.com/aspnet/Docs/pull/2488, which I don't think would result in a merge conflict if I update that branch after a PR for this issue. Otherwise, it might be safer if that other PR gets merged first. Why do I feel a big 'ole GH :bomb: about to go off? :boom: :smile:
