### ISSUE TITLE
Find and fix broken links in docs

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#2633]
Originally created to report search engine results containing an old URL for the Custom Formatters stub topic, the issue has been repurposed as a general find-and-fix issue for broken links in articles.

**Comment by tdykstra** [comment]
When we did the MVC TOC reorg we decided not to do redirects on article stubs.  This URL was changed recently, and the search engine result should have the new stub URL before long.

**Comment by GuardRex** [comment]
I see a handful of broken and malformed links using an online link checking tool. I'll get a PR in to address them shortly.

**Comment by GuardRex** [comment]
Here's what it found. I'll get back from the :muscle: gym :muscle: this afternoon (assuming I survive) and put a PR together to address what I can here, including converting the no-follow links into code.

http://minmat.blob.core.windows.net/temp/links.htm

**Comment by tdykstra** [comment]
Reopening the issue with a different title.  The errors @GuardRex is addressing are worth fixing but are different from the one that prompted the issue creation.

**Comment by GuardRex** [comment]
I went with an old skool standard: [Xanu Link Sleuth](http://home.snafu.de/tilman/xenulink.html).

It turned up the links from the deadlinkchecker-dot-com, but it also found other things to address. For example, the anchors are a bit askew. In the routing doc (`fundamentals/routing`), there are hard-coded anchors. Since DocFX is setting anchors (via `id`) for headings :sparkles: auto-magically :sparkles:, anywhere the handmade anchor matches the anchor generated by DocFX, we see an HTML violation. For example, here is some rendered markup from routing.md ...
```html
<p><a name="url-generation-reference"></a></p>
<h2 id="url-generation-reference">URL Generation Reference</h2>
```
... which may have only occurred 13 times in ASP.NET Core docs but seems to be a problem in 400+ API docs. I'll need to take a closer look at those API docs to see what's what.

It found a bunch of 404's beyond the 2,000 page limit of the online checker ... here's just one buried example: Go to [fundamentals/app-state](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state) and scroll down to *Additional Resources*. Click that resource for *Sample code used in this document*. :boom: :cry:

Let me digest this (extensive) Xanu report this afternoon, and I'll see what I can do.
