### ISSUE TITLE
A plea for demonstrating good standards and practices in docs

### ISSUE THREAD

**Issue by Grinderofl** [aspnet/Docs#2692]
There's an issue that has been bothering me since the beginning of Microsoft's creating of documentation for their products - examples that are either a) doing way too many things or b) are doing things way too simply.

While useful to "get up and running" quick, I think it's false for the official documentation to promote the use of the type of code that is okay for only as long as you have three properties in your domain entity and don't want to do anything other than CRUD on it. The trouble arises when more and more fresh .NET Core developers decide to take that for golden truth and start building complex applications in a similar style. While it may be overkill for simple scenarios, I bring about a plea for updating the documentation code to be more oriented towards proper coding practices such as:

* Not using ViewData (preferably at all, but it has some edge cases)
* Inheritance on view models for things like sort and filter
* Strongly typed sorting and ordering. This would have to use expression trees and reflection, which would not be such a bad idea to display - advanced usage of the language?
* Use of actual view models per entity instead of propagating the entire domain entity from database onto view. 

All of this does not necessarily need introduced at the same time - it's fine to show how it works under the hood with simple example - but please also show the way that doesn't promote code duplication later on in the documentation. There's plenty of space to add "Making sorting and ordering reusable" for instance. 

The reason for all this is so that folks new to .NET platform (an avalanche has been set off, have you noticed everything we're building with Core yet?) aren't set off in the wrong direction. What we don't want is a world full of developers who litter their code with string literals and switches when what they really want is a view model and a bit of reflection! Gang of Four, Fowler, and Evans have done well for developers of the previous generation to help them understand their mistakes - maybe we can use their work to now educate the next gen from ground up and help them NOT make mistakes we have already done? While it's useful to know how things work, it's probably better to come to terms with the fact that a major chunk of devs these days do not in fact do more than find the first way that works for them and stick with it. Can we blame them? No. There's so much information out there that "the right way" is not always obvious enough, especially if you don't even know you can do the advanced stuff. 

... so how about making the way they learn be the correct one from the get go, at least if they decided to use the official documentation? :)

**Comment by ardalis** [comment]
It's a always a balance in docs and tutorials between showing the concept that is the focus of the moment (a particular feature, for instance), and showing "enterprise best practices" (which aren't universally agreed upon in many cases). Personally I agree with you that things like separation of concerns dictate that we shouldn't be exposing domain entities in views or through Web APIs, for instance. But as you note above we often need to use simple examples in order to avoid distracting from the main concept being shown.

The issue you've raised here, while a valuable one for discussion IMO, is also not immediately actionable. We can't make an update to a doc and mark this as "done". What I would recommend is that you find a specific document you think could be improved and either open an issue with your suggestion or better yet, make a pull request showing how you would do it. In terms of overall guidance for the docs, you could do the same thing against the Contributing.md guidelines, which are used to guide how these docs are written.
