### ISSUE TITLE
Globalization and Localization and  Internationalization 

### ISSUE THREAD

**Issue by ntgraph** [aspnet/Docs#305]
Hi to all,
For each new .Net MVC version, there are plenty of tutorials.  But there seems to be lack on covering Globalization or i18n.  We, as new learner, needs some inspired tutorial on globalization with multiple language using resource file and a common switch (placed in header) and a routing rule such /localhost/en-us/controller/action by using a base controller....

Please add this topic to your vnext documentation .  Thanks,

**Comment by alexsandro-xpt** [comment]
Good question, I'm wishing mobilize https://github.com/OpenNetBr to translate it to portuguese Brazil and can't found guidlines for that.

**Comment by glen-84** [comment]
[ASP.NET Localization](https://github.com/aspnet/Localization) is still in development. The MVC parts have not yet been written/integrated, as far as I know.

I would personally write custom middleware (or an [IRequestCultureProvider](https://github.com/aspnet/Localization/blob/5e1fb16071affd15f15b9c732833f3ae2ac46e10/src/Microsoft.AspNet.Localization/IRequestCultureProvider.cs)) to extract the culture code from the URI path. You can also replace it with an empty string so that it doesn't affect your existing MVC routes.

**Comment by Rick-Anderson** [comment]
I hope to start this soon. 
http://docs.asp.net/en/latest/fundamentals/localization.html

I'll be working with Nadeem and starting with http://afana.me/post/aspnet-mvc-internationalization.aspx

I'll need help with Arabic

**Comment by Rick-Anderson** [comment]
copy from dup #653 

Fundamentals -> Localization

The following blogs have some initial content on the localization support in MVC 6:

http://blogs.msdn.com/b/webdev/archive/2015/10/15/announcing-availability-of-asp-net-5-beta8.aspx
http://www.vodovnik.com/2015/09/20/localization-in-asp-net-5-mvc-6/
Also, some initial content was started here: #554

From #522: - customer request:
calendar controls and date time formatting causing lot of issues which needed special care while coding. Please let me know if these have been specifically addressed as part of the latest framework or else is there a recommendation as to how best these can be done from the product team.

**Comment by danroth27** [comment]
@Rick-Anderson Should this article still be marked as blocked?

**Comment by Rick-Anderson** [comment]
@danroth27 removed marked.

**Comment by Rick-Anderson** [comment]
[draft for review](https://www.dropbox.com/s/e11jrxp1qlgyj56/locDoc.docx?dl=0)
I'll move this to GitHub tomorrow and hope to have it staged so you can see the doc build.
@hishamco @cspaniard @lurumad @joeaudette @Muchiachio @jerriep @Bartmax @damienbod please review

**Comment by Bartmax** [comment]
article read. good overall.

Have some concerns, what is the best approach for feedback/review? using
the github discussion feature?
let me know how/where/when I can provide feedback, email won't be a good
tool for that :D

Also it would be great to know who is the audience for this (feedback will
vary according to audience).

Should be a introduction lecture? For technical implementations? anything
else?
I think draft right now have mixed content for different audience and I
would like to help make it better, I'm not saying you can't target wider
audience, but if you do, I expect it to at least be organized accordingly.


Because I can understand that you might be anxious to read feedback, I will
give some minor ones already:

The title have 2 problems:

   1. ASP.NET 5 has been renamed to ASP.NET Core.
   2. Article title should not be *"Internationalization, Localization and
   Globalization"* but rather *"Internationalization:  Localization and
   Globalization"* as you already know because it's defined in the article,
   L10N and G11N are included in I18N.

Bonus track:

*"Creating a multilingual website is not difficult"*


I heavily disagree with that statement and I won't take any article that
make that statement as serious.

Multilingual is indeed *very difficult*. ASP.NET will help you make it
easier or easy, that I agree. which is a totally different thing. If it
were easy, there is no value in reading an article about it in the first
place.


In section *"The terms used so far:"* Locale should be after Culture, Neutral
culture and specific culture terms.


I'm eager to get into discussion about those and more reviews, just let me
know how is your preferred approach to give you feedback.

Thanks for asking me.
I really appreciate it and glad to help.


Greetings,
Bart.

**Comment by Muchiachio** [comment]
Thank you for including me in the review :+1:

> IHtmlLocalizer encodes arguments that are formatted in the resource string, but not the resource string.

An example near this statement or in the code result would be great, I had to read quite a few times to understand which part get encoded and which not. Also there seems to be better a wording for this later on in the document.
> IHtmlLocalizer<BookController> _localizer = localizer;
ViewData["Message"] = _localizer["&lt;b&gt;Hello&lt;/b&gt;&lt;i&gt; {0}&lt;/i&gt;", name];

Does using formatted string work for simple localizer? I think most of the formatting is done in validation messages, would be good to know.
> _localizer = factory.Create(typeof(SharedResource));
ViewData["Message"] = _localizer["Your application description page."];

I believe you are creating a localizer from `SharedResources.resx` right? Will we be able to use `"Your application description page."` as a key in .resx? Because I couldn't get it to work in VS.

Here are other pain points I ran into then globalizing ASP.NET applications through the years
- Client side localization, how do we ensure that numbers, dates and data is validated correctly by unobtrusive validations. Because in simple scenarios, people just localize their applications by not using resources at all (just inline text) and then run into problems on validating their data on the client side. Any examples or information links on how to do that would be great.
- Having different assemblies for resources. Is this scenario supported in ASP.NET Core?
- Implementing your own localizer, any examples on that, especially getting resources from the database. Overriding default `ResourceManager` implementation was quite hard.
- Localizing ASP.NET Core messages, how to override default "required", "value is not valid for type" and other error messages.
- Making localized redirects to not found and error pages, seems straight forward with cookies and headers, but redirecting from query string seems to be difficult.

If anything is not supported in ASP.NET Core, it would be best to put a comment in the docs mentioning that, so people would not go looking and asking as much. As for more examples, they could be added later by the community as long as the docs are available, because it's hard to contribute something to the docs, unless you know how it works internally :smile:

**Comment by hishamco** [comment]
The article read is good,but i think the title needs to change little bit, also ASP.NET should be renamed to ASP.NET Core, furthermore the sequence of the topics in the article may need sort of arrangement, because View Localization for instance may included underneath the Localization in ASP.NET.

> I think draft right now have mixed content for different audience

I think what @Bartmax is right, determine the audince should be taken in consideration if you to do so. 

Last but not least I wrote to articles in localization with titles "Localization in ASP.NET Core" & "Localization Extensibility in ASP.NET Core" but they are written in Arabic Language :smile: , but I can help you to make a rich content.
Finally I appreciate your efforts @Rick-Anderson and all you guys to improve such content

**Comment by damienbod** [comment]
Hi Rick

I think it's great. Thanks. I have nothing to add which has not already been mentioned in the previous comments. You can use my real name in the link, (Damien Bowden @damien_bod), thanks.

Greetings Damien

**Comment by jerriep** [comment]
I just had time to scan through it quickly, so not in much detail. Picked up one small spelling mistake:

"**Latter** in the article I’ll show how...."

**Comment by Rick-Anderson** [comment]
@Bartmax Thanks for the feedback. We can continue feedback on the PR https://github.com/aspnet/Docs/pull/1002

I'll get the title changed in my next commit. I was thinking my version was OK for SEO reasons but I think I'll follow your suggestion.

The audience is anyone who wants to localize a web app. That's a pretty large audience. 

@Muchiachio I added a suggestion on data annotations errors and explained the param encoding better.

I'll add "This article doesn't address client side localization".

**Comment by Rick-Anderson** [comment]
published doc
