### ISSUE TITLE
Write a migration guide for Authentication 1.0 to 2.0

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Docs#3054]
There are a lot of breaking changes between Microsoft.AspNetCore.Authentication.* 1.0 and 2.0 packages, APIs, etc..  Write up a migration guide.

Old APIs are marked as Obsolete, Error, with this link: https://go.microsoft.com/fwlink/?linkid=845470

@rick-anderson edit:

[@]HaoK  will be working on the migration doc specifically for the authentication stack from 1.0 to 2.0,  See https://github.com/aspnet/Security/issues/1310 for the draft

**Comment by Rick-Anderson** [comment]
From: Glenn Condron 
It might be worth a doc to describe this problem with the error message(s) you get. See if we can help get people from google to the solution faster.


From: Eduard Tomàs
Subject: [eShopOnContainers] RE: netcore2 blocking issues

A quick update on this. Basically, it is not possible to reference a netstandard 1.x library compiled against 1.x nugets from a project that uses 2.x nugets.
 
Currently as Identity Server do not support netcore2 we have some libraries compiled against netcore1.x. Some of these libraries are used from the others projects that have been upgraded to netcore2.
 
So we have one netcore2 project using EF 2.x that uses another library that was compiled against netcore 1 using EF 1.x. When nuget restore packages for the netcore2 our project receives (as expected) the EF 2.x packages. But when the library is called, we get a runtime error, because there were breaking changes in EF 2.x.
 
This blog post (https://blogs.msdn.microsoft.com/dotnet/2017/06/28/announcing-ef-core-2-0-preview-2/) is very clear: “EF Core 2.0 won’t be binary compatible with EF Core 1, which means that all code that depends on EF Core needs to at least be recompiled to work with 2.0.”
 
So we can’t upgrade to netcore 2 until IdSvr supports it.
