### ISSUE TITLE
'EntityEntry' does not contain a definition for 'GetDatabaseValues' and no extension method 'GetDatabaseValues' accepting a first argument of type 'EntityEntry' could be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by sonichanxiao** [aspnet/Docs#3167]
When I follow the steps for ASP.NET core tutorial, I couldn't get DepartmentsController.cs compiled because of this method var databaseEntry = exceptionEntry.**GetDatabaseValues()**;
is not defined anywhere the code. I copied the whole Edit method as described in the tutorial. Don't know where I did wrong.

Any clue?

**Comment by jnaputi253** [comment]
Is it specifically **GetDatabaseValues** function that gives an error?  The **exceptionEntry** variable doesn't throw an issue as well?  

I am just asking because I typed down the code inside the `catch` block and I am not getting any compile errors.

If you don't have it, you need to put this statement: `using Microsoft.EntityFramework;` at the top of your file.

**Comment by sonichanxiao** [comment]
I am following the tutorial on https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/concurrency and get stuck at section "Update the Edit methods in the Departments controller".

You can see inside the given code for HttpPost Edit method, there is a method call from exceptionEntry to GetDatabaseValues().
var databaseEntry = exceptionEntry.GetDatabaseValues();

If I compile the solution, I will get the error below:
Error	CS1061	'EntityEntry' does not contain a definition for 'GetDatabaseValues' and no extension method 'GetDatabaseValues' accepting a first argument of type 'EntityEntry' could be found (are you missing a using directive or an assembly reference?)

For the reference, it will not be recognized. I guess it is because this is a ASP.NET Core project, it is using Microsoft.EntityFrameworkCore instead of Microsoft.EntityFramework and I have the statement: using Microsoft.EntityFrameworkCore  on the top of the DepartmentsController.

I didn't type this method, I just copied from the tutorial page.

**Comment by jnaputi253** [comment]
For the `EntityEntry` type, there is a function for `GetDatabaseValues`.

[This](https://docs.microsoft.com/en-us/ef/core/api/microsoft.entityframeworkcore.changetracking.entityentry#Microsoft_EntityFrameworkCore_ChangeTracking_EntityEntry) is the API reference regarding that type.  

Having the statement `using Microsoft.EntityFrameworkCore;` should have made it work.  But, you would need to have installed the NuGet package **Microsoft.EntityFrameworkCore** to use that reference.

**Comment by sonichanxiao** [comment]
A staff from Microsoft replied saying this method is new in EntityFrameworkCore 1.1, I guess when I started the tutorial the EntityFrameworkCore version was still 1.0, after I updated the packages, problem solved.

**Comment by jnaputi253** [comment]
Nice!  My bad for neglecting the update to 1.1.


Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: Xiao <notifications@github.com> Date: 4/5/17  7:31 PM  (GMT-08:00) To: aspnet/Docs <Docs@noreply.github.com> Cc: Juan Naputi <jnaputi253@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [aspnet/Docs] 'EntityEntry' does not contain a definition for
  'GetDatabaseValues' and no extension method 'GetDatabaseValues' accepting a
  first argument of type 'EntityEntry' could be found (are you missing a using
  directive or an assembly reference?) (#3167) 
A staff from Microsoft replied saying this method is new in EntityFrameworkCore 1.1, I guess when I started the tutorial the EntityFrameworkCore version was still 1.0, after I updated the packages, problem solved.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/aspnet/Docs","title":"aspnet/Docs","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/aspnet/Docs"}},"updates":{"snippets":[{"icon":"PERSON","message":"@sonichanxiao in #3167: A staff from Microsoft replied saying this method is new in EntityFrameworkCore 1.1, I guess when I started the tutorial the EntityFrameworkCore version was still 1.0, after I updated the packages, problem solved."}],"action":{"name":"View Issue","url":"https://github.com/aspnet/Docs/issues/3167#issuecomment-292052023"}}}
