### ISSUE TITLE
Default Manager/User claims and implementation steps

### ISSUE THREAD

**Issue by rhires** [aspnet/Docs#3194]
## Requests for new Topics
The sentence: "When an identity is created it may be assigned one or more claims issued by a trusted party. " needs a whole document to go with it. We need to know the process of assigning claims to a first admin user, then non-admin users. We need to know how to alter the Startup.cs file to handle default claims to start with. There needs to be a default user and a management interface. And an example of how to create and manage roles/claims (or whatever the preferred) via a rendered form.

2. Write an outline of the proposed topic contents.
A. Setup for a manager user for when the project is initialize with default Manager claims.
B. Setup for a default user who is able to sign in via the usual "register" functionality with default User claims. 
C. Example code of how to put together a management interface to grant or revoke claims per user. And example code for creating new claims and assigning them.

3. Where would you put the topic in the Table of Contents?
 A. It would go under the "Authorization" section. Not sure after that.

**Comment by blowdart** [comment]
I assume this refers to identity? We won't document a management interface, because frankly that's so application dependent it can't be generic.

**Comment by rhires** [comment]
Yes. Looking at this again, I see that I didn't reference the topic: "Claims-Based Authorization". I'm new to all of the claims thing, so I was looking for an authoritative "this is how you should do it" example, which lots of the docs here have. I mean a most minimal example as a starting point. 

I guess that from lots of looking around there aren't many examples of how to a lot of this, or what the usual patterns might be. I found [this example](https://code.msdn.microsoft.com/ASPNET-Core-MVC-Authenticat-39b4b103#content) but finding it didn't come easy. Having this little bit of code has given me a much better understanding. 

So anyway. Thank you for all the work done to make this so great!

**Comment by ferrx** [comment]
@blowdart I understand that this is something that can be done a hundred ways, but having a guide on using IClaimsTransformer may be what's needed. Low level example usage would go a long way for helping devs understand the high level concepts. 

And I'm not sure, but it seems like a guide could cover Identity/EF usage with Claims, but since (from what I understand..) Identity is so tightly coupled with Individual User Accounts / FBA, it may also be worthwhile to have another guide that ignores the authentication provider and at a high level discusses using IClaimsTransformer (or just custom middleware) to `get user data within the ?authentication? pipeline` and `adds claims to the incoming principal` so that you can `create policies based on claims` and `use HasClaims in a view's controller code` etc..

@rhires In that example, they are using Identity w/ Entity Framework to store data about users. Zero comments in the code so hard to discern exactly what's going on, but it looks like Identity has IdentityUserClaim (see UserController.cs line 130 and other areas of that file) which can store claims for a given user, which are stored in the db and retrieved by Identity and applied to the user when they connect to the application.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
