### ISSUE TITLE
2.0 Getting started - basic Razor Page

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#3552]
About 7 min into video.

@danroth27  do we put this before/after/inside of https://docs.microsoft.com/en-us/aspnet/core/getting-started ?

**Comment by danroth27** [comment]
@shanselman @rowanmiller 

Having a short intro video for ASP.NET Core could be really nice. This could be something we put on the asp.net & dot.net sites for folks that like a video intro, but we would want the video quality to be high for that.

**Comment by danroth27** [comment]
We have something like this already for .NET Core (console apps): https://www.microsoft.com/net/core#windowsvs2017

**Comment by rowanmiller** [comment]
Agreed. As part of the redesign of dot.net I am thinking about getting started content for all different types of apps (having it - not that we'd be authoring it as part of the redesign). Also thinking about where this content belongs, because getting started probably belongs on Docs rather than the marketing site - but we have the current get started stuff there because we can be "fancier" with html 😄.

**Comment by Rick-Anderson** [comment]
fixed by #3722
