### ISSUE TITLE
"Publishing and Deployment" section needs more details on non-VS methods

### ISSUE THREAD

**Issue by Daniel15** [aspnet/Docs#364]
The pages at http://docs.asp.net/en/latest/publishing/index.html and http://docs.asp.net/en/latest/publishing/iis.html are a good start, but this section needs more information on how to publish a site without using Visual Studio, for example, from a build script, build machine, or a giant "deploy the site now" button. I don't think deploying directly from Visual Studio is a very common use case for production sites.

Currently, with .NET Framework 4 and ASP.NET MVC 5, I use the MSBuild `PipelinePreDeployCopyAllFilesToOneFolder` build target (which I believe is roughly equivalent to what VS does) to package the site, and then `rsync` it to my remote server, which is a Linux machine running Mono. What is the equivalent for ASP.NET 5 + MVC 6?

**Comment by GuardRex** [comment]
Web Deploy (MSBuild) works if you keep a few 'gotchas' in mind, and it can run entirely outside of VS via a plain 'ole Powershell script or batch file. My use case was for a staging VM in Azure, but it would work anywhere for IIS ... Azure or on-prem. Here are some references:

https://github.com/aspnet/Home/issues/452#issuecomment-93011639
https://github.com/aspnet/Docs/issues/105

**Comment by Daniel15** [comment]
I figured out that `dnu publish` does most of what I need - I can just publish into a temp directory, then rsync that to my remote server.

**Comment by danroth27** [comment]
Yup, we should cover a full workflow for publishing to Linux/Docker.

**Comment by BerndtH** [comment]
Please cover even a full workflow for publishing to Windows IIS with user-secrets.
The answers of the following questions should be dokumented.

Are the user-secrets only for development?
What happens when you deploy an application with external login providers like Facebook, Google or Twitter to a hosting provider running IIS 7.5?
The application still needs user-secrets in the production environment.
Without them the application will not run, and you will get get the famous ERROR 500.
Who stores the application secrets in the production server?
Who runs the user-secret app on the production server?
Please dokument  these issues in the followind dokuments
docs "DNX Secret Configuration." and 
aspnet/Docs "Enabling authentication using external providers"
aspnet/Docs "Safe Storage of Application Secrets" and
http://docs.asp.net/en/latest/publishing/iis.html

**Comment by danroth27** [comment]
We can't cover ever publishing technology available, but I think we should provide a Publishing Overview doc that goes over the basic mechanics of publishing an ASP.NET Core app regardless of the specific tech involved.

**Comment by danroth27** [comment]
We handle this as part of https://github.com/aspnet/Docs/issues/989.
