### ISSUE TITLE
Improve "Migrating Configuration" with description of all common cases

### ISSUE THREAD

**Issue by evil-shrike** [aspnet/Docs#37]
Configuration is a big topic. In a common web app on old ASP.NET we'd have roughly the following stuff in web.config:
- appSettings with simple key-value settings of the app and libs
- standard sections from .NET like `system.diagnostics`
- settings for asp.net - `system.web`
- settings for web server - `system.webServer`
- custom sections - sections of 3rd party registered in `configSections` element (please pay attention that these libs can be not related with asp.net at all, just some libs)

[The article](http://aspnet.readthedocs.org/en/latest/migrating/migratingconfig/migratingconfig.html) only talks about the first one - appSettings. Yeah, they are easily converted to anything as it's just key-value pair.
But what to do with the others?

The most unclear thing for me is custom sections. Just imagine you used some library. And that library supports configuration - it uses ConfigurationManager which just uses "system configuration file". And now it's empty. We could say something like "do not expect the lib to configure itself from configuration file, configure it on your own via its api". It makes sense indeed. But it breaks my app. It breaks any app. Moreover the lib could not support the same abilities via Api as via config.

I'm not sure that here is a good place to discus the design "deprecating System.Configuration". But anyway consequences of that design should be clearly stated in the docs.
Thanks.

**Comment by andresmoschini** [comment]
+1

**Comment by jods4** [comment]
Here's a use-case close to MS. Right now I try to use ASP.NET 5 on top of .net 4.5.2 but with EF6, since EF7 is looking to not be production-ready for a long while. Try to use and Oracle provider.

Now you're in a very bad place. EF6 insists on using DbProviderFactories and the classes that could reconfigure that are internal. DbProviderFactories cannot really be registered any other way than with a section from `ConfigurationManager`. Ouch.

This is an example, coming right from MS, that some libraries really need to fall back to `ConfigurationManager` in clr runtime.

**Comment by davidfowl** [comment]
There's really 2 questions here with deepest to migration, The .NET Framework story and the .NET Core story. For .NET Framework, we'll try to be as compatible as possible so the libraries "just work". For .NET core libraries can't depend on configuration manager because there is none. They'll need to resort to their own configuration file,  or better, take IConfiguration in their APIs.

**Comment by jods4** [comment]
@davidfowl Totally agree. For Core libs need to be adapted and since `ConfigurationManager` is not there they have to fallback to `IConfiguration` or whatever.

But for the full Framework the story is not great today. I had to rely on a dirty hack using private reflection to reset the internal `ConfigurationManager` state and load `web.config` (as I said, the goal was to configure an Oracle `DbProvider`). If there is a better way let us know!

**Comment by davidfowl** [comment]
I just filed this bug https://github.com/aspnet/dnx/issues/2194

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
