### ISSUE TITLE
Tutorial is invalid because ProcessInfo is internal

### ISSUE THREAD

**Issue by shanselman** [aspnet/Docs#379]
It seems like this tutorial is not valid? http://docs.asp.net/en/latest/tutorials/your-first-aspnet-application.html#adding-client-side-behavior

ProcessInfo appears to be internal. Can this be fixed?

**Comment by shanselman** [comment]
Ok, I get it now. Steve used his own class that he called ProcessInfo that conflicts with the internal one. It's not intuitive.

**Comment by Daniel15** [comment]
Also, building HTML through string concatenation is really not a good idea:
```
items.push('<li class="list-group-item">' + option.Name + '</li>');
```

The very first tutorial a user sees probably shouldn't encourage bad practices, such as shadowing built-in class names or building HTML through string concat :)

**Comment by ardalis** [comment]
I could see renaming ProcessInfo to ProcessInfoViewModel perhaps, since it does conflict with an existing framework type, @shanselman. 

As for the HTML, @Daniel15 would you prefer to see DOM manipulation or a dependency on a particular framework or what? Building the HTML wasn't the primary goal of the demo, so the string approach seemed the simplest without adding more moving parts or complexity than necessary. I'm open to suggestions, though.

**Comment by Daniel15** [comment]
Vanilla DOM is probably best, something like:
```js
function bindData(element, data)
{
	data.forEach(function (option) {
		var optionEl = document.createElement('li');
		optionEl.className = 'list-group-item';
		optionEl.textContent = option.Name;
		element.appendChild(optionEl);
	});
}
```
I didn't test this, but something similar to this should work fine.

(also your C# is indented with spaces but the JavaScript is indented with tabs)
