### ISSUE TITLE
tutorials/first-mvc-app-mac/adding-model update csproj

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#4116]
[csproj](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app-mac/adding-model#prepare-the-project-for-scaffolding)

**Comment by appsaleslover** [comment]
The following no longer works in the Configure method, in .NET Core 2. Causes 'cannot resolve scoped service'.

DBinitialize.EnsureCreated(app.ApplicationServices);

Alternative ways: Add MvcMovieContext context to the configure method's parameters and call context.Database.EnsureCreated directly or add IServiceProvider to the parameters and use getRequiredService. But it appears Main is the preferred place to do this (but requires a lot more code instead of the single liner)

For example, from the EF Core tutorial:
public static void Main(string[] args)
{
    var host = BuildWebHost(args);

    using (var scope = host.Services.CreateScope())
    {
        var services = scope.ServiceProvider;
        try
        {
            var context = services.GetRequiredService<SchoolContext>();
            DbInitializer.Initialize(context);
        }
        catch (Exception ex)
        {
            var logger = services.GetRequiredService<ILogger<Program>>();
            logger.LogError(ex, "An error occurred while seeding the database.");
        }
    }

    host.Run();
}

**Comment by Rick-Anderson** [comment]
fixed
