### ISSUE TITLE
Any plan for translation?

### ISSUE THREAD

**Issue by jakeymvc** [aspnet/Docs#416]
Hello from South Korea.

There are increasing demands in Korea for this documentation. Do you have any plan to translate in near future? We have a voluntary team including Microsoft Korea staff to contribute in translation.

It would be great if we can take part in some translation work.

**Comment by danroth27** [comment]
We do want to make translations available and we plan to leverage the Read the Docs infrastructure for doing this. We haven't started yet because the product (and hence the docs) are still churning pretty rapidly. I think it would make sense to start setting up translations later this year as we get closer to our first Release Candidate.

**Comment by JakeRyu** [comment]
I am really glad to hear that. Looking forward to making contribution.

**Comment by Rick-Anderson** [comment]
adding  @erlimar  - This will be the translate page.

**Comment by agriffard** [comment]
I would be interested in translating the docs in fr-FR. 
I already did this for another open source project, the Orchard CMS docs. 
I had cloned the repo, translated the docs and hosted it on my domain.
But I guess ReadTheDocs as a solution to provide the docs for many cultures.

As you said, RC1 will a good milestone to start the translations.
In the mean time, if you are able to structure the docs so that ReadTheDocs can have at least an homepage translated in another culture, I'd be happy to help.

**Comment by rhires** [comment]
Hmm...while treading carefully, this is an Open Source project and you can do as believe it appropriate - I like consulting with the heads of the project, since being on the same page and playing "team" are good things, but I say go ahead and get started, and you can host on GH your translations, and when ready, and after discussing it, send a pull request. And what @danroth27 says - things are still in transition. I would maybe work on the stuff isn't so likely to change quickly...

**Comment by agriffard** [comment]
After a short investigation, a procedure seems to exist :
http://read-the-docs.readthedocs.org/en/latest/localization.html

They give the example of phpmyadmin which has a https://github.com/phpmyadmin/localized_docs repository linked to another online localization tool : https://hosted.weblate.org/projects/phpmyadmin/documentation .

**Comment by agriffard** [comment]
But I think I will try the first solution: Clone the repo and translate the .rst files

**Comment by danroth27** [comment]
We plan to use the Read the Docs support for localization. We just need to setup the Sphinx projects for the different languages we plan to support, and we plan to do that within the ASP.NET GitHub org. We haven't done it yet because there is still a lot that is changing in the product and we want to focus on getting the right content written first without having to worry about managing multiple translations. I think it makes sense to start ramping up translation efforts after the Nov release candidate release.

**Comment by erlimar** [comment]
OK. Waiting RC1.

**Comment by rehaddad** [comment]
we would like to translate to portuguese pt-Br. when the docs are available, please let me know.
Thanks!

**Comment by danroth27** [comment]
@rehaddad Will do! 

At this point we still have a lot of content in flight, so it looks like we will probably delay localization efforts even further until early 2016. We will keep this this issue updated as our plans solidify.

**Comment by jakeymvc** [comment]
RC2 is now released.

@danroth27 Is there an update on this?

**Comment by danroth27** [comment]
We need to move to docfx first.

**Comment by scottaddie** [comment]
We have Korean localization now: https://docs.microsoft.com/ko-kr/aspnet/core/. The associated repo is here: https://github.com/aspnet/Docs.ko-kr.
