### ISSUE TITLE
Update old windowsazure.com links to azure.microsoft.com (or docs.microsoft.com)

### ISSUE THREAD

**Issue by terrimorton** [aspnet/Docs#4178]
Searching across the .md files, there are 129 hits in 52 files for windowsazure.com.

For example: \Docs\aspnet\aspnet\overview\developing-apps-with-windows-azure\building-real-world-cloud-apps-with-windows-azure\automate-everything.md
- https://www.windowsazure.com/en-us/develop/net/tutorials/web-site-with-sql-database/
- https://www.windowsazure.com/en-us/manage/install-and-configure-windows-powershell/
- https://www.windowsazure.com/en-us/documentation/scripts/
- https://www.windowsazure.com/en-us/manage/install-and-configure-cli/
- https://www.windowsazure.com/en-us/downloads/#cmd-line-tools

All of these links redirect, some to docs.microsoft.com, some to azure.microsoft.com. The articles should be reviewed and 1) updated to current Azure practices/screenshots 2) links updated to current location

**Comment by guardrex** [comment]
@terrimorton Thanks for reporting this.

I corrected the 301/302 links with one of my **RexHacks**:tm: scripts. :smile: There are other 301/302 problems, so I'll prob circle around later with other passes to fix other batches of links. Later, we'll figure out if we should fix up the titles (link text) as well, since they've changed in many cases.

For the problems with individual topics, such as incorrect content/screenshots, they're normally worked on a topic-by-topic basis with one issue per topic (but sometimes with a tracking issue that lists a known number of topics that require attention).

@scottaddie and/or [@]Rick-Anderson will let you know how the other issues with the topics you mentioned should be addressed.
