### ISSUE TITLE
Add some documentation about configurations and hooks in Razor Pages

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Docs#4281]
The current set of Razor Pages articles talk about using Razor Pages which is great. But we have several features that would be useful to document:

* Applying authorization filters via conventions - `AllowAnonymousToPage`, `AllowAnonymousToFolder`, `AuthorizePage`, `AuthorizeFolder`
* `AddPageRoute` to do custom routes to pages
* Using `IPageApplicationModelProvider`, `IPageRouteModelProvider`. Similar components for controllers are documented here - https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/application-model.

**Comment by guardrex** [comment]
#### Samples
* `AllowAnonymousToPage`, `AllowAnonymousToFolder`, `AuthorizePage`, `AuthorizeFolder`
`AddPageRoute`
 https://github.com/aspnet/Mvc/blob/bac68ba3c225b116d5be5ac1a1383d6bad053bf6/test/WebSites/RazorPagesWebSite/Startup.cs
* `IPageApplicationModelProvider`
   https://github.com/aspnet/Entropy/tree/dev/samples/Mvc.CustomRazorPageHandlers
* `IPageRouteModelProvider`
   **?** @pranavkm Are only ref source and tests available?

**Comment by pranavkm** [comment]
I don't think we have one. @sebastienros was asking about this for Orchard. Perhaps he's got one.

**Comment by Rick-Anderson** [comment]
@pranavkm  any chance you could write a sample app showing these and stub out a document?

**Comment by Rick-Anderson** [comment]
> * Using `IPageApplicationModelProvider`, `IPageRouteModelProvider`. Similar components for controllers are documented here - https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/application-model.

see IApplicationModelProvider in [Working with the Application Model](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/application-model), but thers is no `IPageRouteModelProvider` Similar components.

When this is started, set up a meeting with @ pranavkm  to get an outline, etc.

**Comment by guardrex** [comment]
@Rick-Anderson For planning purposes (I'll be digging into this mid to late next week):

Proposal: How about two samples and four topics in the *aspnetcore/mvc/razor-pages/* area?

| Titles | Subjects | Sample |
| --- | --- | :---: |
|*Razor Page conventions for authorization filters in ASP.NET Core* | `AllowAnonymousToPage`, `AllowAnonymousToFolder`, `AuthorizePage`, `AuthorizeFolder` | 1 |
| *Razor Page custom routes in ASP.NET Core* |  `AddPageRoute` | 1 |
| *Customizing the Razor Pages page model provider in ASP.NET Core* | `IPageApplicationModelProvider` | 2 |
| *Customizing the Razor Pages route model provider in ASP.NET Core* | `IPageRouteModelProvider` | 2 |

> When this is started, set up a meeting with @ pranavkm to get an outline, etc.

The first two seem clear/easy. On the last two ... yes, plz ... to insure I don't miss something important from only looking at ref source and [existing samples](https://github.com/aspnet/Docs/issues/4281#issuecomment-329549540), outlines (or even just lists of section subjects) will be helpful.

RE: `IPageRouteModelProvider` sample

* There's a bit to go on: 
  * https://github.com/aspnet/Mvc/blob/8df30325407be3d3c30c850e6f63b1d2969b1dea/test/Microsoft.AspNetCore.Mvc.RazorPages.Test/Infrastructure/PageActionDescriptorProviderTest.cs#L220-L242
  * https://github.com/aspnet/Mvc/blob/8df30325407be3d3c30c850e6f63b1d2969b1dea/src/Microsoft.AspNetCore.Mvc.RazorPages/ApplicationModels/IPageRouteModelProvider.cs

... but sure ... a little dev team sample would be sweet. If there were a delay on a `IPageRouteModelProvider` sample, I can hit the first three topics and get them done and come back to the fourth later (if u want this handled in four topics).

**Comment by guardrex** [comment]
@Rick-Anderson Referring to what I reorganized from the call, the first two will be combined and the last two will be combined ...

| Titles | Subjects | Sample |
| --- | --- | :---: |
|*Razor Page conventions for authorization filters in ASP.NET Core* | `AllowAnonymousToPage`, `AllowAnonymousToFolder`, `AuthorizePage`, `AuthorizeFolder` | 1 |
| *Customizing the Razor Pages page model provider in ASP.NET Core* | `IPageApplicationModelProvider` | 1 |
| *Razor Page custom routes in ASP.NET Core* |  `AddPageRoute` | 2 |
| *Customizing the Razor Pages route model provider in ASP.NET Core* | `IPageRouteModelProvider` | 2 |

On the first two, how about ...

*Razor Page authorization and model provider in ASP.NET Core*

... 59 characters right on the money.

The last two, perhaps ...

*Razor Page custom routes and model provider in ASP.NET Core*

... again, 59 characters.

**Comment by guardrex** [comment]
Cool ... here we go then ...

| Titles | Subjects |
| --- | --- |
|*Razor Page authorization and model provider in ASP.NET Core* | `AllowAnonymousToPage`<br>`AllowAnonymousToFolder`<br>`AuthorizePage`<br>`AuthorizeFolder`<br>`IPageApplicationModelProvider` |
| *Razor Page custom routes and model provider in ASP.NET Core* |  `AddPageRoute`<br>`IPageRouteModelProvider` |

Each with its own sample. I don't want to *overload* a single sample with everything here. That would be quite a bit. We don't want to trigger *The Music Store Effect* ... that's a real thing! lol

I'll start the first one now. With a little luck, we should have something nice to look at Monday or Tuesday of next week. :rocket:

**Comment by guardrex** [comment]
@pranavkm I pinged u on Slack (a DM) with a quick question. https://aspnetcore.slack.com

**Comment by guardrex** [comment]
@pranavkm Here's the current outline. I have a final (important) question on how much theory this topic should have at the bottom of this comment.

Title: *Razor Pages custom route and page model providers in ASP.NET Core*

* Introduction
  * A few lines that explain the subject of the topic.
  * **TBD** *Theory of models and providers*
  * Link to the sample app. List the features that the sample app demos. Link this mini-TOC to the section headers in the topic where these features are described. Should make it a little easier to move around. This topic is 🍖 *meaty* 🍖.
* Add route and application model conventions
  * Add a global route attribute to all pages
    * Use `Conventions` to create and add an `IPageRouteModelConvention` to the collection of `IPageConvention` instances that are applied during route and page model construction.
    * Sample demo: Add `{globalAttribute?}` to the attribute route model of all pages.
  * Add a global header to all pages
    * Use `Conventions` to create and add an `IPageApplicationModelConvention` to the collection of `IPageConvention` instances that are applied during route and page model construction.
    * Sample demo: Add a `GlobalHeader` header to the responses for any page request in the app.
* Page route model provider
  * **TBD** *Additional theory on route model providers* and definitions
  * List the built-in internal providers (note that conventions should be used)
  * Page route action conventions
    * `AddFolderRouteModelConvention`
      * Use `AddFolderRouteModelConvention` to create and add an `IPageRouteModelConvention` that invokes an action on the `PageRouteModel` for all pages under the specified folder.
      * Sample demo: Add `{otherPagesAttribute?}` to the attribute route model of all pages in the sample's *OtherPages* folder.
    * `AddPageRouteModelConvention`
      * Use `AddPageRouteModelConvention` to create and add an `IPageRouteModelConvention` that invokes an action on the `PageRouteModel` for the page with the speciifed name.
      * Sample demo: Add `{aboutAttribute?}` to the attribute route model of the About page.
* Page application model provider
  * **TBD** *Additional theory on app model providers* and definitions
  * List the built-in internal providers (note that conventions should be used)
  * Page model action conventions
    * Show an `AddHeaderAttribute` class that the sample uses to add a header to responses. This class is used in the sample demos that follow.
    * `AddFolderApplicationModelConvention`
      * Use `AddFolderApplicationModelConvention` to create and add an `IPageApplicationModelConvention` that invokes an action on `PageApplicationModel` instances for all pages under the specified folder.
      * Sample demo: Add an `OtherPagesHeader` header to the responses for any page request from the *OtherPages* folder of the app.
    * `AddPageApplicationModelConvention`
      * Use `AddPageApplicationModelConvention` to create and add an `IPageApplicationModelConvention` that invokes an action on the `PageApplicationModel` for the page with the speciifed name.
      * Sample demo: Add an `AboutHeader` header to the response for the About page.
    * `ConfigureFilter`
      * `ConfigureFilter` configures the specified factory to apply filters to all Razor Pages. You can supply a `Func<PageApplicationModel, IFilterMetadata>` factory to an overload of the method.
      * Sample demo: Add a pair of `FilterFactoryHeader` headers with a `AddHeaderWithFactoryAttribute` factory class to all responses from the app.
  * Change the `DefaultPageApplicationModelProvider`
    * Describe the ordinary OOB experience (the conventions for handler naming and request processing). Although this is generally described in the Razor Pages topic (at the bottom of [this section](https://docs.microsoft.com/aspnet/core/mvc/razor-pages/?tabs=visual-studio#writing-a-basic-form)), the implementation to change it here requires more detail on how the OOB named and unnamed handler names work (also, I don't want to require the reader to go look at something else right in the middle of reading this topic).
    * Suggest an alternative scheme where "On" is dropped; the first word segment is used to determine the HTTP verb; and DELETE, PUT, and PATCH verbs are converted into POSTs. (:point_left: a version of your, @pranavkm, [Entropy sample](https://github.com/aspnet/Entropy/tree/dev/samples/Mvc.CustomRazorPageHandlers))
    * Sample demo: Override the `CreateHandlerModel` method to show the implmentation of the new scheme.
    * Describe (but don't demo) additional control opportunities in `CreateHandlerModel`
      * Replace `IsHandler` to change handler method determination
      * Interact with model parameters as they're added to the handler model's parameter collection.
      * Override `CreateModel` to supply custom logic for creating a `PageApplicationModel` for the given `PageActionDescriptor` and `pageTypeInfo`.

I'm working on the more theoretical bits (where I marked "TBD") ... along the lines of what Steve did in the app model topic for MVC, where he speaks to *Models and Providers* and *IApplicationModelProvider*.

This is a good time to discuss how much theory on models and providers should appear: A web dev prob doesn't care too much about the theory. They probably want to know what the feature is, what can they use it for, and how do they implement it.

I'm fearful that if I put much theory (even the low-level, overview amount of theory that Steve put into the app model topic) that the **VERY useful** content in this topic (the convention implementations) won't surface well because potential readers will think the topic is **just theory** or **only for edge cases**.

One possibility here is that I submit the first draft with virtually *no theory* and keep it focused on features and implementation (just like I did for [Razor Pages auth and custom routing topic (links to internal review topic; aspnet/docs 4584)](https://review.docs.microsoft.com/en-us/aspnet/core/mvc/razor-pages/razor-pages-authorization-and-custom-routing?branch=pr-en-us-4584). If so, I'd like to go with a different title that ... well ... frankly ... makes the conventions *sound* as useful *as they actually are*. :+1:
