### ISSUE TITLE
Update "Integrating Azure AD into an ASP.NET Core web app" to ASP.NET 2.0

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#4449]
Currently in review [here](https://github.com/Azure-Samples/active-directory-dotnet-webapp-webapi-openidconnect-aspnetcore/pull/24)

- [Integrating Azure AD into an ASP.NET Core web app](https://azure.microsoft.com/en-us/resources/samples/active-directory-dotnet-webapp-openidconnect-aspnetcore/)
- [Calling a ASP.NET Core Web API from a WPF application using Azure AD](https://azure.microsoft.com/en-us/resources/samples/active-directory-dotnet-native-aspnetcore/)
- [Calling a web API in an ASP.NET Core web application using Azure AD](https://azure.microsoft.com/en-us/resources/samples/active-directory-dotnet-webapp-webapi-openidconnect-aspnetcore/)

@jmprieur can you give me an ETA on when you can get these updated?  Once you get it updated I can do an edit pass on the doc. We point to this doc at https://docs.microsoft.com/en-us/aspnet/core/security/authentication/azure-active-directory/

**Comment by jmprieur** [comment]
@Rick-Anderson : I've updated the sample in GitHub for the first one (See https://github.com/Azure-Samples/active-directory-dotnet-webapp-openidconnect-aspnetcore)
Working on the others.

**Comment by guardrex** [comment]
I have a concern that since it doesn't match the samples over here for the (hypothetical) 2.0 xplat best practices setup that devs (newbies anyway) will find it confusing:
* Configured as a VS solution
* Unnecessary defaults are specified in the project file (and `PackageTargetFallback` shouldn't be necessary ... in theory! lol)
* `wwwroot` handling in an `ItemGroup`
* Not using the `All` package
* Not using the `CreateDefaultBuilder` startup pattern (with `Startup` adjustments for 2.0) + `IConfigurationRoot`
* Gulp? (no `BundlerMinifier.Core`)
* *config.json*? (with *appsettings.json* in use)
* *web.config*-based ... and do transforms work yet? As of late last year, it wasn't possible. The GH tracking for tooling is gone now, so I can't see the progress on that: https://github.com/aspnet/Tooling/issues/252
* Environment TH isn't using the new `includes`/`excludes` attributes
* ... and a few other little things that don't match the latest templates

It might be a good idea to see how it would compose based a current `dotnet new mvc` auth template, but even the possibility of that option is based on where/how the sample is mentioned in Azure topics.

Anywho ... I have some time today, so let me know if u would like me to make a pass on it.

**Comment by jmprieur** [comment]
@guardrex : please go ahead.

**Comment by guardrex** [comment]
@jmprieur Sure thing ... I'll have it for ya this evening.

I'll go with a `dotnet new mvc` auth template first and see if it all composes well. I'll do a search for this sample to see if any topics need a touch of work to go along with the updates.

**Comment by Rick-Anderson** [comment]
@guardrex  Should I assign this to someone?

**Comment by guardrex** [comment]
@Rick-Anderson Looking at your list :point_up: one at a time ...

### Integrating Azure AD into an ASP.NET Core web app

I made the final three touch-ups to that sample at [Update Azure AD/OIDC sample (29)](https://github.com/Azure-Samples/active-directory-dotnet-webapp-openidconnect-aspnetcore/pull/29):
1. It had a tiny conflict in its README.md.
2. I updated the version of `UseMvc` that has the `routes.MapRoute` in it to match the template.
3. I added back the Bower and BundlerMinifer.Core files (although they don't work outside of VS as usual).

The topic at [Integrating Azure AD into an ASP.NET Core web app](https://azure.microsoft.com/en-us/resources/samples/active-directory-dotnet-webapp-openidconnect-aspnetcore/) needs (I think) one touch-up: I moved the AD settings to the *appsettings.json* file so that they would get picked up automatically by the `CreateDefaultBuilder`. Where the topic talks about opening the *config.json* file, it should say to make those settings changes in the *appsettings.json* file. The rest of it is probably ok, but I'd have to take a closer look to know for sure.

### Calling a ASP.NET Core Web API from a WPF application using Azure AD

In the sample, the `TodoListClient` app is netfx 4.5 and the `TodoListService` app is a 1.0 *project.json*-based Core app. Also, the topic mentions using VS2015.

### Calling a web API in an ASP.NET Core web application using Azure AD

The whole sample (two apps) is 1.0 *project-json*-based. The text of the topic is also calling for VS2015.

**Comment by Rick-Anderson** [comment]
@jmprieur what's the state of this?

**Comment by Rick-Anderson** [comment]
@jmprieur what's the state of this?

**Comment by Rick-Anderson** [comment]
@CamSoper I think you can close this once you finish your review.
