### ISSUE TITLE
No .IsVowel for chars??

### ISSUE THREAD

**Issue by Rasmustof** [aspnet/Docs#4509]
Hey Guys,

i was just working on a simple program, but wished that there was a method for checking if any given character is a  vowel or not?

Usage would be like: 
Char c  = 'C'
if(isVowel(c)) 

etc..

this could be done like this if im not wrong:

Public bool isVowel(Char c){
  string v = "aeiouyAEIOUY";
  if(v.IndexOf(c) != -1){
      return true;
  }else return false;
}

**Comment by Rasmustof** [comment]
would make sense to be part of the Char libary ...

**Comment by Rasmustof** [comment]
seems like there should be some extra logic to take care of that Y can be both a vowel and a consonant. but that seems like its quite difficult only taking in a char

**Comment by scottaddie** [comment]
@BillWagner Thoughts? This issue doesn't belong here, but where should we move it?

**Comment by BillWagner** [comment]
I would probably ask here: https://github.com/dotnet/standard/issues  But, @terrajobst may have a better repo for the request.

**Comment by terrajobst** [comment]
@Rasmustof, seems like this is a request for the `System.Char` type. Feel free to file it under https://github.com/dotnet/corefx. However, I don't think this is a super likely API for us to add because (1) the workaround for latin languages is fairly trivial (2) doing it in the platform with proper unicode support might be non-cheap (3) seems like a fairly narrow scenario. That being said, I can be convinced :-0

**Comment by scottaddie** [comment]
Moved to https://github.com/dotnet/corefx/issues/24593
