### ISSUE TITLE
Allow Preview of Docs Changes to Outside World

### ISSUE THREAD

**Issue by spottedmahn** [aspnet/Docs#4670]
## General

I just got a build report, great.  There's a preview url, great.  When I try to view it though, I get

>We are sorry, the page is forbidden

![image](https://user-images.githubusercontent.com/14079228/32185141-c5505f10-bd74-11e7-9b64-2c4a7059f2b2.png)

----

I assume it is only accessible to MSFT employees?  Can it be opened to all contributors?

**Comment by EisenbergEffect** [comment]
@spottedmahn Thanks for bringing this up! Unfortunately, today the review site for PR content builds is behind a Microsoft employee login 😭 I wish it wasn't that way, but for the moment, we're a bit limited in what we can do there. We're working on a few alternate ways to enable external contributors to preview content. Those aren't ready yet, but they are progressing. For the moment, the best way to check for correctness is to see how it renders on GitHub. I apologize for the inconvenience of this. We've heard your request and are putting things in motion to improve this in the future.

Since this is a documentation platform feature and not one that ASP.NET is in control of, and since we've got this solidly tracked internally, please permit the ASP.NET team to close this issue. Feel free to follow up with me personally to share any feedback you have on this or other aspects of docs. You might also want to report or vote for docs site features here: https://msdocs.uservoice.com/forums/364242-general-site-feedback When we release an improvement to contributor preview, we'll most certainly announce it on the docs team blog, which you can find here: https://docs.microsoft.com/en-us/teamblog/

Thanks for your patience and understanding!

**Comment by spottedmahn** [comment]
Hi @EisenbergEffect - thanks for reply!  I understand.

[I've opened up feedback item.](https://msdocs.uservoice.com/forums/364242-site-feedback/suggestions/32083987-allow-preview-of-build-output-for-doc-changes-to-o)

**Comment by guardrex** [comment]
@spottedmahn You can build the docs locally with DocFX :point_right: https://github.com/aspnet/Docs/blob/master/CONTRIBUTING.md#test-your-changes-with-docfx

... you just need one *RexHack*:tm: to make it work. DocFX running locally can't render tab controls properly. What you can do is hack your browser to show the contents of the tabs ... so you can at least :eye: *SEE* :eye: what content you have in the tabs. I use Stylebot, but you can use any of them. Just setup a style for `localhost` (because it will run the site locally in your browser at `localhost:8080`) ...
```css
section[role=tabpanel] {
    display: block;
}
```
The only other caveat is that you won't get the fancy stylesheets of the actual docs site unless you do additional work. I didn't bother. I just use the default DocFX style. I just need to see how the content will render. It gets the links setup (alerts you to broken bookmarks and links), shoots the linked code into thet topic, shoots the images in there. It's really quite useful. :+1:

**Comment by spottedmahn** [comment]
Thanks @guardrex !

I actually just got through my first [PR working completely locally](https://github.com/aspnet/Docs/pull/4690#issuecomment-340887046)!

> RexHack™️

❤️ it!  I'll have to check out [Stylebot](https://chrome.google.com/webstore/detail/stylebot/oiaejidbmkiecgbjeifoejpgmdaleoha?hl=en), looks very interesting.

I noticed the style is not 1 for 1 to what I see online.  I wonder why that is?

Thanks for the reference to making the preview builds available to non-msft employees.

**Comment by scottaddie** [comment]
@guardrex @spottedmahn Tabs are supported in DocFx as of the following release: https://github.com/dotnet/docfx/releases/tag/v2.26

**Comment by guardrex** [comment]
Thx @scottaddie I'll give that a shot.
