### ISSUE TITLE
Diagnosing startup errors

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#4685]
Add/update content that covers diagnosing startup errors when running behind IIS and when hosted on Antares.

We already have these troubleshooting tips when publishing to IIS: https://docs.microsoft.com/en-us/aspnet/core/publishing/iis?tabs=aspnetcore2x#troubleshooting-tips. We should make sure these are still up to date.

`[Edit]`

- [x] I noticed that the [detailedStartupErrors ](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/hosting?tabs=aspnetcore2x#detailed-errors) docs I could find never talked about being able to set it via an environment variable, only showed how to do it in code.
- [ ] There is an experience inside App Services solve problems blade that can be ASP.NET Core aware. This experience needs work, but it might help some people and we should talk about what we can do to make it better.
- [ ] Getting to a view that displays the event log on Antares can be super helpful depending on the errors.
- [ ] Turning on App Insights can be helpful as long as your error happens after we've setup the logging infrastructure. Like in the example pasted below.

**Comment by Rick-Anderson** [comment]
From Glen Condron:
This looks like what happens when you get an exception being thrown in your Configure method, which means you should see an exception logged in Application Insights, something like this:
![image](https://user-images.githubusercontent.com/3605364/32240349-3622ef90-be11-11e7-848a-52d923cb95b4.png)

We log whenever you are behind IIS and a startup error occurs, outside of ANCM errors in starting the process itself. Another option is to try detailedStartupErrors: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/hosting?tabs=aspnetcore2x#detailed-errors. You can turn this on without re-deploying your application by creating an app setting called ASPNETCORE_DETAILEDERRORS and setting its value to true. This will give you details on the page that today just gives you the .NET Core version. Once you’ve done that then the error page that is being displayed should look like this:

If you do this then remember to turn it off again once you have diagnosed your problem.

**Comment by guardrex** [comment]
> We should make sure these are still up to date.

It's been a while ... perhaps as long as a year. We *do* need to add `detailedStartupErrors` and a link over to the Hosting topic down in the Troubleshooting section.

**Comment by glennc** [comment]
- I noticed that the `detailedStartupErrors` docs I could find never talked about being able to set it via an environment variable, only showed how to do it in code.
- There is an experience inside App Services solve problems blade that can be ASP.NET Core aware. This experience needs work, but it might help some people and we should talk about what we can do to make it better.
- Getting to a view that displays the event log on Antares can be super helpful depending on the errors.
- Turning on App Insights can be helpful as long as your error happens after we've setup the logging infrastructure. Like in the example pasted above.

**Comment by guardrex** [comment]
There's probably enough to say about Azure Apps hosting that it could be its own topic. I opened this one back in February and even hacked up a draft outline: https://github.com/aspnet/Docs/issues/2800 ... so this issue could be seen as a dup of #2800 if that topic were to contain all of the juicy details on troubleshooting Azure Apps.

A problem developed over time with the IIS topic: It has became so large that it possibly should be split ... move the troubleshooting into its own topic.

Adding Azure Apps content to it seemed like a bad idea on two counts:
1. Just size ... it's already huge.
2. Focus ... For those truly just hosting on IIS with no interest or need for Azure (**perish the thought!!!** :smile:), they probably don't want to read about Azure Apps in the IIS topic.

**Comment by Rick-Anderson** [comment]
@glennc  suggests 
>Getting to a view that displays the event log on Antares can be super helpful depending on the errors.

@blowdart  won't that require authorization? Can I create a view without auth and say "this needs auth". Why don't we just show them how to use Kudu to view the event log?
