### ISSUE TITLE
FileUploadSample broken

### ISSUE THREAD

**Issue by HansHammel** [aspnet/Docs#4777]
The .\aspnetcore\mvc\models\file-uploads\sample\FileUploadSample is broken. 
I get a `User creation failed with status code: 400` for the multipart form, and the Avatar sample shows no Image, but the files seem to be uploaded to temp folder. No further Investigation of mine. Please fix this.

Thx.

**Comment by Rick-Anderson** [comment]
@guardrex  this isn't your sample is it?

**Comment by guardrex** [comment]
@Rick-Anderson It's for an [@]ardalis topic. It goes with ...

https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/models/file-uploads.md
https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads

**Comment by Rick-Anderson** [comment]
@ardalis  might know the problem.

**Comment by guardrex** [comment]
When this issue is addressed, it might be a good time to look generally at how file/data transfer for large files/streams is covered. Sure, the sample could just be fixed on this issue, but it might also be a good time to assess the whole subject. The author might want to open an issue to expand coverage or even just expand the topic's coverage. 

@nickalbrecht and I were talking on Slack about it. Here are a few notes (mostly from Nick):
* There's no example for handling file Chunking.
* There's no example for Range Bytes when downloading.
* Provide help/examples/tips for resuming large file uploads when users were in remote areas with flaky Internet. Ditching streaming large files and going with chunking instead. Differences; pros and cons; terminology explained; common pitfalls.
* RE: Chunked transfer encoding: HTTP/2 apparently doesn't support it ... it goes to DATA frames. Should DATA frames coverage be explained/demoed?

**Comment by Rick-Anderson** [comment]
@guardrex 	what doc does it go with?

**Comment by nickalbrecht** [comment]
I believe it was
https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/models/file-uploads.md
https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads

**Comment by guardrex** [comment]
@Rick-Anderson It goes with the file uploads topic ... this issue is listed on your new master issue for the topic: #10214

**Comment by Rick-Anderson** [comment]
Closing this one. We can track it in the master issue.

**Comment by nickalbrecht** [comment]
So long as the key points @guardrex pointed out above are added/updated as best as possible. They were the main things we were concerned with when talking about this way back when.

- Upload chunking
- Byte-Range header
- Handling unreliable connections
- HTTP/2 support

Look forward to seeing traction on this one!

**Comment by guardrex** [comment]
Moved to https://github.com/aspnet/AspNetCore.Docs/issues/12285.
