### ISSUE TITLE
improve discover-ability of Migration

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#4840]
https://docs.microsoft.com/en-us/aspnet/core/migration/

One of the questions I got from a number of Boston Code Camp attendees is where to find guidance on migrating an MVC application from .NET Framework 4.7 to .NET Core 2.0.
 
I looked briefly, and I didn’t find anything obvious. Where would you direct them?

**Comment by guardrex** [comment]
Is it supposed to be? :point_right: https://docs.microsoft.com/en-us/aspnet/core/migration/proper-to-2x/

Could the content be expanded and organized more like a 1-2-3 step-by-step guide? ... more like :point_right: https://docs.microsoft.com/en-us/aspnet/core/migration/mvc ... especially picking up at https://docs.microsoft.com/en-us/aspnet/core/migration/mvc#controllers-and-views because I assume a dev would use the 2.0 MVC template to get the process started.
