### ISSUE TITLE
Document deploying an already running app on different OSes with different webservers

### ISSUE THREAD

**Issue by flipdoubt** [aspnet/Docs#4866]
Can someone point me to the official guidance on how to deploy an already running app when running dotnet behind either IIS or NGINX? I've searched, of course, and found all kinds of discussions referencing `app_offline.htm`, but that means nothing on Linux or Mac or when simply debugging with `dotnet run`.

Beyond discussions, where in the docs would I find specifics?

**Comment by Rick-Anderson** [comment]
@guardrex  can you suggest where to start?

**Comment by guardrex** [comment]
Most of the topics and tutorials here and elsewhere that pertain to IIS deployment use Web Deploy (MSDeploy), and there are many MS and community topics for it because Web Deploy has been around for so long (e.g., [Introduction to Web Deploy area topics](https://docs.microsoft.com/en-us/iis/publish/using-web-deploy/introduction-to-web-deploy)).  It's baked into VS, and most VS devs I've encountered use the publishing tools for Web Deploy in VS. The topics in the [Deployment area](https://docs.microsoft.com/en-us/aspnet/core/tutorials/publish-to-azure-webapp-using-vs) are about using Web Deploy. Even from the command line, Web Deploy is fairly easy to use. There has been a call [for them to make Web Deploy xplat](https://github.com/aspnet/Tooling/issues/583), and they might just do that eventually.

A little less well-described would be PowerShell, and you can [take a look at my mad scripting](https://github.com/guardrex/aspnetcore-iis-ps-publish) to get idea what that might look like for IIS. (I wouldn't use that for production tho without extensive testing.)

For Nginx, did you see [Set up a hosting environment for ASP.NET Core on Linux with Nginx, and deploy to it](https://docs.microsoft.com/en-us/aspnet/core/publishing/linuxproduction?tabs=aspnetcore2x)? That might have what you need. It should also be possible to handle deployments in Azure to non-IIS servers with [Azure xPlat CLI technology](https://cloudacademy.com/blog/xplat-azure-cli-tool/), but I haven't explored those tools personally.

There's also some helpful info over in the [.NET Core Deploying topics](https://docs.microsoft.com/en-us/dotnet/core/deploying/).

If this info :point_up: isn't enough tho, let me know. I know (a busy) engineer we can ask about this for more tips/links pertaining to Nginx.

**Comment by guardrex** [comment]
@Rick-Anderson @scottaddie I don't think we have an actionable issue here. Do you want to close this?

**Comment by flipdoubt** [comment]
Those docs tell you how to deploy a new site but not how to update an existing site where DLLs are locked by the already running web server. We need something like app_offline for Kestrel.

**Comment by flipdoubt** [comment]
On Linux. And Mac OS. And wherever Kestrel is found.

**Comment by guardrex** [comment]
Sorry about that @flipdoubt. When you didn't respond to my last post, I thought you found the info you needed. Upon closer inspection, yes, I agree with you. I see some opportunities here.

I was surprised to just learn that the [Create publish profiles for Visual Studio and MSBuild, to deploy ASP.NET Core apps](https://docs.microsoft.com/en-us/aspnet/core/publishing/web-publishing-vs) topic doesn't describe or link to something on setting the `<EnableMSDeployAppOffline>` element in the *.pubxml* file.

Otherwise in the IIS case, manually stopping the AppPool or using PowerShell scripting to stop the AppPool should gracefully release the lock on the app's assembly.

For NGinx, we should ask the busy engineer who I mentioned earlier! :smile: @shirhatti: TL;DR: The [Set up a hosting environment for ASP.NET Core on Linux with Nginx, and deploy to it](https://docs.microsoft.com/en-us/aspnet/core/publishing/linuxproduction?tabs=aspnetcore2x) topic doesn't provide guidance for shutting down the NGinx worker process in order to replace a deployment. Is it just `sudo service nginx stop`? Could I add that to the topic if that's correct?

Starting an app from the command line just takes a Ctrl-C to stop it in order to replace files after the process shuts down and the lock on the app's assembly is released. It's documented in the console itself when the app is run: `Application started. Press Ctrl+C to shut down.`

@Rick-Anderson Please re-open. I'll add this to the work I'm doing for IIS/Antares. We *do* have a few items:
* Describe setting the `<EnableMSDeployAppOffline>` element in the publish profiles topic. [Fix the comma splice in the title, too.] When publishing to Azure, this element is automatically added.
* Add a link to the *app_offline.htm* section of the [ASP.NET Core Module configuration reference](https://docs.microsoft.com/en-us/aspnet/core/hosting/aspnet-core-module#appofflinehtm).
* In the AppPools section of the IIS hosting topic, add a note about stopping the AppPool in order to replace a deployment.
* If @shirhatti says 'yes' to `sudo service nginx stop`, I can add that to the NGinx topic.

> We need something like app_offline for Kestrel.

That's a very interesting idea. You could ask about that in the [Kestrel issues](https://github.com/aspnet/KestrelHttpServer/issues). If you open an issue to ask, please CC me on it. I'd like to follow that discussion.

**Comment by guardrex** [comment]
Let's cross-ref your Hosting issue on this, too :point_right: https://github.com/aspnet/Hosting/issues/1270

**Comment by shirhatti** [comment]
@guardrex 

> I was surprised to just learn that the Create publish profiles for Visual Studio and MSBuild, to deploy ASP.NET Core apps topic doesn't describe or link to something on setting the <EnableMSDeployAppOffline> element in the .pubxml file

If you have an ASP.NET Core project that references the websdk (`Microsoft.NET.Sdk.Web`), we enable the AppOffline rule by default so you really ever have to set it yourself in your publish profile.

> Is it just `sudo service nginx stop`?

Not quite. For the naive solution, you'll have to stop your backend service instead `sudo service kestrel-hellomvc stop`.
There's also always the option of something akin to a blue-green deployment where you bring up a new backend service and then update the virtual host in your nginx configuration to point to the new service. This is will allow you to transition without anytime downtime if your application logic is robust enough to handle this. After the successful transition, you can tear down the old service.
I'm by no means an expert here, but a cursory search by me found a blog post that in spirit captures what I'm suggesting here http://dukebody.com/?p=511

I'm okay with updating the document with the naive approach, as long as we do enough to call out that this is the naive approach and there exist solutions for 0-downtime deployments. I'll defer to @Rick-Anderson and the rest of doc team to make a decision on what to do.

**Comment by guardrex** [comment]
@shirhatti 

> If you have an ASP.NET Core project that references the websdk (Microsoft.NET.Sdk.Web), we enable the AppOffline rule by default so you really ever have to set it yourself in your publish profile.

I mistakenly thought that it was only automatic for Azure publishing. It threw me off because I had VS create a publish profile for a project that referenced the websdk, I checked the *.pubxml* file that it created, and `<EnableMSDeployAppOffline>` wasn't present in the file. I guess ur saying that it uses some other mechanism.

What do you think about adding this to the bottom of the [Compute project items section](https://docs.microsoft.com/en-us/aspnet/core/publishing/web-publishing-vs?tabs=aspnetcore2x#compute-project-items)? ...

> When an ASP.NET Core project references \`Microsoft.NET.Sdk.Web\` in the project file, an \*app_offline.htm\* file is placed at the root of the web application directory. When the file is present, the ASP.NET Core Module gracefully shuts down the app and serves the \*app_offline.htm\* file during the deployment. For more information, see the \[ASP.NET Core Module configuration reference](https://docs.microsoft.com/aspnet/core/hosting/aspnet-core-module#appofflinehtm).

> I'm by no means an expert here

If I had time, I'd like to learn more about it (i.e., learn the basics of NGinx deployment; e.g., do *your* tutorial). Maybe in a few weeks.

The actionable items that I can address for the Antares/IIS work are:
* [ ] In the publish profiles topic, add content along the lines of what I show above :point_up:.
* [ ] In the AppPools section of the IIS hosting topic, add a note about stopping the AppPool in order to replace a deployment. Mention a few of the methods that accomplish this (Manual, Web Deploy, PowerShell).

The remaining item that I can't personally address is:
* [ ] Nginx topic updates regarding replacing a live deployment. As you say, @Rick-Anderson @scottaddie will know how to proceed.

**Comment by Rick-Anderson** [comment]
>  Nginx topic updates regarding replacing a live deployment. 

@shirhatti  can you suggest an author?
