### ISSUE TITLE
Create an intro on using .NET4.6.x with ASP.NET Core

### ISSUE THREAD

**Issue by glennblock** [aspnet/Docs#4869]
The experience for creating ASP.NET Core Apps on .NET 4.6.x is confusing and there is little to no documentation. This hurts adoption for folks that are wading in to ASP.NET Core, but not yet ready to move to .NET Core. It also basically defeats the whole purpose of supporting the full framework in ASP.NET Core period.

I just spent hours trying to figure out how to create an ASP.NET Core App in this manner. Though I selected .NET 4.6.x as the filter the apps I created all ended up targetting .NET Core. The main culprit is the selector on the second page in the upper left, which was defaulting to .NET Core rather than .NET FX. It was non-intuitive for me to look at that dropdown, and I just clicked through to create.

Below you can see the selector set to .NET Framework after I changed it.

![screen shot 2017-11-26 at 12 51 20 pm](https://user-images.githubusercontent.com/141124/33249057-2adbe372-d2dd-11e7-94c3-5a0be4d5e335.png)

The walkthrough should take a developer from scratch and show them to make sure this selector is the proper value. Also it will  show the final result running as exe when the app is executed.

**Comment by glennblock** [comment]
Note: Twitter rant on my play by play experience starts here: https://twitter.com/gblock/status/934865575771226112

**Comment by cartermp** [comment]
Is there a place in the TOC which could effectively house "Other Getting Started" material?  It seems like we're really just missing a few numbered steps on what to do, e.g.

1. File | New
2. ASP.NET Core
3. Something something ignore a lot of the stuff in VS that will confuse you
4. Open project file
5. Edit target framework to `net462` or whichever is best (minimum supported version must be in the doc)
6. Watch as the project system restores things and it's all happy

I'm not really sold on getting screenshots in there, namely because of how fast things can change and this may not be a mainline scenario a year from now, but at least getting the written information is enough to unblock folks.

Appropriate metadata on the doc would also make it very visible on Google + allow us to tuck it away somewhere if we don't want new people coming to the docs site and ultimately being confused.

**Comment by glennblock** [comment]
I would at least recommend a screenshot of the dropdown that is confusing. That's one image that maybe needs to change, but it is where all the confusion lies.

**Comment by Rick-Anderson** [comment]
@glennblock - Why not add an extra screen shot to [Getting started with Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start)

If you're targeting .NET FX, select **.NET Framework**.

I could add the screen shot to other intro tutorials.

**Comment by glennblock** [comment]
Sure.

**Comment by Rick-Anderson** [comment]
@rachelappel  can you take this? I'd add it to the end of the tutorials. It just needs a screen shot showing selecting .NET FX. Then update Create a RP web app and Create a MVC web app to say,
If you're targeting .NET Framework, see ...

**Comment by scottaddie** [comment]
Per @Andrew-MSFT, the framework selector confusion is being addressed in VS 2017 15.6: https://twitter.com/AndrewBrianHall/status/935011893621567488. Let's keep an eye on how that evolves too. Some doc updates may be required afterwards.

**Comment by Andrew-MSFT** [comment]
The "New Project Dialog" will make it clearer that the .NET Framework target selector does not apply to .NET Core and .NET Standard projects.  The specific issue of making sure to call out if the user wants "ASP.NET Core on .NET Framework" (pictured above) will not change in the 15.6 timeframe, so if we don't feel the docs make that clear enough, there will still be value in proactively making that update.
