### ISSUE TITLE
Diagnose ASP.NET Core startup errors on Azure App Service

### ISSUE THREAD

**Issue by glennc** [aspnet/Docs#4890]
We want to provide an fwlink that will provide information for people who are having problems with their application not starting on Azure App Service.

Most of the information we would want is already available in some form, but not necessarily App Service specific. For example we have a doc that tells you how to turn on ANCM logging, but nothing that tells you how to edit that file on App Service and what locations are good to log to in App Service.

I would like to put the fwlink in the next VS update, and ideally update the Kudu deployment scripts as soon as the doc is ready. For example, Kudu can detect if the app failed to start at the end of a deployment and display the link to this doc if it did.

@RickAndMSFT Are you the right person to look at this?

**Comment by guardrex** [comment]
Is it related to or a dup of https://github.com/aspnet/Docs/issues/4685?

**Comment by glennc** [comment]
Yeah, you could see this as a dupe I suppose. This just raises its priority and answers the question about it being its own document.

**Comment by guardrex** [comment]
I deleted that remark since I figured that u already knew about the others (e.g., https://github.com/aspnet/Docs/issues/4685) and were probably asking for something else. I still think a full disclosure topic would be a big hit, but it's not really your ask here :point_right: https://github.com/aspnet/Docs/issues/2800 ... it would be nice to have everything in one spot (eventually).

**Comment by Rick-Anderson** [comment]
@glennc  I changed the issue title to "Diagnose ASP.NET Core startup errors on Azure App Service"

I can get this done in a couple weeks if you provide an outline. I'll fix all or most of #4685

**Comment by guardrex** [comment]
Note to self: Link doc for remote debug.
