### ISSUE TITLE
Remove old client-side dev docs

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Docs#4944]
Per the request of @SteveSandersonMS, we should remove some outdated documents from the **[Client-Side Development](https://docs.microsoft.com/aspnet/core/client-side/)** TOC node. The world has moved on from some of these technologies.

**Comment by Rick-Anderson** [comment]
@scottaddie  will remove them. @SteveSandersonMS  to supply the list of topics to remove.

**Comment by SteveSandersonMS** [comment]
My thoughts on the docs in our "Client-Side Development" area:

| Page | Notes |
| --- | --- |
| Gulp | The content is well written and informative, but is all about using Gulp inside VS. It's not really to do with ASP.NET. Also, Gulp is less widely used these days since Webpack became dominant. |
| Grunt | The content is well written and informative, but is all about using Grunt inside VS. It's not really to do with ASP.NET. Also, Grunt is less widely used these days since Webpack became dominant. |
| Bower | Bower is officially deprecated. We should not have docs about it. |
| Bootstrap | The content is good, but only a small bit of it is specific to ASP.NET. If you're determined to clean up, all the parts that just document Bootstrap components themselves (e.g., jumbotron, buttons, badges, etc.) could be removed, but it's probably not harmful as-is. |
| Knockout | Almost none of this is specific to ASP.NET. It would be better to remove this and just have the SPA docs about the ASP.NET SPA templates. |
| AngularJS | This is about AngularJS (1.x) which is now superseded by a completely different framework (Angular 2+, currently on version 5). Also almost none of this is specific to ASP.NET. It would be better to remove this and just have the SPA docs about the ASP.NET SPA templates. |
| JavaScriptServices | This is OK. It's not about the latest SPA templates, but is still relevant because it's about other APIs that are still supported (e.g., for Webpack dev middleware, or calling Node code directly. |
| Styling (LESS/SASS/etc.) | Content looks fine, but is all about using these styling tools inside VS. It's not really to do with ASP.NET. |
| Bundling and minification | This is fine. |
| Yeoman | Can't think of any reason why we should still have this. We only tell people to use `dotnet new` these days, not Yeoman. |
| Browser link | This is fine. |

Hope that helps in some way. I'll leave it with you folks to make final decisions of what to actually do with the content.

**Comment by scottaddie** [comment]
I propose we remove the following docs, based on Steve's feedback above:
- [AngularJS](https://docs.microsoft.com/en-us/aspnet/core/client-side/angular)
- [Bower](https://docs.microsoft.com/en-us/aspnet/core/client-side/bower) (once it's replaced in the project templates)
- [Grunt](https://docs.microsoft.com/en-us/aspnet/core/client-side/using-grunt)
- [Knockout](https://docs.microsoft.com/en-us/aspnet/core/client-side/knockout)
- [Yeoman](https://docs.microsoft.com/en-us/aspnet/core/client-side/yeoman)

@danroth27 @Rick-Anderson Are you in agreement?

**Comment by danroth27** [comment]
We still have customers using grunt and the tooling still exists, so I think we should leave it.

For bower, the tooling still works, but I think we should add a note at the top similar to what they have on http://bower.io letting folks know that while it's still maintained, it's no longer recommended.

I'm ok with removing AngularJS, Knockout and Yeoman. Can we redirect the AngularJS and Knockout links to the new SPA content? Can we redirect the Yeoman link to the dotnet new docs?

**Comment by scottaddie** [comment]
@danroth27 Yes. I'll take care of this today.
