### ISSUE TITLE
VS/VSC tracking links

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#5204]
@TerryGLee

VS docs: https://aka.ms/vsdownload?utm_source=mscom&utm_campaign=msdocs

... lands on the downloads page. Many topics take the reader to the VS IDE page at: https://www.visualstudio.com/vs/. For VSC, I've seen topics use (and I've used in a few topics): https://code.visualstudio.com/.

Do you have similar links (or even just tracking query strings) for those two?

**Comment by TerryGLee** [comment]
I'll check and report back.

**Comment by TerryGLee** [comment]
A quick update: This is still under discussion.

**Comment by guardrex** [comment]
@TerryGLee Any word on this one?

**Comment by guardrex** [comment]
Since this doesn't seem like a viable issue at the moment, let's close for now. We can reopen this if it becomes a need in the future.

**Comment by TerryGLee** [comment]
Also this is now closed, I will say that this was still under discussion by the product groups but no decision had been made. I did find out that the product group is able to track without tracking URLs those Docs pages that mentioned their VisualStudio.com pages, but they were most interested in having tracking URLs on Download links, particularly. Since that's already happening, then for now, we're good.
