### ISSUE TITLE
upgrade to netcoreapp2.0

### ISSUE THREAD

**Issue by taobaohi** [aspnet/Docs#5232]
upgrade to netcoreapp2.0

**Comment by guardrex** [comment]
@taobaohi We're aware that there are about 27 samples that are still `project.json`-based (and true, we do need an issue for this). There might be a few lingering 1.1-era samples as well. Did you have something else in mind?

**Comment by guardrex** [comment]
@taobaohi I'm going to close the issue because this isn't specific enough to take action on. We can reopen the issue if you provide additional details. Regarding the lingering *project.json*-based samples (if that's what you were referring to), I'll open a tracking issue shortly that identifies the offending samples for update.
