### ISSUE TITLE
Response Caching Middleware

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#5273]
https://docs.microsoft.com/en-us/aspnet/core/performance/caching/middleware

The 2.x sample is doing config in main. Config needs to be in startup. Sample needs to use template code so folks can plug caching into RP or MVC apps. 

The code shown doesn't work with the templates. The 2.x code looks like 1.x code. 

Short term is I need code to enable response cashing with RP template.

**Comment by guardrex** [comment]
The samp was built right after 2.0 released and before we had a firm plan for these samples. That 2.x code does work tho with RP ... it's just using the convenience methods. All I need to do here is put in a proper RP template app with the bits in `Startup`. No sweat. I'll knock this out quickly.

**Comment by guardrex** [comment]
@Rick-Anderson

**CORRECTION:** I just took a closer look ... The main topic for response caching at https://docs.microsoft.com/aspnet/core/performance/caching/response is the one that's supposed to show a webpage-based project sample [MVC currently (and *project.json* :cry:); but should be RP on its next update].

That's why you see the middleware topic showing that sample the way that it does ... it really was just supposed to demo the middleware only. It wasn't supposed to be a webpage-based sample.

If the main topic's sample goes RP (and it should), we probably don't want to have another RP sample for the middleware topic ... it will just end up being a duplicate for the most part.

One option is to update the main topic's sample to 2.0/RP and then either leave this sample as it is or cut it out of the middleware topic entirely. Whether or not it has a sample, I still think it's wise to show both the `Startup` way and the host builder convenience method way ... devs will probably be building apps both ways.

Another option is to merge the middleware topic content (sans the sample bits and cutting duplicate content) into the main response caching topic (at the bottom), which automatically eliminates this version of the sample. The main topic will get a 2.0/RP sample update. That might work out well ... it would get all of our response caching content into one spot with one sample.

How to you want to proceed?

**Comment by Rick-Anderson** [comment]
>I still think it's wise to show both the `Startup` way and the host builder convenience method way ... devs will probably be building apps both ways.

Dev's who want to use the host builder approach will be on their own. They'll be able to figure it out.

All we need right now is a sample that works with RP/MVC/ASP.NET Core 2.x on hooking up response caching middleware from template code.
