### ISSUE TITLE
Replace M.A.All meta-package with Microsoft.AspNetCore.App  - MD files only

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#5314]
![image](https://user-images.githubusercontent.com/3605364/35590459-097e0e7a-05ab-11e8-9e4f-265db68b64d3.png)

currently mentioned in 22 files. This issue is about updating the docs that specifically mention *Microsoft.AspNetCore.All*

We need to convert a few of these and agree on the language and style of the update.

Updating the samples that use the **ALL** meta-package is a lower priority.  See Update all 2.0 samples to use M.A.App, aka Microsoft.AspNetCore.App #6382

**Comment by guardrex** [comment]
For reference: https://github.com/aspnet/Announcements/issues/287

**Comment by guardrex** [comment]
It didn't make sense to search out ALL samps ... many are 1.x because the topic needs them to display 1.x code. It made more sense to just get a list of topics that have the text "View or download sample code," since that language was standardized quite a while ago. That resulted in the following list of 46 topics. There's probably a handful of non-sample projects beyond this, but this seems like a good place to start.

Idk if u want to do assignments, but I marked the ones I built, reworked, or would like to work in case we go that way.

... and brace yourself ... a number of these are *project.json*-based. There are over 20 *project.json* files in the repo.

| | Topic |
| :--------: | ----- |
|  | \client-side\spa-services.md |
|  | \fundamentals\dependency-injection.md |
|  | \fundamentals\environments.md |
|  | \fundamentals\error-handling.md |
|  | \fundamentals\file-providers.md |
|  | \fundamentals\owin.md |
|  | \fundamentals\portable-object-localization.md |
|  | \fundamentals\routing.md |
|  | \fundamentals\static-files.md |
| guardrex | \fundamentals\url-rewriting.md |
|  | \fundamentals\websockets.md |
|  | \fundamentals\configuration\index.md |
| guardrex | \fundamentals\configuration\options.md |
|  | \fundamentals\logging\index.md |
|  | \fundamentals\logging\loggermessage.md |
| guardrex | \fundamentals\middleware\extensibility.md |
|  | \fundamentals\middleware\index.md |
| guardrex | \fundamentals\primitives\change-tokens.md |
| guardrex | \fundamentals\servers\aspnet-core-module.md |
| guardrex | \fundamentals\servers\httpsys.md |
| guardrex | \fundamentals\servers\kestrel.md |
| guardrex | \fundamentals\servers\weblistener.md |
| guardrex | \host-and-deploy\ihostingstartup.md |
| guardrex | \host-and-deploy\windows-service.md |
|  | \includes\webApi\next.md |
|  | \migration\configuration.md |
|  | \migration\webapi.md |
|  | \mvc\advanced\app-parts.md |
|  | \mvc\controllers\dependency-injection.md |
|  | \mvc\views\dependency-injection.md |
|  | \mvc\views\partial.md |
|  | \mvc\views\view-components.md |
|  | \mvc\views\tag-helpers\authoring.md |
| guardrex | \performance\response-compression.md |
| guardrex | \performance\caching\distributed.md |
| guardrex | \performance\caching\memory.md |
| guardrex | \performance\caching\middleware.md |
| guardrex | \performance\caching\response.md |
| guardrex | \security\key-vault-configuration.md |
| guardrex | \security\authentication\cookie.md |
| guardrex | \security\authorization\razor-pages-authorization.md |
| guardrex | \security\data-protection\compatibility\cookie-sharing.md |
| guardrex | \testing\integration-testing.md |
| guardrex | \testing\razor-pages-testing.md |
|  | \tutorials\first-web-api-mac.md |
|  | \tutorials\razor-pages\razor-pages-start.md |

**Comment by scottaddie** [comment]
@guardrex *client-side\spa-services.md* isn't *project.json*-based. You can remove that one from your list above.

**Comment by guardrex** [comment]
It's not ".App" based tho. The list above isn't meant to be a *project.json*-based list. I was just mentioning that in passing. It's all of the topics that have a sample that will need either ".App" or left alone until the trigger is pulled on going with ".App" + extra package references.

**Comment by guardrex** [comment]
If there isn't support for ⚔️ *Divide and Conquer!* 🏹 (assignments), then I'll remove the 1st column.

**Comment by rachelappel** [comment]
@guardrex I looked at the environments and error-handling docs and I don't see any references to "Microsoft.AspNetCore.All" in those.

**Comment by guardrex** [comment]
ok ... cool. thanks. I'll pull those.

**Comment by guardrex** [comment]
Ah .. those have to stay. The environements sample calls for "All" ...

https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/environments/sample/WebApp1/WebApp1.csproj

The error-handling sample is *project.json*-based, so it should go to "App" on its update/upgrade ...

https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/error-handling/sample/project.json

**Comment by rachelappel** [comment]
Oh geez I forgot to look at the samples and hit just the docs.

**Comment by guardrex** [comment]
I totally missed what @Rick-Anderson was asking for here. I thought we'd do both ... fix the doc AND fix the sample. My bad. I think the samps will be a different issue. When we set that up tho ... I'll past that table back in.

**Comment by Rick-Anderson** [comment]
@guardrex 	what's the state of this issue?

**Comment by Rick-Anderson** [comment]
@guardrex 	no hurry, just wanted to get the state. It's not a priority.

**Comment by guardrex** [comment]
ok ... I'll get it. It's going to take a while longer to get samples squared away, so we may as well go ahead. I think (*hope*) that less than a dozen topics need a touch to drop it out of the text (with versioning, of course). The samples associated with those topics may still use the `All` package, and we can fix them up as we go on sample updates.

**Comment by guardrex** [comment]
@Rick-Anderson @scottaddie @tdykstra I'm ready to proceed on this issue today, but let me get the word on if there was a design change. The last info that I have is **_no version on the App package_** ...

https://github.com/aspnet/Docs/issues/8579#issuecomment-424548306
https://github.com/dotnet/sdk/pull/2533
