### ISSUE TITLE
 IHttpClientFactory - HttpClient as a service, handle cross-cutting concerns like caching, retry logic, timeouts and circuit breakers 

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#5402]
aspnet/HttpClientFactory#42

**Comment by stevejgordon** [comment]
I've written a bit about IHttpClientFactory on my blog (https://www.stevejgordon.co.uk/introduction-to-httpclientfactory-aspnetcore and https://www.stevejgordon.co.uk/httpclientfactory-named-typed-clients-aspnetcore) - Would like to have a crack at contributing to the docs if this is open to community engagement?

**Comment by scottaddie** [comment]
@stevejgordon This absolutely is open to community engagement. We'd love to have your help.

The first step is to propose an outline for the new doc. We'll need to get approval on it before writing. Do you have a rough outline in mind?

**Comment by stevejgordon** [comment]
@scottaddie I was going to suggest the following:

- Introduction and Benefits
- Basic Usage
- NamedClients
- TypedClients
- Outgoing Request Middleware (DelegatingHandlers)

**_Future (2.1 preview 2?):_**
- Polly

However I see that the wiki page does include a lot of content already by @glennc that pretty much covers the above and perhaps just needs to be moved to the docs?
https://github.com/aspnet/HttpClientFactory/wiki

I'm sure the team will weigh in with other options for a title but perhaps something more description for the use case, rather than the feature name... e.g. "Making HTTP Requests"

**Comment by scottaddie** [comment]
@glennc @danroth27 Please see the proposed outline above? Thoughts?

**Comment by glennc** [comment]
We also had this issue: https://github.com/aspnet/HttpClientFactory/issues/37

I think all the content for those headings needs to exist. We also wanted specific examples for how to use it in things like WebForms as well as details on unit testing with the factory, both your pages/controllers and your typed clients. Would that be a separate document?

**Comment by rynowak** [comment]
In addition to this we need to cover the connection management/handler rotation/dns kinds of things. The landscape is somewhat complex in 2.1 and will get better in the future, but we should be able to come up with a good set of comprehensive guidance. We should talk more about this when you're ready to start on that part.

List looks good to me overall, and we can close our bug tracking this!

**Comment by scottaddie** [comment]
@glennc Will this API be supported in ASP.NET 4.x? Your reference to WebForms leads me to believe that.

**Comment by scottaddie** [comment]
@stevejgordon Please proceed with writing according to your proposed outline. Assume that the doc will be located under the **Fundamentals** TOC node. In the meantime, I'll meet with @rynowak & @glennc and help fill in the gaps once your PR is submitted. Let me know if you have any questions.

**Comment by glennc** [comment]
It's a netstandard package, so yes. But it is designed to be used with some of ASP.NET Cores primitives. Which you can get with the GenericHost that was done at the start of 2.1. Effectively spinning up some core-isms into your System.Web app.

**Comment by glennc** [comment]
I wasn't as clear as I wanted to be there. It is netstandard which means it can be used in net4.x, but all of ASP.NET Core is that. This one in particular I want to explore using in non Core apps as well. Effectively bridging the experiences.

**Comment by scottaddie** [comment]
@glennc Since this repo/docset is dedicated to ASP.NET Core, I suggest documenting the WebForms stuff in the [ASP.NET 4.x docset](https://docs.microsoft.com/aspnet/overview). Putting it here could lead customers to believe that WebForms is a supported app model in ASP.NET Core. We can easily link over to that doc from here. Are you okay with that approach?

**Comment by glennc** [comment]
Sure. As long as the content exists I am ok with you putting it where it makes the most sense for our customers.

**Comment by stevejgordon** [comment]
@scottaddie Thanks. Excited to have a go at this. I'll start working on it and put in WIP PR in once I have something to show. I may need to advice/guidance on how/where to include samples/snippets. There are samples in the main HttpClientFactory repo but I see that some docs have their own sample project here in order to support building snippets? If it's okay, I'll start by copying over/fleshing out some text and take it from there.

> In addition to this we need to cover the connection management/handler rotation/dns kinds of things. The landscape is somewhat complex in 2.1 and will get better in the future, but we should be able to come up with a good set of comprehensive guidance. We should talk more about this when you're ready to start on that part.

Absolutely! I wasn't sure how much the team wanted to cover on that since I read that the handler rotation is considered less of a key feature once the managed Handler work is ready. I may have mis-interpreted that from @glennc comments though.

@rynowak - Would it be possible to get in touch offline via email? I have some questions that are likely outside the scope of the docs / feature to deepen my understanding of the DNS piece.

**Comment by rynowak** [comment]
Sure that would be great! My email is my github username + microsoft.com

**Comment by stevejgordon** [comment]
@ryanno / @glennc - Do you think we should include a section about the logging from HttpClientFactory and managing the verbosity per client etc?

**Comment by rynowak** [comment]
Yeah, some information about logging is important. I'm a little worried exactly how much will change in between now and release based on feedback...

I'd suggest documenting a few basics for now, and we can revisit after we finish all of the work in this area.
