### ISSUE TITLE
new doc: Razor Pages Areas

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#5407]
aspnet/Mvc#6926, aspnet/Mvc#6604
Scaffold the Identity UI and see how it uses areas.

Rename [Areas in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/areas?view=aspnetcore-2.1) to [Areas in ASP.NET Core for controllers](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/areas?view=aspnetcore-2.1)  
Before the intro, say this is for MVC controllers, see Areas for Razor Pages.

**Comment by guardrex** [comment]
Described by `@DamianEdwards` on the Standup :point_right: https://youtu.be/-EgE79M3tuc?t=34m00s

**Comment by Rick-Anderson** [comment]
@guardrex @scottaddie  who wants this?

**Comment by encrypt0r** [comment]
Can I take this? Is there anything I need to know first?

**Comment by encrypt0r** [comment]
@Rick-Anderson Can I take this? Is there anything I need to know first?

**Comment by Rick-Anderson** [comment]
@encrypt0r yes. Post an outline of the article here. @scottaddie 	do you have an idea for the outline?

**Comment by scottaddie** [comment]
I haven't had time to look at this yet. @encrypt0r Please provide your thoughts on a rough outline, and we'll review it.

**Comment by encrypt0r** [comment]
@scottaddie @Rick-Anderson 
 are you sure it's necessary to create a new page for "Razor Pages Areas"? Because all of the topics discussed in the current article must be duplicated in the new article as well. We can easily expand on the current page to include relevant information about "Razor pages" in the appropriate sections. This allows the users to see the whole picture more easily. Separating them might cause confusion.

**Here are the changes that I think are needed:**

> Area features:
1. Add information about Razor Pages wherever appropriate

> A typical folder structure for that using MVC areas looks like below:

2. Add "Pages" folder and some example pages to the folder structure

> When MVC tries to render a view in an Area, by default, it tries to look in the following locations:

3. Add paths for pages in the listed locations

> Link Generation

4. Add examples for Razor Pages.

5. Edit the article to make sure the flow between the topics are smooth

**Comment by Rick-Anderson** [comment]
@encrypt0r 	you're right. It's much better to have one topic on areas and update it so it applies to RP. Like you say

>Add information about Razor Pages wherever appropriate

**Comment by Rick-Anderson** [comment]
Moved to #9041
