### ISSUE TITLE
Nuget hell

### ISSUE THREAD

**Issue by Sm1le291** [aspnet/Docs#544]
I don't now this is bug or not. But It's really annoying! I try to add references and very often show message like this:
"NU1007 Dependency specified was SolarNet greater 0.3.1 but ended up with SolarNet 1.0.0"
And it is only in vnext project!!! Vnext reset reference version to 1.0.0.0!!! This is bug or feature??? A try many combinations, delete lock files and many other actions. But this does'not help

**Comment by davidfowl** [comment]
What did you do exactly. Can you reproduce it everytime?

/cc @abpiskunov

**Comment by balachir** [comment]
I wonder if you're running into one known issue with Nuget. Can you go to Tools > NuGet Package Manager > Package Manager Settings, and in the Package Sources tab, is the nuget.org feed entry checked?

**Comment by Sm1le291** [comment]
@davidfowl  You may try to add this to project.json to "dependencies" section
"SolrNet": "0.3.1"       
And after you show warning:
"NU1007 Dependency specified was SolarNet greater 0.3.1 but ended up with SolarNet 1.0.0"

**Comment by Muchiachio** [comment]
@davidfowl I found this happening too, especially then some of the versions are already cached in `.dnx/packages` folder, and VS can't restore the newly specified ones (because of wrong nuget feeds and such). Deleting all the packages from `.dnx/packages` folder and running `dnu restore` manually seems to help, at least to find more particular issue with the feeds or versions.

**Comment by danroth27** [comment]
This is not a doc issue. If you are still seeing this problem please open a bug on the [Tooling](https://github.com/aspnet/tooling/issues) repo.
