### ISSUE TITLE
Project Bedrock transports

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#5521]
See https://github.com/aspnet/KestrelHttpServer/issues/1980 and [Bedrock update](https://github.com/aspnet/KestrelHttpServer/issues/1980#issuecomment-377123245)
Document the lower layers. 
The transports

**Comment by davidfowl** [comment]
I want to be careful how we document this, it isn't a part of SignalR anymore it was pushed even down the stack.

**Comment by Rick-Anderson** [comment]
Closing.

**Comment by KPixel** [comment]
I got side-tracked from the various samples I'm working on, and ended up putting together a tutorial for Pipelines. The goal is to go all the way to Connections, but I'm currently stuck.

So, I though I would share what I have:

https://github.com/KPixel/Prototypes/tree/master/Pipelines

The images are [created with an SVG javascript library](https://github.com/KPixel/Prototypes/blob/master/Pipelines/_static/source.html), so they can easily be changed.

**Comment by Rick-Anderson** [comment]
@KPixel how is your tutorial going? Would you be willing to help write this document?

**Comment by KPixel** [comment]
@Rick-Anderson I never received any feedback from what I had [already written](https://github.com/KPixel/Prototypes/tree/master/Pipelines), so I wasn't sure if it was helpful...

**Comment by Rick-Anderson** [comment]
@halter73 can you review @KPixel tutorial?

**Comment by halter73** [comment]
@pakrym @davidfowl Can one or both of you take a look? 

I'm not sure the best place to leave comments, so I'll leave some here for now.

Since you show ReadResult.IsCanceled, I'd mention that the IsCanceled flag is only ever set if PipeReader.CancelPendingRead(). This is an alternative to passing a CancellationToken to PipeReader.ReadAsync() that doesn't throw. You can read again after a canceled read. Sometimes this is used to signal an event of some sort to the reading loop. There's an analogue of PipeReader.CancelPendingRead() one the PipeWriter called PipeWriter.CancelPendingFlush(). This is a somewhat advance topic, so it might be OK to leave out ReadResult.IsCanceled if you don't want to explain the CancelPending*() methods.

Another concept that's perhaps a little less advanced is calling Complete with an Exception argument. This will cause reads or writes on the other side of the pipe to throw the specified exception. This is useful for communicating details of issues like transport failures to the other side of the pipe (e.g. IOExceptions). 

Microsoft.AspNetCore.Connections isn't exactly mature yet, so it might be a little early to write a tutorial, but maybe @davidfowl thinks otherwise.

**Comment by KPixel** [comment]
@halter73 Thanks for the comments. That Receive() loop is only meant to introduce readers to the basics that are required in the loop. So, we can indeed simplified it by removing the IsCanceled part.

By the way, another advanced feature to mention is PipeReader.AdvanceTo(buffer.Start, buffer.End)...

**Comment by KPixel** [comment]
@Rick-Anderson I would like to help write a Pipelines doc. What's the process to get there?

**Comment by davidfowl** [comment]
cc @mairaw

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson I would like to help write a Pipelines doc. What's the process to get there?

@KPixel first step is to put an outline of the doc here. When you make a PR we can supply a TOC commit if you like.

**Comment by KPixel** [comment]
The outline/TOC could be as in the [tutorial](https://github.com/KPixel/Prototypes/tree/master/Pipelines):

1. Link to learn about the primitives Span and Memory
2. Introduction to the Pipe class
3. Simple Pipe sample
4. The Receive() loop
5. Pipes in ASP.NET Core 2.1
6. Introducing IDuplexPipe
7. Creating a pair of DuplexPipes
8. Duplex Connection

Considering how advanced certains sections can get, I don't know if we should split this into many articles (now), or leave it as-is (and refactor later as the extra advanced topics get covered).

More fundamentally, I think this doc belongs in the .NET doc. Probably next to the doc for Span/Memory (which I can't find, aside for the [API doc](https://docs.microsoft.com/en-us/dotnet/api/system.span-1))...

**Comment by KPixel** [comment]
Here is the issue tracking the doc for Span: https://github.com/dotnet/docs/issues/4400

**Comment by Rick-Anderson** [comment]
Closing as moved to dotnet/docs#4400
@KPixel 	let me know if this should remain open and what needs to be done.
