### ISSUE TITLE
Surface these GREAT docs and surface landing page from RP tutorial

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#5649]
Discussed in docs sessions at the Summit: The progression of moving from `dot.net` to the docs makes no mention of how great the docs are. Only the navbar link to **Docs** is present. There is no language to suggest that .NET in general and ASP.NET Core specifically offer better support documentation than other web frameworks.

1. [.NET](https://www.dot.net) `dot.net`/`https://www.microsoft.com/net` :point_right: *Web: web apps and services* link ...
1. [Web and Server Applications](https://www.microsoft.com/net/learn/apps/web) :point_right: *Get started with ASP.NET* button ...
1. [Get Started with ASP.NET](https://www.asp.net/get-started) :point_right: Last step *Razor Pages* link ...
1. [Introduction to Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/razor-pages/?tabs=visual-studio)

Location 1 (above) might include a section (below *One Platform*):

> ### Documentation and Support
>
> Whether you're new to software development or an experienced professional, .NET is fully supported by extensive and helpful documentation, Channel 9 videos, forums, and chat rooms.

Location 2 (above) might include a brief mention along the lines of:

> .NET is supported by helpful documentation, Channel 9 videos, forums, and chat rooms.

Location 3 (above):

Seems ok given that the *Learn more* link lands on https://www.asp.net/learn, which in turn links to ASP.NET and ASP.NET Core doc sets.

I suppose the idea is to encourage the visitor (following the link chain, a **new to .NET** visitor) to get right into building a RP app. However, I'm not so sure that's the only suggestion the text should make. I mean that dumps someone brand new to .NET, possibly new even to software dev or web dev, right into a rather meaty tutorial. I wonder if the last point in Location 3 should do something more like ...

> ### That’s it!
> 
> Next up, continue building your first ASP.NET Core app with Razor Pages or get a general introduction to ASP.NET Core. (link *ASP.NET Core* to https://docs.microsoft.com/aspnet/core/).

Location 4 (above):

One thing I can do is add a quick remark to the top of the tutorial to make it a bit easier for someone trying to reach an overview to get out to the ASP.NET Core landing page.

**Comment by guardrex** [comment]
@scottaddie @Rick-Anderson I did what I could here. Do you want to advance this along for possible changes to microsoft.com pages? If not, you can close this after #5652 merges.

**Comment by shirhatti** [comment]
@rowanmiller Just FYI @guardrex had a couple of suggestions.

**Comment by rowanmiller** [comment]
Hey,

The content on the .NET landing page (location 1) has been very optimized (user testing and A/B testing) to what resonates with "new to .NET" developers. So I don't think we'll list docs there. I do agree docs is a super important part of our platform though... so maybe it could go on the [What is .NET](https://www.microsoft.com/net/learn/what-is-dotnet) page? Which is what you get to if you click the "Learn about the .NET platform" call to action on the landing page.

We are in the early stages of a redesign of Location 2 and 3. 

Location 2 will be more of an overview of ASP.NET - think an ASP.NET equivalent of what Location 1 is to .NET. The primary call to action will still be Get Started though. For location 2, we do have docs on the list of things to test to see if they resonate with "new to .NET" web developers - it could likely be different to folks that come in via ".NET". So if it does test well, then yep, we'll be putting it on the page.

From our testing. Having multiple calls to action at the end of a tutorial aimed at new users is a negative.  Folks want simple and opinionated. That said, I totally agree with your "that dumps someone brand new to .NET, possibly new even to software dev or web dev, right into a rather meaty tutorial". That user you mention is exactly who this content is targeted at. Maybe the solution is to send them to somewhere else (something a little more gentle), rather than having a second call to action?

Curious about your thoughts on all this?

~Rowan

**Comment by guardrex** [comment]
Thanks @rowanmiller for explaining. I defer to the others on the target in the docs; since as you say, where the new dev/new-to-Core dev lands has probably been carefully considered.

My main fix on the associated PR was just to give those devs a "short circuit" link out of that tutorial so that if they prefer not to jump right into that tutorial they can get out to the main ASP.NET Core docs landing page. I'm happy with that.

Sounds like you were already aware of my concerns on this. I'm glad you're planning to test marketing language on this. I just wanted to raise awareness on how *every page leading here makes no mention of how great these docs are.* :cry:

Let's leave this open for just a sec in case the others want to jump in ... especially to confirm that the current landing page in the docs (the tutorial) was determined to be the best place to land folks. I think we can close here after that.

**Comment by rowanmiller** [comment]
I'm actually not sure that we have carefully considered where we send folks after the Get Started page. I think it was more that we decided to swap the Get Started page to Razor Pages (instead of MVC) and that was the best existing content we had.

When we redesigned the .NET marketing content, we developed purpose built content in docs to be the next logical step after the [Get Started with .NET in 10 Minutes](https://www.microsoft.com/net/learn/get-started/windows) tutorial.

As we redesign the ASP.NET content, we'll do the same thing.

**Comment by guardrex** [comment]
I have a bit of a concern about dumping devs into tutorials immediately.

I like the approach that goes from marketing to the main landing page of the docs ... but carefully lay that content out, keep the content focused, make the resources obvious, let people know where to get help, provide the dev with a basic overview of the technology, **THEN** put them into a "Build your first" tutorial experience.

The only way to know if one procedure works better than the other is not to rely on sentiment analysis alone but to rely on a learning objective assessment and sentiment analysis:

* Do they understand the basics of the tech?
* Do they know where to get more info and help?
* Did they enjoy the experience?

I used to teach bio ... I miss it a little bit actually. :smile: lol

**Comment by guardrex** [comment]
I'll close now. Thanks @rowanmiller! :+1:

**Comment by rowanmiller** [comment]
The Get Started flow is specifically for folks who want to build something. We've done a bunch of user studies with our target customers coming into our lab, and the overwhelming feedback from them is that when they look at any new tech, they want to explore it by building something. Of course, that's not everyone, there was a small subset who learn by reading and understanding the pieces of the stack - those would be the folks that head for the docs link in the menu 😄.

We don't really rely on sentiment much. It's all about how successful folks are with the actual product. We look at retention rates as folks move thru milestones in the tutorial (SDK install, app creation, first app run, using the product on a second day etc.). And for studies where we have folks in person, we ask those questions you mentioned too - do they understand the stack, are they enjoying it, etc.

The .NET Get Started has been thru this process, the ASP.NET one has not yet and there is definitely some improvement needed.

I 100% agree that we need to give folks an easy way to understand the stack, and find docs for the specific things they want to do. But the purpose of this flow is to help folks get a feel for the stack with a highly opinionated "do this, then do this" flow.

I think the things you are suggesting come a little later for folks on this flow. Once they've got an app, and have explored a bit, it's time to get them setup to build the actual thing they want. At that point things start to fork a bit and we need a clear layout to help them find what they need.

BTW I know I'm pushing back on some of your suggestions, but I do really appreciate your input here. It's always great to have someone challenge things, and I think the things you are suggesting definitely fit in somewhere in our flow - we just need to work out where.

**Comment by guardrex** [comment]
Very good. I'm glad to hear that broader outcomes are taken into account.

Although there's a desire to be opinionated about where the reader goes immediately after the marketing pitch, a fork (i.e., that "short circuit" I spoke of for those who don't want to go right into a tutorial) might be a good idea.

For example, the current language coming over here is ...

> Now that you've got the basics, continue building your first ASP.NET app with Razor Pages.

... with a button for **Tutorial: Razor Pages**.

However, that could go along the lines of ...

> Now that you've got the basics, continue building your first ASP.NET app with Razor Pages. You can also visit the documentation for an overview of ASP.NET Core and explore its features.

Then, have two buttons: **Tutorial: Razor Pages** and **ASP.NET Core Documentation**

The good news is that at least insofar as the ASP.NET Core landing page (RP tutorial) is concerned, I think we fixed that well. See the last line of the 3rd paragraph at https://docs.microsoft.com/aspnet/core/mvc/razor-pages/?tabs=visual-studio ...

> For an overview of ASP.NET Core, see the Introduction to ASP.NET Core.

That gives them an "out" if they don't like this approach.

On a broader note, I understand that it's difficult for MS to show how sales hinge on docs (or loss of sales/customer retention). I hope that managers figure out new ways to show that docs are critical to profit and loss. I think MS makes far more money (and loses less money) when the docs are good (and marketed). I can't prove it ... it's just a feeling based on speaking to devs over the years.
