### ISSUE TITLE
Make sample download links dead easy to use

### ISSUE THREAD

**Issue by dougbu** [aspnet/Docs#565]
Currently sample links in the documentation point to GitHub source folders. For example http://ef.readthedocs.org/en/latest/getting-started/aspnet5.html links to https://github.com/aspnet/EntityFramework.Docs/tree/master/docs/getting-started/aspnet5/sample. To get from that link to code execution, users must
- Click on the https://github.com/aspnet/EntityFramework.Docs/tree/master/docs/getting-started/aspnet5/sample link.
- Navigate to the root of the https://github.com/aspnet/EntityFramework.Docs repo. There are two links to that location on the page.
- Click on the "Download Zip" link.

Could do this in one step, either linking from the docs to https://github.com/aspnet/EntityFramework.Docs/archive/master.zip and describing the folder of interest or (better) creating smaller Zip files, hosting them somewhere, and linking there.

Could also describe how to clone sample-containing repos separately if that is necessary.

(The links from MVC documentation to sample are often worse: They take users to 404s like https://github.com/aspnet/docs/tree/master/aspnet/testing/unit-testing/sample or the version-neutral https://github.com/aspnet/Home/tree/dev/samples.)

**Comment by jwdavidson** [comment]
Sample files probably need to be hosted elsewhere other than GitHub as it is not possible to easily download project subfolders. If that is not possible then it is necessary to create each sample project as its own project within the aspnet repository so that it will work as designed with GitHub integration (clone or zip files)

**Comment by Rick-Anderson** [comment]
@danroth27  can we at least provide a link to steps to get the source? see https://docs.asp.net/en/latest/fundamentals/logging.html#comment-2444368656

When you click on "View or download sample from GitHub" you can't actually download the sample from there, can you? Somehow you have to figure out you have to go up all the way to the top of the project and download the whole thing.
And then obviously when you open it up in VS 2015 update 1, it gives you a bunch of errors. And that's all it does. It says ToDoApi unavailable so know, instead of learning how to use logger as per the tutorial, you're trying to bug fix the sample code.
What does " run the sample application using the web command" mean? Is this something most readers of this site will know how to do? Just run the web command. Even if you figure out that's probably not the web command but the command "dnx . web" and if you figure out in which windows in Visual Studio to type it into, that is still not enough information to get it to work, is it?

**Comment by Rick-Anderson** [comment]
@danroth27 We need to standardize on this. For the short term I propose we have shared stub on how to get to the sample code.

1. Download the entire repo.
2. Unzip
3. navigate to the folder (look at the URL to figure out the folder).

**Comment by Rick-Anderson** [comment]
@danroth27  @tdykstra  @spboyer  customers are complaining about our current text **View or download sample code** (see [Configuration ](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration)comments)
I propose we change the text to "View sample" "Instructions to download code" and we write a short article telling them how to download the code.

**Comment by tdykstra** [comment]
Sounds good.  I might reword the two links to "View sample code" and "Instructions to download" 

Would be nice if we could provide the path in the instructions doc ... maybe include it as query string in the Instructions link and tell them they can see it in the URL?

**Comment by spboyer** [comment]
The issue here is that the dev doesn't want to download the entire repo to get the code for `Hello World` or `Response Caching`.

We need to get a better structure about how to organize the code samples and perhaps include a zip? 

@danroth27 @billwagner

**Comment by Rick-Anderson** [comment]
GitHub is missing this feature. We identified this problem 2 years ago on Azure docs.

**Comment by Rick-Anderson** [comment]
@mairaw  @tdykstra  TLDR:
The problem: We tell customers to download the sample. We provide a link to the sample, but you can't download from the sample link. You need to figure out:

1. Navigate to repro.
2. Download the entire repro (and probably unzip)
3. navigate to the sample

ACOM had re-usable sections - How did ACOM migrate without shared/included sections. That's what we need here.  Should we request this feature? Until it comes, we need one document explaining the process. That doc should probably live in the .NET repo.

**Comment by jwdavidson** [comment]
There is an extension for the Chrome Browser called GitHub Plus by V
Malhotra
https://chrome.google.com/webstore/detail/github-plus/anlikcnbgdeidpacdbdljnabclhahhmd?hl=en-US
that enables single file downloads with certain characteristics. This shows
that there is a possibility to do this in github

**Comment by mairaw** [comment]
I believe @dend has already a feature request for this and @spboyer was also looking at some options. It's a big ask from customers. 
I know nothing about ACOM so I can't comment on that.

Documenting the process on .NET repo is ok for now.

**Comment by Rick-Anderson** [comment]
moved to https://github.com/dotnet/docs/issues/1644
