### ISSUE TITLE
Publishing to IIS - needs link to •Installing ASP.NET 5 On Windows

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#571]
Add https://docs.asp.net/en/latest/getting-started/installing-on-windows.html to the start of the instructions.

**Comment by OndrejValenta** [comment]
I actually create new issue to move installation part of Publishing to IIS to Installing ASP.NET 5 on Windows. That would be more consistent I'd say and also more convenient for system administrators, which are probably going to be the ones installing and preparing environments.

**Comment by Rick-Anderson** [comment]
@OndrejValenta you don't need to install ASP.NET on the server to run asp.net app.

**Comment by OndrejValenta** [comment]
Oh, really? I didn't know that.. So because asp.net 5 is using DNX there is no need to install anything else on server than just DNVM, DNX and HttpPlatformHandler, right? I see your point now, but I also think there should be an article explaining the situation, because the system administrators I know are used to installing software through installers, to configure ASP.NET environment from IIS and especially to ask questions like "what are we doing?" and "why is it done this way?". The plain and simple installation guide won't be enough in my opinion.

**Comment by Rick-Anderson** [comment]
All the server needs is Install the HTTP Platform Handler
