### ISSUE TITLE
"Minimum module configuration" for IIS + ANCM caused confusing for perf test

### ISSUE THREAD

**Issue by bangbingsyb** [aspnet/Docs#5844]
https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/iis/modules.md

Looks like the "Minimum module configuration" in this doc caused a lot of confusion among users - while it is the right minimum requirement to make ASP.NET core app work, people think it's the fastest configuration and use it in all sorts of perf tests:

aspnet/IISIntegration#747
aspnet/Performance#186

I think it might worth to make some clarifications in this doc.

**Comment by guardrex** [comment]
Thanks @bangbingsyb ... btw -- no need to cross-post so many times. We see it. :wink: :smile:

**Comment by guardrex** [comment]
Thanks for pointing this out @bandbingsyb. I agree we should point it out. I'd like to even *steal* :smile: some of your language for the note on your other comment.

@shirhatti We have two options here:
* Add a couple of lines under our current content; because technically speaking, the module is still not strictly required.
* Go ahead and add it to the recommended minimum module configuration, making our advice never to run without it. I would still state that it isn't strictly required.

**Comment by bangbingsyb** [comment]
Sorry for spamming multiple discussion on the same topic - was used to StackOverflow and ServerFault where copy & paste the same comment to similar problems is often needed otherwise the right people might not see it 😄.  Sure, feel free to use the explanation I put in the comment.

**Comment by guardrex** [comment]
Thanks ... no worries on the posting. On second thought, it's just as well that you DID post over on the perf issue because they will need to see that when they setup their perf tests.

Thanks for allowing the use of your language for this. Let's confer with @shirhatti (and perhaps @Tratcher will weigh in) on how best to handle it according to those two approaches that I laid out above :point_up:.

**Comment by Tratcher** [comment]
@pan-wang @jkotalik

**Comment by guardrex** [comment]
*Last call for comments.* I'm going to need to 🥊 knock this out 🥊 soon. I want to square this away on this sprint.

Current plan: Add a few lines at the bottom of the section surfacing the info. I'll *steal* (with permission, thanks @bangbingsyb) a bit of the good language that @bangbingsyb supplied for the note.

**Comment by pan-wang** [comment]
@guardrex  I am not sure what does ".NET Core Active" mean.
I know ASP.NET Core offers alternative solution/feature for some iis modules, however, it is very hard to write a simple document giving recommendation on yes or no. A lot of time, it really depends on user's application and requirement. For instance, IIS HttpCacheModule. If user turns this feature on, it will save the request to the kestrel and have better performance.  Also, for ISAPI and ISAPI Filter, I am sure what the similar feature is provided by ASP.NET Core and why  they are marked as active. Unless user specifically configure an IIS modue/feature, otherwise, even the module is in the pipeline, the perf impact is ignorable based on previous perf test.
Managed  modules belong to ASP.NET not IIS.

**Comment by guardrex** [comment]
@pan-wang 

> I am not sure what does ".NET Core Active" mean.

It was an attempt at the time to indicate which modules are functional with ASP.NET Core apps.

I agree with everything else you said. This topic could perhaps have more guidance in the future. What I was trying to do was give developers a clear indication of which modules work and which ones don't work with ASP.NET Core ... and then to also have the alternatives there. Before this topic was put up, devs had no idea which modules worked, and they were asking from time-to-time about it in chat.

WRT this issue ... I'm just going to add a few lines at the bottom stating something similar to what @bangbingsyb said ... something along the lines of ...

> The UriCacheModule allows IIS to cache website configuration at the URL level. Without this module, IIS must read and parse configuration for every request, even when the same URL is repeatedly requested. Parsing the configuration every request results in a significant performance penalty. Although the UriCacheModule isn't strictly required for a hosted ASP.NET Core app to run, we recommend that the module be enabled for ASP.NET Core deployments.

... I just rattled that off with the help of @bangbingsyb's text. I'll get final draft language in on the PR.

> IIS HttpCacheModule. If user turns this feature on, it will save the request to the kestrel and have better performance.

Should I include another note recommending that the HttpCacheModule also be used in a minimal module configuration? ... similar to what I have above.
