### ISSUE TITLE
Security: Add docs for using Claims/ Cookie Middleware

### ISSUE THREAD

**Issue by rustd** [aspnet/Docs#589]
Do this without ASP.NET Identity so we can teach users the basics of Claims and Cookie middleware

**Comment by danroth27** [comment]
@pranavkm What scenario are we trying to help users accomplish here? Seems like https://github.com/aspnet/Docs/issues/590 would cover this sufficiently.

**Comment by pranavkm** [comment]
Wrong @pranavkm

**Comment by danroth27** [comment]
Sample of what this should cover: https://github.com/aspnet/Security/blob/dev/samples/CookieSample/Startup.cs

**Comment by isaac2004** [comment]
@danroth27 @Rick-Anderson so the goal here is to show an example of Claims and Cookie middleware without Identity for ASP.NET Core? Should this section be added [here](https://docs.microsoft.com/en-us/aspnet/core/security/cookie-sharing). Otherwise, with some guidance I can take a look at this issue.

**Comment by danroth27** [comment]
@blowdart Do you see any value in documenting this? Should we just close this issue?

**Comment by blowdart** [comment]
Close it, we have https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?tabs=aspnetcore2x
