### ISSUE TITLE
Add doc section:Enable using a Cookie Session Store from DI

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#5922]
From https://github.com/aspnet/Security/pull/1719

@HaoK

we should have an explicit section recommending this pattern of how to configure options instances with things from DI in this doc maybe? https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options

```
public class UseSomethingFromDI : IConfigureNamedOptions/IConfigureOptions<YourOptions> {
       public CookieConfig(ISomethingFromDI thing) => _thing = thing;
       public void Configure([string name,] YourOptions o) { o.Thing = thing; }
   }
   services.AddTransient<IConfigureOptions<YourOptions>, UseSomethingFromDI>();
```

**Comment by HaoK** [comment]
We can also demonstrate a new in 2.1 API ConfigureOptions here as well maybe:

`services.ConfigureOptions<UseSomethingFromDI>` instead of `services.AddTransient<IConfigureOptions<YourOptions>, UseSomethingFromDI>();`, this uses reflection to basically do the same thing and also lets UseSomethingFromDI configure multiple option types if desired.

**Comment by HaoK** [comment]
Maybe this should go into a separate bug, but another good 2.1 options feature to doc eventually is the new `IOptionsBuilder` and related overloads, see https://github.com/aspnet/Security/issues/1718#issuecomment-380204790 its related to this general idea of being able to more easily configure options with things from DI

**Comment by Rick-Anderson** [comment]
`IOptionsBuilder` was documented [here](https://github.com/aspnet/Docs/pull/9456/files)

Moved to #10392
