### ISSUE TITLE
Add Microsoft.AspNetCore.App to dotnet docs repo

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#5937]
Update the [Metapackages](https://docs.microsoft.com/en-us/dotnet/core/packages#metapackages) sections to include  Microsoft.AspNetCore.App

**Comment by guardrex** [comment]
We may need to move a blurb from the Kestrel topic over here. It pertains to the reasoning behind having to add an explicit package reference to the Libuv transport package to 2.1 apps that use the `App` package to avoid a breaking change for 2.1. See the discussion on #6184. Once it's over here, we can link it in the Kestrel topic instead of maintaining the details there. cc/ @natemcmaster

**Comment by Rick-Anderson** [comment]
This has been updated in the donet docs repo
