### ISSUE TITLE
Hosting .NET Core app as IIS Sub Application

### ISSUE THREAD

**Issue by terndrup** [aspnet/Docs#6027]
Hi all,

i'm trying to host an .NET Core web application as a sub application under the IIS Default Website and it is behaving very strangely. What I'm looking to do is something like:

- Default IIS Website
  I- DotNetCoreApp (Converted to Application in IIS)

I have converted the .NET Core app to an application and I have created an AppPool with "No Managed Code" and assigned it to it. It all seems fine but when I browse to my .NET Core app it fails to load some static content. Specifically, it seems to serve some content such as the favicon and robots.txt from the http://localhost/DotNetCoreApp/public/ root as expected, but requests to JS files and stylesheets are sent directly to http://localhost/js/myfile.js and http://localhost/css/mystyle.css and they are served correctly but I would expect them to have the DotNetCoreApp prefix as well.

Finally, i have a JS webapplication that is bundled with WebPack in /public/dist/main.<hash>.js which the Home Controller places into the template but unlike the others, the http://localhost/dist/main.<hash>,js does not get served and the /DotNetCoreApp/ is not auto-prefixed.

Also my application does not realise it is in a virtual web root, any URL links to "/mypage" are requesting http://localhost/mypage isntead of http://localhost/DotNetCoreApp/mypage as I would expect.

My simple webconfig file is:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="dotnet" arguments=".\MyDotNetCoreApp.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="false" />
  </system.webServer>
</configuration>
```
and in my Startup.cs I'm using:

```cs
 public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory factory)
        {
            factory.AddConsole(Configuration.GetSection("Logging"));
            factory.AddDebug();

            app.UseStaticFiles();
            app.UseMvc(routes =>
            {
                routes.MapRoute("default", "{*url}", new { controller = "Home", action = "Index" });
            });
        }

        public static void Main()
        {
            Logs.initialize();
            var cwd = Directory.GetCurrentDirectory();
            var web = Path.GetFileName(cwd) == "server" ? "../public" : "public";

            var host = new WebHostBuilder()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseWebRoot(web)
                .UseKestrel()
                .UseIISIntegration()
                .UseStartup<Startup>()
                .Build();

            host.Run();
        }
```

Any help with this would be GREATLY appreciated.. It's doing my head in...

**Comment by guardrex** [comment]
@terndrup By "virtual web root," do you mean "IIS virtual directory"? If so, IIS vdirs aren't supported with ASP.NET Core, and that might explain why you're having path-related issues.

**Comment by terndrup** [comment]
@guardrex thanks for your reply. What I meant was that all relative paths are being rooted to the parent at http://localhost/ rather than my "web root" at http://localhost/DotNetCoreApp . Sorry if my terminology is off, i'm new to this whole IIS thing :)

I don't think I'm using a Vdir as I converted my .NET Core app directory to an Application in IIS. Thanks!

**Comment by terndrup** [comment]
Thank you for your elaborate reply! So, I cannot honestly say that I understand why, but the following seems to make my application work as I expect:

```cs
           app.UsePathBase("/DotNetCoreApp");

            app.Use((context, next) =>
            {
                context.Request.PathBase = "/DotNetCoreApp";
                return next();
            });
```

I would expect these two things to do much the same thing and therefore be mutually exclusive, but so far I have not gotten it to work with having just one of them. When I have only one of them in place, not all links are appended properly. Both of them there seems to cover all my requests.

You were right on point with the leading "/" on most of my applications URLs. I was under the impression that Kestrel would still be able to map that to my subdirectory but I was able to fix that by appending /DotNetCoreApp/ to all my static HTML URLs.

The Client side was a different matter.. since I had a self-contained React application with its own routing in place, any URL with "/" in front would go straight to the localhost root (this is not a .Net Core issue, I guess that's just the browser more than anything). For now, I have fixed that by outputting the Kestrel assigned basepath (i.e. "DotNetCoreApp") as a global JS variable through my .NET Core Controller, and then my frontend picks that up and appends all requests with it.

This approach **seems to work** although it may not win many coding or infrastructure awards, so far it's the only way I have gotten it to work. Further suggestions are very welcome!

As for documentation, it would be great if we could elaborate some of the documentation and/or guides for some of the Sub App related methods such as app.UsePathBase and host.UseWebRoot vs host.ContentRoot etc a bit . I'm happy to help with the limited knowledge I have!

**Comment by guardrex** [comment]
> You were right on point with the leading "/" on most of my applications URLs. I was under the impression that Kestrel would still be able to map that to my subdirectory but I was able to fix that by appending /DotNetCoreApp/ to all my static HTML URLs.

Yeah ... I had a feel'in it might be like that. I don't see it too much in my own bits because I rely so heavily on the Azure CDN to serve static assets and haven't maintained many sub apps (actually, I got rid of several sub apps ~13 years ago at my org and never looked back! lol), but it makes sense from the browser's perspective.

We recently (less than a month ago) put up a topic that talks about [PathBase Middleware](https://docs.microsoft.com/aspnet/core/host-and-deploy/proxy-load-balancer#deal-with-path-base-and-proxies-that-change-the-request-path). I'd like to link that better generally. That probably means not just linking it to the sub apps section of the IIS topic but also checking to see if it should be linked in other spots where link generation and routing are discussed.

Ugh ... I realize looking at the scenario here how hard it is to find the critical piece of info. A bit of what you ran into here is in that section :point_up: where `PathBase` is described with the `app.Use` middleware ... it says ...

> ... fix redirects and links by setting the request's PathBase property ...

... buried in one line ... of one section ... in one (new) topic ... in a large doc set. Welcome to software engineering in 2018! 😅 *Yikes!*

> This approach seems to work although it may not win many coding or infrastructure awards, so far it's the only way I have gotten it to work. Further suggestions are very welcome!

I don't have much experience with that scenario, so that sounds good to me. However, *I might be having more of that experience SOON.* I've been getting into [Blazor](http://blazor.net), and Blazor apps can be hosted in a client-server arrangement from an ASP.NET Core app. I'm just learning and understanding more now about the trials and tribulations of SPA client-side routing and serving SPAs. :smile:

> elaborate some of the documentation ... Sub App ... app.UsePathBase and host.UseWebRoot vs host.ContentRoot

One thing for sure, I think a link to our new proxy coverage (PathBase Middleware and `PathBase`) should be added to the Hosting on IIS sub app section. You may have found out faster about these if they were linked better. They aren't described anywhere else in the docs. Otherwise, the [web root](https://docs.microsoft.com/aspnet/core/fundamentals#web-root) and [content root](https://docs.microsoft.com/aspnet/core/fundamentals#content-root) are described elsewhere, and that also is probably good to link in the sub app section given that sub apps present special challenges for linking and routing static assets.

Let's use this issue to track the work. Just a note tho ... I'm 🏃😵 *crazy busy at the moment* 😵🏃 :smile: ... it will take a few weeks to clear the high priority work. Then, I'll have some time to work on this. 😅

> I would expect these two things to do much the same thing and therefore be mutually exclusive, but so far I have not gotten it to work with having just one of them. When I have only one of them in place, not all links are appended properly. Both of them there seems to cover all my requests.

... that's a good point for further thought and possible expansion in the new proxy/LB topic. PathBase Middleware is about removing a URL segment before the app sees the request URL. `PathBase` is about a trimmed path hitting the app, where you need the app to take that segment into consideration when forming links and redirects. If you have further ideas about the language used in [that section](https://docs.microsoft.com/aspnet/core/host-and-deploy/proxy-load-balancer#deal-with-path-base-and-proxies-that-change-the-request-path), please post your ideas here, and I'll take your input into account when I look closer at that section's language.

If you find anything strange that looks like a bug, PathBase Middleware is over in [Microsoft.AspNetCore.Http.Abstractions](https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http.Abstractions/Extensions/UsePathBaseMiddleware.cs), but they don't want issues for it opened there. They're triaging issues for it in the [Home repo issues](https://github.com/aspnet/Home/issues). If you open an issue, you can ping `@JunTaoLuo`, as I think he [wrote that middleware](https://github.com/aspnet/HttpAbstractions/pull/689).

**Comment by smartprogrammer93** [comment]
Any news on this?

**Comment by guardrex** [comment]
@terndrup Ok ... I'm up to this issue now. Things are looking good.

I think your scenario was a bit more complex than the standard subapp case because I recall that you had to use the PathBase Middleware and set `Request.PathBase`.

The good news is that URLs to MVC/RP endpoints are created properly by routing without taking any special steps (at least when the subapp is an ASP.NET Core app using the latest bits, 2.2 prerelease). I think you were ok with this aspect, too, in your scenario.

As you point out in your OP, the static file assets can misbehave depending on how they're referenced. 

If a subapp uses relative links (e.g., `src="/image.png"`), it all ends up with a lots of tears :cry:. I think you saw this: Using a plain relative link (`src="/image.png"`) won't work. The link is rendered that way, so the parent app's Static File Middleware tries to handle requests for the asset and serve it from the parent app's webroot.

The answer is to use the tilde (`src="~/image.png"`). We currently describe the tilde as "pointing to the webroot," which doesn't quite do it justice. I'm thinking about elaborating on it a bit in the subapp section of the IIS topic.

When the tilde is encountered, the pathbase is added to an asset's link. For example if a subapp exists at `/subapp`, an image within the subapp at `src="~/image.png"` is rendered at `src="/subapp/image.png"`. 

I have several updates to make to the content:

* The proxy/LB topic should be linked. I'll probably link it *generically* by saying that in some scenarios path segments must be removed and/or applied and to see that topic for more info.
* I see one 🐞 *bug* 🐞 in the 2.2 coverage that I need to fix: Now that we aren't inheriting the IIS handler, that section in the *web.config* file should remain in the subapp's *web.config* file.
* I don't remark on creating a separate app pool for the subapp.
* I don't remark on converting the folder in the parent app into an app in the IIS Manager. The topic shouldn't rely on prior knowledge on this point.
* Lastly, I'll call out that the tilde should be used in the subapp for all static assets to get the paths to these assets rendered correctly.

Thanks again for opening this issue. I'll ping u on the PR to take a look.

**Comment by antoniobeltran** [comment]
Has there been some smooth resolution for this? You would think there would have been a straight forward solution set by now? trying to install asp.net core as a subapp and having that issue where files are returning 404 because it's hitting localhost/filename instead of localhost/subapp/filename... Is there a new method to resolve this rather than updating a bunch of paths?

**Comment by antoniobeltran** [comment]
maybe this is a solution? https://docs.microsoft.com/en-us/iis/extensions/url-rewrite-module/url-rewrite-module-video-walkthrough

**Comment by antoniobeltran** [comment]
ok.. solution:

edit: ClientApp\package.json

add:

  "homepage": "http://localhost/subapp",

done

**Comment by profkaygee** [comment]
This file does not exist in .net core 3.1 applications.

**Comment by alexandis** [comment]
I have the same problem. I thought probably to use **UseWebRoot** and **UseContentRoot** calls within **ConfigureWebHostDefaults**, but it does not work. It is all very weird: it needs to be a simple way to tell the app what is a ROOT folder for it instead of dragging folder name everywhere.

**Comment by alexandis** [comment]
> maybe this is a solution? https://docs.microsoft.com/en-us/iis/extensions/url-rewrite-module/url-rewrite-module-video-walkthrough
No good to use rewrite where it needs to be possible just to indicate proper ROOT :)

**Comment by alexandis** [comment]
> This file does not exist in .net core 3.1 applications.

No good to use rewrite where it needs to be possible just to indicate proper ROOT :)

**Comment by alexandis** [comment]
> maybe this is a solution? https://docs.microsoft.com/en-us/iis/extensions/url-rewrite-module/url-rewrite-module-video-walkthrough

No good to use rewrite where it needs to be possible just to indicate proper ROOT :)

**Comment by Tratcher** [comment]
@antoniobeltran @alexandis this is a very old issue that has been closed for some time. Please open a new issue with the details for your scenarios.
