### ISSUE TITLE
Discussion: Download and modify sample or step-by-step instructions

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#6098]
Use this issue to leave your comments on articles that use download/modify the sample compared to step-by-step instructions to build the sample. For example, [Create an ASP.NET Core app with user data protected by authorization](https://docs.microsoft.com/aspnet/core/security/authorization/secure-data) recommends you download starter app. You can also download the completed app and follow along.

Would you prefer less step-by step instructions on building a sample and more focus on:

* The scenario the sample code solves.
* More explanation of the APIs used.
* Best practices.

Leave a link to the tutorial you're commenting on.

**Comment by guardrex** [comment]
This issue might be for consumers only, but I just wanted to drop in some recent feedback from a reader that pertains to this subject about the RP tutorial.

A dev told me that they prefer that each part of the series (in this case just the File Uploads part) started with a sample that matched the beginning of that part. They didn't want to go all the way back to the first part of the tutorial and build the entire RP tutorial sample from scratch just to get up to the File Uploads part. They didn't want to see the 100% completed sample (with File Uploads bits) at the start of the File Uploads part either. They wanted to start the sample without File Uploads and then only add File Uploads.

**Comment by user135711** [comment]
Here were my results: The class library template is not available in VS15.7 preview after installing sdk 2.1.300-Preview2 or 2.1.0-preview2-final so the only option is to manually download the files from [github](https://github.com/aspnet/templating/tree/dev/src/Microsoft.DotNet.Web.ProjectTemplates/content/RazorClassLibrary-CSharp) until someone adds the nuget package reference. The downloaded project references `<PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.1.0-rc1-30661" />` that only exists in myget so I had to add `<add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />` to the NuGet.Config and the same url to the Tools->Nuget Package Manager Settings->package sources to get the dependencies to restore and the project to compile. I couldn't get the project to run because a compatible runtime was not found that matched the version used by the sdk for Microsoft.AspNetCore.App I couldn't find an exact runtime installation that would match any of the available AspNetCore.App version 2.1.0* and so suspect you may have a nightly build of the runtime. The prereleases of semver are exact so even if the ~or ^ higher version is availabe, it won't satisfy a pre-release.
