### ISSUE TITLE
doc:  Map asp.net core 2.0 Identity to existing DB schema 

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#6107]
From https://github.com/aspnet/Identity/issues/1768

@Misanthrop87 can you supply the draft text and I'll work on getting it updated.

Why did you use  https://www.c-sharpcorner.com/article/crud-operation-with-asp-net-core-mvc-web-app-using-ado-net/ and not a combination of [ASP.NET Core MVC with EF Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/?view=aspnetcore-2.1) (or better [RP with EF](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-2.1) and for authz https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data

EF is our recommended data access

**Comment by Misanthrop87** [comment]
I'm not sure if this heading represents my request for better documentation of Windows Authentication (Transform Active Directory Groups into Identity roles). 
I agree that the part in the heading could be also very useful, however I cannot help really much because in the end I chose to use the existing Active Directory. And here my suggestion was to point out in the documentation that existing AD groups can be directly used as roles in the asp.net core 2.0 Identity / Authorisation module.
