### ISSUE TITLE
ASP.NET Core MVC versus Razor pages

### ISSUE THREAD

**Issue by robertparis** [aspnet/Docs#6138]
Microsoft said: If you choose this tutorial over the Razor Pages version, please leave a note explaining why.

Why?
The Model-View-Controller (MVC) pattern helps make your web APIs and web apps testable.

Seems like a simple decision.

**Comment by guardrex** [comment]
Thanks for the feedback @robertparis. Just want to mention in passing that we've had a topic pertaining to [testing RP apps (unit + integration)](https://docs.microsoft.com/aspnet/core/testing/razor-pages-testing) since early December. It's generally just as easy to set up and test using either dev scenario.

With the new testing package (in 2.1 preview now), things will be even a bit better for 2.1. That work is under review on https://github.com/aspnet/Docs/pull/4832 in case you wanted to take an advance look. 

Note that when 2.1 is released, we'll cut the integration testing section from the RP testing topic. The updated integration testing topic (on that PR) focuses on RP; and the integration testing approaches are almost same between MVC and RP. We should 🤞 only need the one integration topic going forward.

**Comment by Rick-Anderson** [comment]
Dup of #3889
