### ISSUE TITLE
Diagnostics

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#62]
ASP.NET 5->Runtime->Diagnostics
- Configuring an error handling page
- Using the error page during development
- Runtime info page
- Welcome page
- Using AppInsights

**Comment by ardalis** [comment]
The environment variable and other parts of ErrorPage are still TODO in the source: https://github.com/aspnet/Diagnostics/blob/dev/src/Microsoft.AspNet.Diagnostics/ErrorPageExtensions.cs - line 43, also the ErrorPage view has commented out the Cookies and Environment tabs.

@danroth27 
Should I just note that they're not fully baked yet and otherwise work around such things?

**Comment by danroth27** [comment]
@davidfowl @glennc @muratg Could you guys please comment on what we should document for the ErrorPage at this point?

**Comment by ardalis** [comment]
I'm adding in comments regarding the incomplete functionality.
Since AppInsights requires significant changes to Startup.cs and I would like to keep the Diagnostics demo's sample project simple, I'd prefer to pull it into its own separate article, in which case this one is ready to be PR'd.

**Comment by muratg** [comment]
https://github.com/aspnet/Diagnostics/issues/130

**Comment by danroth27** [comment]
I agree on putting AppInsights in a separate article.

**Comment by muratg** [comment]
See my comment on aspnet/Diagnostics#130. We decided to keep the current behavior, so @ardalis's doc will be valid in the future too.
