### ISSUE TITLE
Angular 6.0.0

### ISSUE THREAD

**Issue by dballemo** [aspnet/Docs#6208]
How to update the net core 2.0 template with Angular 6.0.0 and the new structure (angular.json)? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c047bdd1-1464-4398-92c6-65ab88093525
* Version Independent ID: 1ea83a29-79de-272f-fea0-fb6b3ea1a444
* Content: [Use the Angular project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/spa/angular?view=aspnetcore-2.0&tabs=visual-studio)
* Content Source: [aspnetcore/spa/angular.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/spa/angular.md)
* Service: **unspecified**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **scaddie**

**Comment by scottaddie** [comment]
@dballemo Since this is a project template issue rather than a docs issue, I'm closing this. Please see the following issue, which is already tracking this request: https://github.com/aspnet/JavaScriptServices/issues/1637. I recommend giving the issue a "thumbs up" to help the engineering team gauge interest and plan accordingly.
