### ISSUE TITLE
Server-side rendering

### ISSUE THREAD

**Issue by vladkolodka** [aspnet/Docs#6222]
It looks like that section "Server-side rendering" is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3154dec-545a-c749-76ac-1f4581c2f922
* Version Independent ID: cd33922a-0feb-2a37-4e8e-6d7856617a31
* Content: [Use the React project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/spa/react?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/spa/react.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/spa/react.md)
* Service: **unspecified**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **scaddie**

**Comment by ryanbrandenburg** [comment]
Per previous conversations with @SteveSandersonMS my understanding is that this is an intentional omission. Our goal with the "SPA" templates has been parity with their versions of "dotnet new", and "create-react-app" does not support SSR. Would it be helpful to include a little info dialog which calls out SSR as a non-goal for us? Or would that be too inside-baseball and we should just leave it as is?

**Comment by SteveSandersonMS** [comment]
I agree with your assessment, @ryanbrandenburg.

Yes, I think it would be reasonable to add a subheading to the React template docs stating explicitly that SSR is not an intended feature simply because it's not part of CRA, just so we can point people to it whenever they file this issue.
