### ISSUE TITLE
Update  IHostingStartup article to show Identity RCL

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#6225]
Once "Scaffold Identity in ASP.NET Core projects" is complete, point out in the intro it uses `IHostingStartup` 

Add `Scaffold Identity` to TOC 

Consider getting `IHostingStartup` in the title.  Can't we come up with a better title for the article?

**Comment by guardrex** [comment]
It was challenging to name that topic. I think we can do better. Is it ok if I float some alternative titles tomorrow?

**Comment by guardrex** [comment]
Here's one that's a little easier to grasp because it drops the "platform-specific configuration" bit, which came from the API description of [IHostingStartup](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.hosting.ihostingstartup?view=aspnetcore-2.0) ...

*Enhance an app from an external assembly in ASP.NET Core*

... and btw ... the "enhance an app" bit is there to avoid the phrase *Add features to an app*.

**Comment by guardrex** [comment]
Another thing occurs to me ... This is in *Host and deploy*; but upon reflection, I think the topic should moved to *Configuration*. We already have a node there, so it's an easy move.

**Comment by guardrex** [comment]
[Move and rename IHostingStartup topic (\#6229)](https://github.com/aspnet/Docs/pull/6229)
