### ISSUE TITLE
clarify purpose of BuildWebHost

### ISSUE THREAD

**Issue by SimonCropp** [aspnet/Docs#6234]
here https://docs.microsoft.com/en-us/aspnet/core/fundamentals/?view=aspnetcore-2.1&tabs=aspnetcore2x

we have 

```
    public class Program
    {
        public static void Main(string[] args)
        {
            BuildWebHost(args).Run();
        }

        public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .Build();
    }
```

why isnt it 

```
    public class Program
    {
        public static void Main(string[] args)
        {
             WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .Build().Run();
        }
    }
```

i.e. what is the purpose of the `BuildWebHost`?

**Comment by rachelappel** [comment]
Hi @SimonCropp. Great question! They both do basically the same thing, but the syntax has been changed for simplicity in Core 2.1. The doc shows the older way because it hasn't been upgraded to 2.1 RC1 just yet.

This blog post may shed a bit more light on some of the details of the builder. 
https://andrewlock.net/exploring-program-and-startup-in-asp-net-core-2-preview1-2/

**Comment by rachelappel** [comment]
@SimonCropp  Quite possibly, but not being the original author I don't know what the requirements were for the author at the time of writing to say why it isn't in there. Sometimes items don't make it (or do) into docs because of some other reason that sounded good at the time.
While we do sweep the content to make updates, unfortunately we can't get to all of them in a manner that is timely for everyone (since everyone has different needs).

We greatly appreciate these opened issues as well as any help in adding content that is missing. If you are interested in contributing, that would be awesome! Just create a PR and add what content you think would help. Your community contributions are helpful and matter! All of the docs team is here to back you up. Just give a shout! No pressure though and we can incorporate your feedback from issues in the next update round.
