### ISSUE TITLE
Some of the methods appear not to exist

### ISSUE THREAD

**Issue by arame3333** [aspnet/Docs#6267]
I am finding that the methods AddHttpsRedirection and UseHttpsRedirection do not exist. My intellisense is not indicating which libraries they belong to.
I assume I have to specify a library in a using statement and maybe install one via nuget, but I am not getting any clues from where.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ddfb2f-5dea-5e31-2a27-02a4dc16104c
* Version Independent ID: 12ca0b9a-2638-a4ce-c45f-d4579c83dafb
* Content: [Enforce HTTPS in an ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/enforcing-ssl.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/enforcing-ssl.md)
* Service: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@arame3333 You're aware that they're 2.1 pre-release (RC1 as of yesterday), correct? Just checking, since there's some additional config required to use pre-release bits that devs sometimes aren't aware of.

They live in the `Microsoft.AspNetCore.HttpsPolicy` package, which is included in the `Microsoft.AspNetCore.App` metapackage. However, the extension methods should be available without a `using` statement in `Startup.cs`. Check out the sample for the topic here :point_right: https://github.com/aspnet/Docs/tree/master/aspnetcore/security/enforcing-ssl/sample

@Rick-Anderson might be planning to add the sample link to the topic at a later date (when 2.1 RTMs and the sample is updated for 2.1 RTM).

**Comment by Rick-Anderson** [comment]
@arame3333  if you set the version selector to 2.0 or lower, they don't show up.

![image](https://user-images.githubusercontent.com/3605364/39778377-d65fec40-52a1-11e8-843f-cb56ea468804.png)

**Comment by Rick-Anderson** [comment]
@arame3333  thanks for pointing this out. I created #6287 to address this and I'll get it added in the next week. Having links for those APIs should help. I agree it's confusing as it is.

**Comment by Rick-Anderson** [comment]
cc @scottaddie  
This is a problem we should keep in mind as new APIs roll out. I think having the API links will help.

**Comment by guardrex** [comment]
> I assume I have to specify a library in a using statement and maybe install one via nuget

I thought this was an implementation question ... "How do I use these APIs now (in pre-release)?"-type of question. 

@arame3333 Clarify your ask ... Are you trying to use the API in an app, or are you just looking for the API generally in the docs/API browser/Nuget.org?

**Comment by Rick-Anderson** [comment]
@arame3333  they are in the  [Microsoft.AspNetCore.App](https://www.nuget.org/packages/Microsoft.AspNetCore.App) metapackage for ASP.NET Core
