### ISSUE TITLE
Is the Authorize attribute needed in Razor Pages? What about Roles, Claims and Policies?

### ISSUE THREAD

**Issue by Ponant** [aspnet/Docs#6301]
I am pretty much confused as to how Authorization/Authentication would now work in Razor Pages. What if you want to set the equivalent of MVC [Authorize(Policy = "AtLeast21")] in Razor Pages? It seems to me that the docs about Claims, Role-based policies semantics dot not exactly apply in Razor Pages anymore, is that correct? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3a49eaa-a2ee-baac-e614-5e2f7c74072a
* Version Independent ID: 09513dc8-546a-ea10-9f0b-cde361127647
* Content: [Razor Pages authorization conventions in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/razor-pages-authorization?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/authorization/razor-pages-authorization.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authorization/razor-pages-authorization.md)
* Service: **asp.net-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@Ponant The `[Authorize]` filter attribute has been supported since 2.0 in Razor Pages, but note that it works at the page model **class** level: https://docs.microsoft.com/aspnet/core/mvc/razor-pages/filter?view=aspnetcore-2.1&viewFallbackFrom=aspnetcore-2.0#authorize-filter-attribute

There's a line in the [Filters for RP topic](https://docs.microsoft.com/aspnet/core/mvc/razor-pages/filter) at that top that explains ...

> Razor Page filters are similar to ASP.NET Core MVC action filters, except they can't be applied to individual page handler methods.

I looked to see if there was an issue open discussing supporting a scenario where filters could be applied to individual page handler methods, but I don't see one. You can ask the engineers by opening an issue in the MVC repo: https://github.com/aspnet/Mvc/issues. If you do, please cc/ me on it, so I can see what they say.

**Comment by guardrex** [comment]
> better alternative to transcribe [Authorize(Policy="AtLeast21")] in the new Razor Page?

You should be able to put that on a page model class. It will apply the policy to **ALL** handlers for that page.

> AuthorizePage?

Yes, that's right. There's an overload that will allow you to specify a policy ...

https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.pageconventioncollectionextensions.authorizepage?view=aspnetcore-2.1#Microsoft_Extensions_DependencyInjection_PageConventionCollectionExtensions_AuthorizePage_Microsoft_AspNetCore_Mvc_ApplicationModels_PageConventionCollection_System_String_System_String_

Tell you what ... I'm going to add an example of that to the topic. Right now, there's just this one line there. It's a good idea to add a quick example in the text. I'll use this issue to track the work, and I'll get to it within a couple of weeks (we're crazy busy at the moment with 2.1 work).

> what would become `services.AddAuthorization(options => { options.AddPolicy("AtLeast21", policy => policy.Requirements.Add(new MinimumAgeRequirement(21))); });`

AFAIK, yes. That should work. If it doesn't work, ping me back, and I'll take a closer look (it's been a while since I've played with putting a policy on the `AddAuthorization` extension method). However, I think what you show is correct.

**Comment by Ponant** [comment]
@guardrex , ok I will try it out but my question was to be able to go through my code as I am porting things to Razor Pages.

 In the meantime, yes I think I think the docs could be updated, examples are much better than a sentence :) .

I think you could see with @blowdart if there is no need for an update on 
https://docs.microsoft.com/en-us/aspnet/core/security/authorization/claims?view=aspnetcore-2.1
https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-2.1
and also roles and resource-based policies. All these docs use as an example traditional MVC, so dropping a few lines of code of equivalent-or-superior razor page framework **would really help**, or in the worst case some bold statement to explain to the reader that this also applies to Razor Pages but that the code is not shown.

**Comment by blowdart** [comment]
It does sound like there's a doc update needed, either a page for traditional MVC and one for Razor Pages, or mix them into one (which might confuse people)

**Comment by Ponant** [comment]
@blowdart , I learned pretty much all I needed from your single Workshop 2.0, but it was all traditional MVC. The equivalent for RazorPages would just perfect for many people I think. I looked up if you talked about razor pages and security, but nothing so far.

**Comment by blowdart** [comment]
For me that's kind of on purpose for a couple of reasons,

1. More people are using MVC so it reaches more
2. It's easier to demo, because it's attributes, and no hopping back to config to add rules.

**Comment by guardrex** [comment]
> need for an update on ...

> It does sound like there's a doc update needed, either a page for traditional MVC and one for Razor Pages, or mix them into one (which might confuse people)

I'll take a look when I get to this, but the updates for this issue will be for the RP conventions topic. When I see where more work is needed (e.g., Security TOC area), then I'll open one or more new issues for that. That work will probably fall to another author.

I should be able to look at this in a few weeks. Sorry for the delay, but I'm slammed at the moment.

**Comment by Ponant** [comment]
I totally agree with your points @blowdart , at the same time it seems that Razor Pages will be cleaner in the long run. As a side note, let me say that this AddDefaultIdentity really sucks (sorry for the team). Here in Europe GDPR is ruling and you cannot just take an identity library without knowing what is inside. And it is pretty much likely you will have to override it. Scafolding did not help much. And AddIdentity seems an outsider.

**Comment by blowdart** [comment]
Yea, GDPR is painful, we're balancing ease of use, with helping you meet your obligations. 2.1 will see enhancements, around cookies and download/delete

**Comment by Ponant** [comment]
Yes I have seen already 2.1 and I am working on it to port an app from 1.0 that we have been building. That is great that you did this, really. Now, GDPR I know quite a bit about it because I have to, and I can see that I agree with a lot of their requirements. Also, I will bet a beer that you will have a similar thing in the US (see the Facebook discussion a few weeks ago at Congress etc).

Regarding you last paragraph and as far as I can see, my understanding of GDPR and for reading the Azure docs on the matter is that GDPR will be a shared responsibility. So I see two reasons why I think it is better to offer a VS experience project template that reveals most of the code from the outset (as it used to be). The first reason is that, in my opinion, 80 devs out of 100 will likely make changes, even minor but they will have to scaffold, so make life easier for them and they can pack to a lib if they want latter. The second reason is that GDPR is not only about what the db contains, but also how you protect the data. The prime example relevant for this discussion is how you set password policies, how set set sign in. Here the practice is to confirm email prior to entering the website. Another practice that will boom in the future is following the NIST recommendation and anyone who does some math would agree with the, the idea of upper case letters+some non alphanumeric one to create pwds is just ridiculous. It is in general better to set long paraphrases. I assume these things can be changed but my point is that it is less direct with this default UI stuff.
If for instance users complain that you are not checking email upon registration can bring you up a fine. I am happy to help if need be.

**Comment by blowdart** [comment]
There's another balancing act here. GDPR is more than just code, as I know you're aware. But most developers aren't. We can't and won't say "This makes your site GDPR compliant", because that's utterly false. You have to make decisions specifically for your own use case.  Which I can't do automatically.

But this is a conversation that should happen down a pub. With an expensed bar bill :)

**Comment by Ponant** [comment]
Of course you cannot say this, but the picture is that you kind of offer a car whereas they (will) need the spare parts as far as they want to have a public or corporate facing website. Trump will pay for the beer!

**Comment by Rick-Anderson** [comment]
@Ponant have you seen [Create an ASP.NET Core app with user data protected by authorization](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-2.1)

**Comment by Ponant** [comment]
@Rick-Anderson thanks, I remember having seen the old traditional MVC example, so this will help.

**Comment by guardrex** [comment]
@joeruder We recommend ASP.NET Core Identity. It's fully featured and well supported by our documentation and sample apps. The docs kick off the coverage with [Introduction to Identity](https://docs.microsoft.com/aspnet/core/security/authentication/identity).

WRT to your specific questions ...

'Yes' on the template. You'll see that there is app template identity configuration built-in to the `dotnet new` command and templates available in Visual Studio to help you set up and configure ASP.NET Core Identity. See the Security docs for more info, and more info on the `dotnet new` command is over at: https://docs.microsoft.com/dotnet/core/tools/dotnet-new

RE: Assigned passwords ... **Any approach or configuration that has significant risk isn't recommended or supported by MS.** Every practice pertaining to password management that's supported and recommended is covered by the docs. AFAIK none of the supported password management strategies allow the assignment of passwords; however, I'll defer to the security experts here ... and none other than **THE @blowdart 🎯** is listening!

**Comment by blowdart** [comment]
Yes you'd use register as a template, no we wouldn't really recommend it, if only because we don't have password expiration, so you can't force a change on first login

**Comment by pholly** [comment]
@joeruder Use ASP.NET Core Identity like @guardrex mentions. 

To manually create the users: adapt code from the Registration page.

For passwords: Create the users with random passwords. Adapt code from the Account/ForgotPassword page to send users an email with a token in the url that when clicked will take them to the Account/Manage/SetPassword page.
