### ISSUE TITLE
Entity Framework 6 configuration

### ISSUE THREAD

**Issue by damienpontifex** [aspnet/Docs#633]
I have [started working](https://github.com/damienpontifex/Docs/tree/ef6-article) on a new topic for configuring and utilising EF6 in ASP.NET 5 after aspnet/Home#1062 in collaboration with @pgrudzien12 after his article http://bleedingnedge.com/2015/11/01/entity-framework-6-with-asp-net-5/

It covers:
- Connection strings and DI
- Configuration in code of EF6

**Comment by Eilon** [comment]
@rowanmiller

**Comment by rowanmiller** [comment]
Hey,

I took a look at the article and it looks like good info. You should probably call out that migrations commands won't work because xproj does not support loading commands into Package Manager Console (this will change for RTM though).

Happy to do a final review etc. if you send a PR.

~Rowan

**Comment by danroth27** [comment]
@damienpontifex Are you still planning on contributing this article? Sounds like @rowanmiller is happy to review the PR.

**Comment by virshu** [comment]
So, what are the options regarding migrations? I am getting "tables has changed" error, pointing to tutorial on migrations, and that doesn't work...

Frankly, some authoritative guidance on combining ASP.NET 5, MVC 6, and EF6 would be *really* helpful. There are snippets here and there - but I have a team of quite experienced .NET/MVC/EF developers that are pulling their hair out (sigh)

**Comment by pgrudzien12** [comment]
@virshu I have project in advanced phase with EF6 and asp.net 5 and i'm so far happy with solutions i've given on my blog. If you have any specific problems i'm happy to help you. Tweet me if any of the solutions provided does not work for you.

**Comment by virshu** [comment]
Thank you, @pgrudzien12 ! Your blog post (and similar on docs.asp.net) was the most helpful for us to get ASP.NET 5 + EF 6 working together. Still, it felt that solution was very brittle; inability to run migration was just the latest problem. I guess it was the last straw that made us rethink the decision *not* to go with EF7. We have the database from the legacy system; but otherwise the application is quite greenfield. We had significant problems importing EF7 POCO classes. We still have a few problems - but it's pretty clear how to handle them.

So, the bottom line, we made New Year decision to switch to EF7... We'll see how it goes :)
