### ISSUE TITLE
Update all 2.0 samples to use M.A.App, aka Microsoft.AspNetCore.App

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#6382]
This is the master issue.

**Comment by guardrex** [comment]
Recommendation: Use https://github.com/aspnet/Docs/issues/5495 because it has all of the samples listed (e.g., `project.json` samples slipped through the cracks on prior update attempts) and authors won't trip over each other trying to get all of the samples updated. I marked the ones that I'd like to handle, if that's ok. I built most of the ones that I self-assigned.
