### ISSUE TITLE
Expand scope of the Enforce HTTPS article

### ISSUE THREAD

**Issue by shirhatti** [aspnet/Docs#6538]
Our current Enforce HTTPS article isn't sufficient for folks looking to enforce HTTPS on their deployment. While all the content lives in our docs, we don't do a good enough job of cross-linking to relevant content.

Here's my proposed additions to the TOC

- [x] Setting up HTTPS
  - [x] Cross-link to existing server specific guidance on enabling HTTPS
  - [x] Cross-link to the proxy guidance especially around validating forwarded headers **Addressed by #6644.**
  - ALLOWED_HOSTS and HTTPS_PORT need to be set
- [x] Enforcing HTTPS in Azure App Service
  - [x] Antares has a portal experience where you can check a box to enable HTTPS which is what we should guide people towards
- [x] Enforcing HTTPS behind other proxies
- [x] Surface IIS hosting issues in the IIS topic pertaining to use of the middleware when the site isn't configured for HTTPS in IIS. For example, see https://github.com/aspnet/Home/issues/3176.

**Comment by Rick-Anderson** [comment]
Here's my proposed additions to the ~TOC~ article layout

@shirhatti  can you supply the content for **Enforcing HTTPS behind other proxies**? If so, I can prioritize this.

cc @guardrex  - who could probably knock off the link addition pretty quickly.

**Comment by guardrex** [comment]
Sure, but can "pretty quickly" be after my 2.1 issues are resolved? I can do it asap after that.

**Comment by Rick-Anderson** [comment]
@guardrex  I meant to say, after he's done with 2.1, I don't think it will take him long to add those links.

**Comment by guardrex** [comment]
*From @Praveen-Rai on #9052 ...*

This has been missing link in our Hosting section.

Few references :
aspnet/KestrelHttpServer#2902
https://stackoverflow.com/questions/52227372/asp-net-core-application-service-only-listening-to-port-5000-on-ubuntu
https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-16-04

@guardrex I think it's time to add SSL configuration to our documentation. Let'sEncrypt should be a good CA for SSL certificates for our documentation.

Also, below pages will need the details on the same :
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-apache?view=aspnetcore-2.1&tabs=aspnetcore2x
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.1
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.1

**Comment by guardrex** [comment]
@Praveen-Rai

I took a look at these, and here's where I'm at until @shirhatti puts an :eye: on the situation ...

1. aspnet/KestrelHttpServer#2902, specifically the bit on linking Kestrel endpoint config into the Linux topics :point_right: AFAIK, this isn't actionable (*yet* anyway). I discussed this point briefly with @shirhatti on another issue/PR, and my take-away was that only a reverse proxy config is supported and that devs should use the approach laid out in the Linux topics. Namely, HTTPS endpoint config and HTTPS redirection should be handled by the proxy ... not Kestrel. Therefore ... AFAIK ... we wouldn't need to link the Kestrel endpoint config here. @shirhatti will advise further on this. Things may have changed since we last spoke about this.

1. https://stackoverflow.com/questions/52227372/asp-net-core-application-service-only-listening-to-port-5000-on-ubuntu :point_right: Not actionable, since my understanding is that using the dev cert for an endpoint with a deployed app isn't a supported scenario. @shirhatti will advise further.

1. https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-16-04 :point_right: Not actionable unless/until management "picks a winner" here. I personally don't like when they do that. It isn't ... well ... *fair!* :smile: lol (I'm such a *ham!* lol) It's up to them tho. Again, @shirhatti will advise further.

These topics *almost* have what they need for a *draft* of changes requested. I need to look at a few more things before I take the PR off WIP and call for review. We'll definitely patch it up based on engineers and management direction on review and any guidance we get for those items :point_up:.

**Comment by Praveen-Rai** [comment]
@guardrex I believe there's some mis-understanding here. I meant to have detailed steps on obtaining & installing SSL certificates, Configuring Kestrel Endpoints ( along with proxy server ) to use the certificate ( else one might end up with issue similar to aspnet/KestrelHttpServer#2902 ). The other two links are for reference : 

- https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-16-04
This article has detailed steps to obtain and install Let's Encrypt SSL certificate on Ubuntu and configure NGinx to use it.
 
- https://stackoverflow.com/questions/52227372/asp-net-core-application-service-only-listening-to-port-5000-on-ubuntu
This points to the solution i posted for the issue that i faced ( aspnet/KestrelHttpServer#2902 ). It shows how to change the format from PEM to PKCS12 using OpenSSL ( As of now kestrel configuration only supports PKCS12 certificates, i've already raised an issue at [Kestrel Repository](https://github.com/aspnet/KestrelHttpServer/issues/3017) ).

Sorry that was my bad, i just created the issue and added links without adding details.

**Comment by guardrex** [comment]
> detailed steps on obtaining & installing SSL certificates

Unless @shirhatti wants to cover it, we link out for that type of coverage given that we only support reverse proxy (AFAIK). I need his approval before expanding the coverage, and then he should say what we're linking to.

> Configuring Kestrel Endpoints

Not supported for the Linux reverse proxy scenario until @shirhatti tells me otherwise.

> Let's Encrypt

I can't pick any "winners" here. Management has to make that call. I'm just a *little green dinosaur* in a big .NET world, so I defer to management.

> change the format from PEM to PKCS12 using OpenSSL ... configuring Kestrel endpoints to use the certificate

Again, not supported (AFAIK) unless/until @shirhatti tells me otherwise.

I'm not saying 'no' to any of this. It's just not my call. They need to make the call on these. Stand-by ... @shirhatti will come on and let us know.
