### ISSUE TITLE
SQL Errors?

### ISSUE THREAD

**Issue by whyisjacob** [aspnet/Docs#6591]
When I ran `Update-Database` I got the error `A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 50 - Local Database Runtime error occurred. Specified LocalDB instance name is invalid.
)`

How do I fix that? I followed the tutorial to a "T" and still got the error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.0)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Service: **unspecified**
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by rachelappel** [comment]
@whyisjacob Hello and thanks for the question. Check that the connection string in appsettings points to a valid database, and check if using SQL rather than localdb, that port 1433 is bound/open for it (it should be but just in case) @Rick-Anderson may also have some other ideas as to why this would happen, but it's likely from the SQL side of things - meaning that you did follow the example just fine, but something might not have been installed quite right.

**Comment by whyisjacob** [comment]
Thanks for the response @rachelappel I greatly appreciate it. How would be the best way to check that stuff? I'm new on the Windows/Visual Studio platform and not 100% sure where to check for that.

**Comment by Rick-Anderson** [comment]
@whyisjacob that's a common error when you miss a step.
Use localdb, don't change that.

**Comment by Rick-Anderson** [comment]
Create a new Razor Pages web app with individual user accounts. Run the app and register a new user. If that works, compare the code in the two projects.
