### ISSUE TITLE
update for 2.1 : Account confirmation and password recovery in ASP.NET Core

### ISSUE THREAD

**Issue by Alienroid** [aspnet/Docs#6632]
1. AddIdentity should be updated to be AddDefaultIdentity
2. don't need .AddDefaultTokenProviders();
3. needs to add services.AddSingleton<IEmailSender, EmailSender>(); in configservice

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1bea60-d173-f6d2-3559-b147699e295a
* Version Independent ID: 98e7aacb-2a01-d581-9b03-bfef2893163e
* Content: [Account confirmation and password recovery in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-2.1&tabs=aspnetcore2x#debug)
* Content Source: [aspnetcore/security/authentication/accconfirm.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/accconfirm.md)
* Service: **unspecified**
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @Alienroid ... I'll add this to our sample update tracking issue (#5495).

**Comment by davidhenley** [comment]
Has this been updated? I cannot figure out how to override EmailSender using 2.1

**Comment by bcisnero** [comment]
The instructions and the snapshot for creating a web project using visual studio for ASP.NET Core 1.x are wrong because is selecting  .NET Core 2.0

**Comment by bcisnero** [comment]
Sorry if this is a dumb question, but how do you guys manage the sample apps when making changes because of version change? Do you create a complete sample app? if so, how do you ensure that will be attached to the right doc? I want to take care of this changes, but I'm completely sure about the strategy

**Comment by guardrex** [comment]
> how do you guys manage the sample apps when making changes because of version change?

Each sample app is versioned to the latest release (at the time the sample is updated) for 1.x or 2.x (and 3.x in the future).

> Do you create a complete sample app?

When a new major version releases, yes, we create a new physical sample. However, that physical sample might be the previous sample version just updated for the new release.

> How do you ensure that will be attached to the right doc?

We reference the "samples" folder inside a folder named after the topic folder in GitHub. See some of our topics in GH to see how they're laid out, but best for you to look at linked PRs on #5495. We have inconsistencies in the repo generally. :cry: I'm working to iron this out now as I address these and get them all on the same page for folder naming.

> I want to take care of this changes, but I'm completely sure about the strategy.

It's complicated 😅 ... but doable. Some of these are MVC apps or even console apps, and we're moving them to Razor Pages. Sometimes the work to convert to Razor Pages pushed off to a new issue. Some of these are even 1.x-era xproj/project.json-based samples. Today, I'm doing both a 2.1 update and a shiny new Razor Pages app for the app/session state topic.

If you look at #5495 and study the linked PRs on the ones I've already done, you'll see the patterns. Feel free to ask if you have any questions.

This particular topic, https://docs.microsoft.com/aspnet/core/security/authentication/accconfirm, could get a little thorny because the sample is supplying 1.1 code only ... and it's MVC ... not Razor Pages like we'd prefer it to be.

The intention of the topic is that the dev will walk-through and build a new app from scratch. If we want to retain the 1.x steps here (unlikely), then we'd isolate these 1.x code blocks from the new 2.1 code blocks using "moniker-ranges." If we just drop the 1.x experience (likely), then it will be easier in that the whole sample can just be converted to 2.1 and the sample code blocks will only show 2.1 code from the one sample. Either way tho ... it really should go to a Razor Pages experience start-to-finish.

@Rick-Anderson Do you know if you want to retain the 1.1 bits from the *Account confirmation and password recovery* topic? ... and we are taking this one to Razor Pages, too, correct?

**Comment by bcisnero** [comment]
Ok, so I guess I'll start reviewing the linked PRs and then I'll start
developing a 2.1/razor sample app to cover this topic? Or do you guys have
other priority that I could be more helpful?

**Comment by guardrex** [comment]
There are up-for-grabs issues ... https://github.com/aspnet/Docs/issues?q=is%3Aopen+is%3Aissue+label%3Aup-for-grabs

**Comment by Rick-Anderson** [comment]
Actually, everything is up for grabs. I wouldn't filter on that label.

**Comment by Rick-Anderson** [comment]
@bcisnero  This one is high on the priority list.

**Comment by guardrex** [comment]
:smile: Should the label be retired?

**Comment by bcisnero** [comment]
you mean the #6632?

**Comment by Rick-Anderson** [comment]
Yes, this issue

**Comment by Alienroid** [comment]
I'm not Microsoft employee. I just reported the issue. Should I unfollow?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by guardrex** [comment]
> Should I unfollow?

You mean because of the volume of messages?

**Comment by Alienroid** [comment]
Seems like these are internal discussion within Microsoft? I just posted the issue and the workaround/solution…

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by guardrex** [comment]
No discussions in the repo issues are internal. Sometimes devs unsubscribe from notifications if there's a lot of talk on the issue or PR and they don't want to get the pings.

**Comment by bcisnero** [comment]
I wish there was a better way to ask this questions without creating that amount of traffic :) 
So I created a new branch where I added a copy of the existing sample app with the changes needed to address this issue. Now the question is for the document, based on what @guardrex commented when I asked about the strategy, should I remove all the references for the core 1.x and left only those for the core 2.x? Or should I state that this how-to is only for core 2.1?

**Comment by guardrex** [comment]
@bcisnero We haven't traditionally retained the prior sample for tutorials. However, this one is authored by @Rick-Anderson, so he'll make the final call on keeping or dropping the current sample.

**Comment by bcisnero** [comment]
Understood.

Thanks,
Ben.

**Comment by Rick-Anderson** [comment]
Fixed in #7614
