### ISSUE TITLE
EntityFramework Toolreference.

### ISSUE THREAD

**Issue by marante** [aspnet/Docs#6683]
In one step, you ask us to add the following line:
```xml
<DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.1" />
```
And you state that we can't use the package manager to use install-package to install it. Why is this? And also, how do I make sure what version I put in? Is there a way to figure out the latest stable version?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b34c4871-adc3-0d13-6f20-6f6ac1f65e91
* Version Independent ID: ea1742b3-808b-d449-3308-6847a9f339f9
* Content: [Add a model to an ASP.NET Core Razor Pages app with Visual Studio Code](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages-vsc/model?view=aspnetcore-2.0)
* Content Source: [aspnetcore/tutorials/razor-pages-vsc/model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages-vsc/model.md)
* Service: **unspecified**
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment]
@marante The available package versions are listed here: https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Tools.DotNet/2.1.0-preview1-final. If you're targeting .NET Core 2.0, version 2.0.3 of the package is the latest stable version.

The manual edit of the *.csproj* file is necessary because NuGet doesn't provide support for adding `<DotNetCliToolReference />` nodes. Instead, NuGet adds package references as `<PackageReference />` nodes. This is less of a concern, since .NET Core 2.1 (released today) eliminates the need for many of the `<DotNetCliToolReference />` nodes.

**Comment by marante** [comment]
Oh, okey. Should I install 2.1 .NET Core and use that instead?

**Comment by scottaddie** [comment]
@marante If you're able to, the 2.1 version of the .NET Core SDK is highly recommended. You'll gain improved performance by installing it. Additionally, you'll gain access to all the new features in ASP.NET Core 2.1.

**Comment by Rick-Anderson** [comment]
> And you state that we can't use the package manager to use install-package to install it. Why is this? And also, how do I make sure what version I put in? Is there a way to figure out the latest stable version?

That's no longer true with 2.1 - which solves the versioning problem. It will be sometime before I can update the VSC version for 2.1. The VS version is live now.

**Comment by marante** [comment]
Thanks, both of you, for replying. I will get around to 2.1 and ser if I can get it working. Is there some place I can go to see how I would use the new features on VSC, or do I wait for your update Rick?
