### ISSUE TITLE
Solution for: 'No executable found matching command "dotnet-watch"

### ISSUE THREAD

**Issue by streetwiseherc** [aspnet/Docs#6802]
While I'm assuming that the sample projects .csproj file contains the correct DotNetCliToolReference, someone reading this might not have it entered in correctly and may be confused by the error they receive when executing 'dotnet watch' at the command line.  Would it make sense to add a note that the following lines are required in the .csproj file?

&lt;ItemGroup&gt;
     ...
    &lt;DotNetCliToolReference Include="Microsoft.DotNet.Watcher.Tools" Version="2.0.2" /&gt;
  &lt;/ItemGroup&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75e3163f-1903-f2c7-8909-d34f917944bf
* Version Independent ID: 55aae418-9d32-5b2b-1df7-5e4e76313ec4
* Content: [Develop ASP.NET Core apps using a file watcher](https://docs.microsoft.com/en-us/aspnet/core/tutorials/dotnet-watch?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/dotnet-watch.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/dotnet-watch.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
I though @scottaddie  updated this for 2.1, but the download is using 2.0
@scottaddie  can comment. 
@streetwiseherc  are you using 2.1 .Net Core SDK ?

**Comment by scottaddie** [comment]
@streetwiseherc The ASP.NET Core 2.0 version of the doc contains instructions for adding the `DotNetCliToolReference` element: https://docs.microsoft.com/aspnet/core/tutorials/dotnet-watch?view=aspnetcore-2.0#add-dotnet-watch-to-a-project. That section isn't present in the ASP.NET Core 2.1 version of the doc because you would have .NET Core SDK 2.1 installed. The 2.1 SDK comes bundled with the dotnet-watch tool.
