### ISSUE TITLE
Possible help for Scaffold the Model section.

### ISSUE THREAD

**Issue by yamazaroon** [aspnet/Docs#6894]
I'm a newbie to ASP.NET so I understand if this is not an issue for well-versed programmers.  I spent quite a bit of time trying to get the "No executable found matching command "dotnet-aspnet-codegenerator"" issue worked out.  The instructions provided state to open a command prompt and build the project there.  This did not result in any errors regarding the plural "Students", so that seems to have been worked out in one of the updates.  I did receive the "No executable found matching command "dotnet-aspnet-codegenerator"".   I tried building the package in the command prompt as instructed with no resolve.  The following is I was able to do to work this out for myself.  

The first thing that I missed was that understand from the walkthrough that the "Microsoft.VisualStudio.Web.CodeGeneration.Tools" package also needs to be added.  After researching, I finally worked this out by installing the "Tools" package through the package manager console.  However, when installing it through the package manager console and then rebuilding the project in VS, it gets added to the .csproj file as a "PackageReference".  This part took me some time to figure out.  After looking closely back at your coding inside the .csproj file, I noticed that it was entered under the &lt;DotNetCliToolReference Include=""&gt;section.  I manually edited the .csproj file with the correct version of my Microsoft.VisualStudio.Web.CodeGeneration.Tools (ver 2.0.4), and then followed your instructions for "dotnet restore" followed by "dotnet aspnet-codegenerator razorpage -m Student -dc SchoolContext -udl -outDir Pages\Students --referenceScriptLibraries".  I then built the project in the command prompt with "dotnet build" and got the proper result.  

I feel that some additional instructions pointing out that the "tools" package needs to be installed and must be entered as a "DotNetCliToolReference" could help save people at my level some time and ease of understanding.  This is my first post on here and hopefully will help save someone else some time.  Thank you for your tutorial @tdykstra and @Rick-Anderson. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-2.1#feedback)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/intro.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment]
@yamazaroon We've created issue https://github.com/aspnet/Docs/issues/6857 to document this tool. That will address your concerns. Once you upgrade to .NET Core SDK 2.1, the `<DotNetCliToolReference />` node should be removed from your *.csproj* file. This code generation tool became a global .NET Core CLI tool in the 2.1 release. What you noticed with the `<PackageReference />` node being added is a known limitation of NuGet. The *.csproj* file has to be manually edited to convert it to a `<DotNetCliToolReference />` node.

@Rick-Anderson Anything you want to adjust with this doc in the meantime?

**Comment by Rick-Anderson** [comment]
This tutorial is marked for update to 2.1, which skips those steps.  See #6482
see https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.1
Visual Studio takes care of scaffolding.

**Comment by raghukrishnamoorthy** [comment]
@scottaddie That's all good but does not solve the problem. I've installed Microsoft.VisualStudio.Web.CodeGeneration.Tools as well. There is no DotnetCli node like you mentioned but I still get the "No executable found matching command "dotnet-aspnet-codegenerator". What do you suggest I do?

**Comment by scottaddie** [comment]
@raghukrishnamoorthy Please provide the following info, so I can better assist:
1. The output of running `dotnet --info`.
2. The contents of the *.csproj* file.
3. Do you have a *global.json* file in your solution? If so, which SDK version is it using?

**Comment by raghukrishnamoorthy** [comment]
Hi @scottaddie 

Output of running dotnet --info
-------------------------------------------------------------
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300
 Commit:    adab45bf0c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300\

Host (useful for support):
  Version: 2.1.0
  Commit:  caa7b7e2ba

.NET Core SDKs installed:
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
------------------------------------------------------------------


2. Contents of the csproj file
------------------------------------------------------------------
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.4" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Utils" Version="2.1.0" />
  </ItemGroup>

</Project>
-----------------------------------------------------------------------------------
3. I do not have a global.json file in my solution

FWIW, the fix for me was manually installing the asp-net-codegenerator by executing this command

>dotnet tool install -g dotnet-aspnet-codegenerator

This one line being added to the docs would solve the problem. If this tutorial is outdated and not maintained anymore, well sorry for the trouble.

**Comment by Rick-Anderson** [comment]
`dotnet tool install -g dotnet-aspnet-codegenerator` is only required for the CLI. It's not required when using Visual Studio.
Thanks for that info, it might help someone else.

**Comment by raghukrishnamoorthy** [comment]
@Rick-Anderson 

Hey Rick, first up, thanks for all the awesome tutorials. Learned a ton.

The instructions in the tutorial use CLI right now and not visual studio. Unless the Instructions in the tutorial are changed to reflect scaffolding using Visual studio, then the current instructions in the tutorial are incomplete/erroneous at best.

**Comment by Rick-Anderson** [comment]
@yamazaroon  thanks, I wasn't sure which tutorial you were following.  I created #7069 to track this.

**Comment by scottaddie** [comment]
@raghukrishnamoorthy It's also worth noting that the `dotnet tool install` command only works when you have version 2.1 of the .NET Core SDK installed. This tutorial currently assumes use of the 2.0 SDK.

@Rick-Anderson It's not explicitly called out, but this tutorial seems to cater to Windows / Visual Studio devs. For example, the [Add scaffold tooling](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-2.1#add-scaffold-tooling) section talks about using PMC. Should this tutorial be converted to Windows only, and then we'd create a similar x-plat tutorial? Or should this tutorial be converted to not use PMC at all? For example, the `Install-Package` commands could be replaced with .NET Core CLI commands.

**Comment by Rick-Anderson** [comment]
@yamazaroon  this is scheduled to be updated to 2.1 in the next month. I haven't got around to it yet.

#6482
