### ISSUE TITLE
How to pass state between clients and the Hub class

### ISSUE THREAD

**Issue by IonutArhire** [aspnet/Docs#6899]
It isn't specified how to pass state between clients and the Hub class, like for an older version: https://docs.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/hubs-api-guide-server#how-to-pass-state-between-clients-and-the-hub-class

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1387f556-b4b7-70f9-5bd0-f0bccc597689
* Version Independent ID: fb016cdc-d281-6b5b-7466-2c718e7274b4
* Content: [Use hubs in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-2.1)
* Content Source: [aspnetcore/signalr/hubs.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/hubs.md)
* Product: **aspnet-core**
* GitHub Login: @rachelappel
* Microsoft Alias: **rachelap**

**Comment by rachelappel** [comment]
@anurse what's the official guidance since there are no sessions and no proxy?

**Comment by anurse** [comment]
You pass state by calling methods on the Hub. Hub "state" was explicitly removed because it wasn't really behaving in the way users expected (even when you change state it's only sent to the other side when the next method is called). If you have state you want to track, store it somewhere on the server (the connection has an `Items` collection, or you can use the User/Connection identity as a key in some other data store) and add methods to update that state, which you call from the client/server.

**Comment by IonutArhire** [comment]
Thank you very much!
