### ISSUE TITLE
Console command to make new Razor Page project is incorrect

### ISSUE THREAD

**Issue by RyanTaite** [aspnet/Docs#6930]
Currently states you should run the command `dotnet new webapp -o RazorPagesMovie` when instead it should be `dotnet new razor -o RazorPagesMovie`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cafe31d3-11f1-d679-1937-915690ac7360
* Version Independent ID: e6b12009-be25-33e0-c5a8-8a1bd686b387
* Content: [Get started with ASP.NET Core Razor Pages in Visual Studio Code](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages-vsc/razor-pages-start?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages-vsc/razor-pages-start.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages-vsc/razor-pages-start.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@RyanTaite Thanks for commenting. They introduced an alias for `razor` ... `webapp`. Do you have the 2.1 SDK installed? ... The alias works with 2.1. Otherwise for 2.0, you're correct, it would be `razor`. If you flip the doc to "2.0" (upper-left of the page), it should flip the command back to using `razor`.

**Comment by RyanTaite** [comment]
Looks I don't have 2.1 installed, and only 2.0! Totally my mistake then. Thank you!
