### ISSUE TITLE
Working with Multiple Environments

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#70]
ASP.NET 5->Runtime->Working with Multiple Environments
- Development vs Staging vs Production
- Startup conventions
- Env vars

**Comment by GuardRex** [comment]
@danroth27 It's a documentation pain point at [Working with Multiple Environments](http://docs.asp.net/en/latest/fundamentals/environments.html) for the `<environment>` tag functionality, since The Lesser Scotts just showed that in their demo at Build. I was wondering if you had anything at all you could supply on that? It doesn't seem to work out-of-the-box. https://github.com/aspnet/Home/issues/534 (and I am on the nightly bits with VS 2015 RC).

**Comment by danroth27** [comment]
@GuardRex This topic is related to the environment Tag Helper, but it will only cover the underlying infrastructure for environments in ASP.NET 5. Tag Helpers will covered under the MVC docs. This content is still on the backlog.

**Comment by GuardRex** [comment]
@danroth27 Thanks. I'll reference my discovery about the collision of Tag Helpers and minification here just in case someone hits this looking for help. https://github.com/aspnet/Home/issues/534
