### ISSUE TITLE
Building Web Applications with Entity Framework

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#72]
ASP.NET 5->Working with Data->Building Web Applications with Entity Framework
- Configuring EF at startup
- Migrations 
- Diagnosing database errors

**Comment by ntgraph** [comment]
Hi,
Please have also a documentation covering multiple models in a single view.  It is always easy to scaffold one model, one controller and all CRUD views, but there is time that one view will need to display one main model and some others models for a complete overall view.
I am looking forward to see such topic.
Thanks,

**Comment by natemcmaster** [comment]
This would be a good place to answer a common question: should I use DI on my controller to get an instance of my DbContext? or `using(var c = new DbContext())` within methods of the controller?)

**Comment by LorenDorez** [comment]
This might be a good place to talk about connecting EF to an existing DB as everything ive been reading says its only using CodeFirst Approach

**Comment by danroth27** [comment]
We could base this on http://www.asp.net/mvc/overview/getting-started/getting-started-with-ef-using-mvc/creating-an-entity-framework-data-model-for-an-asp-net-mvc-application

**Comment by gkrilov** [comment]
Previously with EF6 and MVC 5 we used to have a separate project for the data access layer where we had our context and repositories. The context was setup in this separate project. We then used services with unit of work to access the repositories in the web project.

How will this work in vNext with EF7? Would we still have all the data access stuff separately and then use services in the main web project? Or would we somehow mix the two together? 

If separately then services.AddEntityFramework() in the startup.cs will not be required anymore right? Since the context will be setup in the data access layer

Please have a section on best practices :)

**Comment by ardalis** [comment]
I'm hoping to write some articles that show proper separation of concerns and layered architectures before RTM. These will include how to separate data access concerns into a separate project from the UI layer.

**Comment by gkrilov** [comment]
That would be great! It's good to separate the data layer out in big applications and it feels like .NET core + EF7 will have some differences in how that works

**Comment by danroth27** [comment]
We are now linking to the EF articles on integrating with ASP.NET 5: https://docs.asp.net/en/latest/data/index.html

**Comment by rhires** [comment]
I'm confused. Is the link supposed to point to EF6 references, or EF7? The main page this link points to talks about EF6 (the third link/bullet point), and if you hit "next" it keeps you on the EF6 track, but if you click the link for the text "ASP.NET 5 Application to New Database" and the 2nd bullet point, they point to EF7 stuff. I'm asking because I know that aspnet5 is supposed to work with both EF6 and EF7...just not sure how this page is supposed to make that explicit.

**Comment by Rick-Anderson** [comment]
@rhires  The first two links are EF7, the last is EF6. Thanks for pointing this out. I opened #785 to track this.
