### ISSUE TITLE
Add docs for each of the authentication providers to help new users

### ISSUE THREAD

**Issue by christiansparre** [aspnet/Docs#727]
I think it would be an idea to add some documentation for each of the providers. For one I have run into a few gotchas using the Google OAuth provider, like remembering to enable the Google+ API in the Google developer console.

Would love to contribute if needed.

**Comment by danroth27** [comment]
@christiansparre Yup, this is needed. A contribution would be welcome!

**Comment by danroth27** [comment]
See what we've got already for Facebook at https://docs.asp.net/en/latest/security/sociallogins.html.

**Comment by christiansparre** [comment]
I think that is a great overall guide to setting up social login. Would it be an idea with subpages for each provider?

**Comment by danroth27** [comment]
I think a subpage for each supported provider would work great.

**Comment by danroth27** [comment]
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/facebook-logins
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/twitter-logins
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/google-logins
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/microsoft-logins

However, it looks like these topics aren't showing up in the TOC. They should probably be in a separate folder. Opened #2332 to track fixing. Closing this one since the content is there.
