### ISSUE TITLE
User.Identity.Name is allways null

### ISSUE THREAD

**Issue by shlomitubul** [aspnet/Docs#7295]
how can i add authentication like windows authentication ? (both wpf client and hub.) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9bc1072-be2c-94f6-49bf-daa9e97dff2d
* Version Independent ID: 36052173-7061-6d01-8aed-915685cd7cf6
* Content: [ASP.NET Core SignalR .NET Client](https://docs.microsoft.com/en-us/aspnet/core/signalr/dotnet-client?view=aspnetcore-2.1)
* Content Source: [aspnetcore/signalr/dotnet-client.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/dotnet-client.md)
* Product: **aspnet-core**
* GitHub Login: @rachelappel
* Microsoft Alias: **rachelap**

**Comment by rachelappel** [comment]
Hi @shlomitubul! Thanks for the question. Since you are using ASP.NET Core security, you can run with any of the existing methods of authentication that you would use without SignalR in a regular ASP.NET app and WPF client. When testing, if you log in, then you should get a non null value (when following what's in the doc below). This doc covers what's needed for ASP.NET Core. 
https://docs.microsoft.com/en-us/aspnet/core/?view=aspnetcore-2.1
We expect to have a similar doc, but highlighting that it works the same in SignalR soon.
