### ISSUE TITLE
BuildWebHost is unavailable

### ISSUE THREAD

**Issue by gjaryczewski** [aspnet/Docs#7298]
With SDK 2.1, it looks like BuildWebHost(args) should be replaced by CreateWebHostBuilder(args).Build().

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a111b14d-2c56-f0a9-d318-f99ae6bb016e
* Version Independent ID: 91430704-1e14-9b10-9fd1-d5a19cc5d380
* Content: [Working with SQLite and and Razor Pages](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages-vsc/sql?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages-vsc/sql.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages-vsc/sql.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@Rick-Anderson, this one didn't make the cut for work on https://github.com/aspnet/Docs/pull/6562. I was initially under the impression we hadn't worked the RP tutorial yet. I better leave this open until you have a chance to take a look. If you want me to catch it in my final sweep of topics later on #6091, let's close this, and I'll work it on #6091.

**Comment by rajendrarama** [comment]
The above code in program.cs leads to the error:
InvalidProgramException: Vararg calling convention not supported.

**Comment by rldml** [comment]
When will this part of the tutorial will be updated to .NET CORE 2.1? I'm stuck at this part and i can't get progress. I've changed

CreateWebHostBuilder(args).Build().Run();

to

var host = CreateWebHostBuilder(args).Build();
host.Run();

but even then there is no chance to make

var scope = host.Services.CreateScope();

because the method doesn't exist. Instead there is a method called GetService(), but at that point i don't get any clue how to step further. Debugging don't show any variables, even my breakpoint is simply ignored (or perhaps never reached, i really don't know)

Even if you don't update the tutorial, can you please describe in the comments, how to implement the SeedData-class in the startup-process?`

Thx.

**Comment by rldml** [comment]
Humpf....

Now there is CreateScope(). I don't know what i've done wrong. 

Sorry...

**Comment by rldml** [comment]
Just a last comment:

using Microsoft.Extensions.DepencyInjection;

That was my missing part. Sorry @all... I'll promise to read more carefully in the future...

**Comment by guardrex** [comment]
Just in passing, the seeding approach is a change in progress. For an example, see this remark ... https://github.com/aspnet/Docs/issues/9205#issuecomment-433765522

The issues where the work is occurring can be found by searching the repo issues: https://github.com/aspnet/Docs/issues?q=is%3Aissue+seed+is%3Aopen

I think some of the closed issues may indicate where some of the topics use the new approach. All of the topic samples will eventually use the new approach. I think the remaining topics will get attention after 2.2 comes out, and that's tentatively scheduled to happen by year's end.
