### ISSUE TITLE
Add documentation for Server Side rendering from Angular templates

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Docs#7310]
We should update https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-2.1&tabs=visual-studio#server-side-rendering to include the new steps for enabling SSR (Server Side Rendering) as mentioned [here](https://github.com/aspnet/templating/pull/581#pullrequestreview-131259812).

Per `@SteveSandersonMS` 	

>  In the worst case we could remove the whole section about SSR and just say it's not something we have any recommendations about how to do. But it would be better if there was a known set of steps to enable SSR that we could document.

**Comment by BeejeeDS** [comment]
So 3 sprints later and this has still not been completed?
How is that even possible, just update the damn file already.

**Comment by Rick-Anderson** [comment]
@kichalla can you provide a draft to this update (or suggest someone else?).

**Comment by ryanbrandenburg** [comment]
Angular SSR docs ended up being removed entirely. Details [can be found here](https://github.com/aspnet/Docs/pull/11151).

**Comment by MusicDemons** [comment]
The framework changes way too much lately to provide a proper documentation about server-side rendering.

Aside from that, the implementation relies on third-party libraries such as express-engine.

If you really want to implement SSR, please consult https://medium.com/@pieterjandeclippel/server-side-rendering-in-asp-net-core-angular-6df7adacbdaa for ASP.NET Core 2.2 and Angular 8.1.

**Comment by PieterjanDeClippel** [comment]
The framework changes way too much lately to provide a proper documentation about server-side rendering. Aside from that, the implementation relies on third-party libraries such as express-engine.

That's why Microsoft decided to remove this from the documentation.

If you really want to implement SSR, please consult https://medium.com/@pieterjandeclippel/server-side-rendering-in-asp-net-core-angular-6df7adacbdaa for ASP.NET Core 2.2 and Angular 8.1.
