### ISSUE TITLE
Azure KeyVault configuration provider for dotnet core: include MSI piece

### ISSUE THREAD

**Issue by hiraldesai** [aspnet/Docs#7380]
It looks like version `2.1.1` of `Microsoft.Extensions.Configuration.AzureKeyVault` includes the awesome hidden gem that has Managed Service Identity support. It reduces the overhead of managing secrets/certificates as long as you're hosting in Azure with integrated Active Directory.

```
        public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .ConfigureAppConfiguration((context, config) =>
                {
                    var builtConfig = config.Build();
                    var keyVaultConfigBuilder = new ConfigurationBuilder();
                    keyVaultConfigBuilder.AddAzureKeyVault(builtConfig["KeyVaultUrl"]);
                    var keyVaultConfig = keyVaultConfigBuilder.Build();
                    config.AddConfiguration(keyVaultConfig);
                })
                .Build();
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cc0b77a-df21-7007-5cec-4399d98c6dc6
* Version Independent ID: efe5ae5e-ff64-f1c7-6920-4512fc8f36d1
* Content: [Azure Key Vault configuration provider in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/security/key-vault-configuration.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/key-vault-configuration.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks for the note @hiraldesai. I'll take a look at this as soon as I can get free.

**Comment by Rick-Anderson** [comment]
@CamSoper @scottaddie 	is this something you could do?
cc @guardrex

**Comment by scottaddie** [comment]
@Rick-Anderson I can take care of it. There's a meeting tomorrow to discuss. We may be able to simply link to the existing Azure .NET dev center doc.

**Comment by abhiTechcs** [comment]
Hi Scott, 

Is this something you are looking forward to include this feature in near future?
We really wanted to utilise the MSI functionality from our web Api to get Key vault configuration builder.

appreciate your help in advance. :)

cheers,
Abhi

**Comment by scottaddie** [comment]
@abhiTechcs I plan to work on this in the current sprint. In the meantime, see the following doc:

https://docs.microsoft.com/azure/key-vault/quick-create-net

You can also see how I've configured Key Vault with MSI in one of my personal repos:

https://github.com/scottaddie/ViewComponentsDemo/blob/master/ViewComponentsDemo/Program.cs#L18-L21

In this app, the .NET Core CLI's Secret Manager tool is used locally if the `ASPNETCORE_HOSTINGSTARTUP__KEYVAULT__CONFIGURATIONENABLED` environment variable is `false`. Set that to `true` to use Key Vault locally instead of Secret Manager.

**Comment by EdBlankenship** [comment]
@guardrex @scottaddie Any news on when this may land?

**Comment by guardrex** [comment]
Not on my end ... this is assigned to Scott, so I defer to him.

**Comment by guardrex** [comment]
I have a process now. It was a bit of hand-to-hand combat there with the docs and portal to get it straight. I'm happy with the outcome. https://rexkeyvault.azurewebsites.net/

@Rick-Anderson Here are some notions ...

WRT this issue: We can link out for MSI basics, but I don't want to leave our readers at the mercy of those docs and the portal. There are some 🐉🐉🐉 in there, and I'd hate to see a dev get the :fire: *breath* :fire: (*I got a little singed myself today!* :smile:) I have a nice sample app, and I have a good **_no-tears process_** to provide.

Due to portal and AAD-AKV churn since the topic was first written, this is as good a time as any to update the whole topic. The samples should go to 2.2 and RP. We should provide the portal-only experience, which wasn't possible when the topic was first written.

Therefore, the PR can also cover:
* [Enhance the topic and convert the 2.x samples to use Razor Pages apps (aspnet/Docs 10216)](https://github.com/aspnet/Docs/issues/10216)
* [Access Denied #7932 (aspnet/Docs 7932)](https://github.com/aspnet/Docs/issues/7932)

... so I can knock out three issues here (hopefully by tomorrow night).

**Here's the question tho wrt the process:** Do you want to retain the PowerShell approach here along with the portal experience, or do you want to drop the PowerShell approach and try to link out for it? I'm on the fence about it and can work it either way.

**Comment by Rick-Anderson** [comment]
@glennc 	can you answer this?

>  Do you want to retain the PowerShell approach here along with the portal experience, or do you want to drop the PowerShell approach and try to link out for it?

My preference is `Azure CLI`, it's easier to maintain.

**Comment by Rick-Anderson** [comment]
>  you mean only CLI ... no portal.
Yes

Definitely can't say don't use the portal. The Azure team needs to doc the portal. The portal changes frequently.

**Comment by guardrex** [comment]
I know ... just kidding. I do feel bad tho for anyone who hits a few snags that I hit.

**Comment by guardrex** [comment]
@glennc I'm going to attempt to slide in a note regarding a couple of 🐉 when using the portal. The topic will go with Azure CLI as its main approach. I'll ping u on the PR with the critical bits in a PR comment.
