### ISSUE TITLE
Integration test guideline for views not working on TFS build agents

### ISSUE THREAD

**Issue by Tornhoof** [aspnet/Docs#7408]
The method ``GetProjectPath`` in the code example https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/testing?view=aspnetcore-2.1#accessing-views assumes a fixed folder structure.
On TFS (and probably VSTS too), the folder structure changes, the binaries are e.g. in C:\Agent\_work\1\b, the source in C:\Agent\_work\1\s.
So any attempt to find the ``wwwroot  path`` will fail as the test is executed from within the binaries directory and the relative path does not match anymore.

Please provide a better way to find the wwwroot path which also works on TFS build agents
My current workaround is a post build which does a  xcopy of the wwwroot to the targetdirectory.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5cce372-24e2-3489-cb19-c85d934e5d3b
* Version Independent ID: 9d12b19f-a94e-4df4-357b-3f3b93696eb6
* Content: [Test controller logic in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/testing?view=aspnetcore-2.1)
* Content Source: [aspnetcore/mvc/controllers/testing.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/controllers/testing.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Did you try the new testing infrastructure? ... https://docs.microsoft.com/aspnet/core/test/integration-tests

The underlying logic is different for inferring the content root: https://docs.microsoft.com/aspnet/core/test/integration-tests#how-the-test-infrastructure-infers-the-app-content-root-path

I can't guarantee the behavior with TFS build agents, but you'd also have the `UseSolutionRelativeContentRoot` setting at your disposal that might help.

@Rick-Anderson @scottaddie @rachelappel We didn't discuss this topic ... **_YET_**. It would've come up tho for the sample update at some point.

**Comment by Tornhoof** [comment]
No I haven't yet tried the new infrastructure with this specific product.
Looking at `` UseSolutionRelativeContentRoot`` https://github.com/aspnet/Hosting/blob/f9d145887773e0c650e66165e0c61886153bcc0b/src/Microsoft.AspNetCore.TestHost/WebHostBuilderExtensions.cs#L61, it's basically ``GetProjectPath`` just with a different name.

Looking at the new ``WebApplicationFactoryContentRootAttribute`` and related code, that one looks better, specifically the related msbuild targets. I'll have to try those and get back to you.

**Comment by Tornhoof** [comment]
I tried out the new testing infrastructure, with ``WebApplicationFactory`` et al. 
I got it working for the tutorial of the page above, but for my application it's not a good fit.
- No proper support for Kestrel, HttpSys, I know there is the fake TestServer approach -> https://github.com/aspnet/Mvc/issues/7818
- No async init support, seeding data with some sync over async approach isn't what I consider a valid approach (Xunit has IAsyncLifetime for that btw.)

I ran into a few additional problems where the Fixture class is actually in a shared third project, but that might be just my rather complex project setup. 

In any case, you can close this issue as from my pov https://docs.microsoft.com/aspnet/core/test/integration-tests documents the current approach well enough.

**Comment by guardrex** [comment]
@javiercn, there's testing feedback for you here.

**Comment by guardrex** [comment]
@Tornhoof I hope you found a good solution for your scenario.

Your OP here has feedback regarding:

* `GetProjectPath` from the *Testing controllers* topic *Accessing views* section. That approach and content has been removed in the time since you opened this issue. You mentioned that `UseSolutionRelativeContentRoot` (from the *Integration tests* topic) relies on about the same approach internally.
* A fixed folder layout assumption by the engineers.
* Build agent scenario.

If your request is still valid feedback for the engineers, you can re-open this issue at [aspnet/AspNetCore issues](https://github.com/aspnet/AspNetCore/issues). You'd need to re-cast the explanation a bit given that the content you referenced before isn't available any longer.

AFAICT, we don't have anything actionable based on guidance from engineering at this time. If they come up with something, we'll open a new issue to cover it. Thanks again for opening this issue and discussing your scenario here.
