### ISSUE TITLE
Why Microsoft.AspNetCore.App is recommended rather than Microsoft.AspNetCore.All?

### ISSUE THREAD

**Issue by jsakamoto** [aspnet/Docs#7424]
There is no problem that change referencing meta package from "All" to "App" in my cases.

However, since I am interested, I'd like to know what advantages or reasons it has.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5324eda1-40f2-4e41-08ff-c2610f3853c2
* Version Independent ID: 99d54f78-d56e-8061-e821-90748722c184
* Content: [Microsoft.AspNetCore.All metapackage for ASP.NET Core 2.0 and later](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/metapackage?view=aspnetcore-2.1#migrate)
* Content Source: [aspnetcore/fundamentals/metapackage.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/metapackage.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @jsakamoto ... see https://docs.microsoft.com/aspnet/core/fundamentals/metapackage-app ... one of the main reasons is that the ASP.NET Core engineering team wants the metapackage to (mostly) contain the packages that they directly control.

**Comment by jiimaho** [comment]
The *.All metapackage referenced third party dependencies, not managed by the .NET Core team. Since they did not want to implicitly rerference those third party dependencies, they had to come up with a new name for the metapackage, that does not include third party dependencies. This name seem to be *.App.

This is the best conclusion I have drawn from reading the docs.
