### ISSUE TITLE
IIS 502.5 Process Failure error

### ISSUE THREAD

**Issue by MarsAstro** [aspnet/Docs#7585]
When following this guide, the published app gives an IIS 502.5 error. It works when run locally, but does not work for the hosted app. I followed the guide step by step, with the exception that I made an MVC app rather than just a base Web application. I did this with a clean install of Visual Studio Community 2017.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71a44c72-d256-fbee-ea70-2eb7472f8182
* Version Independent ID: 157027ff-0bad-828d-a442-a98acd219fba
* Content: [Publish an ASP.NET Core app to Azure with Visual Studio](https://docs.microsoft.com/en-us/aspnet/core/tutorials/publish-to-azure-webapp-using-vs?view=aspnetcore-2.0#feedback)
* Content Source: [aspnetcore/tutorials/publish-to-azure-webapp-using-vs.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/publish-to-azure-webapp-using-vs.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @MarsAstro ... see the Troubleshooting guide for IIS deployments ...

https://docs.microsoft.com/aspnet/core/host-and-deploy/iis/troubleshoot

... then check the Common Errors topic for additional help ...

https://docs.microsoft.com/aspnet/core/host-and-deploy/azure-iis-errors-reference

If you're still having issues, ask for help on Stack Overflow or one of the ASP.NET Core chats (Gitter or Slack). Please do post back here when you find out what the problem was so that we can make sure the docs cover your issue.

**Comment by MarsAstro** [comment]
I just opened the app again 2 hours later, and now it works fine. I guess there was some process that wasn't finished yet, because I've changed nothing since I originally pressed "Publish".

**Comment by guardrex** [comment]
Interesting! Startup usually only takes a few seconds. It's true that a 502.5 will be returned by IIS (running under Azure Apps) if the app fails to respond within 120 seconds. You can extend that by setting a longer `startupTimeLimit`. See: https://docs.microsoft.com/aspnet/core/host-and-deploy/aspnet-core-module

I'll close this since it seems things are working for you now.
