### ISSUE TITLE
dotnet commands fail if you are not in the correct folder

### ISSUE THREAD

**Issue by KirkMunro** [aspnet/Docs#7730]
This tutorial series includes Visual Studio commands and dotnet CLI commands. If you follow the Visual Studio commands and then later decide you want to try some of the dotnet equivalents (instead of invoking Update-Database, for example), those commands may fail if you are not in the proper folder (the project folder -- if you create this using Visual Studio with a full solution, you will likely have your solution in a separate folder from the project, and by default the Package Manager Console will be in the solution folder, not the project folder where it needs to be for the dotnet commands to work properly). This is only a problem if you try the two different command types as you work through this tutorial. I'm pointing this out because I ran into this very issue, using the Visual Studio steps with PowerShell for the most part, then later trying some of the CLI commands only to see them fail. Also, when you get to the "Read related data" step of the tutorial where currently it only offers dotnet CLI steps, those steps will not work, blocking you from progressing unless you figure out a workaround (copy from the end result, which is not ideal, or use Visual Studio to set up scaffolding for the Course model).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-2.1&tabs=netcore-cli#create-the-contosouniversity-razor-pages-web-app)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/intro.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Irene726** [comment]
Hi Kirk, im experiencing a lot of issues in the Read related data part of the Razor pages tutorial. Can you please help me?

**Comment by KirkMunro** [comment]
@Irene726 If you're hitting the same issues I ran into (which happened because I was using Visual Studio to go through the tutorial, not the dotnet CLI), then when you get to [this step](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/read-related-data?view=aspnetcore-2.1#scaffold-the-course-model), instead of exiting Visual Studio and running dotnet CLI commands as instructed, follow [these instructions from the first part of the tutorial](https://docs.microsoft.com/en-gb/aspnet/core/data/ef-rp/intro?view=aspnetcore-2.1&tabs=visual-studio#scaffold-the-student-model), but replace Student (when it refers to the Student model) with Course. Those steps will unblock anyone who is stuck on this part of the tutorial that is missing instructions for Visual Studio users.

You'll have to do the same thing when you are [instructed to scaffold the Instructor model](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/read-related-data?view=aspnetcore-2.1#scaffold-the-instructor-model), a little bit later in the tutorial, but replacing Student with Instructor in that case.

Please let me know if that helps get you past your issues or not.

**Comment by Irene726** [comment]
Hi Kirk, thank you for your reply. I followed the instructions from the link you gave me however after I clicked the 'Add' button in the Add Razor pages using Entity Framework (CRUD) dialog window, it showed this error message ; There was an error running the selected code generator: 'Sequence contains no elements'
![error](https://user-images.githubusercontent.com/41277836/43051125-d350ebac-8e57-11e8-9c4e-80b78449a74a.JPG)

I was following the razor pages tutorial by running the command - "dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Design --version 2.1.0
dotnet aspnet-codegenerator razorpage -m Course -dc SchoolContext -udl -outDir Pages\Courses --referenceScriptLibraries" in a powershell window that I opened up in the specified directory. After running it, it gave the error that the Build failed. in order to fix the build and the errors in my project, i installed packages which made the errors go away however there was one error left - 'The project was restored using Microsoft.NETCore.App version 2.1.1, but with current settings, version 2.1.0 would be used instead.  To resolve this issue, make sure the same settings are used for restore and for subsequent operations such as build or publish.  Typically this issue can occur if the RuntimeIdentifier property is set during build or publish but not during restore.'

I have attached screenshots of my csproj file where you will see the packages I installed. 
![csproj1](https://user-images.githubusercontent.com/41277836/43051170-d9906a6e-8e58-11e8-8e8a-63cc515c38f3.JPG)
![csproj2](https://user-images.githubusercontent.com/41277836/43051172-e55e2818-8e58-11e8-8eed-9ccfe854a32c.JPG)

I have also looked at the csproj file that is available on github but it did not work either.

-Irene
