### ISSUE TITLE
Clarification on `AddAzureWebAppDiagnostics` for apps targetting .NET Core

### ISSUE THREAD

**Issue by frankfajardo** [aspnet/Docs#7776]
Question about this statement: *If targeting .NET Core, don't install the provider package or explicitly call AddAzureWebAppDiagnostics.*. What is the impact of actually either adding the package or calling the method  on an app targettting .NET Core? I'm trying to understand why the package shouldn't be installed *OR* call the method. It is unclear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.1#azure-app-service-provider)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **tdykstra**

**Comment by scottaddie** [comment]
@frankfajardo The *Microsoft.Extensions.Logging.AzureAppServices* package is included in the ASP.NET Core metapackage. The doc assumes you're using either the .All or the .App metapackage in your ASP.NET Core project that targets .NET Core. There is, however, nothing that prevents you from installing individual packages instead of just the 1 monolithic metapackage. I do agree this sentence could use some clarification. I'll adjust it.

**Comment by pranavkm** [comment]
@pakrym has more expertise in this area.

**Comment by pakrym** [comment]
> @pranavkm @BrennanConroy Do either of you know why we say to not explicitly call AddAzureWebAppDiagnostics? Is this called automatically when targeting .NET Core?

There is an Azure AppServices site extension that calls `AddAzureWebAppDiagnostics` automatically when the app is running in Azure. It's available since 2.0

**Comment by madmox** [comment]
This is still not clear at all to me whether I should install the package `Microsoft.Extensions.Logging.AzureAppServices` or not, if I want to log to Azure diagnostics when deploying to an Azure web app & targeting .NET Core 2.1.

The documentation states:
* The provider package **isn't** included in the `Microsoft.AspNetCore.App` metapackage. To use the provider, install the package.

So at first I assumed I had to install the package. But then I read:
* The provider is automatically made available to the app when the app is deployed to Azure App Service.

And from here:
* The `Microsoft.Extensions.Logging.AzureAppServices` package **is** included in the ASP.NET Core metapackages.

It's very confusing. Is the package `Microsoft.Extensions.Logging.AzureAppServices` included in the ASP.NET Core metapackages, or not?

**Comment by scottaddie** [comment]
@madmox Something may have changed since I last responded. I've confirmed that the `Microsoft.Extensions.Logging.AzureAppServices` package is NOT included in the `Microsoft.AspNetCore.App` metapackage. Since you're targeting .NET Core 2.1, you WILL need to install the `Microsoft.Extensions.Logging.AzureAppServices` package. For future reference, you can confirm whether it's included or not in VS 2017 with these steps:

1. In Solution Explorer, expand your project's **Dependencies** node.
1. Expand **NuGet**, then expand **Microsoft.AspNetCore.App**.
1. Search for the package name.

**Comment by madmox** [comment]
So I just need to install the package in my solution (and activate logging in the portal) to enable Azure diagnostics on my web app once deployed, without **any** code addition? Like, maybe it justs make a dll available at runtime, and the site extension uses it.

**Comment by madmox** [comment]
What is confusing is:
* Since you're targeting .NET Core 2.1, you WILL need to install the Microsoft.Extensions.Logging.AzureAppServices package
versus:
* You shouldn't need a package reference to get logging in AppServices starting with AspNet Core 2.0.

I think I understand that the first sentance might just refer to the fact of being able to access the Azure logging API from my code, rather than just enabling Azure logging on the app, but this part of the documentation (and this thread) is confusing in a way.
