### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by Eldorian** [aspnet/Docs#7932]
I've been banging my head on this all day. 

Does this only work if the application is hosted on Azure? Is there something else that needs to happen in order to authenticate from an on prem server to Azure Key Vault - perhaps through Azure AD?

I have the VaultName, ClientId, and ClientSecret. The app is registered in Azure AD and I just flat out get an Access Denied every time I try and run this code. I feel like I'm missing something in this documentation somewhere.

I'm running on .net core 2.1.300

@Rick-Anderson 	edit: 3.9 K PV
Comment Hub: I like the content, but clear cut example of how to programatically access a simple secret (most simple use case) is obscured.
Content-Accuracy 12/19/2018  It is too abstract. The reader is viewing this page in order to add support for keyvault access to an application. This document does not focus on the practical steps required to do that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cc0b77a-df21-7007-5cec-4399d98c6dc6
* Version Independent ID: efe5ae5e-ff64-f1c7-6920-4512fc8f36d1
* Content: [Azure Key Vault configuration provider in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/security/key-vault-configuration.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/key-vault-configuration.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Eldorian ... No, the app doesn't need to be in Azure, and I retested the sample app just the other day when I updated the configuration provider code.

The text is a bit dated in that when I wrote this the Azure Portal didn't have an UI for adding secrets to the vault and setting access for the app. You probably noticed that they've added the needed UI to the portal to perform the steps without PS.

Since you have the ClientId and ClientSecret, I assume that those steps worked ok. If you're getting an access denied from the service, then it's not a connection problem.

You did give the app List and Get permission, correct?
The app is listed in the portal as having access to the key vault, correct? IIRC that's done on the key vault side after the app is registered in Azure AD.

**Comment by Eldorian** [comment]
> The app is listed in the portal as having access to the key vault, correct? IIRC that's done on the key vault side after the app is registered in Azure AD.

And this was the issue... I thought I had it registered, and the app was showing up under access policies. And then I noticed that the "save" button up top was clickable. I never saved it.

**Comment by guardrex** [comment]
Cool ... Leave this issue open. I'll crosslink it to the issue that I have open to update the topic. I'll probably keep the Powershell instructions and add the portal UI steps.

**Comment by Eldorian** [comment]
Just an FYI, our admin we have for Azure, also did this exact same thing. It might be worth calling out that you need to click save after changing the access policy or doing anything in the Key Vault as it appears it's all saved but really isn't.

Or convince someone to change the UX behavior in Azure :)

**Comment by SriharshaAngadi** [comment]
Hi Can this provider work with vault provided by HashiCorp https://www.vaultproject.io/ ?

**Comment by guardrex** [comment]
@SriharshaAngadi No, it's Azure Key Vault specific. You could look at how it has been developed and write your own provider perhaps if you can't find one from a 3rd party source. The reference source for this provider is here :point_right: https://github.com/aspnet/AspNetCore/tree/master/src/DataProtection/AzureKeyVault

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by Rick-Anderson** [comment]
@guardrex 	if you reopen this one, let me know why.

**Comment by guardrex** [comment]
The topic doesn't use Azure's preferred approach. At the time the topic was written, there was no portal capability to managing the secrets. The topic is 100% PowerShell. Since that time, the portal has all of the goodies to do everything thru the GUI. The topic can keep its PowerShell in place, but it should show the Azure portal steps, too.

However, it's up to you. If you want to just leave the topic PowerShell-only and let the devs access the Azure topics that deal with secrets, then that's ok. When I get to the sample update, I should be able to merely cross-link some resources to cover it.
