### ISSUE TITLE
Is there any sanitize library such as AntiXSS library for ASP.NET CORE

### ISSUE THREAD

**Issue by saineshwar** [aspnet/Docs#7962]
## General
Is there any sanitize library such as AntiXSS library for sanitizing Inputs in ASP.NET CORE

**Comment by guardrex** [comment]
Hello @saineshwar ... I don't have direct knowledge on them, but I see a few for ASP.NET Core in a NuGet search that you can investigate: https://www.nuget.org/packages?q=antixss

Our guidance for AntiXSS is here :point_right: https://docs.microsoft.com/aspnet/core/security/cross-site-scripting

**Comment by saineshwar** [comment]
hi @guardrex  in that document you have not show how to sanitizing Inputs  Regular Expression

**Comment by guardrex** [comment]
It seems that use of regular expressions wasn't a recommended or supported approach at the time the topic was written. The topic was (probably\*) reviewed by our security manager, `@blowdart`, so the approaches it describes and recommends are the only ones supported.

\*probably = The topic predates the repo (imported on Oct 28, 2016), and we can't see history prior to import. Therefore, I can't see who reviewed the topic when it was written.

Since the topic was written by @Rick-Anderson, I'll let him remark further on this.

**Comment by blowdart** [comment]
AntiXSS used to have sanitzation, but we pulled it, because it was broken and couldn't be fixed. Hence the confusion. There are no libraries from Microsoft for sanitization, we generally recommend Markdown (with a parser that strips embedded HTML) for rich text input.
