### ISSUE TITLE
Server-Side Caching Support

### ISSUE THREAD

**Issue by alohaninja** [aspnet/Docs#8045]
This seems to be only a client-side caching mechanism - the only server-side approach doesn't seem to be supported on .NET Core yet. Can we get some clarification here that this does not cache on the server? 

Reference: https://github.com/filipw/Strathweb.CacheOutput/issues/217

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6728e59-93ec-891e-0416-94819296ad72
* Version Independent ID: 5d581acc-c651-2112-844a-6b85dc5a99a6
* Content: [Response caching in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/response?view=aspnetcore-2.1)
* Content Source: [aspnetcore/performance/caching/response.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/performance/caching/response.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @alohaninja ... That's correct. It's a client-side cache that conforms to the HTTP spec, not a server-side cache. The request for server-side caching is at https://github.com/aspnet/Home/issues/2612. I'm going to close here, since this isn't actionable for the docs. You can ask the engineers further about it if you wish over on that issue.
