### ISSUE TITLE
ASP.NET Core Module stdout log

### ISSUE THREAD

**Issue by mikecasas** [aspnet/Docs#8095]
Nothing seemed to work until I capitalized the logs folder in my web.config. Mine looks like stdoutLogFile=".\Logs\stdout". My actual 'logs' folder is all lowercase.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4f16c68-708b-003e-8c63-1df60c6344d0
* Version Independent ID: 25fa0508-4450-9051-cdd7-0d3260c60b4f
* Content: [Troubleshoot ASP.NET Core on IIS](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/troubleshoot?view=aspnetcore-2.1)
* Content Source: [aspnetcore/host-and-deploy/iis/troubleshoot.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/iis/troubleshoot.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by jkotalik** [comment]
@mikecasas what version of the AspNetCoreModule are you using? We can confirm that the path is case insensitive in the new ANCM.

**Comment by mikecasas** [comment]
@jkotalik Is there a quick way to get the version number? Like a ```winver```

**Comment by guardrex** [comment]
@mikecasas See: https://docs.microsoft.com/aspnet/core/host-and-deploy/aspnet-core-module#module-version-and-hosting-bundle-installer-logs

**Comment by jkotalik** [comment]
Alright that is the most recent version. I'll file an issue to verify the behavior, and we can update the documentation. 

Slightly off topic, @guardrex @shirhatti @muratg when should we start writing docs for all of the work we have done with ANCM? Things are fairly stabilized now.

**Comment by guardrex** [comment]
@jkotalik Anytime for the issue. It would probably take a few weeks to get to the work given that I'm **_still_** trying to get back to 2.1 sample updates. 😅

Can you open a docs issue assigned to me with the work to be done? Otherwise if you can send me a list of your engineering issues/PRs of work that you want covered, I'll open an issue based on those.

Note that our versioning is by ASP.NET Core release, and it might be difficult to map ANCM updates exactly if they didn't coincide cleanly with Core releases. It's helpful for each ANCM enhancement to know if it fell in under 2.0 or 2.1 ... or is going to land for 2.2.

**Comment by pakrym** [comment]
I wasn't able to verify case-sensetivity of log file name. There is a known issue in V1 ACNM that you might be hitting: module doesn't automatically create subfolders so you have to have existing `Logs` directory for `stdoutLogFile=".\Logs\stdout"` to work.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
