### ISSUE TITLE
Can't switch to Razor Views at this Point

### ISSUE THREAD

**Issue by jasoncoe2** [aspnet/Docs#8142]
All, thanks for everything you do.  However, I can't switch as I have too many views already built.  I need some simple filtering and paging on a couple pages.  This is a bridge application that will be end of life in a couple years.  I just can't see the need to go back and redo all the work I did in Core 1.x or 2.0.  My next app will for sure use razor.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15e2038b-fa1b-897c-32ee-7173c7d1d909
* Version Independent ID: 000c5a97-c1b2-9a48-289d-83ec4f0c0c98
* Content: [ASP.NET Core MVC with EF Core - Sort, Filter, Paging - 3 of 10](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/sort-filter-page?view=aspnetcore-2.1)
* Content Source: [aspnetcore/data/ef-mvc/sort-filter-page.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-mvc/sort-filter-page.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
@jasoncoe2  did you want to report a problem with the document?

**Comment by lm28** [comment]
If you are going to have multiple "flavours" of a product (IE Razor vs MVC) then please PLEASE!!!!! ensure that you have a (preferably) different sample project for each. I have been chasing my tail for MONTHS trying to get ONE sample project to work because everything is so mixed up. How is anybody supposed to learn with so many ambiguities?
