### ISSUE TITLE
Old Angular version

### ISSUE THREAD

**Issue by chrisbilljones** [aspnet/Docs#8163]
This cli command uses an old angular version (5 vs 6). This is especially bad when you install up to date libraries like Material UI and get error messages all over the place due to version mismatch.
Can't you change the cli so that you pull the latest angular template automatically?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32a18270-91cd-2a02-2eb8-2c8b1ed03737
* Version Independent ID: c58d57e5-a0c2-201d-f6dd-076ad5971fcb
* Content: [Use the Angular project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/client-side/spa/angular.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/spa/angular.md)
* Product: **aspnet-core**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **scaddie**

**Comment by SteveSandersonMS** [comment]
In ASP.NET Core 2.2, we're updating the template to use the Angular 6.

Unfortunately we can't have it dynamically fetch the latest automatically, because then we would be unable to test newer versions to ensure they actually work within the middleware we're providing. Newer versions of third-party libraries frequently change in ways that require us to alter documentation or middleware to retain functionality.

**Comment by chrisbilljones** [comment]
Hi, thanks for your reply. IMHO you should at least state in the text, which Angular version is used.

**Comment by seansols** [comment]
I know this is a slightly older thread, but I came here on my quest to figure out why the tutorial didn't work with Angular 6. I found an interesting solution that you create the project per usual, then delete the ClientApp folder. Use Command Line to navigate to your Project folder, then execute "ng new ClientApp". Kinda makes you wonder why Visual Studio can't do "ng new" from the start tho.
