### ISSUE TITLE
Login link not generated after following all the steps

### ISSUE THREAD

**Issue by hmihail** [aspnet/Docs#8201]
I followed all the steps here, and after switching primary key to &lt;int&gt;, the 'Register' and 'Login' links are not generated anymore. In my html page I have just this: 
`<a class="nav-link" href="">Login</a>`

but the code looks like this:
`<li class="nav-item"><a asp-page="/Account/Login" class="nav-link">Login</a></li>`

For the page to work, I had to change the @inject statements like this:
```
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager 
```

Anyone has an ideea why?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5d03a65-2965-0261-3d05-bf2c89721fd2
* Version Independent ID: 37f74d7d-ed17-eb35-183d-02f04183f880
* Content: [Configure Identity primary key data type in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-primary-key-configuration?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/security/authentication/identity-primary-key-configuration.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/identity-primary-key-configuration.md)
* Product: **aspnet-core**
* GitHub Login: @AdrienTorris
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@hmihail  routing needs a valid route to generate a link. 

>For the page to work, I had to change the @Inject statements like this:

So is everything working? What's the correct URI for Login?

**Comment by hmihail** [comment]
The URI should by /Account/Login, but even if I enter in the browser that addres, I get 404:
`No webpage was found for the web address: https://localhost:44305/Account/Login`

**Comment by Rick-Anderson** [comment]
Try `https://localhost:44305/Identity/Account/Login`

**Comment by Rick-Anderson** [comment]
The links are not generated because you don't have a valid route. I'm not sure what you did wrong. You can probably get a quicker response on StackOverflow.

The login page doesn't use route data - so changing the PK doesn't affect routing.

**Comment by hmihail** [comment]
I did nothing else, it was an empty project. ijust followed the instructions here. 

With the link `https://localhost:44305/Identity/Account/Login` it works.
I tried StackOverflow, but nobody answered :(

I can provide the source code if necessary.

**Comment by Rick-Anderson** [comment]
> the link `https://localhost:44305/Identity/Account/Login` works.

That's because you're using the new 2.1 templates which use `/Identity` for the area. Your problem has nothing to do with changing the PK. You must have 2.0 code mixed with 2.1 code.

See 
* https://docs.microsoft.com/en-us/aspnet/core/migration/20_21?view=aspnetcore-2.1#changes-to-authentication-code
![image](https://user-images.githubusercontent.com/3605364/44598540-31eff380-a788-11e8-8448-2a0990864647.png)

* https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-2.1&tabs=visual-studio
* https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.1&tabs=visual-studio

**Comment by hmihail** [comment]
You are right, thanks for pointing that out. I have copied the `LoginPartial` code from somewhere, and missed the `asp-area="Identity"`.

Thank you!

**Comment by chpong** [comment]
I created an ASP.NET Core 2.1 MVC app with authentication enabled using individual user accounts (store user accounts in-app), and verified that the Identity's register and login links are generated correctly:
  - `https://localhost:XXXXX/Identity/Account/Register`
  - `https://localhost:XXXXX/Identity/Account/Login`

I followed the steps in this doc to change the identity user and identity role primary key to `Guid`. But it didn't work (bug for this doc?) because I also need to update the `Views/Shared/_LoginPartial.cshtml` with the following:
  - `@inject SignInManager<ApplicationUser> SignInManager`
  - `@inject UserManager<ApplicationUser> UserManager`

After that, I notice the Identity's register and login links are generated correctly. They became "unrouted":
  - `https://localhost:XXXXX/?area=Identity&page=%2FAccount%2FRegister`
  - `https://localhost:XXXXX/?area=Identity&page=%2FAccount%2FLogin`

Not only the link are not generated correctly, the previously working URLs stopped showing the register and login page content too:
  - `https://localhost:XXXXX/Identity/Account/Register`
  - `https://localhost:XXXXX/Identity/Account/Login`

Is this a known issue? Any idea how I can fix this?

Thank you.

**Comment by chpong** [comment]
Thanks @Rick-Anderson, @scottaddie, @HaoK and @javiercn for finding the fix.

The solution is applicable to ASP.NET Core 2.1 only (not 2.0). is to add **`.AddDefaultUI()`** in the Startup.cs:

    services.AddIdentity<ApplicationUser, ApplicationRole>()
        .AddEntityFrameworkStores<ApplicationDbContext>()
        .AddDefaultUI()
        .AddDefaultTokenProviders();

See [#6967](https://github.com/aspnet/Docs/issues/6967) for similar issue.

**Comment by scottaddie** [comment]
I'll be documenting this as part of https://github.com/aspnet/Docs/issues/8605

**Comment by rafaelalmeida12** [comment]
A interface do usuário da identidade é implementada usando o Razor Pages. Para que o roteamento do nó de extremidade os mapeie, adicione uma chamada MapRazorPagesno seu UseEndpointsretorno de chamada:
`
app.UseEndpoints(endpoints =>
{
    // ...
    endpoints.MapRazorPages();
});
`

**Comment by HousingCode** [comment]
`app.UseEndpoints(endpoints =>
{
// ...
endpoints.MapRazorPages();
});`

**Comment by Ankit2923** [comment]
Add "app.MapRazorPages()"  in the program.cs file
