### ISSUE TITLE
Update Getting Started Razor doc for Visual Studio for Mac to use New Project

### ISSUE THREAD

**Issue by sayedihashimi** [aspnet/Docs#8347]
In the [Introduction to Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-2.1&tabs=visual-studio-mac) doc for Visual Studio for Mac at the very top it instructs the reader to use `dotnet new` to create the Razor web project.

![image](https://user-images.githubusercontent.com/1283154/44857531-fea4dd00-ac3d-11e8-9543-60734b3b5f2d.png)

Visual Studio for Mac has a Razor template, the ASP.NET Core Web App template. This should be updated to instruct the reader how to create the project in Visual Studio for Mac instead of using `dotnet new`.

I just saw that [this tutorial](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages-mac/razor-pages-start?view=aspnetcore-2.1) does the same thing.

**Comment by Rick-Anderson** [comment]
Moved to #8369
@sayedihashimi  thanks for the report. We're creating doc issues from the GitHub integration at the bottom of the doc. That makes it more visible when we're updating the doc. We'll get this fixed in the next update.

This is not an onboarding tutorial despite being in the "Get started" section. The new instructions will be like the **Visual Studio** tab instructions, a link to another article.
