### ISSUE TITLE
Installing hosting bundle seems to cause restart of application pools

### ISSUE THREAD

**Issue by bernhof** [aspnet/Docs#8428]
While this is not an issue in itself, a mention of this in the docs under "Install the .NET Core Hosting Bundle" would be nice, since this can cause some hickups on (especially) older web applications that have special requirements for app pool recycling.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec484002-18c1-6a0d-00de-820d56f038d3
* Version Independent ID: 7903ce53-2cbb-f083-7479-c8abc30211a0
* Content: [Host ASP.NET Core on Windows with IIS](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/index?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/host-and-deploy/iis/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/iis/index.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @bernhof ... I can't speak to the current hosting bundle having this behavior (first that I've heard of this). Let's ask the engineers about it.

As a side-note: For the upcoming 2.2 release, they are going to make it so that the hosting bundle installer performs an IIS restart, which is going to have the same effect as what you're asking about. I'll use this issue to document that. For more info, see https://github.com/aspnet/IISIntegration/issues/1278.

@jkotalik @joeloff ... Does using the current hosting bundle installer cause some or all app pools to recycle?

**Comment by jkotalik** [comment]
The current hosting bundle can cause an iisreset (which stops all app pools) if the ANCM installers detect that IIS needs to reset to complete installation. We are working on making the installers reset no matter what because, as mentioned here: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.1&tabs=aspnetcore2x#install-the-net-core-hosting-bundle, net start/stop are required to pick up the dotnet path changes. Once the feature is verified and in, I'll ping this thread again so we can collaborate on making the docs correct.

**Comment by guardrex** [comment]
> Once the feature is verified and in, I'll ping this thread again so we can collaborate on making the docs correct.

In the meantime, I'll add a short note that pertains to the current installer and just mark the PR as addressing this issue to keep it open after we merge. I'll ping u for review on it shortly.

**Comment by bernhof** [comment]
Just wanted to put a quick thumbs up for responding so quickly to issues like this. Keep up the good work! 👍

**Comment by guardrex** [comment]
Thanks @bernhof ........ *just don't look at the backlog!* 🙈 :smile: lol ... I think what will happen is that there will be a decent break after all of the 2.2 issues are resolved (and the samples are updated) and before 3.0 gets on us where we can dig into the backlog. Well ...... it's a prayer to the :pray: *server gods* :pray: anyway. :smile:

**Comment by guardrex** [comment]
Fixed by https://github.com/aspnet/Docs/commit/4480bb13021dc33541e034bdcfaaa593f0b98c5e
