### ISSUE TITLE
Needed to reset Student ID seed value when re-initializing data

### ISSUE THREAD

**Issue by Millardh77** [aspnet/Docs#8504]
Just something that might help others...I had to reset the student ID after I had added a row in testing and then later attempting to invoke the DbInitializer.  When I allowed it to attempt to seed, I wasn't getting any data in the Enrollment table and it was throwing an error because the StudentID foreign key wasn't in sync with the identity field ID of the Student table.  I just ran: DBCC CHECKIDENT ('Student', RESEED, 0). and it fixed the issue. I wasn't sure if I just missed a step or something. :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/intro.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Millardh77  thanks for the tip. Changing the PK is generally not recommended and very problematic.

**Comment by Millardh77** [comment]
Not trying to pick, but in this situation, in order to get the data populated to all of the tables as expected, either the primary key has to be reset or each of the records in the enrolment table would have to be changed to reflect the new student ids to satisfy the FK constraint.  I know this is a tutorial with demo data and you wouldn't want to do that in a production environment, but I was only trying to get it to work and that was a simple solution.

**Comment by Loves2Code** [comment]
I have to agree with @Millardh77.
This is not an issue of changing a primary key.
This was a demo, where things are supposed to work.
An inexperienced developer would follow along and, as per instructions in the tutorial, add and delete a record in the Student table as part of testing the scaffolded Student Pages. In deleting the Student (or Students) they inserted, those StudentID's of 1 (or more) are no longer available, since the Student table is using IDENTITY INSERT - the values, once deleted, are no longer available.
When the student copies the code for inserting Enrollment records, the code is using StudentID's that will cause a referential constraint failure because the StudentID in the Enrollment table is a FOREIGN KEY.
Perhaps totally unaware that the Student table, once a Student record is deleted, will never allow a StudentID of "1", will insert data into the Enrollment table, as instructed, and get this error.  without the experience to see that the Enrollment records inserted have to start at the NEXT StudentID, not at "1", as the instructions tell us.
A novice would throw up their hands in frustration.
@Millardh77's solution is also correct, `DBCC CHECKIDENT ('Student', RESEED, 0)`, though it should be added to the tutorial in a way a novice can execute [I had to get to SQL Server Management Studio and [figure out how to connect to the (localdb)\\mssqllocaldb instance](https://dotnetthoughts.net/connecting-localdb-using-sqlserver-management-studio/)]. Otherwise, users who add and delete more than one record while testing the scaffolded Students forms will have to have different StudentID values inserted into the Enrollment table for the code to succeed.
