### ISSUE TITLE
M.A.App should be version-less

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#8579]
The templates don't generate a version. This sample shouldn't.
See [this PR](https://github.com/aspnet/Docs/commit/f3f87290d570fe07fe26526f40ceae6321998fff) to backout changes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cabe9331-b438-fabe-18ca-15f752ec6778
* Version Independent ID: 3294609f-b881-1fec-de04-2021b48de489
* Content: [Microsoft.AspNetCore.App metapackage for ASP.NET Core 2.1 and later](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/metapackage-app?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/metapackage-app.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/metapackage-app.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
I'll find out next Tuesday when `@natemcmaster` returns from VAC. Can you remind me then? I'm guessing yes.

**Comment by guardrex** [comment]
@Rick-Anderson Reminder to ask Nate about adding back the versions to our `App` package refs.

**Comment by natemcmaster** [comment]
After lots of discussion and experimentation, we are going to stick with original design -- versionless PackageReference is the recommended way to use Microsoft.AspNetCore.App. We should update our docs and guidance to match this recommendation.

Just FYI - we implemented and tested alternatives ways to reference the Microsoft.AspNetCore.App shared framework. While these might have been accepted if we had done them in the first place, we did not feel the benefits of switching approaches outweighed the costs. This was especially true as we began to design 3.0. In 3.0, we plan to rework the way shared frameworks are referenced in projects. Rather than introducing more churn, we're going to make some improvements in the 2.2 SDK for using the versionless PackageReference (see dotnet/sdk#2533), and will focus our efforts on making 3.0 better.
