### ISSUE TITLE
Best practice for compressing images?

### ISSUE THREAD

**Issue by daveabrock** [aspnet/Docs#8726]
Contributor question: do you have a standard way to compress images for use on the site? A common compression library? Any best practices? I just ended up using [TinyPNG](https://tinypng.com/).

**Comment by Rick-Anderson** [comment]
@daveabrock 	nope. 

cc @tdykstra 	@scottaddie 	@guardrex

**Comment by daveabrock** [comment]
I was able to use the [TinyPNG API](https://tinypng.com/developers) to do it. The screenshot ended up being the same exact size as the one I replaced. Would it be worth adding a section asking contributors to make sure to compress images/screenshots with their choice tool to help performance?

**Comment by tdykstra** [comment]
Image file compression the sort of thing we should be able to automate. I believe there's an outstanding work item to do that.  I'll check.

**Comment by tdykstra** [comment]
Turns out there is no work being done to automate image compression, apparently due to a concern about consequences for image quality.  So it would be OK to mention it as a manual process in the contributor guide.  But I would present it as an optional procedure, not as a recommended or required one.

**Comment by daveabrock** [comment]
Great, thanks. I'll get a PR in the next few days. Performance is near and dear to my heart but I will definitely phrase it gently as @tdykstra suggests. :)
