### ISSUE TITLE
Add Azure Table "Binding" tutorial

### ISSUE THREAD

**Issue by schey** [aspnet/Docs#8744]
It'd be great to see the same but with Azure storage tables instead of sql DB.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39b6d0f3-9bc7-d091-0d45-9fc1e2e7aac8
* Version Independent ID: 20e7eb53-215b-09ab-205d-d20177221278
* Content: [Add validation to an ASP.NET Core Razor Page](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/validation?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages/validation.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/validation.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @schey ... If there was an EF Core provider, it would have been a snap to wire up. There are no current plans to offer it, even with Cosmos dB. Therefore, this falls into the *roll your own* scenario bucket, but there might be some 3rd party options out there. Since there's no in-the-box way to do it, we won't be covering it in the docs. For reference, see ...

* https://github.com/aspnet/EntityFrameworkCore/issues/1142
* https://github.com/aspnet/EntityFrameworkCore/issues/13323
