### ISSUE TITLE
Manually utilizing model binders from RazorPages in ASP.Net Core 2.x

### ISSUE THREAD

**Issue by EliasCK** [aspnet/Docs#8745]
Asp.Net Core RazorPages has this feature where it'll automatically map URL queries and form data to a PageModel object using attributes like the BindPropertyAttribute.

```
public class MyModel : PageModel
{
    [BindProperty]
    public Customer Customer { get; set; }

    [BindProperty]
    public string SomeData { get; set; }
}
```

I would love to utilize that feature in my own pipeline, preferebly without having to have use PageModels as a base-class. But I've been unable to find any information on how to do so online. 

Would be cool if it was possible to do something like this:

`someModelBinder.BindContextToModel(myStronglyTypedModelOfQueriesAndFormData, httpContext);`

Is something like this achiveable atm?

**Comment by guardrex** [comment]
Hello @EliasCK ... This is the documentation repo with just a handful of doc authors monitoring. We recommend that general questions go to a support forum, such as Stack Overflow, or a support chat, such as Gitter or Slack. You'll get a much faster answer, since so many more devs are reading/responding on those forums.
