### ISSUE TITLE
Does this configuration provider support arrays?

### ISSUE THREAD

**Issue by Jaffacakes82** [aspnet/Docs#8750]
The configuration for Serilog in the appsettings.json file looks something like this:

```
"Serilog": {
    "MinimumLevel": "Debug",
    "WriteTo": [
      {
        "Name": "AzureTableStorage",
        "Args": {
          "storageTableName": "logs",
          "connectionString": ""
        }
      }
    ]
  }
```

I've been trying to replicate the structure using the '--' delimiter notation so I can store the connection string in Key Vault and inject it at runtime but it doesn't appear to be working. Is it possible to replicate the Serilog configuration object using this provider?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cc0b77a-df21-7007-5cec-4399d98c6dc6
* Version Independent ID: efe5ae5e-ff64-f1c7-6920-4512fc8f36d1
* Content: [Azure Key Vault configuration provider in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/key-vault-configuration.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/key-vault-configuration.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Jaffacakes82 ... *Yes*, but make sure you use the approach in the prefix sample that replaces the double-dash (`--`) in AKV keys with a colon (`:`) for configuration ...

https://github.com/aspnet/Docs/blob/master/aspnetcore/security/key-vault-configuration/samples/key-name-prefix-sample/2.x/Program.cs#L33

https://github.com/aspnet/Docs/blob/master/aspnetcore/security/key-vault-configuration/samples/key-name-prefix-sample/2.x/Startup.cs#L36-L62

... barring the prefix parts ... You don't need to implement those bits, since that doesn't apply to your scenario.

The keys/values will be ...

| AKV Key | Value | Read in config as |
| --- | --- | --- |
| `Serilog--MinimumLevel` | `Debug` | `Serilog:MinimumLevel` |
| `Serilog--WriteTo--Name` | `AzureTableStorage` | `Serilog:WriteTo:Name` |
| `Serilog--WriteTo--Args--storageTableName` | `logs` | `Serilog:WriteTo:Args:storageTableName` |
| `Serilog--WriteTo--Args--connectionString` | *value* | `Serilog:WriteTo:Args:connectionString` |

> it doesn't appear to be working

Make sure that your AVK provider (`AddAzureKeyVault`) is **after** the File Configuration Provider (`AddJsonFile`) or call to `CreateDefaultBuilder`.

I also note that the sample README (possibly the "basic" sample; possibly language in the topic) could use a touch of work. There are two samples here (basic and prefix). The "prefix" sample has the bits to store hierarchical keys in AKV and load them properly for configuration of the app, but the "basic" sample doesn't. The "basic" sample is set up for the simplest case, which is just to read non-hierarchical keys from AKV. I think the "basic" sample should use the same approach as the "prefix" sample, but I need to take a closer look and mull it over a bit more. 

I'm out on vacation until the end of next week 🏖, and I'll take a closer look when I get back. In the meantime, see the "prefix" sample and see if you have your keys set up as I show. Let me know if you have a :smile: or ☹️ outcome. Let's leave this issue open either way until I can take a closer look.

**Comment by Jaffacakes82** [comment]
Thanks for getting back to me so quickly @guardrex, I think it's still a 😞outcome for now.

I've got it working for other hierarchical values e.g. connection strings and my Serilog keys do match those you have detailed above.

Do I not have to index the 'WriteTo' property?

Enjoy your vacation :).

**Comment by guardrex** [comment]
> Do I not have to index the 'WriteTo' property?

"index" ?? I don't follow.

WRT troubleshooting: You could have it show you what it's bringing into configuration from AKV. I have a test app that does it this way ...

```cshtml
@using Microsoft.Extensions.Configuration
@inject IConfiguration Configuration

...

@foreach(var kvp in Configuration.AsEnumerable())
{
    <li>@kvp.Key : @kvp.Value</li>
}
```

**Comment by Jaffacakes82** [comment]
Serilog expects an array of sink configuration objects to the 'WriteTo' property. Will the AKV provider be clever enough to expand a secret with the following name for example?

`Serilog--WriteTo[0]--Args--connectionString`

I'll do some debugging and let you know what I find.

**Comment by guardrex** [comment]
> Will the AKV provider be clever enough to expand a secret with the following name for example?

Good question ... I don't know. Normally, array binding to a POCO class uses a "colon-array index-colon" structure (e.g., `entry:0:key`, `entry:1:key`, ... `entry:[n]:key`); however, I wouldn't be surprised if it was **not** capable of doing that.

**Comment by Jaffacakes82** [comment]
OK, I've got it working locally using the notation in your comment above. Thanks for your help! It's still blowing up from my Azure Web App but I'm guessing this is probably something wrong with the deployment.

You're a legend!

**Comment by guardrex** [comment]
Let's leave this open. This issue will auto-close when the PR merges.
