### ISSUE TITLE
Add documentation for "Hosting considerations" when running SignalR

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Docs#8755]
**Describe the new topic**

- There are various things that can affect ASP.NET Core SignalR deployments that we need to document
   - Sticky sessions are required, it would be good to show in a couple of common environments how that is setup
      - Azure App Service
      - HA proxy (link to external doc)
      - nginx (link to external doc)
      - kubernetes (https://github.com/aspnet/SignalR/issues/2333#issuecomment-391396158)
   - Controlling the number of concurrent connections via the various servers
      - IIS (we need to see if this is even possible)
      - Kestrel
  - A short blurb that describes the fact that multiple servers requires a backplane and we have redis built in (link to the scale out doc that we don't have yet https://github.com/aspnet/Docs/issues/7814)

**Comment by anurse** [comment]
HAProxy: https://www.haproxy.com/blog/load-balancing-affinity-persistence-sticky-sessions-what-you-need-to-know/

nginx: https://docs.nginx.com/nginx/admin-guide/load-balancer/http-load-balancer/#sticky

This could possibly be merged with the high-level parts of #7814 and then the Redis-specific stuff could be moved off to a sub-doc or something. There's a lot of similarity here since most modern applications are hosted with multiple server instances, which means scale-out is a consideration.
