### ISSUE TITLE
Update routing docs

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#8763]
*From @JamesNK (https://github.com/aspnet/Routing/issues/720)* ...

- [x] **catchAll @JamesNK (https://github.com/aspnet/Docs/pull/8759)
- [x] Discuss MVC's EnableEndpointRouting flag @guardrex
- [x] Conceptual differences between Endpoints and Routes @rynowak
- [x] Differences in behaviour between Endpoints and Routes (mostly link generation) @rynowak
- [x] Link Generator @rynowak
- [x] Extensibility via Parameter Transformers @JamesNK (https://github.com/aspnet/Docs/pull/8759)
- [x] Extensibility via Endpoint Selector @rynowak

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32374077-e02e-d6a6-1cea-05e58447b7cd
* Version Independent ID: 86aeab13-1c25-9fc1-4e56-0390cb40c242
* Content: [Routing in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/routing.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/routing.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by rynowak** [comment]
*I'm adding my own little summary here of what I think is the important information. Feel free to edit, rewrite and transform this into content that makes sense in the flow of the existing docs.* 👍 

# Conceptual differences between Endpoints and Routes

Endpoint routing is a new routing and dispatching system that changes how frameworks like MVC and primitives like middleware interact. For most application developers these details won't be important, but Endpoint Routing introduces new concepts and capabilities that the ASP.NET Core platform will leverage increasing over the next few releases.

Endpoint routing introduces the eponymous `Endpoint` class - a data type for a unit of routing. Frameworks like MVC register all of their endpoints, and the routing implementation makes all routing/dispatching decisions based on programmable and extensible criteria. The endpoint contains a delegate that can be executed and also a collection of arbitrary metadata objects. The metadata is used by middleware to implement cross-cutting concerns based on policies and configuration attached to each endpoint.

When a routing middleware executes, it sets an `Endpoint` and route values to a feature on the `HttpContext`. Middleware running after the routing middleware can see the `Endpoint` and can take actions based on the middleware. Example: an authorization middleware can interrogate the endpoint's metadata collection for an authorization policy that has been applied. When all middleware have executed - the endpoint's delegate is invoked.

The routing system in Endpoint Routing is responsible for all dispatching decisions. Since middleware apply policies based on the selected endpoint, it is important that any decision that can affect dispatching or the application of security policies be made inside the routing system. Previously MVC had its own layer of dispatching functionality including selecting an action by route values, selecting an action by HTTP method, selecting an action by content type. These features have been re-implemented on top of Endpoint Routing extensibility so they can be used by other frameworks or features.

Endpoint Routing also introduces the `LinkGenerator` API which is backed by the concept of an *address* and *address schemes*. An address scheme is a way of determining which endpoints should be consider for link generation - for example, the route name + route values features many users are familiar with from MVC are implemented as an *address scheme*. 

When the `LinkGenerator` is called the provided *address* is used to look up a set of candidate endpoints. Then each endpoint is tried in order to see if link generation is possible based on the provided data.

Endpoint Routing also supports most of the common features for application developers such as:
- Route template syntax
- Conventional-style and attribute-style configuration
- `IRouteConstraint`
- link generation via `IUrlHelper` (used by Tag Helpers and Html Helpers) in MVC

A comparison...

**IRouter-based routing:**
- `IRouter`-centric (a piece of code that makes routing decisions)
- Routing decisions made at the *end* of the middleware pipeline
- No way for middleware to know what will be matched
- No way to enumerate all things that are routable
- URI generation works based on route values + route name
- Each `IRouter` is a black-box and can have an arbitrary implementation (MVC is an implementation)

**Endpoint Routing:**
- `Endpoint`-centric (a thing that can be routed to)
- Routing decisions can be made wherever desired in the middleware pipeline
- Middleware that appear after a *routing* middleware can inspect the result
- Possible to enumerate all `Endpoint`s (all things that can be routed to)
- URI generation is based on *addresses* - supports arbitrary extensiblity
- Frameworks register endpoints, one predictable implementation of routing features


Endpoint routing introduces some new concepts for how dispatching is done and how URI generation is done. For the most ap

**Comment by rynowak** [comment]
*I'm adding my own little summary here of what I think is the important information. Feel free to edit, rewrite and transform this into content that makes sense in the flow of the existing docs.* 👍

# Differences in behaviour between Endpoints and Routes (mostly link generation)

Endpoint routing is designed to be as compatible as possible with the experiences that application developers rely on for routing and linking functionality. Most features in MVC will behave identically for typical use cases.  Some noteworthy intentional differences in behaviour are listed here...

---

Link Generation as used by MVC with conventional routes will behave differently when attempting to link to an action/controller that does not exist.

```
app.UseMvc(routes =>
{
    routes.MapRoute("default", "{controller=Home}/{action=Index}/{id?}");
});
```

Suppose you tried to generate a link to an action using this route.
```
Url.Action("ReadPost", "Blog", new { id = 17, });
```

In `IRouter`-based routing the result of this is always `/Blog/ReadPost/17` even if the `BlogController` does not exist or does not have a `ReadPost` action method.

In Endpoint Routing the result will be `/Blog/ReadPost/17` if the action method exists, and `` (empty string) if it does not. Conceptually, Endpoint Routing does not know what to link to if the action does not exist. 

----

*Ambient value invalidation* for link generation behaves differently when uses with Endpoint Routing. *Ambient value invalidation* is the algorithm that decides which route values from the currently executing request (the ambient values) can be used in link generation operations.

In general the idea behind ambient values and ambient value invalidation is to be provide a convenience for the common case of linking back to the same URI as the currently executing request. This is common because a form will typically perform an HTTP POST to the same URI - which will be handled by the a different action method. This is a typical pattern for MVC controllers and Razor Pages.

```
app.UseMvc(routes =>
{
    routes.MapRoute("default", "{controller=Home}/{action=Index}/{id?}");
});
```

```
@* In /Views/Store/Purchase.cshtml *@

<form asp-action="Purchase">
</...>
```
If the URI matched was `/Store/Checkout/18` then the route values would be `{ controller = "Store", action = "Purchase", id = "18", }`. All of these route values would be reused and the same URI would result.

However, this feature as-implemented in `IRouter` for usages in MVC when using attribute routing or with Razor Pages has some undesirable characteristics. When linking to another action (or another page) route values can be reused in ways that are unfamiliar and undesirable (based on the original purpose stated above).

```
@* In /Pages/Store/Info.cshtml *@
@page "{id}"
@Url.Page("/Login")
```
```
@* in /Pages/Login.cshtml *@
@page "{id?}"
```
If the URI matched was `/Store/Info/18` then in `IRouter`-based routing, the link generated on the `Store/Info` page would be `/Login/18`. The `id` value of `18` would be reused even though the link destination was a different part of the application entirely.

In Endpoint Routing, the result will be `/Login`. Ambient values are not reused when the destination for linking is a different action or page.

**Comment by rynowak** [comment]
*I'm adding my own little summary here of what I think is the important information. Feel free to edit, rewrite and transform this into content that makes sense in the flow of the existing docs.* 👍

# Link Generator

Endpoint Routing provides a new API called `LinkGenerator` that performs URI generation. `LinkGenerator` is a singleton service that can be retrieved from DI, and it can be used outside of the context of an executing request. MVC's `IUrlHelper` and features that rely on it (Tag Helpers, Html Helpers, and Action Results) have been updated to use the `LinkGenerator` to provide the same functionality.

NOTE: `LinkGenerator` has a lot of stuff on it that we don't think will be useful to users in 2.2. I'm just describing the things I think users should want to use now. 

`LinkGenerator` can link to MVC's actions and pages via the `GetPathByAction`, `GetUriByAction`, `GetPathByPage`, and `GetUriByPage` extension methods. There are two flavours of each of these, one with an `HttpContext` and one without. These methods are functionally equivalent to `Url.Action` and `Url.Page` but offer more flexibility and options. The `GetPath...` methods are most similar to `Url.Action` and `Url.Page` in that the generate a URI containing an absolute path. The `GetUri...` methods always generate an absolute URI containing a scheme and host.

The methods that accept an `HttpContext` are said to generate a URI in the context of the executing request. The ambient route values, URL base path, scheme, and host from the executing request will all by used unless overridden. 

NOTE: I don't have too much to say about this because its very similar to existing things in purpose. The details of how the APIs work are documented in the code:
https://github.com/aspnet/Mvc/blob/release/2.2/src/Microsoft.AspNetCore.Mvc.Core/Routing/PageLinkGeneratorExtensions.cs
https://github.com/aspnet/Mvc/blob/release/2.2/src/Microsoft.AspNetCore.Mvc.Core/Routing/ControllerLinkGeneratorExtensions.cs

NOTE: SECURITY SECURITY SECURITY - Take care when using `GetUri...` in an application configuration that does not validate the host header of incoming requests. These features are convenient to use, but if the host header of incoming requests has not be validated, can expose untrusted input from a request back in URIs on a page. We recommend that all production applications configure their serve to validate the host header against known valid values.

NOTE:  Take care when using `LinkGenerator` from middleware in combination with `Map` or `MapWhen. `Map` changes the base path of the executing request which will affect the output of link generation. All of the `LinkGenerator` APIs allow specifying a base path - specify an empty base path to undo `Map`s effect on link generation.





*I'm adding my own little summary here of what I think is the important information. Feel free to edit, rewrite and transform this into content that makes sense in the flow of the existing docs.* 👍

# Endpoint Selector

NOTE: I think this section is very low priority. These features are advanced extensibility that is provided for frameworks and libraries. I don't expect application developers to use these features.

Endpoint Routing exposes some new extensibility points for influencing how endpoints are matched to requests. 

The `EndpointSelector` is a service that can be replaced that makes the final decision given a set of endpoints that match the request. https://github.com/aspnet/Routing/blob/release/2.2/src/Microsoft.AspNetCore.Routing/Matching/EndpointSelector.cs The `EndpointSelect` runs at the end of the matching process, and can see all of the candidates that were considered and whether or not they are consider valid.

The `IEndpointSelectorPolicy` allows plugging in a policy that can filter the set of candidates for a request or can short-circuit the request by returning a *rejection endpoint*. https://github.com/aspnet/Routing/blob/release/2.2/src/Microsoft.AspNetCore.Routing/Matching/IEndpointSelectorPolicy.cs Implementations of `IEndpointSelectorPolicy` should inherity from `MatcherPolicy` and must be registered as a singleton service of type `MatcherPolicy`. An implementation might also want to implement `IEndpointComparerPolicy` to provide a sort order for endpoints.

Examples of features that could be implemented by these extensibility points:
- Versioning
- A/B testing
- Overloading (based on query string or another criteria)

**Comment by rynowak** [comment]
*I'm adding my own little summary here of what I think is the important information. Feel free to edit, rewrite and transform this into content that makes sense in the flow of the existing docs.* 👍

# Link Generator

Endpoint Routing provides a new API called `LinkGenerator` that performs URI generation. `LinkGenerator` is a singleton service that can be retrieved from DI, and it can be used outside of the context of an executing request. MVC's `IUrlHelper` and features that rely on it (Tag Helpers, Html Helpers, and Action Results) have been updated to use the `LinkGenerator` to provide the same functionality.

NOTE: `LinkGenerator` has a lot of stuff on it that we don't think will be useful to users in 2.2. I'm just describing the things I think users should want to use now. 

`LinkGenerator` can link to MVC's actions and pages via the `GetPathByAction`, `GetUriByAction`, `GetPathByPage`, and `GetUriByPage` extension methods. There are two flavours of each of these, one with an `HttpContext` and one without. These methods are functionally equivalent to `Url.Action` and `Url.Page` but offer more flexibility and options. The `GetPath...` methods are most similar to `Url.Action` and `Url.Page` in that the generate a URI containing an absolute path. The `GetUri...` methods always generate an absolute URI containing a scheme and host.

The methods that accept an `HttpContext` are said to generate a URI in the context of the executing request. The ambient route values, URL base path, scheme, and host from the executing request will all by used unless overridden. 

NOTE: I don't have too much to say about this because its very similar to existing things in purpose. The details of how the APIs work are documented in the code:
https://github.com/aspnet/Mvc/blob/release/2.2/src/Microsoft.AspNetCore.Mvc.Core/Routing/PageLinkGeneratorExtensions.cs
https://github.com/aspnet/Mvc/blob/release/2.2/src/Microsoft.AspNetCore.Mvc.Core/Routing/ControllerLinkGeneratorExtensions.cs

NOTE: SECURITY SECURITY SECURITY - Take care when using `GetUri...` in an application configuration that does not validate the host header of incoming requests. These features are convenient to use, but if the host header of incoming requests has not be validated, can expose untrusted input from a request back in URIs on a page. We recommend that all production applications configure their serve to validate the host header against known valid values.

NOTE:  Take care when using `LinkGenerator` from middleware in combination with `Map` or `MapWhen. `Map` changes the base path of the executing request which will affect the output of link generation. All of the `LinkGenerator` APIs allow specifying a base path - specify an empty base path to undo `Map`s effect on link generation.





*I'm adding my own little summary here of what I think is the important information. Feel free to edit, rewrite and transform this into content that makes sense in the flow of the existing docs.* 👍

# Endpoint Selector

NOTE: I think this section is very low priority. These features are advanced extensibility that is provided for frameworks and libraries. I don't expect application developers to use these features.

Endpoint Routing exposes some new extensibility points for influencing how endpoints are matched to requests. 

The `EndpointSelector` is a service that can be replaced that makes the final decision given a set of endpoints that match the request. https://github.com/aspnet/Routing/blob/release/2.2/src/Microsoft.AspNetCore.Routing/Matching/EndpointSelector.cs The `EndpointSelect` runs at the end of the matching process, and can see all of the candidates that were considered and whether or not they are consider valid.

The `IEndpointSelectorPolicy` allows plugging in a policy that can filter the set of candidates for a request or can short-circuit the request by returning a *rejection endpoint*. https://github.com/aspnet/Routing/blob/release/2.2/src/Microsoft.AspNetCore.Routing/Matching/IEndpointSelectorPolicy.cs Implementations of `IEndpointSelectorPolicy` should inherity from `MatcherPolicy` and must be registered as a singleton service of type `MatcherPolicy`. An implementation might also want to implement `IEndpointComparerPolicy` to provide a sort order for endpoints.

Examples of features that could be implemented by these extensibility points:
- Versioning
- A/B testing
- Overloading (based on query string or another criteria)

**Comment by rynowak** [comment]
*I'm adding my own little summary here of what I think is the important information. Feel free to edit, rewrite and transform this into content that makes sense in the flow of the existing docs.* 👍

# Link Generator

Endpoint Routing provides a new API called `LinkGenerator` that performs URI generation. `LinkGenerator` is a singleton service that can be retrieved from DI, and it can be used outside of the context of an executing request. MVC's `IUrlHelper` and features that rely on it (Tag Helpers, Html Helpers, and Action Results) have been updated to use the `LinkGenerator` to provide the same functionality.

NOTE: `LinkGenerator` has a lot of stuff on it that we don't think will be useful to users in 2.2. I'm just describing the things I think users should want to use now. 

`LinkGenerator` can link to MVC's actions and pages via the `GetPathByAction`, `GetUriByAction`, `GetPathByPage`, and `GetUriByPage` extension methods. There are two flavours of each of these, one with an `HttpContext` and one without. These methods are functionally equivalent to `Url.Action` and `Url.Page` but offer more flexibility and options. The `GetPath...` methods are most similar to `Url.Action` and `Url.Page` in that the generate a URI containing an absolute path. The `GetUri...` methods always generate an absolute URI containing a scheme and host.

The methods that accept an `HttpContext` are said to generate a URI in the context of the executing request. The ambient route values, URL base path, scheme, and host from the executing request will all by used unless overridden. 

NOTE: I don't have too much to say about this because its very similar to existing things in purpose. The details of how the APIs work are documented in the code:
https://github.com/aspnet/Mvc/blob/release/2.2/src/Microsoft.AspNetCore.Mvc.Core/Routing/PageLinkGeneratorExtensions.cs
https://github.com/aspnet/Mvc/blob/release/2.2/src/Microsoft.AspNetCore.Mvc.Core/Routing/ControllerLinkGeneratorExtensions.cs

NOTE: SECURITY SECURITY SECURITY - Take care when using `GetUri...` in an application configuration that does not validate the host header of incoming requests. These features are convenient to use, but if the host header of incoming requests has not be validated, can expose untrusted input from a request back in URIs on a page. We recommend that all production applications configure their serve to validate the host header against known valid values.

NOTE:  Take care when using `LinkGenerator` from middleware in combination with `Map` or `MapWhen. `Map` changes the base path of the executing request which will affect the output of link generation. All of the `LinkGenerator` APIs allow specifying a base path - specify an empty base path to undo `Map`s effect on link generation.





*I'm adding my own little summary here of what I think is the important information. Feel free to edit, rewrite and transform this into content that makes sense in the flow of the existing docs.* 👍

# Endpoint Selector

NOTE: I think this section is very low priority. These features are advanced extensibility that is provided for frameworks and libraries. I don't expect application developers to use these features.

Endpoint Routing exposes some new extensibility points for influencing how endpoints are matched to requests. 

The `EndpointSelector` is a service that can be replaced that makes the final decision given a set of endpoints that match the request. https://github.com/aspnet/Routing/blob/release/2.2/src/Microsoft.AspNetCore.Routing/Matching/EndpointSelector.cs The `EndpointSelect` runs at the end of the matching process, and can see all of the candidates that were considered and whether or not they are consider valid.

The `IEndpointSelectorPolicy` allows plugging in a policy that can filter the set of candidates for a request or can short-circuit the request by returning a *rejection endpoint*. https://github.com/aspnet/Routing/blob/release/2.2/src/Microsoft.AspNetCore.Routing/Matching/IEndpointSelectorPolicy.cs Implementations of `IEndpointSelectorPolicy` should inherity from `MatcherPolicy` and must be registered as a singleton service of type `MatcherPolicy`. An implementation might also want to implement `IEndpointComparerPolicy` to provide a sort order for endpoints.

Examples of features that could be implemented by these extensibility points:
- Versioning
- A/B testing
- Overloading (based on query string or another criteria)

**Comment by rynowak** [comment]
Sorry for the spam. You can blame the github outage for this I think. As I sat there whistfully resubmitting this all afternoon and evening. Note that the posts get more correct and complete over time.

**Comment by guardrex** [comment]
@rynowak This isn't going as smoothly as I would've liked. Just a note for the future here.

Your notes are good, but the notes only moderately align with the sections of the topic, and we're versioning for old vs. new ... not seeking to compare and contrast `IRouter`-based vs. `Endpoint`-based.

Some of the routing members that aren't mentioned in your notes are mixed into the text in places where your notes indicate a change either in how routing works or behaves. It's not clear in those spots if the unmentioned members are still there and still work in roughly the same way. I'll search to confirm if a member still exists. If so, I'll assume it works about the same way.

In the future for *rip-the-guts-out-of-it* overhauls of sections of the framework, I recommend:

1. An engineer creates a doc branch (not a PR) and ...
    * Indicates old vs. new and calls out the diffs right in the topic. This can be accomplished by agreeing on a notation scheme for comments (i.e., all engineering notes are in blockquote).
    * Add paragraphs/sections (notes) for completely new content.
1. The docs team member wordsmiths the content and applies the versioning from there.

I mention this for the future ... not for this issue/PR, per se.

I'm 🤞 on this, but this PR could turn out to be a 👻 **_FrankenDoc_**:tm: 🎃. 😨

**Comment by guardrex** [comment]
@rynowak Quick ❓: The topic is all over the map on *URI* and *URL*. It seems like it would be safe for me to convert all instances to **URI**; and then where you determine it should be *URL* on review, I can revert in those spots. Does that sound good to u?
