### ISSUE TITLE
TempData isn't persisting data on Production Server [ASP.NET CORE 2.1]

### ISSUE THREAD

**Issue by Oscar3000** [aspnet/Docs#8774]
Hello, I have an issue and I have searched the docs to see maybe I made a mistake or something. My issue is this, After saving a product, I use the PRG(Post-Redirect-Get) pattern so the user doesn't resubmit the form when pressing the browser back button. I display a one time message using TempData since it persists data to the next request before deleting. This method works fine on my development environment. But after I deploy the application to a production server, although the action methods follow the PRG pattern, the TempData isn't persisted. I want to know if it's because it is hosted behind a reverse proxy server(in my case IIS).

**Comment by guardrex** [comment]
Hello @Oscar3000 ... I think you'll need to ask on a support forum, such as Stack Overflow, or a support chat, such as Gitter or Slack. Here on the docs repo, there are only a few docs authors monitoring the issues. If you open a question on SO, you'll get dozens/hundreds of dev eyes on the scenario. If you think there is some strange framework behavior involved, you can also reach out to the Microsoft engineers by opening an issue on the [aspnet/Home issues](https://github.com/aspnet/Home/issues) (be sure to provide plenty of scenario info and if you can post a repro project up to GH it's often helpful to them).

If you figure out that there is a docs coverage issue, please do post back here so that we can take a look.
