### ISSUE TITLE
JSON FileProvider does not mention new method .ConfigureAppConfiguration() on the WebHostBuilder. 

### ISSUE THREAD

**Issue by PhilPeters304** [aspnet/Docs#8795]
When trying to add my own custom JSON file to the configuration using ASP .NETCore 2.1 I had to use .ConfigureAppConfiguration() instead of  .AddJsonFile() as the latter wouldn't add the configuration to the provider list.  Couldn't find that documented here

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-2.1#json-configuration-provider)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @PhilPeters304 ... You didn't mean to say "instead of," did you? Did you mean to say you had to use `AddJsonFile` **_inside of_** `ConfigureAppConfiguration`?

It's covered a little earlier in the *Providers* section ...

https://docs.microsoft.com/aspnet/core/fundamentals/configuration#providers

Yes, I see an update that will help resurface it in the provider sections ...

Just prior to each mention of `UseConfiguration`, the sections should add that to configure the app to use `ConfigureAppConfiguration` and link back up to the *Providers* section.

Thanks for opening this. We just did a major overhaul of the topic a couple of weeks ago, and your feedback will help improve it.

**Comment by PhilPeters304** [comment]
Sorry yes! I did mean that exactly!  I read too far down! Thanks
