### ISSUE TITLE
Can't Figure Out How to get Code to Work

### ISSUE THREAD

**Issue by regal60740** [aspnet/Docs#8807]
When I get to this code in the tutorial : 
var todoClient = new TodoClient();

// Gets all to-dos from the API
var allTodos = await todoClient.GetAllAsync();

// Create a new TodoItem, and save it in the API
var createdTodo = await todoClient.CreateAsync(new TodoItem());

// Get a single to-do by ID
var foundTodo = await todoClient.GetByIdAsync(1);

I don't know how to use it. I wish you would just give us the steps to use the code and not assume we know what you are talking about. Many of us are Jr. Developers and we are not familiar with your code so please assume we know nothing and give us detailed instructions instead of bits of code that we have to figure what to do with.  That is one of the reasons I don't like Microsoft tutorials. They are many times not detailed enough and I waste many hours just to figure out what to do. I have been working with software for a while and I can just imaging what a true beginner would go through. They probably just get frustrated and give up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2483813a-3c16-7ddd-3160-43e6843b55d4
* Version Independent ID: 25f7fb5b-92b0-a45b-57ab-fdceab571884
* Content: [Get started with NSwag and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-nswag?view=aspnetcore-2.1&tabs=visual-studio%2Cvisual-studio-xml)
* Content Source: [aspnetcore/tutorials/getting-started-with-NSwag.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/getting-started-with-NSwag.md)
* Product: **aspnet-core**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Can you download the completed sample and compare?

**Comment by Rick-Anderson** [comment]
Can you go through https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.1 first?

**Comment by regal60740** [comment]
I downloaded the code yesterday and will work with it today to try and get
it to work. I was using a different program yesterday and for some reason,
some of the methods were giving me errors saying they did not exist even
though they did exist.

**Comment by regal60740** [comment]
I did the program above (first-web-api). That doesn't help me with this tutorial. I am trying to do your instructions for the Xamarin.Forms: Copy the generated C# code into a file in a client project (for example, a Xamarin.Forms app). I can't get the C# code to work in the program. I created the first program and can get an Android Emulator to run but I can't get the C# class added to the program to run it. I've spent a day on this and this is what I was talking about when I said you assume we know what you are talking about and we don't. You should put this in your tutorial and show us how to add the generated C# file to the Xamarin.Form project. I am having all kinds of reference errors and can't get your code to work that is calling the TodoClient class.

**Comment by zuckerthoben** [comment]
What kind of Xamarin.Forms approach (Shared or Standard Library) are you using and where are you putting the code that is generated by swagger? If you use a .NET Standard Library you can put the TodoClient class directly in there. Most likely you will need to add a reference to the Component Model DataAnnotations NuGet package (in all Xamarin client projects) and perhaps Newtonsoft.JSON, so that the client class is free of build errors. After you built the standard library in Visual Studio you will be able to use the TodoClient in this Standard Library.  @regal60740

**Comment by regal60740** [comment]
I used the Standard Library. I'm having issues with the await keyword now.
I can't seem to just plug your code in without the await errors. I put the
code generated by swagger in a class file called TodoClient.cs and put it
in App2 project. There is also an Android project and a IOS project. The
Android project runs OK. I am trying to get the TodoClient.cs file to run
with the Android Emulator.

**Comment by regal60740** [comment]
I've fixed the await errors, but now I'm getting errors for missing
App2.dll.

**Comment by zuckerthoben** [comment]
Pls zip and upload your sample solution and link it here so that we can find and fix the issue.  @regal60740

**Comment by regal60740** [comment]
Here is the zipped solution. Thanks.
 App2.zip
<https://drive.google.com/file/d/1DM9lRmIdvuDVNZaQIgWTVny5BHvKOwR6/view?usp=drive_web>

**Comment by regal60740** [comment]
I installed this package but it installed in the Android project and not
the App2 project which is the problem I have been having all along. The
TodoClient class is in the App2 project. If I try to put it in the Android
project, it is not seen and Intellisense tells me to put it in the App2
project.

**Comment by zuckerthoben** [comment]
Generally always install all NuGet packages in all Xamarin client projects.

**Comment by regal60740** [comment]
The program builds now but when I run it, I get an exception.

**Comment by zuckerthoben** [comment]
And what is this exception? If you want to get help on the internet, you have to give the people a good amount of information so that they are able to give advice. Also try searching explicit resolutions to exceptions you are facing.

@regal60740  Try following the documentation for getting started:
Xamarin.Forms: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/get-started/ 
.NET Core: https://docs.microsoft.com/en-us/dotnet/core/get-started?tabs=windows
ASP.NET Core: https://docs.microsoft.com/en-us/aspnet/core/getting-started/?view=aspnetcore-2.1&tabs=windows


All in all I don't see a necessary todo here for the docs. There will always be an entry burden for documentation and we can't really change that without hurting the overall readability. I advise to close this issue @Rick-Anderson.

**Comment by regal60740** [comment]
All this could have been avoided by including the code in the tutorial.
That way, the outcome is controlled by the author. I like tutorials that
are complete and don't leave me guessing as to what I'm supposed to do.
You're right that we've spent enough time on this and I have already moved
on to other tutorials. I just hope others have better luck with this
Xamarin example. I sure did not.

**Comment by RSuter** [comment]
Maybe we should mention that you need to install System.ComponentModel.Annotations in the .NET Standard case (mostly used scenario)? It's just one sentence (info box maybe?) but in my experience this is important information for lots of devs...

@zuckerthoben thanks for looking into this.
