### ISSUE TITLE
SignalR Scaleout

### ISSUE THREAD

**Issue by CKDK** [aspnet/Docs#8862]
Since scale out is no longer supported does that mean that SignalR no longer logs client metadata in the server?
And how come redis is still supported?

It would be great with an interface provided to handle the logging of client metadata which developers could implement in a middleware or service provider to handle where and how the metadata is saved for example MySql. Then Sticky sessions don't need to be implemented since the client will exist for all servers in the farm. Note that for this type of application messages wouldn't have to exist for all servers. The Sticky session approach sounds like a great solution for chat applications but SignalR is used for much more than that and applications not using SignalR for chat, only require the client to exist for all servers.

I believe that such an Interface would conform with the new .net core standards, give developers the best of both worlds and it would ultimately make SignalR more flexible to its different uses. 

Maybe is just me but adding more servers = more administration here I am talking about Redis, so being able to use what is already in place is ideal for keeping cost and administration time down. 

Hope I didn't over step my bounds here and thanks in advanced for taking the time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04f4bdfd-dfac-d6ae-4bd9-57439d300a5d
* Version Independent ID: 1f37f1ba-3e43-e726-f231-52acc6d26516
* Content: [Differences between SignalR and ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/version-differences?view=aspnetcore-2.1)
* Content Source: [aspnetcore/signalr/version-differences.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/version-differences.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
> Since scale out is no longer supported 

@CKDK 	 where did you get that information?

**Comment by CKDK** [comment]
Hi Rick, I have the information from the following link;
https://docs.microsoft.com/en-us/aspnet/core/signalr/version-differences?view=aspnetcore-2.1

in the following section;

" Sticky sessions now required
Because of how scale-out worked in ASP.NET SignalR, clients could reconnect and send messages to any server in the farm. Due to changes to the scale-out model, as well as not supporting reconnects, this is no longer supported. Once the client connects to the server, it must interact with the same server for the duration of the connection. "

kind regards
@CKDK

**Comment by davidfowl** [comment]
Scale out is absolutely supported and is required when you're running on multiple servers and need to send to connections that span those servers. The connection management requires sticky sessions so that one connection is only ever on a single node at any one time. This dramatically simplifies connection management and makes it reliable to get connect and disconnect events.

So yes
- Scale out is supported
- It requires sticky sessions
- We only have redis built in provider we ship out of the box

> It would be great with an interface provided to handle the logging of client metadata which developers could implement in a middleware or service provider to handle where and how the metadata is saved for example MySql. Then Sticky sessions don't need to be implemented since the client will exist for all servers in the farm. Note that for this type of application messages wouldn't have to exist for all servers.

We have no plans to add support for this as it means pushing more than just the connection ids into MySql but the data as well. That complicates the transport layer itself which is just responsible for shuttling bytes back and forth. You have a few options if you can't manage the sticky sessions requirement:

- Restrict your clients to websockets only. ASP.NET Core SignalR lets you configure the allowed transports for an end point. It also lets you skip the negotiation phase so that you can just directly connect via websockets.
- Scale out yourself. Don't use the built in mechanism for scaling out, you can handle propagating messages between servers with whatever mechanism makes sense for your environment. This *does* mean that `Clients.All` means clients on your specific server, not all servers in the farm.

> Maybe is just me but adding more servers = more administration here I am talking about Redis, so being able to use what is already in place is ideal for keeping cost and administration time down.

Unfortunately, thats the reality when you have persistent connections in a cluster of machines. You're dealing with a distributed system and tradeoffs have to be made.

**Comment by Rick-Anderson** [comment]
@tdykstra 	can you get some of this information added to the docs?
