### ISSUE TITLE
Convert ToC parent nodes to only expand/collapse

### ISSUE THREAD

**Issue by tdykstra** [aspnet/Docs#8871]
* In the Tables of Contents for Azure services, grouping nodes that have article nodes under them do not themselves link to an article -- they only expand or collapse the group.  For consistency, we should follow suit.
* Other ToC's also do not duplicate their ToC link lists in index.md files; we should eliminate those as well.

Fixed by #9133

**Comment by guardrex** [comment]
On several Index pages, I added the topic descriptions to help the reader understand more about what's in each topic.

For example, see:

* [Performance Index](https://docs.microsoft.com/aspnet/core/performance)
* [Docker Index](https://docs.microsoft.com/aspnet/core/host-and-deploy/docker/)
* [DP config Index](https://docs.microsoft.com/aspnet/core/security/data-protection/configuration)

These examples have a single lead-in line to orient the reader to the node's articles. (I think the single line in these cases can be further improved.)

I like [Fundamentals: Hosting](https://docs.microsoft.com/aspnet/core/fundamentals/host/) because it provides an expanded introduction blurb about what the whole section pertains to (better than a single line), then it has the links+descriptions.

I speculate that eliminating Index pages in most cases forces readers to click on several topics in the node to see what each section of the TOC is about and what each topic covers (if the titles aren't very descriptive), while a well-crafted Index page aids in navigation and understanding.

Therefore, I suggest considering the wise use of Index pages before removing them. If you would like to see a further example of what I propose, allow me to present you with a before and after example using one of the existing link-list-formatted pages. For example, I could take [DP implementation Index](https://docs.microsoft.com/aspnet/core/security/data-protection/implementation/), do a quick number on it (it would only take a few minutes), and then you could see what I mean.

**Comment by tdykstra** [comment]
* Not all clicks are created equal.  😄  Browse through [Azure Functions](https://docs.microsoft.com/azure/azure-functions/), for example.  Expanding and collapsing a node is instantaneous, no need to wait for a page to load. You can quickly find what you need (within the limitations of a ToC structure that puts doc type at the top level).
* ToC entries, though short, do give a good feel for what you could expect to find -- the descriptive text in Performance Index, for example, is not that much more informative than the ToC node names.
* Duplicate content is always best avoided. It's more work to maintain and it gets out of sync when people update one copy (the ToC, for instance) and not the other copy (the index file). If we kept index-file-links on parent nodes, I would at the very least be inclined to eliminate the full copy of the ToC section links, i.e., just have section overview text.

**Comment by guardrex** [comment]
The prob here is that it isn't known (by me anyway) how an enhanced landing page helps readers over no landing page at all.

I don't want to draw conclusions without controlled user testing and some basic statistical comparisons (and don't forget adjustments for simultaneous inference). Wow ... that fancy degree is finally paying off here! :smile: lol Until then, we're (*I'm* anyway) just guessing.

I agree that the one-line leader isn't useful and that if the titles are descriptive that it's fairly clear what a reader will get. For something like Tag Helpers, yeah ... nix the landing page ... that would be dumb in that case. However, I feel that a good example of using an Index page is when the Index has more to say about what's in the node, any a/b-types of decisions/options the reader has, when there's common cross-cutting content to share, and when the article titles aren't all that clear (e.g., "Generic Host" vs. "Web Host" ... says *nothing* really all by themselves in a TOC area).

The Index pages that are link-lists are useless, yes. However, I don't recommend a wholesale deletion of the pages. I think these pages should be assessed on a case-by-case basis to see which ones can be enhanced into something useful.

**Comment by tdykstra** [comment]
We're planning to do some experimentation/user testing with the ToC, so this will be one of the areas we'll look at. I do think all or none should be expand/collapse, so you know what to expect when you click the text of a parent node.  If we go for expand/collapse, something like the index (sans ToC link list duplication) in some cases would be preserved as an Overview link, first link in the section.

**Comment by guardrex** [comment]
I disagree with that approach, but thanks for hearing me out.
