### ISSUE TITLE
How to perform simple authorization in code?

### ISSUE THREAD

**Issue by ackava** [aspnet/Docs#8874]
I have already looked into `IAuthorizationService`, but I can't figure out AuthorizationPolicy, I have setup simple cookie based custom authentication.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c3930e5-8a4f-8bdf-7167-9aed8afc4253
* Version Independent ID: cea5942d-fb01-f5bf-3b63-25873d5b79cf
* Content: [Simple authorization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/simple?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/authorization/simple.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authorization/simple.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @ackava ... It's not currently linked into the Policies topic, but there is a sample at ...

https://github.com/aspnet/Docs/tree/master/aspnetcore/security/authorization/policies/samples/PoliciesAuthApp1

It's an older 1.0-era sample (due for update on #5495), but it should still compile and run.

See if you can get the sample app running. If you need additional guidance, we recommend a support forum, such as Stack Overflow, or a support chat, such as Slack or Gitter. There are only a handful of doc authors on this repo, so we don't have the staffing to field general support requests. We do, however, definitely handle doc issues. If you run into a problem with the Policies doc or the Simple Auth doc, please do let us know about that here.

**Comment by guardrex** [comment]
Your remarks are one of the first reports (probably the only report on this repo) that pushes back on the idea that devs can just go to SO and get a good, fast answer.

I've added this issue to the sample tracking issue. Whenever the docs team gets to the sample (+topic) update, they'll see this and possibly be able to work with you to address what's missing from the topic.

Since you're not getting assistance on SO, you can try the [aspnet/Home issues](https://github.com/aspnet/AspNetCore/issues). The engineers are super-busy, so make sure that you lay out the full scenario clearly in your opening post. If it's a specific code-related problem, it's best if you can put up a repro project on GH and link that into the issue so that the engineers can see what you're trying to do.

Leave this issue open. I hope it will get worked when you get more info on how to resolve your scenario and when the docs team gets to this sample+topic for updates. Idk when that will be. We're going as fast as we can. 🏃🏃🏃🏃🏃🏃😅

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
