### ISSUE TITLE
Clarification on Login form display scenarios

### ISSUE THREAD

**Issue by goonerify** [aspnet/Docs#8876]
The second condition for displaying the login form should probably be "When a user accesses a **restricted** page..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction to Identity on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/identity.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @goonerify ... Thanks for commenting.

The whole line is ...

> When a user accesses a page where they are not authenticated or authorized, they are redirected to the Login page.

It implies such is the case when it says "where they are not authenticated or authorized" because everyone is authorized to access an unrestricted page. However, I like the idea of being explicit.

I also note another small change: This is a list of two conditions for the lead-in statement ...

> The Login form is displayed when:

... so it isn't necessary to have the phrase "they are redirected to the Login page" added to the second item.
