### ISSUE TITLE
Testing on different environment

### ISSUE THREAD

**Issue by seshenoy** [aspnet/Docs#8917]
Hi,
Nicely mentioned on how to test locally. However, if I need automation tests to run in different environments, can it be done ? My concern is that I am referring the API project to my integration library and then running it locally. Will it work once I deploy my API to an environment and run integration tests against it ? 
If so, how can I implement that ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.1)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @seshenoy ...

> deploy my API to an environment 

Do you mean that your API would be a live app somewhere and the integration tests use an HttpClient and hit its endpoints?

**Comment by seshenoy** [comment]
Hi @guardrex 
Yes that is correct... it will be deployed to live/PPE/Staging environment as part of CD and my integration test needs to test it as part of CD task before promoting to the next environment.


On my local VS 2017, I need to execute those tests as well without the need to use another VS2017 to host it in localhost.... The approach you suggested, is good but it will always uses the Startup of the API which means in my local , I cannot change configs to point to different environment. So is it possible to achieve these ?

**Comment by guardrex** [comment]
I see ... sorry ... I was confused about your scenario. Use the patterns that the topic shows. Use `CreateClient` to get your `HttpClient` and hit the endpoints from the test library. I thought for a sec that you were trying to hit an external (outside of a tested app) API endpoint, so I was wondering why not just mock that external app's responses for the SUT. I see now that your API **_is the SUT_**. Use `CreateClient` as the topic+sample shows.

For environment, configure the web host of SUT from the test lib. For example in the `CustomWebApplicationFactory` ...

```csharp
protected override void ConfigureWebHost(IWebHostBuilder builder)
        {
            builder.UseEnvironment("Production")
            ...
```

... that will set the environment of the SUT to *Production*.

When calling `WithWebHostBuilder`, I don't see `UseEnvironment`, but you should be able to do it this way ....

```csharp
var client = _factory.WithWebHostBuilder(builder =>
                {
                    builder.UseSetting("Environment", "Production");
                    ...
```

That should also set the environment of that particular test to *Production*.

See if those approaches work and let me know how it turns out. I think this is such an important question that the topic should explain it.

**Comment by seshenoy** [comment]
@guardrex Sorry I was OOF yesterday. Thanks for your response. I will try it out shortly but just to be on the same page , let me reframe my ask... Please let me know if your above suggestion still holds good.

**What We Have Today**

- A web api in ASP.NET core 2.0
- Integration test with XUnit that is configured to be executed as a task in our CD after deployment to PreProd
- XUnit integration test is not using the Startup of SUT. It is creating a httpclient to point to the preprod location, framing the request object and making the call
- While in local machine, the Engg will need to open another VS instance, run the app locally and then the XUnit tests can be executed by pointing to localhost url taken from config
-  Engg on local machine can change the config value from local host to PreProd if they want to see the results of a test on PreProd ( or any env they want ).

**What We Would LIKE TO HAVE**
- Not use multiple VS instances if we need to run it locally ( this is achieved by your original solution )
- Have the ability to change config and point to any environment to execute IT against that environment ( not possible from the approach suggested originally since it always debugs local one )
- Ensure our tasks to run IT as an automation in our CD pointing to PreProd still holds good and not violated. The Integration test should point to PPE API SUT and not a local host spin up in the release server/ build server.


Let me know if I am clear and we are on the same page.

**Comment by guardrex** [comment]
Yes, indeed. The new testing infrastructure will save you from having to maintain all of that complicated infrastructure.

[I'll refer to your Web API below as just "the app" or the "SUT."]

AFAICT, you'll implement your new integration testing pretty much exactly as the topic shows with special attention paid to two areas that aren't covered:

1. I need to add some content on controlling the SUT's environment. In my last post :point_up:, I showed the two approaches, which depend on how you set your tests up. You can use both approaches if you want ... the topic's sample app uses both.

   * Use one or more custom factories, which create the SUT's configuration independently of the tests.
   * Use `WebApplicationFactory` and call `WithWebHostBuilder` in individual tests.
   
   I'll enhance the topic to explain how to set the environment using both approaches.
1. ... and I can't help as much with this one given my lack of DevOps experience, but I'll ping Scott when he gets back from vacation, and he'll probably have some good advice. What I'll describe here is based on some *educated guesses* subject to revision by Scott when he gets back. :smile:

   I understand that you want to set the SUT to a different hosting environment based on where it's running. I assume you need this for the usual reason: to control which set of resources the app consumes for testing ... e.g., using a test dB *and NOT the real one*. lol

   On a dev machine, you want to run the SUT in *Development*. In the CD/CI, you may want it to be *Staging* or *Production* (or create your own, e.g., *Test*) depending on how you want to set up testing.

   A simple approach would be to set the SUT's environment on the basis of the familiar `ASPNETCORE_ENVIRONMENT` env var. You're probably already setting it locally via *launchSettings.json* (VS) or *launch.json* (VSC). All you need to do is inject the `IHostingEnvironment`, read the `EnvironmentName`, and use the value to configure the SUT.

   Locally, the env var value will supply *Development*, and the SUT will run the same. In CD/CI, you set the env var on the server, and it will come in *Staging*, *Production*, or whatever you set it to in that environment. The SUT will run the same. You could also use a custom env var if you need to.

   There are other approaches you could take, too. Instead of an env var, you could use a command-line argument passed to the `dotnet test` command. You could possibly use a settings file-based approach ... something like a *test.json* file. A local version of the file for dev and a different file sitting on the test server that configures the SUT for the test environment. Any of these approaches should be fine.

   As long as your CD/CI is performing a `dotnet test` and can fail when any of the tests fail, you should be good to go. Scott knows more about the options, especially in non-Azure CD/CI and can comment further.

Let's leave this open. I'll ping Scott later, and I'll make some enhancements to the topic. This issue will auto-close when the PR merges.

**Comment by guardrex** [comment]
@scottaddie TL;DR ... In a DevOps scenario where one desires to configure the environment for tests, are there any caveats to configuring the environment for the following test environment scenarios ...

* Set the `ASPNETCORE_ENVIRONMENT` env var on the testing system.
* Place the environment setting into an appsettings file on the test system (granted that the environment must match the name in the file, e.g., *appsettings.staging.json* and the environment is `Staging` or *appsettings.test.json* and the environment is `Test`).
* Pass the environment to `dotnet test` as a command-line arg on the testing system (presuming that the system is running that command to execute the tests).
