### ISSUE TITLE
Create a sample for Authorization Policy Providers topic

### ISSUE THREAD

**Issue by diberry** [aspnet/Docs#9013]
The sample from github requires .net core 2.2.0 preview but the doc's date is from May. It would be nice if the sample either worked with the current released version of .net (instead of preview) or the doc stated at the top that a preview version of .net is required to use the authorization policy providers (which is the implication). 

```
PS C:\Users\diberry\repos\CsharpCoreAuthSamples\samples\CustomPolicyProvider&gt; dotnet run
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.2.0-preview2-26905-02' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet\
  - Installing .NET Core prerequisites might help resolve this problem:
      http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are installed:
      2.0.9 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.2 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.5 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 150023ea-e35a-4a06-6f71-7ab63994b07f
* Version Independent ID: 7b5c3832-a5a3-a27a-eed3-3ecfc3e8dbe2
* Content: [Custom Authorization Policy Providers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/iauthorizationpolicyprovider?view=aspnetcore-2.1#feedback)
* Content Source: [aspnetcore/security/authorization/iauthorizationpolicyprovider.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authorization/iauthorizationpolicyprovider.md)
* Product: **aspnet-core**
* GitHub Login: @mjrousos
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @diberry ... Thanks for commenting. IMO, we should have a docs sample for this wired up to the current release. We do that (guessing) >95% of the time.

The topic links directly to the [AuthSamples sample](https://github.com/aspnet/AuthSamples/tree/master/samples/CustomPolicyProvider). Usually, we don't link to engineering samples because they often don't work well for teaching concepts alongside the topic. Plus, you pointed out correctly that versioning can be an issue. If we link to engineering master, we're often not providing current release code.

There may have been a good reason at the time the sample was set up this way ... not sure about that. The original issue that generated the PR (and the PR) doesn't speak to the choice. If management decides to keep the engineering sample linked, then they'll close this in a bit.

If we proceed tho, let's use your issue here to track the work. I'm going to update the title. I've added this to the [sample update tracking issue](https://github.com/aspnet/Docs/issues/5495), and we'll get to it as soon as we can. 🏃🏃🏃🏃😅
