### ISSUE TITLE
RC1 -> RC2 migration guide needs to be written by RC2

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#910]
Per "Damian Edwards"  this needs to be published by RC2.

**Comment by OlegKi** [comment]
:+1:  It's very good idea!

**Comment by danroth27** [comment]
Some stuff that is probably still relevant although mostly covered in Zlatko’s DNX -> .NET CLI doc (see attached): 
- https://github.com/aspnet/specs/blob/master/notes/.NET%20CLI%20and%20ASP.NET%205.md
 
Implement Main with WebHostBuilder logic
- ASP.NET Core apps are just console apps
- Webroot and port configured in hosting.json (assuming you are using the default configuration setup)
- WebHostBuilder API updates: https://github.com/aspnet/announcements/issues/141 
 
Namespace and package name change: Microsoft.AspNet.* -> Microsoft.AspNetCore.*
- See https://github.com/aspnet/Announcements/issues/144 for details 
 
Working with IIS
- Add and configure the dotnet-iis-publish tool in the scripts section
- Switch to new middleware. No longer called in Startup.Configure - set it up using the WebHostBuilder
 
Turn on server garbage collection in project.json or app.config when on full .NET Framework
 
MVC
- Set option in project.json to preserve the compilation context (if you are doing views)
- No need to reference the tag helper package, it's now referenced by Razor
- Controllers are in DI by default - PR in flight, follow up when done
- New controller discovery logic - PR in flight, follow up when done
- ViewComponents changes
  - Sync APIs are gone
  - InvokeAsync takes an anonymous object with properties instead of params 
 
Running your app
- “dnx web” is no longer a thing - use “dotnet run” or “dotnet <dll name>” instead
 
Commands are now tools: secret manager, watch, sqlcache
- New package ID
- Configure in the tools section in project.json
 
Configuration
- Follow up with Diego/Hao on what has changed for RC2
 
Logging
- Logging extensions have been simplified and clarified. See https://github.com/aspnet/announcements/issues/148
- Trace is now considered more verbose than Debug and Verbose is removed: https://github.com/aspnet/announcements/issues/124
 
Environment variable and IHostingEnvironment changes:
- Specifying the environment: ASPNETCORE_ENVIRONMENT 
- See https://github.com/aspnet/Announcements/issues/108 for the rest (make sure you read all of the comments)
 
Link to DNX -> .NET CLI migration topic
Link to EF Core migration topic
Link to RC2 Announcements for a complete list of breaking changes in RC2
 
We should test the migration doc using the RC1 and RC2 templates and also with a real app (e.g. live.asp.net or hubbup.io).

**Comment by JunTaoLuo** [comment]
Issues and suggestions in addition to Dan's previous comments:

- `hosting.json` is no longer read by default, users need to explicitly add their own configuration sources and pass a configuration to `WebHostBuilder`
- webroot is by default `wwwroot`
- default server url is `localhost:5000`
- more to come...

**Comment by GuardRex** [comment]
Could mention the change in published output: The devs just say 'it's flat now,' but it's not really "flat" if there are any folders in the output, nor does it really show/describe what will be there. @blackdwarf I think was going to have something more visual or descriptive in cli docs. I have the layouts here: https://github.com/dotnet/cli/issues/937#issuecomment-186737388

IIS: Perhaps talk a bit about the new location of `web.config` and alert to the issue of the `web.config` ever accidentally getting renamed or moved that IIS will serve sensitive files in the content root that aren't explicitly restricted by file extension unless `Hidden Segments` is used to protect those files. I didn't open a feature request on possibly defaulting the `dotnet-publish-iis` tooling to include `<hiddenSegments>`, but it was easy to implement and @moozzyk is aware of what I did. https://github.com/aspnet/IISIntegration/issues/164#issuecomment-217665016

idk if DNX was failing to move empty folders to published output with `dnu publish`, but `dotnet publish` fails to move empty folders, so a dummy file is needed until that is addressed for RTM. https://github.com/dotnet/cli/issues/1396 and https://github.com/dotnet/cli/issues/2911

One of the most confusing aspects for devs coming in to all of this has to do with the application types, specifically the package options that are needed for the self-contained app, which is the most flexibly defined in terms of its dependencies. It would also be good if the RID's are mentioned and the `dotnet publish` command examples. I realize this is an RC1-to-RC2 doc, but something along these lines would ward off confusion and reduce the calls for help ...
- NuGet packages (libs)
- Applications
  - Portable (`runtimes` not needed or ignored, `dotnet publish -c Release`)
    - `Microsoft.NETCore.App` with `"type": "platform"`
  - Self-contained (with `runtimes` required, `dotnet publish -c Release -r <RID>`)
    - `Microsoft.NETCore.App` without `"type": "platform"`, or ...
    - `NETStandard.Library` with `Microsoft.NETCore.DotNetHostPolicy`, or ...
    - `Microsoft.NETCore.Platforms`, `Microsoft.NETCore.Runtime`, and `Microsoft.NETCore.DotNetHostPolicy` <-- This doesn't quite work; however, "those in-the-know" should answer, "What's the minimum set of host/platform/runtime packages needed for self-contained apps if the dev is going to hand-pick all of their deps (i.e., **not** use `Microsoft.NETCore.App` and **not** use `NETStandard.Library`)?"

**Comment by dlebedynskyi** [comment]
@JunTaoLuo 
Could you please clarify following 

> hosting.json is no longer read by default, users need to explicitly add their own configuration sources and pass a configuration to WebHostBuilder

I'm trying to run asp.core app on ssl with WebListerner.
before we just could to dnx command ` "express":  ""Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener" `. but since commands are now removed I was wondering if hosting.json can help with this now

**Comment by danroth27** [comment]
https://github.com/aspnet/Docs/pull/1161

**Comment by JunTaoLuo** [comment]
@dlebedynskyi, you should take a look at https://github.com/aspnet/Announcements/issues/174. The idea is that these configuration sources, such as command line arguments and JSON files, must now be added explicitly by using a `ConfigurationBuilder` and passing its output to the `WebHostBuilder`.

**Comment by dlebedynskyi** [comment]
Thank you  very much @JunTaoLuo.
 so from what I see we can use 
something like this 
```
   .AddJsonFile("hosting.json")
   .AddJsonFile($"hosting.{env.EnvironmentName}.json", optional: true);
```
and from what i see here https://docs.asp.net/en/latest/fundamentals/servers.html
```
// hosting.json
  "server": "Microsoft.AspNet.Server.Kestrel",
  "server.urls": "https://localhost:5004/"
```
how do you specify certificate / password in this case? Is there any spec on hosting.json file content? cause I really not sure how to map these lines now 

https://github.com/aspnet/KestrelHttpServer/blob/dev/samples/SampleApp/Startup.cs#L48
https://github.com/aspnet/KestrelHttpServer/blob/dev/samples/SampleApp/Startup.cs#L51

**Comment by JunTaoLuo** [comment]
@dlebedynskyi https://github.com/aspnet/KestrelHttpServer/blob/dev/samples/SampleApp/Startup.cs#L51 configures the same setting as `server.urls` in your `hosting.json`. For certificate and password, you can read from other sources of configuration (such as environment variables or user-secrets) and pass it to the method in the sample.

**Comment by dlebedynskyi** [comment]
@JunTaoLuo correct. except `.UseUrls("http://localhost:5000", "https://localhost:5001")` is going in `static void Main`  not `public Startup(IHostingEnvironment env)` maybe it would be nice it you have some example with reading serverUrls from actual env via hosting.json
