### ISSUE TITLE
Bearer Token Authentication

### ISSUE THREAD

**Issue by CalumJEadie** [aspnet/Docs#9147]
Please could you expand on the recommendation that bearer token authentication is used rather than cookie based authentication in a non-browser scenario. We currently have a C# WPF desktop application using cookie authentication and are trying to establish the benefits and drawbacks of migrating to bearer token authentication on our usage of SignalR.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0da2144-3730-f8ef-1d16-a89f11fd6198
* Version Independent ID: 6d8f5bc8-8f5c-ba13-b7f2-0366eac46f81
* Content: [Authentication and authorization in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-2.1)
* Content Source: [aspnetcore/signalr/authn-and-authz.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/authn-and-authz.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **anurse**

**Comment by anurse** [comment]
What kind of expansion are you looking at? Cookies are generally not a great option for non-browser clients since they are difficult to manage. If you are using Cookies today and it's working then you're certainly able to continue doing so. Cookies also require that you go to the site itself to acquire a token whereas Bearer tokens can be issued by all sorts of authentication systems (Azure AD, OAuth, etc.).

The content of a cookie **is** by definition a Bearer token (because anyone who holds the token is considered authenticated), a cookie is just a browser-specific way (the `Cookie` and `Set-Cookie` headers) of sending that token and making sure it's sent on every request. When you aren't using a browser, that system is mostly unnecessary and provides a bunch of extra complexity to your system and makes it difficult to offload authentication.

This is a general API design question and not something that's really specific to SignalR. There are likely lots of discussions about the specific drawbacks and advantages of one over the other when designing web APIs, and I may have missed some here, so I'd suggest doing some research on that.

**Comment by CalumJEadie** [comment]
Thanks very much Andrew for such a fast and helpful response.

Reading over the docs, we thought perhaps there was a specific benefit to using bearer tokens (without using cookies as the transport mechanism) that would specfically impact aspects of SignalR such as performance or scalability, aside from the general considerations around designing Web APIs.

If I understand correctly, aside from the general considerations around authentication mechanisms of Web APIs (such as database lookups required, ease of working with and storing tokens/cookies on the client, ability to revoke, refreshing / renewal, ability to revoke on password change) how authentication is implemented in the application doesn't have any particular gotchas for using SignalR.

**Comment by anurse** [comment]
Yeah, SignalR isn't much different from a standard Web API for most things.

> ability to revoke, refreshing / renewal, ability to revoke on password change

This is one area where there are some additional considerations with SignalR. A SignalR connection is persistent and often uses one long-running WebSocket request. We authenticate the token when the connection is established but don't **reauthenticate** while the connection is running. This means that if you revoke the token, existing connections won't be automatically terminated. We have had some other users look in to this and [come up with a strategy to monitor their connections and automatically terminate them if the token becomes invalid or expired](https://github.com/aspnet/SignalR/issues/1159#issuecomment-368864944). We don't have anything built-in for this but it is something you can achieve.

**Comment by tdykstra** [comment]
I don't see that last point explained in the doc; I'll add it.

**Comment by CalumJEadie** [comment]
Thanks very much @anurse and @tdykstra!
