### ISSUE TITLE
Incomplete code samples

### ISSUE THREAD

**Issue by sharyex** [aspnet/Docs#9165]
The code samples do not contain almost half of the code presented on this page, e.g. the actual sign in and cookie creation parts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2229fc6-f8c8-952e-e567-b1d5a463055a
* Version Independent ID: b18a015b-914d-f014-f711-120d208904d9
* Content: [Use cookie authentication without ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/security/authentication/cookie.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/cookie.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @sharyex ... The sign-in bits are in the `OnPostAsync` method of the *Login.cshtml.cs* file. Since a dev would supply their own auth logic (i.e., not use Identity), we have a stub method set up for `AuthenticateUser` down at the bottom of the class. It returns an [ApplicationUser](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/cookie/samples/2.x/CookieSample/Data/ApplicationUser.cs) or `null` depending on the result of your custom auth (e.g., database lookup).

https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/cookie/samples/2.x/CookieSample/Pages/Account/Login.cshtml.cs

Let's discuss this further if you aren't getting what you need from the sample.

WRT the code not in the sample: We had a request to show how to handle claims, and we put that piece into the sample. As for the rest of the examples in the topic that aren't in the sample, we're still taking feedback on what the sample should demonstrate. In most of the non-sample scenarios covered by the topic, we hope a cut-and-paste out of the topic into the reader's app will be enough to get them going.

**Comment by isak-84** [comment]
Hi! About the HttpContext.SignInAsync method, does it only work in razor pagemodels? I tried to paste the code inside a c# class, but it says HttpContext have no method called SignInAsync.

**Comment by guardrex** [comment]
@isak-84 Add a namespace to your code file ...

```csharp
using Microsoft.AspNetCore.Authentication;
```
