### ISSUE TITLE
Multiple handlers for a requirement: parallell async with fast bail out?

### ISSUE THREAD

**Issue by austvik** [aspnet/Docs#9194]
multiple handlers for a requirement: Say you have several async ones, going against AAD or databases.
Can you get them to be evaluated in parallell, and cancel others after the first one succeeds?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1141d92-adeb-6841-229f-914c808f9a2b
* Version Independent ID: 7089b376-949f-c1c6-c37a-5d8cc7ecf104
* Content: [Policy-based authorization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/authorization/policies.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authorization/policies.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by HaoK** [comment]
We don't have any support for this in box, but you could probably drop in your own implementation of IAuthorizationService to implement this:

https://github.com/aspnet/Security/blob/master/src/Microsoft.AspNetCore.Authorization/DefaultAuthorizationService.cs#L80

**Comment by icistrate** [comment]
I would have liked to see bit more about the "PermissionHandler" (a handler for multiple requirements) .. the sample code doesn't reference it and cannot clearly see how the value in context.Resource is passed in. I am having something similar where I want to validate multiple requirements (Owner of a resource or ADMIN) using IAuthorizationService. Would that be possible?

**Comment by zendu** [comment]
I had a slightly different need.

- 1 requirement
- 4 handlers
- Handlers should be called in certain sequence and next one is called only if requirement is still not succeeded.

I could have written single handler which runs all 4 checks in if-else ladder; however that felt like putting too much logic in one place. Also there would be no way to add/remove or alter sequence easily.

Here is what I did:
- Write 4 handlers that derive from `AuthorizationHandler<MyRequirement>`
- Register them as singleton services instead of singletons of `IAuthorizationHandler`
- Write a 5th handler that derives from `AuthorizationHandler<MyRequirement>` and register it `services.AddSingleton<IAuthorizationHandler, SequentialMyRequirementHandler>
- Configure an array of 4 types above as option
- SequentialMyRequirementHandler
   - Uses the the option and IServiceProvider as constructor parameters
   - Use the array of types to get handler instances from service provider
   - Call each handler in loop and break if requirement is satisfied.
   - Notice that this handler does not succeed or fail requirement on its own.


            // call each handler
            foreach(var handler in handlers)
            {
                // call handler
                await handler.HandleAsync(context);

                // if current requirement is successful
                if(!context.PendingRequirements.Contains(requirement))
                {
                    break;
                }
            }

I would have liked for context to provide a method to check if given requirement is successful or not instead of looping over list of pending requirements. But this will have to do for now.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
