### ISSUE TITLE
Show logging setup example with WebHostBuilder extensions?

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Docs#927]
@ardalis @Rick-Anderson @danroth27

RE: https://github.com/aspnet/Docs/blob/master/aspnet/fundamentals/logging.rst

This might be too much (perhaps only showing the `.Configure(app => ...)` section would suffice), but I was wondering if it would be a nice add-on to the logging doc to show how to set it up when using `WebHostBuilder` extensions? (thanks to @davidfowl for the tip on how to do it this way)
```c#
using Microsoft.Extensions.Logging;

var host = new WebHostBuilder()
    .UseServer("Microsoft.AspNet.Server.Kestrel")
    .UseDefaultConfiguration(args)
    .UseIISPlatformHandlerUrl()
    .ConfigureServices(services =>
    {
        services.AddMvc();
    })
    .Configure(app =>
    {
        var loggerFactory = app.ApplicationServices.GetService<ILoggerFactory>();
        loggerFactory.AddConsole(minLevel: LogLevel.Debug);
        app.UseIISPlatformHandler();
        app.UseMvcWithDefaultRoute();
    })
    .Build();
host.Run();
```

**Comment by danroth27** [comment]
I think most of our Fundamentals docs should show the Startup class pattern instead of WebHostBuilder, but we do need to figure out where to document WebHostBuilder in our RC2 docs. I've opened https://github.com/aspnet/Docs/issues/929 to track this. Closing this issue as I think the Logging doc is fine as is.
