### ISSUE TITLE
Why Environment variables are safer than Secret Manager tool in staging/production ?

### ISSUE THREAD

**Issue by PierreRoudaut** [aspnet/Docs#9320]
Both do not encrypt secrets and their vulnerability is tied to the access of the machine. Am I missing something ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c99993c-c983-6fda-6c3a-ce4ec8c1d5db
* Version Independent ID: ba688ac2-e90e-fce5-f60d-40c2553c3efd
* Content: [Safe storage of app secrets in development in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-2.1&tabs=windows)
* Content Source: [aspnetcore/security/app-secrets.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/app-secrets.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
That's correct. The goal is to keep secrets out of source control and keep production secrets off of development machines. If you need a higher level of security, there's Azure Key Vault and 3rd party providers.

**Comment by guardrex** [comment]
Oh ... and btw ... Secret Manager isn't for staging/production ... it's only for your dev machine. The general advice for production is always either env vars, Azure Key Vault, or 3rd party production secret management system.

**Comment by PierreRoudaut** [comment]
Sorry to insist, but I'm curious to know what justifies the "general advice" to use env vars over over Secret Manager. Could you give me a clarification ?

**Comment by guardrex** [comment]
@blowdart

**Comment by blowdart** [comment]
Environment variables was where the industry went, so in this case we followed.

**Comment by MattNCI** [comment]
Pierre R, I suppose it is assumed that developers and testers shouldn't have access to production secrets at all (and if you tried your dev app in prod it would fail to deploy/run) 
A production sys admin usually *does* have access to the secrets since they're the ones who maintain it. An environment variable or a text file in a secure path on a hardened production server is safer (not safe, but safer) than a connection string in the app code itself. IMO :)
