### ISSUE TITLE
This article doesn't make it clear if Groups can be used as security mechanism

### ISSUE THREAD

**Issue by Eirenarch** [aspnet/Docs#9349]
The article should make it very explicit even with a Note if groups are secured. IIRC SignalR 1 Groups were NOT secure and clients could listen even if they were not explicitly added on the server. I don't know what the case with SignalR Core is but whatever it is it should be stated very clearly in the docs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8d77892-d376-2f23-2634-f5d34d962a1e
* Version Independent ID: 92ed6330-b49f-1620-6beb-8556a78ac7da
* Content: [Manage users and groups in SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/groups?view=aspnetcore-2.1)
* Content Source: [aspnetcore/signalr/groups.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/groups.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by scottaddie** [comment]
Let's ask @BrennanConroy

**Comment by BrennanConroy** [comment]
I don't see a great reason why we should specifically call out groups as being "secure".

We have a [doc on security](https://docs.microsoft.com/aspnet/core/signalr/security?view=aspnetcore-2.1) that calls out specific items that you should consider for security purposes.
And one on [auth](https://docs.microsoft.com/aspnet/core/signalr/authn-and-authz?view=aspnetcore-2.1) to call out specifics on authentication and authorization.

**Comment by Eirenarch** [comment]
Because if you Google "are signalr groups secure" you will see a number of results stating they are not. There are very few items usually in some comments that state that SignalR Core groups are secure. For years Microsoft explicitly told devs in the docs that groups were not secure now there is no information in the docs on the security, not in this article and not in the article comparing SignalR vs SignalR Core

**Comment by BrennanConroy** [comment]
>not in the article comparing SignalR vs SignalR Core

Fair enough. We might want to consider mentioning it in the comparison doc then. @anurse thoughts?

**Comment by anurse** [comment]
Groups in ASP.NET Core SignalR _are_ a little more secure (since they aren't tracked by the client) but I don't feel confident calling them out as a security mechanism. We should put a message in our docs to say that they are not designed to be a security mechanism. Something like:

Groups are not intended to be a security feature. Use Authentication and Authorization functionality (some links here) in ASP.NET Core to protect access to resources

**Comment by Eirenarch** [comment]
OK I am really confused. If I have a Group representing a chat room and I add people on the server with the proper credentials check can I confidently send a message and be sure that people I have not added can't read those messages?

**Comment by anurse** [comment]
The reason I say it's not a "security feature" is because we haven't done the work of going through it thoroughly to vet it for security issues. Authentication and Authorization systems generally need varying degrees of security checks, depending on the system, and making a blanket statement about "security" is something we do very very cautiously.

In your scenario, you're probably fine using a Group for this purpose. It all depends on the level of intrusion you're worried about. If you feel confident that you control all the servers in your SignalR app, then Groups are probably sufficient, since they are completely managed on the server. If you check the credentials, and only ever add the user to the group if the credentials are valid then you can be reasonably sure that messages sent to that group will only go to authorized users. However, Authentication claims generally have a bunch of features that Groups do not, such as expiry and revocation. If a user's permission to access the group is revoked, you'll have to manually detect that and remove them from the group.

**Comment by Eirenarch** [comment]
I see. So I think this topic which

1. Is very common question, and a concern for many of the SignalR use cases
2. Differs from the behavior of the previous version of SignalR which still dominates the Google results
3. Is relatively complex and nuanced

Definitely should be covered in the docs.

**Comment by anurse** [comment]
> 2\. Differs from the behavior of the previous version of SignalR which still dominates the Google results

I'm not sure I'd say it differs much in terms of user scenario, since the previous version also stated that they should be avoided as a security mechanism

I definitely agree some docs updates would be good here though.
