### ISSUE TITLE
Deployment Issues

### ISSUE THREAD

**Issue by toryb** [aspnet/Docs#9406]
This was a very helpful article. However, the information for deploying the sample did not work for me. I encountered two issues that I had to handle manually. 

First, the modify_deps_json.ps1 did not appear to work. The runtime location in StartupDiagnostics.deps.json did not get "lib/netcoreapp2.1/" prefixed to the assembly. I had to do that manually. 

Second, the dotnet store command added all the dependencies to the store but it did not add the StartupDiagnostics to the store. I had to add that manually also.

Thanks for the information!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 613ad64e-bc62-edf7-2e86-42210de718f4
* Version Independent ID: aabbbc32-3237-5ef9-c422-892dc6884a22
* Content: [Enhance an app from an external assembly in ASP.NET Core with IHostingStartup](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/platform-specific-configuration?view=aspnetcore-2.1&tabs=windows#runtime-store)
* Content Source: [aspnetcore/fundamentals/host/platform-specific-configuration.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/host/platform-specific-configuration.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @toryb for the report. I'll re-run the steps and see if I can repro. It's possible that churn in the SDK has broken something along the way since we first put the topic up.

**Comment by guardrex** [comment]
For Item 1 thus far, it's working here (the spacing the file is ugly due to the PowerShell module that handles JSON (`ConvertTo-Json`), but I see two updates to make from the result:

* I changed the name of the assembly but don't show the new name in the topic (*StartupEnhancement.dll* :point_right: *StartupDiagnostics.dll*).
* The deps are different: The hosting and DI packages are present.

I'll check on your Item 2 next.

In the meantime, let's compare notes on PowerShell: Execute a `$PSVersionTable.PSVersion` command at a PS command prompt and see what you get. I'm on 5.1. If you have an older version, it *might* explain why the file wasn't updated ... perhaps something to do with the commands in the PS script not having the intended effect on the file.

Here's the top of the file that the script produced here. The `runtime` is correct as `"lib/netcoreapp2.1/StartupDiagnostics.dll"` ...

```json
    "targets":  {
                    ".NETCoreApp,Version=v2.1":  {
                                                     "StartupDiagnostics/1.0.0":  {
                                                                                      "dependencies":  {
                                                                                                           "Microsoft.AspNetCore.Hosting":  "2.1.0",
                                                                                                           "Microsoft.AspNetCore.Hosting.Abstractions":  "2.1.0",
                                                                                                           "Microsoft.Extensions.DependencyInjection":  "2.1.0"
                                                                                                       },
                                                                                      "runtime":  {
                                                                                                      "lib/netcoreapp2.1/StartupDiagnostics.dll":  {

                                                                                                                                                   }
                                                                                                  }
```

**Comment by guardrex** [comment]
**Yes!** on Item 2.

@pakrym TL;DR The `dotnet store` command doesn't put the hosting startup assembly into the user profile's store at `C:\Users\{USER_PROFILE}\.dotnet\store\x64\netcoreapp2.1` as it did before and as we say in the topic. Did the cheese move on this aspect?

Should I now say that instead of running the `dotnet store` command on the hosting startup project ...

```console
dotnet store --manifest <PROJECT_FILE> --runtime <RID>
```

```console
dotnet store --manifest StartupDiagnostics.csproj --runtime win7-x64
```

Ref: https://docs.microsoft.com/aspnet/core/fundamentals/host/platform-specific-configuration#runtime-store

... that the user should manually move the hosting startup assembly to the folder?

**Comment by toryb** [comment]
@guardrex ,
> In the meantime, let's compare notes on PowerShell: Execute a `$PSVersionTable.PSVersion` command at a PS command prompt and see what you get. I'm on 5.1. If you have an older version, it _might_ explain why the file wasn't updated ... perhaps something to do with the commands in the PS script not having the intended effect on the file.
> 

Here is my PS version info.

Major: 5  Minor: 1  Build: 17134    Revision:228

I will provide a little more information after my next meeting. I'll show the top of my deps.json file from the deploy folder.

**Comment by guardrex** [comment]
Ok, thanks. It doesn't seem like the PS version is to blame then. I'll check the publish command that I was using and post that in here to make sure that we're both using the same command. I'll get back to this sometime this weekend.

**Comment by toryb** [comment]
@guardrex,

I looks like I am getting an error: 

> 1>Modify the deps.json file ...
1>& : AuthorizationManager check failed.
1>At line:1 char:6
1>+ & { &'.\modify_deps_json.ps1' 'Debug'}
1>+      ~~~~~~~~~~~~~~~~~~~~~~~~
1>    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
1>    + FullyQualifiedErrorId : UnauthorizedAccess

I tried running VS as administrator and that didn't help. I'm not sure what needs to happen to be able to execute the script, but now I know why it isn't working.

**Comment by guardrex** [comment]
In the project file where the script is called, try changing the execution policy of the script from *Unrestricted* to *Bypass*, which is slightly less restricted:

```
-executionpolicy Unrestricted
```
... to ...
```
-executionpolicy Bypass
```
If that doesn't work, try adding the `-Force` flag to it and see what happens ...
```
-executionpolicy Bypass -Force
```
If none of that works, is the project sitting on a share off of your local machine? If so, try copying the entire project to your local machine, reset the switch to just `-executionpolicy Unrestricted`, and see if it will run.

**Comment by guardrex** [comment]
This issue will be resolved by the changes coming on https://github.com/aspnet/Docs/pull/9478.
