### ISSUE TITLE
ASP.NET Core 2.2 to 3.0 migration

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#9490]

**Comment by natemcmaster** [comment]
We're getting close to 3.0 Preview 1. Here is some information that I shared with our testers which I believe will also be relevant for customers. 

The following changes need to be made to project files to upgrade from ASP.NET Core 2.x to 3.0.

* Update `<TargetFramework>` to `netcoreapp3.0`
* Remove the `<PackageReference>` to Microsoft.AspNetCore.All and Microsoft.AspNetCore.App.
   * **Preview 1 Known Issue** - workaround for NuGet/Home#7342 - projects which do not start with `<Project Sdk="Microsoft.NET.Sdk.Web">` will get compiler or runtime errors due to missing Microsoft.AspNetCore.* assemblies. This is most often the case for test projects and class libraries. The workaround is to add the following to the .csproj file.
	```xml
		<ItemGroup>
		   <FrameworkReference Include="Microsoft.AspNetCore.App" />
		</ItemGroup>
	```

* Update the `Version` on remaining `<PackageReference>`'s to Microsoft.AspNetCore.\* packages to 3.0.0-preview-18579-0053 (or whatever the Preview 1 build number ends up being)
	* If there is no such version of the package, this may be one of the packages which has been deprecated in 3.0. Many of these are part of Microsoft.AspNetCore.App and do not need to be referenced individually anymore.
TODO: document a complete list of packages we no longer produce. Rough draft here: https://github.com/aspnet/AspNetCore/issues/3756
* Some APIs were removed from Microsoft.AspNetCore.App between 2.x and 3.0. You may need to add `<PackageReference>` items if you are using API from packages listed in https://github.com/aspnet/AspNetCore/issues/3755
  * Notable mentions: Entity Framework Core and System.Data.SqlClient are no longer part of Microsoft.AspNetCore.App.
  * **Preview 1 Known Issue** - the assemblies shipping in Microsoft.AspNetCore.App has not been finalized yet and will change before 3.0 RTM. We intend to remove a few more assemblies, most notably Newtonsoft.Json.

**Comment by muh00mad** [comment]
I'm using visual studio 2019 build 16.3 and I've a .net standard library targeting `netstandard2.1`, when i add 
```
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App"/>
  </ItemGroup>
```

the project throw error `error NETSDK1073: The FrameworkReference 'Microsoft.AspNetCore.App' was not recognized` is there any work around to resolve this?
