### ISSUE TITLE
service account needs LOGON AS SERVICE permission

### ISSUE THREAD

**Issue by rmtexas** [aspnet/Docs#9573]
The account created for the service will additionally require LOGON AS SERVICE permission.  This can be accomplished by using the Services control panel and setting the login there, or by changing the appropriate local or group policy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0bd8cb8-7e28-8c4d-a550-3aea8f3ab4dd
* Version Independent ID: 4b60d24e-ef05-15e5-10b4-483094081bf3
* Content: [Host ASP.NET Core in a Windows Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.1)
* Content Source: [aspnetcore/host-and-deploy/windows-service.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/windows-service.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
Thanks @rmtexas ... I set this process up from an elevated command prompt and didn't perform a restart test.

@Tratcher @blowdart ... permission to proceed with an update to surface this?

**Comment by blowdart** [comment]
Sure

**Comment by guardrex** [comment]
Very interesting ... just discovered that the `ServiceUser` was already granted that right ...

<img width="458" alt="capture" src="https://user-images.githubusercontent.com/1622880/48441361-edee0880-e750-11e8-97a9-225be8665a37.PNG">

I presume that this occurs when the service is created ...

```
sc create {SERVICE NAME} binPath= "{PATH}" obj= "{DOMAIN}\{USER ACCOUNT}" password= "{PASSWORD}"
```

... I'll open an issue for the doc maintainer of `sc create` to see if they can provide some additional info: https://docs.microsoft.com/windows-server/administration/windows-commands/sc-create

@rmtexas, I'll close this, since the instructions *should work*. :pray: If you disagree and think we need to discuss/work further on this, let me know. We can re-open and continue to discuss.

**Comment by pherbel** [comment]
This sc create command will not grant "log on as a service" rights for user.

So now there is no really command line option for this.

**Comment by guardrex** [comment]
@pherbel Please open a new issue using the **Content feedback** at the bottom of the topic. We don't work closed issues.
