### ISSUE TITLE
Uploading files larger than 30 MB in Linux/nginx

### ISSUE THREAD

**Issue by neno978** [aspnet/Docs#9594]
Although adding an option like .UseKestrel(options =&gt; { options.Limits.MaxRequestBodySize = 52428800 // 50MB }) resolves 30MB upload limitation of .NET Core, in Linux/nginx I have noticed that uploads/downloads exceeding the 30 MB size occasionally   fail with 502 error or 504 error or following:     
 System.Net.Http.HttpRequestException: An error occurred while sending the request. ---&gt; System.Net.Http.CurlException: Server returned nothing (no headers, no data)\n   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)\n   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapp

Could the streaming resolve it? Or has someone already experienced that problem?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [File uploads in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-2.1)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/models/file-uploads.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @neno978 ... We won't be able to assist with troubleshooting it here on the documentation repo. We just work on docs issues here.

We recommend posting to a support forum, such as Stack Overflow, or a support chat, such as Slack or Gitter. If the community can't help and/or this looks like a possible issue in framework code, open an issue on the aspnet/Home repo issues for the engineers to take a look.

If you do open at aspnet/Home, they will likely need a fully working repro project posted to GH that demos the issue or at least full traces from the app (e.g., Wireshark), so you might want to have all of that ready when if you post there. You might want to ask first on Stack Overflow ... this might be something that other devs know about and can comment on quickly without having to draw time from the engineers.

If you find out something broadly applicable to file uploads that the docs should cover, please come back and post back to this issue so that we can take a look. We have an open tracking issue for this topic, and your notes might result in some additional content when the doc is addressed. See: #5331
