### ISSUE TITLE
reading outlook email using asp.net app

### ISSUE THREAD

**Issue by shanishkr11** [aspnet/Docs#9626]
I am create one app for read email from outlook in local it working but after hosting on iis server it's throwing following error.

Retrieving the COM class factory for component with CLSID {0006F03A-0000-0000-C000-000000000046} failed due to the following error: 80070005 Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED)).
Please help me about this one.
Thanks.

**Comment by guardrex** [comment]
Hello @shanishkr11 ... You'll need to explore COM security and granting the IIS app pool user's identity permissions to use COM. Since our docs are web-workload focused, I doubt that they'll ask us to write about Office Interop here. It's more likely that it would come up over in the .NET Core topics for discussion (for example: https://github.com/dotnet/core/issues/402).

The official docs for COM security: https://docs.microsoft.com/windows/desktop/com/setting-processwide-security

I think the most helpful parts will be the sections on launch security (https://docs.microsoft.com/windows/desktop/com/setting-processwide-security-using-dcomcnfg#setting-launch-permissions-for-an-application) and access (https://docs.microsoft.com/windows/desktop/com/setting-processwide-security-using-dcomcnfg#setting-access-permissions-for-an-application).

If you have questions or run into trouble, the Office Team recommends Stack Overflow for general developer questions, as we do. I think when you search that error, you'll see several posts on the subject. You can make a suggestion to the Office Team at [Office UserVoice](https://officespdev.uservoice.com/).
