### ISSUE TITLE
Why should we use IOptions<T> when we can inject the configuration object directly.

### ISSUE THREAD

**Issue by charinirao** [aspnet/Docs#9663]
Hello, by using IOptions&lt;T&gt; we are taking a dependency on microsoft.extensions.options in every library. This page does not go into details about why we can not inject the configuration object T directly into constructor? Even if we inject IOptions&lt;T&gt; we are still grabbing the options.value in the constructor and assigning to a local variable. Can you explain explicit reasons why we should use IOptions&lt;T&gt; ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed39cb0e-aa85-8bba-ffb4-859b56a60723
* Version Independent ID: dc7e3449-650b-d117-5eac-69e5ccb250cb
* Content: [Options pattern in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/configuration/options.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/configuration/options.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by HaoK** [comment]
Options also has validation now which we are not going to do at the configuration level, so that is an additional benefit that comes along with using options

**Comment by guardrex** [comment]
Thanks ... I'll see about getting that in along with the work for #9662.

**Comment by charinirao** [comment]
@guardrex - thanks! Can you point me to any sample on how the validation for IOptions works.

**Comment by guardrex** [comment]
@charinirao I'm working on the PR for this update now. Turns out **_we did cover validation_** ... it's in the 2.2 version of the topic. The 2.2 version will become the default version of the topic after 2.2 RTM.

See: https://docs.microsoft.com/aspnet/core/fundamentals/configuration/options?view=aspnetcore-2.2#options-validation

**Comment by Valeriy1991** [comment]
Hi guys! It’s not quite clear to me why validation of options is needed, since it is possible in your Ioc container to register dependency resolution for your `IOptions<>` - I'm found that this case is work fine:
```csharp
        public static void RegisterAppSettings(this ContainerBuilder builder)
        {
            builder.Register(context =>
            {
                var appSettingsOptions = context.Resolve<IOptions<AppSettings>>();
                if (appSettingsOptions?.Value == null)
                    throw new ArgumentNullException(nameof(appSettingsOptions));

                if (appSettingsOptions.Value.ConnectionStrings == null)
                    throw new ArgumentNullException(nameof(appSettingsOptions),
                        "Section \"ConnectionStrings\" in configuration file is null");

                if (appSettingsOptions.Value.MailSettings == null)
                    throw new ArgumentNullException(nameof(appSettingsOptions),
                        "Section \"MailSettings\" in configuration file is null");

                return appSettingsOptions.Value;
            }).InstancePerLifetimeScope();
        }
```
In my opinion, options validation is the developer responsibility, and if developer does not describe validation rules (in Ioc, for example), then it becomes a problem of developer :)

May be I'm wrong - tell me, please, if this is so.
