### ISSUE TITLE
External Resources

### ISSUE THREAD

**Issue by abron-s** [aspnet/Docs#9666]
Is there a list of recognized or recommended quality resources - whether books, online docs or even blogs - that complement this documentation?  In general, across all doc, a section of external resources for further reading/referencing would be useful.  The docs seem to be concise for a singular purpose of whetting appetite!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction to Identity on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/identity.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @abron-s ... In addition to the [ASP.NET Community Standup](https://live.asp.net/) and [ASP.NET Core Slack Team Room](http://tattoocoder.com/aspnet-slack-sign-up/), there are resource lists. We don't intend to maintain a similar list in this doc set because they already exist either maintained by the community or other repos.

Check out the following:

* https://github.com/quozd/awesome-dotnet
* https://github.com/Microsoft/dotnet/blob/master/dotnet-developer-projects.md
* https://github.com/Microsoft/dotnet/blob/master/dotnet-consumer-projects.md
* https://github.com/Microsoft/dotnet/blob/master/dotnet-free-oss-services.md

... and there might be others. That's just off the top of my head.

I'll close as answered, but we can re-open this issue if you would like to discuss anything further.
