### ISSUE TITLE
Issue Initializing DB with initial data

### ISSUE THREAD

**Issue by stephenmorton** [aspnet/Docs#9672]
Hi guys, love these tutorials. 
Having an issue with "Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8" ASP.net core 2.1, 
Getting Started
"Add code to initialize the DB with test data"
When I restart the database, as expected, the database tables for Course and Student get loaded with the sample data. However, the Enrollment table does not, it has no data.
I tried to enter data manually, but when I try to add a record, I get an error that the Enrollment, Grade column. The column is an int type, but trying to enter a grade of A for example, obviously doesn't work (A isn't an int). I am guessing this is wht the initialize didn't data fill the enrollment table.I figured an issue with my version of asp.net core or something (2.1.6). i tried to change the data type to enum, but can't do so, doesn't seem to be available in the VS database designer. ASP.net has set it to type int. So, for some reason the initialize doesn't set the grade column correctly. What should it be and if it should be enum, why can I not select this data type in the VS DB designer?
Thanks in advance.

**Comment by guardrex** [comment]
RE: https://docs.microsoft.com/aspnet/core/data/ef-rp/intro

Hello @stephenmorton ...

> the enrolment table can't get propagated, as entity constraint with studentID failed, no student ID 1

Yes, that's correct. The referential integrity is enforced. This is a fairly common problem with our topics ... we rely upon some prior knowledge or topics in other documentation sets. The link to "navigation property" is broken, so that should be fixed. I'll take care of that.

Regarding ...

> The tutorial does mention try adding a used and then prior to initialising, remove them

Where does it say that? Can you paste in the link to the topic and the line that tells the reader to do that?

**Comment by guardrex** [comment]
Yes, I see your point. I'll move that to a new issue to get it resolved.
