### ISSUE TITLE
Link to Azure publish from command line is invalid

### ISSUE THREAD

**Issue by madmox** [aspnet/Docs#9716]
In the section "Publishing to Azure", the link in the sentence "The app can also be published to Azure from the command line" points to a page that does not describe how to publish a .NET Core web app to Azure using CLI.

In fact, I could not find any documentation describing how to publish an ASP.NET Core web project to an Azure web app using only the built-in tools from CLI (not using git).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62fb594f-04bf-c4d7-c94b-6cd6d8b12d75
* Version Independent ID: 64e973ac-838d-4459-06b0-4e943bff936e
* Content: [Host and deploy ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/host-and-deploy/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-apps/?view=aspnetcore-2.1#publish-using-command-line-interface-cli-tools

**Comment by Rick-Anderson** [comment]
@tdykstra 	should I make an issue for the TOC entry publish with CLI which doesn't link to CLI publishing?

![image](https://user-images.githubusercontent.com/3605364/49119185-62de3980-f24b-11e8-8027-38f6401402a9.png)

My link above does use CLI

**Comment by madmox** [comment]
The paragraph linked in your 1st post explains how to prepare the deployment files using `dotnet publish` command, but does not explain how to publish the files to Azure **using CLI**, which is what you usually need when scripting deployments. It only states:

> Move the contents of the bin/Release/{TARGET FRAMEWORK}/{RUNTIME IDENTIFIER}/publish directory to the site in App Service.

I was really looking for a replacement for the `MSBuild` `DeployOnBuild` / `PublishProfile` command which I have been using with ASP.NET framework (maybe this still works? although I'd prefer using the `dotnet` CLI tool rather than `MSBuild`).

**Comment by Rick-Anderson** [comment]
@madmox I think the preferred approach is the Azure Cloud Shell.

https://docs.microsoft.com/en-us/azure/app-service/app-service-web-tutorial-dotnetcore-sqldb?view=aspnetcore-2.1

**Comment by madmox** [comment]
So, there is no way to build locally and publish using CLI tools? The Azure Cloud Shell example uses git deployment, which builds the project on the target web app.

**Comment by tdykstra** [comment]
@Rick-Anderson 
@Rick-Anderson 

>should I make an issue for the TOC entry publish with CLI which doesn't link to CLI publishing?

It does do publish with CLI, using Git.  We couldd use this issue to add a link to non-Git CLI deployment if such an article exists.

**Comment by guardrex** [comment]
From your remark @madmox, it looks like you're not trying to use MSDeploy (??).

Just as a btw @Rick-Anderson @tdykstra ... That description is in the publish profiles topic. We might need to cross-link better, since an Azure Apps profile should work via that approach. I haven't tried it from a CL ... just from VS ... but there's no reason to think it wouldn't ✨ *Just Work*:tm: ✨

https://docs.microsoft.com/aspnet/core/host-and-deploy/visual-studio-publish-profiles#publish-to-an-msdeploy-endpoint-from-the-command-line

**Comment by guardrex** [comment]
@madmox WRT ...

> from the dotnet CLI toolchain

There's [dotnet msbuild](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-msbuild) ...

> The command has the exact same capabilities as existing MSBuild command-line client.

It should work with a publish profile. I haven't tried it, but it seems like it would work. 🤞 

@Rick-Anderson @tdykstra There's cross-linking opportunities here + possibly surfacing `dotnet msbuild`. If you'd like me to work this, we could schedule for late in the month. I don't think it would take long to resolve it.

**Comment by cephalin** [comment]
@tdykstra I'd actually never known before that dotnet can publish. We don't have anything that publish with that route. Since App Service doesn't write for multiple permutations, is this something that most people will prefer instead of publishing with Git?

**Comment by tdykstra** [comment]
@Rick-Anderson @scottaddie @guardrex See question from Cephas -- what method should the Azure App Service docs focus on?  I'd say stick with Git publishing.

**Comment by guardrex** [comment]
Git sounds good to me.

I suggest a cross-link over to the publish profiles topic at the end in an *Additional resources* section because that's a bit hard to find if one doesn't want to use Git. Could link it directly to that MSDeploy/CLI section that I mentioned earlier ... and then ...

That publish profiles topic section could have a cross-link over to `dotnet msbuild`. The text isn't really accurate the way that it's currently written because it was written before `dotnet msbuild` was a thing. Also, that section could use a passing remark (or a link to a bookmark in the topic) about Azure Apps. I'd test the approach (Azure Apps profile deployment) to make sure it works ... it should work ... there's no reason for it not to work.

I can work on this in a couple weeks if you guys want. I don't think it would take very long. Assign me and put it on the backlog if you like.

**Comment by guardrex** [comment]
@madmox I should be able to get to this in a few weeks. If you have a good/bad experience ... gotchas ... additional thoughts ... please let me know here so that I can take your feedback into account for the updates.

My last post lays out some of the things that I'd like to do. Thus far, the `dotnet msbuild` command with an Azure Apps publish profile looks like a good bet for a scriptable scenario. I'll make sure cross-links surface the approach and to the `dotnet msbuild` command.

**Comment by madmox** [comment]
Thanks for the feedback. I'm OK with the clarifications you intend to make, it sounds good.

git deployment is definitely the thing you have to "push" forward as it is a more versatile approach, but at the time being it's not always possible / sometimes a bit complicated to set up correctly (thinking large projects taking forever to build on web apps, mixed csproj projects failing to build because of netstandard references issues (this one does not concern dotnet core), incompatible build extensions like webcompiler...). So yeah, you definitely need to make the dotnet msbuild section more visible in the doc!

**Comment by cephalin** [comment]
Adding my two cents:

For the App Service side, I don't think of it as "which one do we want to push", but really "which one is representative of the audience at large", with the addition of "what is the one link to point people to find out more about .NET Core+App Service". The App Service article is not the place to become a collection of links for .NET Core customers, but primarily for a "first 5 minutes with the service" experience. 

@madmox with the concerns you bring up, does it make Git an unattractive option for .NET Core customers? That's the question we would ask from our end. When you say it's not always possible/easy, are you saying the majority case or the minority case? All those issues you brought up are things that we probably should cover in our .NET/Core specific "Configure app" article we intend to rewrite. Do you have a doc somewhere that outlines the issues and configuration steps to address each?
