### ISSUE TITLE
Terminology: aspnet mvc Functional and Integration test samples vs documentation

### ISSUE THREAD

**Issue by tomfurrier** [aspnet/Docs#9726]
https://github.com/aspnet/Mvc/blob/1.0.0/test/Microsoft.AspNetCore.Mvc.FunctionalTests/MvcTestFixture.cs

The official samples use the TestServer in Functional tests, and nowhere in the IntegrationTests samples. 

I wonder if it should be clarified what is the relation between Integration test concept here in the docs vs Integration and Functional tests in the samples?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.1)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @tomfurrier ... Thanks for commenting.

`TestServer` is used inside of `WebApplicationFactory`. It's described in the [ASP.NET Core integration tests](https://docs.microsoft.com/aspnet/core/test/integration-tests?view=aspnetcore-2.1#aspnet-core-integration-tests) section of the topic.

The link you provided is 1.0, which is out-of-support. Here is current (2.2.0-preview3), which uses `WebApplicationFactory` ... https://github.com/aspnet/Mvc/blob/2.2.0-preview3/test/Microsoft.AspNetCore.Mvc.FunctionalTests/Infrastructure/MvcTestFixture.cs

I asked at the time the topic was written if we want to distinguish "integration testing" from "functional testing," and the answer was 'no' ... the engineer and docs team didn't want to broach the definition of "functional testing" in these topics. Since that question was clearly answered at the time, we'll leave the current definitions in place.

I'll close, since we don't have an action item to address. We can re-open this issue if you would like to discuss anything further. Thanks again for commenting.

**Comment by tomfurrier** [comment]
Thanks for the clarification!
