### ISSUE TITLE
explain the limitations of migrations for SQLite and the options

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#9784]
Review SQLite in this and [Adding a field](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/new-field?view=aspnetcore-2.1)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by tdykstra** [comment]
In these tutorials let's keep migrations for SQLite: it works with SQLite because the only operation being done in the tutorial is add a column and that's a supported operation for the SQLite provider.  

What we need to do in the add-a-column tutorial is explain the limitations of migrations for SQLite and the options -- i.e., delete the database and use ensure created, or write SQL for the up method.   I'll add the explanations as part of reworking the tutorial for MVC (content model).
