### ISSUE TITLE
Contoso University 

### ISSUE THREAD

**Issue by surfmuggle** [aspnet/Docs#9791]
I found this outdated [tutorial on contoso university](https://docs.microsoft.com/en-us/aspnet/mvc/overview/getting-started/getting-started-with-ef-using-mvc/creating-an-entity-framework-data-model-for-an-asp-net-mvc-application) which pointed to [the razor-pages-start tutorial](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-2.1). But on this page there was no mention of the university sample.

A search for [contoso university](https://docs.microsoft.com/en-us/search/index?search=contoso+university&skip=10&scope=ASP.NET%20Core) did not seem to be promising.

May be you could add this link instead: https://github.com/jbogard/ContosoUniversityDotNetCore/tree/master/ContosoUniversity

**Comment by guardrex** [comment]
I see where you're coming from @surfmuggle, but it's by-design. The wording of the note in the old tutorial could be a bit clearer that the tutorial series has been replaced (rather than existing as a "newer version").

I don't think we want that link in the RP tutorial because the Contoso tutorial/sample has no bearing on the topic+sample provided in the topic.

I'll make a change to the note. Thanks for commenting.
