### ISSUE TITLE
No executable

### ISSUE THREAD

**Issue by FrankPeach** [aspnet/Docs#9797]
I have followed this tutorial but what do I put for binPath= "{PATH}" ?? there is no executable created when I run dotnet publish. the publish command creates a dll not an exe.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0bd8cb8-7e28-8c4d-a550-3aea8f3ab4dd
* Version Independent ID: 4b60d24e-ef05-15e5-10b4-483094081bf3
* Content: [Host ASP.NET Core in a Windows Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.2)
* Content Source: [aspnetcore/host-and-deploy/windows-service.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/windows-service.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
The properties in your project file might not be correct. Compare to the sample app.

Make sure you have the latest SDK.

... and you're looking in the *publish* folder, correct?

**Comment by guardrex** [comment]
No, that's not it. There should be an exe matching the name of your app's assembly.

You should put your project file up. Something is amiss with it (probably ... guessing).

**Comment by guardrex** [comment]
Make sure your SDK is 2.2 ..... `dotnet --version`. If not, get 2.2 :point_right: https://dotnet.microsoft.com/download

**Comment by FrankPeach** [comment]
OK I was running the sample app under 2.1 Once I installed and used 2.2 I got the sampleApp.exe. I didn't realize that this tutorial only worked under 2.2

**Comment by guardrex** [comment]
The tutorial *will*&dagger; cover both 2.1 and 2.2, while the sample app will only be 2.2. For 2.1, the `<AppHost>` must be set explicitly.

&dagger;The 2.1 updates go live today ... perhaps even within the next few hours. Those updates are on https://github.com/aspnet/Docs/pull/9768.

Sorry about the doc churn catching you off-guard like this. With many thousands of users, no doubt a few will hit a topic right in the middle of a major overhaul.

Since this seems resolved, I'll close now.
