### ISSUE TITLE
context.User.IsInRole() involves claims which are not mentioned

### ISSUE THREAD

**Issue by nathrossel** [aspnet/Docs#9832]
By searching on the Internet and other documentation, I could finally get it but the code samples in SeedData and in AuthorizationHandlers should include the Claims because the statement context.User.IsInRole( ) in HandleRequirementAsync( ) cannot work without Claims. I find good that this article doesn't focus on the Claims but they should be part of the samples and with some short explanations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b66f8ffa-699c-8b11-0cab-805f5953805f
* Version Independent ID: 7c151ed5-fd78-84fd-a08a-88912990c4ca
* Content: [Create an ASP.NET Core app with user data protected by authorization](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/authorization/secure-data.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authorization/secure-data.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@joeaudette 	can you comment?

**Comment by joeaudette** [comment]
The sample does in fact include roles in the seed data, which is sufficient for .IsInRole([RoleName]) which is used in the authorization handlers.

Roles ARE Claims, but not all Claims are Roles. Role Claims and other Claims are attached to the ClaimsPrincipal the same way, just with Role Claims the ClaimType is Role, whereas other claims have other values for ClaimType.

Therefore since we are seeding Roles, we are seeding Claims because Roles are Claims.

No additional claims are needed in this sample in my opinion, role claims are most commonly used in authorization. You can use other claims in authorization requirements but use of role claims is sufficient for this example. There are other articles about [claims based authorization](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/claims?view=aspnetcore-2.1), this one uses [role based authorization](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/roles?view=aspnetcore-2.1). Adding additional claims checks in this sample would be making the example more contrived because "Administrators" role or "Managers" role are sufficient. It is also possible to use custom rules in authorization handlers which is not illustrated in this sample but is [discussed in other documentation](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-2.1).
