### ISSUE TITLE
Update Middleware

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#985]
- [x] address @danroth27  https://github.com/aspnet/Docs/pull/1163 feedback
- [x] Edit pass
- [x] update static files will not be protected by any authentication
- [x] Add link to Migrating HTTP Modules to Middleware

Rewrite as
Middleware are software components that are assembled into an application pipeline to handle requests and responses. Each component chooses whether to pass the request on to the next component in the pipeline, and can perform certain actions before and after the next component is invoked in the pipeline. Request delegates are used to build the request pipeline. The request delegates handle each HTTP request.

 Each middleware component in the request pipeline is responsible for invoking the next component in the pipeline, or short-circuiting the chain if appropriate.

**Comment by ArashMotamedi** [comment]
@Rick-Anderson Since understanding the Aspnet5 Middleware architecture requires a different thought process than the previous event-based handlers, or the flow-based perspectives, it might be beneficial and illuminating to include a couple of examples for Middlewares that do isolated work (for example, handle a certain type/route of request) vs those that do broad, cross-cutting work (e.g. logging, or catch-all exception handling).

**Comment by Rick-Anderson** [comment]
@ArashMotamedi  great idea. Any chance you could send me a sample and I'll add you to the authors list.

**Comment by ArashMotamedi** [comment]
@Rick-Anderson This post seems to cover this topic quite thoroughly: https://docs.asp.net/en/latest/migration/http-modules.html 

Perhaps no need to duplicate, but a link would be helpful; something like "to understand the difference between request pipelines in ASP.net 5 and the previous versions, read [link]"

**Comment by Rick-Anderson** [comment]
@ArashMotamedi I agree, We'll add that. Thanks!

**Comment by uselesshasid** [comment]
The example

`app.Run(async context =>
    {
        await context.Response.WriteAsync("Map Test Successful");
    });`

Wont compile unless you add a using statement

`using Microsoft.AspNet.Http;`

Please update the document, as its not obvious

**Comment by Rick-Anderson** [comment]
The [Middleware doc](https://docs.asp.net/en/latest/fundamentals/middleware.html) states:
 Also, in this example a design decision has been made that static files will not be protected by any authentication. This is a tradeoff that improves performance when handling static files since no other middleware (such as authentication middleware) needs to be called when handling these requests (ASP.NET 5 uses a specific wwwroot folder for all files that should be accessible by default, so there is typically no need to perform authentication before sending these files). If the request is not for a static file, it will flow to the next piece of middleware defined in the pipeline (in this case, Identity). 

I believe this is misleading at best. "a design decision has been made that static files will not be protected by any authentication" I don't understand that.

We don't have a built in mechanism to use authentication with static files in the wwwroot directory. One approach to protecting them is to App_Data folder (see [this SO answer](http://stackoverflow.com/questions/36775942/how-do-i-serve-static-files-only-to-authorized-users-in-asp-net-5)

I think it's best to remove all the auth talk about static files and move that to the [Working with Static Files](https://docs.asp.net/en/latest/fundamentals/static-files.html).

**Comment by ardalis** [comment]
I didn't realize you couldn't put Auth middleware in front of static content. If that's the case, I agree we should make the update you suggest, and refer to the Working with Static Files article for more info.

**Comment by Rick-Anderson** [comment]
@ardalis I'm making the change & fixing a couple other things. I'll have your review the PR.

**Comment by Rick-Anderson** [comment]
@Tratcher is the following OK?

context is the pipeline set up by the default templates, ie:

```
app.UseExceptionHandler("/Home/Error");
app.UseIISPlatformHandler(options => options.AuthenticationDescriptions.Clear());
app.UseStaticFiles();
app.UseIdentity();
 app.UseMvc(routes =>
```

The order in which you add middleware components is critical to your app’s security, performance and functionality. For example, adding exception handling after any other middleware components will miss exceptions thrown by those components. In the code above, the static file module is called early in the pipeline so it can handle requests and short circuit without going through unnecessary stages of the pipeline. The authentication middleware is added to the pipeline before any module that handles requests that need to be authenticated.

Do you want to add anything to that?

**Comment by Tratcher** [comment]
Sounds pretty good. I've included one line from your other description:

"The order in which you add middleware components is generally the order in which they take effect. This can be critical to your app’s security, performance and functionality. For example, adding exception handling after any other middleware components will miss exceptions thrown by those components. In the code above, the static file module is called early in the pipeline so it can handle requests and short circuit without going through unnecessary stages of the pipeline. The authentication middleware is added to the pipeline before any module that handles requests that need to be authenticated."

How do we capture that the pipeline terminates at a certain point and then executes in reverse on the response? This is one of the most common misunderstandings around the positioning of the exception handling middleware. People think it needs to be after the component that causes the exception, not before it. How's this?

"The order in which you add middleware components is generally the order in which they take effect on the request, and then in reverse for the response. This can be critical to your app’s security, performance and functionality. In the code above, the static file middleware is called early in the pipeline so it can handle requests and short circuit without going through unnecessary components. The authentication middleware is added to the pipeline before anything that handles requests that need to be authenticated. Exception handling must be registered before other middleware components in order to catch exceptions thrown by those components."
