### ISSUE TITLE
Fiddly little thing about dragging style sheets...

### ISSUE THREAD

**Issue by rswetnam** [aspnet/Docs#9895]
For years, I have dragged style sheets onto the template _LayoutPages in.Net with the resulting line of code something like:
&lt;link href="~/css/custom.css" rel="stylesheet" /&gt; which start with the href property.

This is usually placed under the line of code in _Layout that starts with the rel property and looks like this:
&lt;link rel="stylesheet" href="~/css/site.css" /&gt;

Like a little troll, I then dutifully change either the existing line of code or the new line of code so that both lines start with rel or href and I can more readily pick out the different files being referred to.  I know this makes absolutely now difference in how the program runs - but as I was just looking at the new version of Visual Studio 2019, I got to wondering - is there something I am missing?  Is Microsoft doing this deliberately to irritate the obsessive-compulsives amongst us, or might it want to take the opportunity of a new version of of Visual Studio to make the order of href and rel consistent between templates and program?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b29734d0-2d2b-3b82-0456-785cc7f361fd
* Version Independent ID: ab07129c-a4dd-44de-45f9-4b49eff0b54c
* Content: [Layout in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/layout?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/views/layout.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/layout.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
HI @rswetnam ... We won't be able to address that valuable feedback here on the docs repo, as we just use the templates for our sample apps mostly in the same form as we receive them from engineering. It sounds like you're making a suggestion for the templates. If so, I recommend opening an issue with that feedback on the [aspnet/AspNetCore issues](https://github.com/aspnet/AspNetCore/issues), where the engineers who work on the templates and other managers will see it.

Since this isn't actionable for the docs, I'm going to close the issue. We can re-open to discuss further if needed.
