### ISSUE TITLE
Correct name of IIS Middleware pairing token header

### ISSUE THREAD

**Issue by Julian89757** [aspnet/Docs#9920]
can i still access the kestrel server when the app is behind the iis proxy server?
the aspnetcore module specify the port  by environment_variable when kestrel startup, the environemnt_virable is  "ASPNETCORE_PORT",right  ? I still ca not access the kestrel server when host behind iis.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe69b3a9-896f-e189-0c2c-f87ff735df9c
* Version Independent ID: 97c8549b-66ad-0a23-1971-784fb923042a
* Content: [ASP.NET Core Module configuration reference](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-2.2)
* Content Source: [aspnetcore/host-and-deploy/aspnet-core-module.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/aspnet-core-module.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Julian89757 ... If you don't set `<AspNetCoreHostingModel>` to `InProcess` (or if you set it to `OutOfProcess`, which is the default), the out-of-process hosting model is used and Kestrel is used in a reverse proxy with IIS.

> the environemnt_virable is "ASPNETCORE_PORT",right ?

Yes

> access the kestrel server

Stand-by for a few hours ... I need to speak with one of the engineers about something pertaining to this before I answer. I'll get back to you soon.

**Comment by guardrex** [comment]
@Julian89757 ok ... I found the answer. First, I'll explain how it works and reference what we have in the docs. There's a small issue because the IIS Middleware changed. I'll need to make a tiny topic update to cover it.

There's a *pairing token* (stored in `ASPNETCORE_TOKEN`) that ensures that Kestrel will only respond to requests that come from IIS, so you won't be able to issue requests directly to Kestrel (out-of-process behind IIS) unless you set a header  on requests with the token value. For more info, see [Proxy configuration uses HTTP protocol and a pairing token](https://docs.microsoft.com/aspnet/core/host-and-deploy/aspnet-core-module#proxy-configuration-uses-http-protocol-and-a-pairing-token).

Here's the problem with the topic. The **_OLD_** header name is `MSAspNetCoreToken`. At some point, the name changed. The new header name is `MS-ASPNETCORE-TOKEN` ...

https://github.com/aspnet/AspNetCore/blob/2.2.0/src/IISIntegration/src/Microsoft.AspNetCore.Server.IISIntegration/IISMiddleware.cs#L21

Obtain the port (`ASPNETCORE_PORT`) and the token (`ASPNETCORE_TOKEN`) and compose a request to directly to Kestrel: `http://localhost:{PORT}` with the token value in a header named `MS-ASPNETCORE-TOKEN` ... and it should ✨ *Just Work*:tm: ✨.

Leave this issue open ... I'll use this issue to update the topic, and this issue will automatically close when the PR is merged.

**_Thanks for asking!_** We probably wouldn't have caught this one for quite a while if you hadn't said something.
