### ISSUE TITLE
Document how to replace the Authentication/Identity related middlewares in the integration tests

### ISSUE THREAD

**Issue by lnaie** [aspnet/Docs#9957]
Hi,

For integration tests, this continue to be a problem, especially with so many (sometimes outdated) unofficial examples around. Because of that, some of old working hacks won't work anymore in the new releases.

Please help with this,
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.1#)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @lnaie ... Can you clarify your request? Are you asking about how to test with an authenticated/unauthenticated clients, or are you actually trying to replace middlewares in the SUT?

**Comment by lnaie** [comment]
It's about how to replace the middlewares responsible for authorization.

**Comment by guardrex** [comment]
Thanks @lnaie ... Call `ConfigureTestServices` on the builder when either overriding `ConfigureWebHost` or calling `WithWebHostBuilder`. There's an example of this in the [inject mock services area of the topic](https://docs.microsoft.com/aspnet/core/test/integration-tests#inject-mock-services) ...

```csharp
var client = _factory.WithWebHostBuilder(builder =>
    {
        builder.ConfigureTestServices(services =>
        {
            services.AddScoped<IQuoteService, TestQuoteService>();
        });
    })
    .CreateClient();
```

... you should be able to swap in your services similarly.

RE: Expanding the topic generally with more examples and particularly for auth testing ... **_Yes!_** We have several issues in this area that we hope to address, including:

* [How to create authenticated request?](https://github.com/aspnet/Docs/issues/6882)
* [add Integration Testing chapter for the Contoso University example code](https://github.com/aspnet/Docs/issues/3438)
* [Using Kerberos/Negotiate/UseDefaultCredentials with WebApplicationFactory](https://github.com/aspnet/Docs/issues/9451)
* [How to test Web API with Jwt Bearer Authentication](https://github.com/aspnet/Docs/issues/8796)
* [How to actually perform post requests?](https://github.com/aspnet/Docs/issues/7526)

The priorities on these would have them worked sometime in early to mid-2019. I suggest that because the .NET Core 3.0 release is anticipated sometime in 2019 and we just had the 2.2 release. If one or more community members don't work on any of these issues, they might be worked by the docs team before the team gets close to a 3.0 release. The work for 3.0 will be another 🏃😅 very busy period for the doc authors, and these will be considered low priority compared to the 3.0 doc issues.

Let's leave this issue open so that the doc author(s) and/or engineers can take a look at this when the time comes.

**Comment by jabbera** [comment]
For those interested I build a package that makes this simple: https://github.com/jabbera/aspnetcore-testing-role-handler

Feedback welcomed.

**Comment by jelster** [comment]
I've created a [gist ](https://gist.github.com/jelster/6b850d567acef343e59fad70cb20455a) demonstrating the use of a test authentication middleware/scheme and the registration of that middleware in an integration test project (commented on #6882 as well) 

HTH

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.

**Comment by vanillajonathan** [comment]
Instead of replacing the Authentication/Identity related middlewares in the integration tests you can add a fake [`AuthenticationHandler`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.authenticationhandler-1) that gets configured by the WebHostBuilder in the [`WebApplicationFactory`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.testing.webapplicationfactory-1) of your test class.
For how to do this, see: https://github.com/aspnet/AspNetCore.Docs/issues/6882#issuecomment-540020183
