### ISSUE TITLE
runtimes directory is not documented in Directory structure

### ISSUE THREAD

**Issue by nicksterx** [aspnet/Docs#9965]
When you publish an application with multiple TargetFrameworks a runtime directory is generated with multiple runtime support. This is confusing and not documented on what the purpose of the runtimes are or why are they generated. 

Example of runtime directory output:
```
runtimes/
   - debian.8-x64/
   - fedora.23-x64/
   - fedora.24-x64/
   - opensuse.13.2-x64/
   - opensuse.42.1-x64/
   - osx/
   - osx.10.10-x64/
   - rhel.7-x64/
   - ubuntu.14.04-x64/
   - ubuntu.16.04-x64/
   - ubuntu.16.10-x64/
   - unix/
   - win/
```

Stackoverflow post related to this https://stackoverflow.com/questions/53507229/when-publishing-how-do-i-target-specific-net-core-runtimes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 566f8ed0-217e-5125-b0f7-6d93c3a145c1
* Version Independent ID: 9fa94395-eff8-3b12-c2d5-c1c6d4142378
* Content: [ASP.NET Core directory structure](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/directory-structure?view=aspnetcore-2.2)
* Content Source: [aspnetcore/host-and-deploy/directory-structure.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/directory-structure.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@nicksterx You shouldn't have a *runtimes* folder when publishing an FDD. The runtime is on the host for an FDD. A runtime (just one of them) is part of the deployment of a self-contained deployment, but it won't be in a *runtimes* folder.

Anyway ... I'm happy that you opened this issue.

The purpose of the topic is to exhibit the *publish output* of the `dotnet publish` command for deployment purposes. Since the *publish* folder is a child of the runtime for a self-contained deployment, we don't need to address that subject here. **_However!_** ......

> This is confusing and not documented on what the purpose of the runtimes are or why are they generated.

It's in the .NET Core doc set. We just document the ASP.NET Core (web bits) over here. See :point_right: [.NET Core RID Catalog](https://docs.microsoft.com/en-us/dotnet/core/rid-catalog)

... so I think what this topic could use is an *Additional resources* section with links over to that content to help readers find the frameworks and RIDs that pertain to publishing projects. I'd also like to link the `dotnet publish` topic and the deployment types topic in the new section.

I also discovered looking at the topic here that there's a couple of minor changes in the published output that occurred with the 2.2 (and/or 2.1) release that I need to address.

Thanks for opening, I'll knock these out right now.

**Comment by nicksterx** [comment]
@guardrex Thank you for taking a look at this! 

The _runtimes_ folder is apart of the output when publishing an FDD. 

If I run this command 

```sh
dotnet publish -c Release -o ..\publish
```

The published output matches the directory structure I had above. 

However if I specify my startup project in the publish command

```sh
dotnet publish .\startupProject.csproj -c Release -o ..\publish
```

it generates a simpler published out but _runtimes_ is still apart of it

```
- publish/runtimes/
   - unix/
   - win/
```

I like the idea of the _Additional resources_ I discovered this page trying to find the reasoning for the runtimes publish output.

**Comment by nicksterx** [comment]
@guardrex I'm running dotnet version: 2.1.500 but the project was started on 2.0.5

**Comment by nicksterx** [comment]
@guardrex 

I believe this is because of a netstandard project being a project dependency of a netcoreapp project. If I run 

`dotnet publish -c Release -o ..\publish .\SampleApp\SampleApp.csproj`

it outputs a runtime directory of 

```
- publish/runtimes/
   - unix/
   - win/
```

If I remove the netstandard project as a project dependency then none of the runtimes are built. I'm not sure if this is documented anywhere.

**Comment by guardrex** [comment]
That's interesting. Now that I can repro it, I'll take a look and get back to you. Give me a few days ... I'm 🏃🏃🏃🏃😅 at the moment.

**Comment by guardrex** [comment]
Just took a look ... I can't repro this behavior. I built an app with a project ref to a class lib that targets `netstandard2.0` and uses the BCrypt package. Published output of this FDD app doesn't include a *runtimes* folder.

<img width="223" alt="capture" src="https://user-images.githubusercontent.com/1622880/52587928-db8f7380-2e00-11e9-9fcb-46089992819d.PNG">

I don't have anything specific to doc at this point, but we can re-open if more information comes to light.
