### ISSUE TITLE
  Approved and Rejected buttons aren't display in the administrator page

### ISSUE THREAD

**Issue by kokilasanjeewa** [aspnet/Docs#9998]
Approved and Rejected buttons aren't display in the administrator page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b66f8ffa-699c-8b11-0cab-805f5953805f
* Version Independent ID: 7c151ed5-fd78-84fd-a08a-88912990c4ca
* Content: [Create an ASP.NET Core app with user data protected by authorization](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/authorization/secure-data.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authorization/secure-data.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @kokilasanjeewa ... It's very likely due to one or both of the following:

* A password hasn't been provided as a user secret with the Secret Manager tool.
* The database has contacts, which prevents the seeding code from running and you don't get the default manager and administrator account when the app starts.

For instructions, see :point_right: https://docs.microsoft.com/aspnet/core/security/authorization/secure-data#test-the-completed-app

This happened just a short time ago to another reader (https://github.com/aspnet/Docs/issues/9894), and we expanded that section to explain what to do. I'll close this as answered, but we can re-open this to discuss further if needed.

**Comment by kokilasanjeewa** [comment]
Yes its work.and added services.AddIdentity<IdentityUser,IdentityRole>()
                .AddEntityFrameworkStores<ContactManagerContext>()
                .AddDefaultTokenProviders().AddDefaultUI();
